### ISSUE TITLE
Remove fontforge dependency if practicable

### ISSUE THREAD

**Issue by ianbarber** [google/WebFundamentals#1000]
FontForge setup is tricky, and its not entirely clear we need all of the features. We should investigate what font types we need to generate, and if possible simplify or remove this step from out build process.

/cc @wibblymat

**Comment by petele** [comment]
@gauntface - we should figure out if this is still required.

**Comment by gauntface** [comment]
I've been using the svg's rather than Material Design icon font just so the colors can be altered and I have done nothing to use font forge in current set up of Ruby and Gulp soooo . . . . . my assumption is this is already the case.

**Comment by petele** [comment]
Wheee!
