### ISSUE TITLE
Two consecutive samples partially overlap

### ISSUE THREAD

**Issue by jacquerie** [google/WebFundamentals#1006]
See for instance https://developers.google.com/web/fundamentals/getting-started/your-first-multi-screen-site/responsive#constrain-the-maximum-width-of-the-design, where the absolutely positioned `.highlight-module__cta` is partially covered by the next relatively positioned `.highlight-module`.

I'm also slightly puzzled by the empty `.container` that appears between the two, but it's probably unrelated.

**Comment by petele** [comment]
@PaulKinlan - can you take a look and see if this is still relevant, if so can you either fix or add some detail as to what needs to be fixed and we'll reassign?

**Comment by gauntface** [comment]
I just trying looking at this - I can't see what the problem is - can anyone take a screenshot of the issue? Is this all browsers, Chrome or something else?

**Comment by petele** [comment]
Prob not an issue in new redesign.
