### ISSUE TITLE
Feedback for: /fundamentals/getting-started/web-starter-kit/index.html

### ISSUE THREAD

**Issue by stevemao** [google/WebFundamentals#1009]
![screen shot 2014-11-20 at 11 25 38 am](https://cloud.githubusercontent.com/assets/6316590/5117405/05b083b8-70a8-11e4-992c-f2f41ad2f43c.png)
The two triangles looks very confusing.. Don't know what tab is currently active.
![screen shot 2014-11-20 at 11 27 36 am](https://cloud.githubusercontent.com/assets/6316590/5117422/410bb716-70a8-11e4-8838-3b15ea98565d.png)
Also happens when mouse is not over. Probably a bug

**Comment by petele** [comment]
Known issue that we'll need to address in the redesign.
