### ISSUE TITLE
Data URIs

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#101]
Add materials about data uris to image article

**Comment by petele** [comment]
Sam, can you make a decision on whether it makes sense to add this or not? If not, please close.

**Comment by samdutton** [comment]
Hmm.. 

I think yes: data URIs and inline SVGs.

The Udacity course has information about how to include images inline [here](https://www.udacity.com/course/viewer#!/c-ud882/l-3483659506/m-3588778631). The script/graphics for this would be a good basis for content here, and we could build similar demos.

If no objections, early Q2.

**Comment by petele** [comment]
Objections == 0;

**Comment by petele** [comment]
Hey @samdutton - can you take a look and add this to your plate? ;)

**Comment by samdutton** [comment]
Looks like Q2 came and went ;).

I'll add an **Inline images** section (based on the Udacity content) under the **Other image techniques** heading.

**Comment by PaulKinlan** [comment]
@samdutton it would be good to close this off.

**Comment by PaulKinlan** [comment]
(as in finish the work)

**Comment by samdutton** [comment]
Oops... fell off the radar. Will do it early next week. Promise!

**Comment by samdutton** [comment]
@joemedley PTAL

**Comment by petele** [comment]
This has been completed.
