### ISSUE TITLE
Feedback for: /fundamentals/getting-started/web-starter-kit/setting-up.html

### ISSUE THREAD

**Issue by delebash** [google/WebFundamentals#1010]
Under the Sass section you say that once you install Gulp globally that Sass will be available to you.  I am pretty sure that the gulp-ruby-sass still relies on ruby and sass, so you still need to install ruby and sass separately for Windows Os.  Otherwise nice articles!

See [gulp-ruby-sass page](https://github.com/sindresorhus/gulp-ruby-sass)

**Comment by dturner** [comment]
Same for me on OSX. Had to install ruby and sass manually using `gem install sass`.

**Comment by addyosmani** [comment]
@PaulKinlan could we update the version from the WSK site on WF to 0.5.3 (https://github.com/google/web-starter-kit/archive/v0.5.3.zip)? I think this might be causing some confusion as this version no longer requires Ruby to get things running.

**Comment by PaulKinlan** [comment]
@gauntface. all links to the DL should be automatically generated.

**Comment by gauntface** [comment]
I believe they are - although I've witnessed the two links getting out of sync before.

The main problem is we need a regular update cycle - once every so often isn't good enough.

**Comment by PaulKinlan** [comment]
You can do that now. We only updated 2 weeks ago. Has there been another
update?

**Comment by PaulKinlan** [comment]
As in has wsk revved in the last two weeks

**Comment by addyosmani** [comment]
It hasn't revved in the last two weeks but the current version on the site is still pointing to 0.5.2: https://developers.google.com/web/starter-kit/ (note the 0.5.2 labelling and links)

**Comment by gauntface** [comment]
Where does that number come from?

I swear someone spent some time doing something to make the download link stay up to date.

Either way the yaml file for the header links isn't updated.

![web_starter_kit_ _web_fundamentals](https://cloud.githubusercontent.com/assets/139760/6459788/15e04832-c192-11e4-92d0-45b4490ea486.png)

I think we should just point people to releases - this has been a constant issue and we can't run JS, we have no regular update path and no one has time to maintain this thing.

**Comment by PaulKinlan** [comment]
We have a regular update path, it takes one email to sort in an emergency .
please speak to pete. We need to sort out why that link is not updated.

I'm going to set up a regular sync again to cover wf releases.

**Comment by petele** [comment]
Created a /web/starter-kit/download/ that redirects to the latest download. While this requires a server-side redirect, we'll be able to consistently keep the same url for downloads and always have it point to the latest content.

**Comment by petele** [comment]
Simplified this even more, now clicking on those links redirects the user to https://github.com/google/web-starter-kit/releases/latest which is always the latest release.
