### ISSUE TITLE
[JA] Feedback for: /fundamentals/getting-started/web-starter-kit/setting-up.html

### ISSUE THREAD

**Issue by jacquerie** [google/WebFundamentals#1014]
[This page](https://developers.google.com/web/fundamentals/getting-started/web-starter-kit/setting-up?hl=ja) appears to be mostly untranslated.

(I simulated the effect of my PR #1002 for clarity, but it's not yet live)

**Comment by petele** [comment]
I've marked it for re-translation for the next round.
