### ISSUE TITLE
Refactor navigation.liquid

### ISSUE THREAD

**Issue by jacquerie** [google/WebFundamentals#1018]
Similar to issue #755, HTML tags appear in class names:

```HTML
<li class="main-nav__item main-nav__item--web-<strong>fundamentals</strong> main-nav__item--home">
  [...]
</li>
```

This is a rather trivial problem, but this, issue #1009 and several other nuisances (a `header` inside of a `header` is incorrect HTML, which means that every page on the site does not validate) point to a refactor of this template, whose complexity has grown out of bounds.

**Comment by petele** [comment]
This *hopefully* isn't an issue with recent issues.  Please refile a new issue if it is.
