### ISSUE TITLE
Feedback for: /fundamentals/performance/optimizing-content-efficiency/image-optimization.html

### ISSUE THREAD

**Issue by kelter-antunes** [google/WebFundamentals#1038]
Portuguese page is really bad formatted and impossible to read...
![screen shot 2014-12-08 at 02 31 04](https://cloud.githubusercontent.com/assets/6965808/5334101/6285c0ac-7e82-11e4-8402-9e52e0b6e547.png)

**Comment by petele** [comment]
Fixed in staging, should roll out in the next week.
