### ISSUE TITLE
Feedback for: /fundamentals/performance/optimizing-content-efficiency/image-optimization.html

### ISSUE THREAD

**Issue by TiagoPortfolium** [google/WebFundamentals#1063]
Hi,

I noticed some errors in the html code which caused the page to be huge in the pt-br language.
The problem starts in this div: ```html <div class="content">``` because the tag it is not being closed properly and there is some other problems.

I suggest you replace that  ```html <div class="content">``` with:

 ```html <div class="content"><p>A primeira pergunta que você deve se fazer é se determinada imagem é realmente necessária para alcançar o efeito desejado. O bom design é simples e sempre resultará em um melhor desempenho. A melhor estratégia de otimização é eliminar recursos de imagem sempre que possível, pois eles geralmente consomem muitos bytes em relação aos recursos em HTML, CSS, JavaScript e outros. Uma imagem bem posicionada pode dizer mais que mil palavras. Por isso, cabe a você encontrar o equilíbrio.</p><p>Em seguida, é preciso considerar se há outra tecnologia que possa gerar os resultados desejados de maneira mais eficiente:</p><ul><li><strong>Efeitos CSS</strong> (gradientes, sombras etc.) e animações CSS podem ser usados para gerar recursos que não dependem de resolução e mantêm a qualidade em qualquer nível de zoom, além de geralmente consumirem bem menos bytes do que um arquivo de imagem.</li><li><strong>Fontes da Web</strong> permitem o uso de elegantes faces de tipos e mantêm a capacidade de selecionar, pesquisar e redimensionar o texto, o que significa uma grande melhoria na facilidade de uso.</li></ul><p>Pense duas vezes antes de incorporar texto por meio de código em uma imagem. A qualidade da tipografia é essencial para um bom design, para o branding e para facilitar a leitura, mas o texto em imagens prejudica a experiência do usuário. O motivo é que esse tipo de texto não pode ser selecionado, pesquisado, ampliado nem acessado, além de não ser exibido corretamente em dispositivos com alto DPI. Usar fontes da Web requer um [conjunto próprio de otimizações] (https://www.igvita.com/2014/01/31/optimizing-web-font-rendering-performance/), mas resolve todos os problemas citados acima e é sempre uma opção melhor para a exibição de texto.</p><h2 id="imagens-vetoriais-vs-imagens-de-varredura">Imagens vetoriais vs. imagens de varredura</h2></div></div>``` 

I basically copied the structure of the uk page and added the text in pt-br. And make sure to close ```html <div class="content">``` just before this div: ```html <div class="highlight-module highlight-module--left highlight-module--learning">```.

**Comment by jacquerie** [comment]
Hi! Thanks for reporting. Unfortunately we can't use your suggestion as-is: the HTML code is generated, not manually written. Your report is still valuable, because it highlights a problem in the generator.
