### ISSUE TITLE
Translation not working on Safari 8.0

### ISSUE THREAD

**Issue by jiayihu** [google/WebFundamentals#1064]
Refering to this article about [CSS vs Javascript Animations](https://developers.google.com/web/fundamentals/look-and-feel/animations/css-vs-javascript) in this [example](http://googlesamples.github.io/web-fundamentals/samples/look-and-feel/animations/box-move-keyframes.html) the box doesn't translate at all, but the opacity animation works. I'm using Safari 8.

**Comment by PaulKinlan** [comment]
@paullewis - can you have a look in to this pls.

**Comment by paullewis** [comment]
It'll be because the latest Safari unprefixed transition but _not_ transform, so there should be an additional declaration:

```css
transition: -webkit-transform /* etc */;
```

**Comment by petele** [comment]
@paullewis - can you please either add the declaration or lmk if it's been addressed?
