### ISSUE TITLE
Feedback for: _utils.scss

### ISSUE THREAD

**Issue by jamierytlewski** [google/WebFundamentals#1066]
I'm just curious as to why content-box is being used for the container versus border-box for all? Thanks!
Jamie

**Comment by PaulKinlan** [comment]
I can't actually recall now, @peduarte might recall, but I do suspect it was a positioning thing. :)

**Comment by peduarte** [comment]
Don't remember off the top of my head, but it must be because I wanted the padding-left and padding-right to add up to the max width of the container. @jamierytlewski @PaulKinlan
