### ISSUE TITLE
Feedback for: /fundamentals/getting-started/?hl=ru

### ISSUE THREAD

**Issue by denpatin** [google/WebFundamentals#1072]
The same issue as with #1070 is here.
![screen shot 2015-01-04 at 11 27 37 pm](https://cloud.githubusercontent.com/assets/1271040/5607359/623eaefe-9469-11e4-97a0-a46b76ab30b6.png)

**Comment by denpatin** [comment]
Any ideas on how to without loss of sense reduce both the title and the body?

**Comment by PaulKinlan** [comment]
Nope.  I am all ears.  We should probably really change this page.

**Comment by petele** [comment]
Same as #1070
