### ISSUE TITLE
Feedback for: /fundamentals/performance/optimizing-content-efficiency/image-optimization.html

### ISSUE THREAD

**Issue by sgbotsford** [google/WebFundamentals#1075]
I'm puzzled by the reluctance for double downloading.

Consider the following strategy:  The default image size is proportional to the final image, but only 100 pixels wide.  The browser scales it and it looks awful.  Because it's small, however, the response is fast fast fast.  

However in that time, the server can track how fast the network connection is to that browser.  As well, hardware probing JS can run.  Now the server can send the appropriate image for that particular client.

But you downloaded the same image twice!  No you didn't.  Suppose it's a iPhone 4 with 640 real pixels 320 CSS pixels.  YOu have a beautiful banner 100% that's 4 times as wide as tall.  The initial image then is 100 x 25 pixels, and acts as a place holder.  The final one is 640 x 160.  The second one is 36 times the size.  Do you *really* care about 3% extra downloading if the first usuable display is 2 seconds faster?

**Comment by petele** [comment]
While true in theory, no servers currently track speed or anything like that, so it's not a viable solution for developers to use today.
