### ISSUE TITLE
View Source links broken

### ISSUE THREAD

**Issue by erickoledadevrel** [google/WebFundamentals#1078]
The "View Source" links in the header 404. For example, the homepage's source currently links to:

https://github.com/Google/WebFundamentals/tree/master/src/site/_en/fundamentals/index.html

It should instead link to:

https://github.com/Google/WebFundamentals/tree/master/src/_langs/en/fundamentals/index.html

Looks like the fix would simply involve a small change to https://github.com/google/WebFundamentals/blob/master/src/_includes/beta.liquid.

**Comment by wibblymat** [comment]
Oops, my fault. Will fix tomorrow.

**Comment by wibblymat** [comment]
I made a PR to fix the links. The code layout on Github has changed recently. Even if the template had been updated correctly, the live links would still have been broken until the next publish.
