### ISSUE TITLE
Feedback for: /fundamentals/look-and-feel/animations/animating-modal-views.html

### ISSUE THREAD

**Issue by miadabrin** [google/WebFundamentals#1083]
I think browser compatibility with the "pointer-events" css attribute must be taken into consideration. IE does not generally support it .maybe a better approach should be setting "visibility: hidden" when the box is hidden and then setting it to "visibility: visible" when you intend to show it and then animating your modal view. although I am not aware of the performance considerations of this change.

**Comment by petele** [comment]
@gauntface - can you comment here?

**Comment by gauntface** [comment]
Can't say anything for definite without trying stuff out, but ' touch-action' / 'ms-touch-action' may be able to solve this rather than switching the visibility stuff.

Looking http://csstriggers.com/, visibility is pretty expensive - layout, paint and composite.
