### ISSUE TITLE
Feedback for: /fundamentals/getting-started/web-starter-kit/setting-up.html

### ISSUE THREAD

**Issue by JTonyC** [google/WebFundamentals#1084]
Hi,

I had slight issues with the install of the web development kit. I install Node.js, as per the walk-through,  no issues there, however, after I ran the gulp serve command, it started the process, but then gave this error when it came to applying styles:

gulp-ruby-sass: 'sass' is not recognized as an internal or external command,
operable program or batch file.

The page displayed, but, it didn't have any css styling and didn't look like the resulting screenshot on the tutorial. I searched on stack and found this:

http://stackoverflow.com/questions/24937506/gulp-ruby-sass-not-a-recognized-command-in-windows

Naturally, I follow the answer, installed Ruby, then installed Sass using the Ruby command 

'gem install sass' 

As suggested, then when running 'gulp serve', it correctly displayed the page, with styling as per the screenshot in the tutorial.

I feel this is quite fundamental, newbies like me may not know where to look or how to resolve it. Just thought I'd make you aware of it and maybe include the ruby and Sass install steps in the tutorial.

(If this was supposed to happen at the npm of npm gulp install steps, it didn't for me or if this is a test of developer problem solving, good show :+1: )

Kind regards

**Comment by PaulKinlan** [comment]
Hi,

Can you raise the issue on https://github.com/Google/Web-Starter-Kit that is where a lot of the issues should be tracked (unless it is a documentation issue)

**Comment by JTonyC** [comment]
My apologies, I didn't make this clear.

This is a documentation issue. From above:

I install Node.js, as per the walk-through, no issues there, however, after I ran the gulp serve command, it started the process, but then gave this error when it came to applying styles:

gulp-ruby-sass: 'sass' is not recognized as an internal or external command,
operable program or batch file.

This error occurred because I didn't have Ruby installed, which was a requirement to install Sass. The npm gulp install does not install Ruby and so it throws the above error when you run the gulp serve command, consequently, no styling is made to the test pages.

The documentation doesn't state this step.

**Comment by PaulKinlan** [comment]
Cc @gauntface
