### ISSUE TITLE
Feedback for: /fundamentals/resources/contributors/index.html

### ISSUE THREAD

**Issue by OlafvdSpek** [google/WebFundamentals#1092]
http://googlesamples.github.io/web-fundamentals/samples/_nl/layouts/rwd-fundamentals/vp-no.html and http://googlesamples.github.io/web-fundamentals/samples/_nl/layouts/rwd-fundamentals/vp.html are found on https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/set-the-viewport?hl=nl but do not exist.

**Comment by OlafvdSpek** [comment]
Both links still return 404 for me.

On Fri, Jan 16, 2015 at 2:21 PM, Paul Kinlan <notifications@github.com>
wrote:

> Closed #1092 <https://github.com/google/WebFundamentals/issues/1092> via
> #1093 <https://github.com/google/WebFundamentals/pull/1093>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/WebFundamentals/issues/1092#event-220062308>.
>



-- 
Olaf

**Comment by PaulKinlan** [comment]
The new build hasn't been deployed yet.
