### ISSUE TITLE
Question: how to setup the development environment after the switch to GAE?

### ISSUE THREAD

**Issue by jacquerie** [google/WebFundamentals#1096]
I took a brief hiatus from contributing, and now I'm having a little trouble setting up my development environment again.

Simply running 

    $ make server

doesn't work anymore. Sometimes I get tons of

    There was an error highlighting your code.

errors and then an `ArgumentError` for Pygments.rb, other times I get tons of

    2015-01-16 14:06 grunt[35154] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

errors.

What's working for me is adding the `WebFundamentals/appengine` folder into GoogleAppEngineLauncher, then running

    $ grunt build

then clicking "Run" into the corresponding entry in GoogleAppEngineLauncher and finally visiting `localhost:8081/web/fundamentals`.

This looks a bit complicated compared to what I was doing earlier, so I'm wondering if I'm missing a crucial step.

**Comment by wibblymat** [comment]
Hi! Sorry about breaking everything :)

There have been lots of changes recently, and there are some loose ends that need tidying.

I don't use `make`, so I have consistently failed to keep it working. However, you can instead use `grunt build` to build the site and then `grunt gae:local` to run a local development server. `grunt gae:local` shouldn't require you to do anything in the GoogleAppEngineLauncher.

`grunt develop` does both of the above things for you, opens the index page in your browser, and sets up a `watch` task that monitors for changes in the source. However, the `watch` doesn't work on Mac due to some OS X bugs (this is the FSEvents.framework errors you see above.)

**Comment by PaulKinlan** [comment]
@wibblymat can you make sure the guide is up todate.

**Comment by jacquerie** [comment]
I'm not having success with `gae:local`. I tried debugging by setting `async: false` and adding a debugging argument

    args: {
            'log_level': 'debug'
    }

but had no success: I get a `Running "gae:local" (gae) task` line and no further output (or website on `localhost:8081`). I'm led to believe that `grunt-gae` is failing to invoke `dev_appserver.py`.

**Comment by fedex1** [comment]
I'm seeing a similar issue

It appears the css files are not found at all in the latest from github

For example,

requesting 

`http://localhost:8080/web/fundamentals/resources/samples/css/normalize.css`

results in this 404 error:

`INFO     2015-01-20 03:12:22,856 module.py:718] default: "GET /web/fundamentals/resources/samples/css/normalize.css HTTP/1.1" 404 -`

I see the code that maps _langs/en/fundamentals to /web/fundamentals for other than css but for css

There is 

    - url: /web/(.*\.(woff|eot|ttf|css))
      static_files: build/\1
      expiration: 1d
      upload: build/(.*\.(woff|eot|ttf|css))
      http_headers:
        Access-Control-Allow-Origin: https://developers.google.com
which does not seem to work

One patch is to do this to create a real `build/fundamentals/resources/samples/css` directory

`mkdir -p build/fundamentals/resources/samples/css`
`cp -Rp build/_langs/en/fundamentals/resources/samples/css/  build/fundamentals/resources/samples/css
`

I'm using dev_appserver.py but the same is true for grunt gae:local

**Comment by petele** [comment]
This should be fixed, if it isn't, try blowing away your existing repo and starting again.
