### ISSUE TITLE
Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/index.html

### ISSUE THREAD

**Issue by AndyWays** [google/WebFundamentals#1097]
## Google Its With Great Pleasure I Say To Thee

 I had assumed that `google = awesome on the webosphere`.

I had made that assumption and would have thought it would make sense given [Google](http://google.com) builds the webs; and offer FREE `free=no cost` instruction on how to [Build The Web](http://apple.com) via their [Web Fundamentals Page!](http://developers.google.com/web/fundamentals/) 

#### Apparently though ####

...when clicking on your The link to [View Source!]
(https://github.com/Google/WebFundamentals/tree/master/src/site/_en/fundamentals/getting-started/your-first-multi-screen-site/index.markdown)
![screen shot 2015-01-17 at 12 09 07 pm](https://cloud.githubusercontent.com/assets/8979411/5790187/b019598a-9e41-11e4-86c4-ef9b4fbdc7d5.png)

The link to [View Source!](https://github.com/Google/WebFundamentals/tree/master/src/site/_en/fundamentals/getting-started/your-first-multi-screen-site/index.markdown) is no good mang! Itsa broken and returns a [404 Error!]
![screen shot 2015-01-17 at 12 12 47 pm](https://cloud.githubusercontent.com/assets/8979411/5790203/5df1b854-9e42-11e4-942e-1ea4825180ff.png)
<hr /hr>

##### Well thats all I have, this was fun and instructional. My recommends are as follows:

1.  someone should
    * _**`firm up the fundamentals`**_ 

<h5>The Plebeian Would REF</h5>

>>itz the same as _**`http://-in`**_ the right _`{jangle tooth}`_ 

That is to say not ~~incorrectly~~ :bowtie:

-   `[AKA]` in the `codec world` as  **_`derpin it to it`_**.

Thank you.  :see_no_evil: :hear_no_evil: :speak_no_evil: :gun:

**Comment by PaulKinlan** [comment]
We are fixing the 404 in the next deploy.
