### ISSUE TITLE
set up web starter kit

### ISSUE THREAD

**Issue by poltiser** [google/WebFundamentals#1098]
I have installed successfully Web Starter Kit and after running a command in terminal " $ gulp serve" I got a message that command "gulp" does not exist?

What should I do next?
Any Web Kit for dummies?
Pls advise!

PS. Ubuntu XFCE 14.10 amd64

**Comment by PaulKinlan** [comment]
Cc @gauntface

**Comment by shantanuraj** [comment]
Is gulp installed globally?

  npm install gulp -g

**Comment by poltiser** [comment]
Yes - I have followed the instructions from 
https://developers.google.com/web/fundamentals/getting-started/web-starter-kit/setting-up#install-these-one-time-dependencies

Tx

**Comment by Uriahs9** [comment]
Assuming you have windows. Did you run as cmd as admin?

**Comment by poltiser** [comment]
No Windows - XFCE ubuntu 14.10 amd64

**Comment by PaulKinlan** [comment]
https://github.com/Google/Web-Starter-Kit might be the best place to ask this question.
