### ISSUE TITLE
Feedback for: /fundamentals/tools/setup/editor.html

### ISSUE THREAD

**Issue by ohyouknowwho** [google/WebFundamentals#1099]
Minor point for this one.

Gutter Color is a ST3 only plugin. When you land on sublime text page it gives you ST2 download. It's worth mentioning because I'm relatively new to this, and got to Gutter color and it's not available currently for ST2.

Since it's a wide audience you'll be reaching, I think it's worth consideration.

**Comment by PaulKinlan** [comment]
cc @gauntface

**Comment by gauntface** [comment]
Sorry - I totally didn't realise git gutter was ST3.

**Comment by ohyouknowwho** [comment]
@gauntface 

Gutter Color not Git Gutter! :laughing: 

Sorry for the delay in responding.
