### ISSUE TITLE
Does the requestAutocomplete example rac.html actually work?

### ISSUE THREAD

**Issue by fedex1** [google/WebFundamentals#1106]
It appears that the example at https://googlesamples.github.io/web-fundamentals/samples/input/form/rac.html  may not work.

First of all,  https is needed

Then, you see the following messages:
(what does "Oops, Google Wallet is not supported with this merchant" mean?  How do we support it?

I apologize if this an old issue or my issue, but I've been trying to understand this for a while.

![screen shot 2015-01-21 at 12 32 40 am](https://cloud.githubusercontent.com/assets/167614/5831675/18abdab6-a105-11e4-8839-980c2c6d61b0.png)

if you click on the account area you see:

![screen shot 2015-01-21 at 12 32 55 am](https://cloud.githubusercontent.com/assets/167614/5831676/18ad1994-a105-11e4-9b99-7fe4c7a56fd7.png)

**Comment by PaulKinlan** [comment]
Are you based in the US?

**Comment by buticm** [comment]
@PaulKinlan I'm based in US. I have valid google wallet account with valid credit card on file.
Another production website to try is:
http://m.bowflexmaxtrainer.com/bowflex-max-trainer-us/homepage.jsp?bbOptiTest2=1
- add any product to cart
- click on "go to checkout" button on cart page
The same native window will appear, but no way to pay with google wallet.

Note, that if I set to use sandbox account (in chrome://flags) everything works as expected, but doesn't work with normal google wallet account at all.

**Comment by PaulKinlan** [comment]
You need to be on https.  I believe this is the reason, and why our example fails.

**Comment by buticm** [comment]
@PaulKinlan all checkout and cart pages are on https in the example that I provided.
The same thing happens with this example on https, when I manually fix the url to be on https.

**Comment by fedex1** [comment]
@PaulKinlan I apologize for missing your question.  Yes I was testing from the US.

**Comment by navarr** [comment]
Judging by [This Mozilla Ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1007181) Google has to add your website to a whitelist in order for that not to show up?

There's no documentation about it *anywhere*.

**Comment by noahcooper** [comment]
I'm getting this same error on my page (which, to the previous question, is served over HTTPS), and not really sure how to resolve it.

This issue and the aforementioned mozilla.org bug seem to be the only places anywhere on the Internet that even mention this error message.

**Comment by petele** [comment]
rAC has been deprecated
