### ISSUE TITLE
Feedback for: /fundamentals/performance/critical-rendering-path/constructing-the-object-model.html

### ISSUE THREAD

**Issue by ahmadajmi** [google/WebFundamentals#1110]
The embedded video from Udacity height is not correctly shown as

![screen shot 2015-01-24 at 2 40 36 pm](https://cloud.githubusercontent.com/assets/626005/5887409/010335ba-a3d7-11e4-8ecc-7fe074b641ed.png)

**Comment by matt3224** [comment]
Set padding bottom to a percentage

**Comment by matt3224** [comment]
Have you got a link?

**Comment by petele** [comment]
Fixed by Udacity.
