### ISSUE TITLE
Change comments in SCSS File from /* to //

### ISSUE THREAD

**Issue by MikeMitterer** [google/WebFundamentals#1112]
In most cases it makes no sense to show SASS-comments in the generated CSS-File.

Take for example _utils.scss
`/*==========  VARIABLES  ==========*/`

You'll find `/*==========  VARIABLES  ==========*/` in the generated CSS - useless.
This should be:
`// ==========  VARIABLES  ==========`

**Comment by PaulKinlan** [comment]
Well.... They shouldn't be there at all.  Our build process should be minified completely.

**Comment by petele** [comment]
Comments are stripped by the minification process...
