### ISSUE TITLE
Move staging build server to compute

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1116]
We desperately need to move the staging build server to Compute Engine and away from my RackSpace server, we have not had a working staging environment since we introduced all the translations.  @crhym3 had started to set up the environment but we would love to get that scheduled and started.

cc @marcacohen

**Comment by crhym3** [comment]
Oh, yes, sorry about that. I'll get back to this shortly. Give me a couple
days.

I actually wanted to try Travis first, it should be easier than maintaining
a GCE instance.

Will report back here with details.

**Comment by PaulKinlan** [comment]
It's all cool, I forgot about it to until this morning when I saw my server crash :)

**Comment by PaulKinlan** [comment]
I am open to any solution you have btw, GCE was the closest to the current method.

**Comment by marcacohen** [comment]
Alex is on it.

Alex - let me know if there's anything I can do to help.

On Thu, Jan 29, 2015 at 8:29 PM, Paul Kinlan <notifications@github.com>
wrote:

> I am open to any solution you have btw, GCE was the closest to the current
> method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/WebFundamentals/issues/1116#issuecomment-72098198>
> .
>



-- 
Marc Cohen
http://about.me/marc1

**Comment by crhym3** [comment]
@PaulKinlan can you assign this to me? Meanwhile I'm forking this repo to try this out with Travis and then create a PR against this issue if this works as I imagine it will.

Or maybe I'll use @wibblymat's fork - will talk to him tomorrow.

**Comment by PaulKinlan** [comment]
@crhym3 let me add you to the project.  Looks like you aren't a member

**Comment by crhym3** [comment]
Working on it in [travis](https://github.com/google/WebFundamentals/tree/travis) branch. I'm close.
