### ISSUE TITLE
Feedback for: /fundamentals/performance/optimizing-content-efficiency/image-optimization.html

### ISSUE THREAD

**Issue by gsousa** [google/WebFundamentals#1119]
The portuguese version of this article has css issues after the explanation about the vector images making the article hard to read. Using Safari on OS X 10.10.2.

**Comment by PaulKinlan** [comment]
Can you share a quick screenshot?  I suspect there is an issue with the translation.

**Comment by gsousa** [comment]
Sure, here they are, you can see where it changes from the first screenshot
![ss1](https://cloud.githubusercontent.com/assets/71772/6728101/f7c85422-ce1e-11e4-8977-db4af51de4f6.png)
![ss2](https://cloud.githubusercontent.com/assets/71772/6728100/f7aa8b04-ce1e-11e4-8154-e8f7481aac28.png)

**Comment by PaulKinlan** [comment]
Urgh. Thanks.
