### ISSUE TITLE
Typo in /fundamentals/performance/critical-rendering-path/measure-crp.html

### ISSUE THREAD

**Issue by srus** [google/WebFundamentals#1121]
__documentContentLoaded__ should be __DOMContentLoaded__.

**Comment by PaulKinlan** [comment]
@srus did we ever pull this in ?

**Comment by srus** [comment]
Yes, you [merged it](https://github.com/google/WebFundamentals/pull/1122) with master. I accidentally closed this issue, but realized that is your decision to do that, so I reopened it.

**Comment by PaulKinlan** [comment]
Ah. Right :) I am ok with you closing it.

**Comment by srus** [comment]
:+1:
