### ISSUE TITLE
Missing word "rather" on /web/fundamentals/look-and-feel/animations/css-vs-javascript

### ISSUE THREAD

**Issue by Fastone45** [google/WebFundamentals#1123]
https://developers.google.com/web/fundamentals/look-and-feel/animations/css-vs-javascript

"If you’re already using jQuery or a JavaScript framework that includes animation functionality then you may find it more convenient overall to stick with that for your animations (rather) than switching to CSS."

**Comment by PaulKinlan** [comment]
This should be live soon.
