### ISSUE TITLE
Feedback for: /fundamentals/input/form/choose-the-best-input-type.html

### ISSUE THREAD

**Issue by Aeyoun** [google/WebFundamentals#1124]
Should inform about the limitations of `input type=number`. Its being used blindly all over. I’m thinking of the value being set to empty strings on invalid input and especially [localization problems](https://www.aeyoun.com/posts/html5-input-number-localization.html).

**Comment by PaulKinlan** [comment]
We should sort something out.  Thanks for the research btw, very insightful.  Let me have a think with @petele about what we should do.

**Comment by petele** [comment]
@Aeyoun - I'd really like to see this get fixed in Chrome & other browsers, any chance you filed a bug? If so, can you provide the links?  If not, I can file one for Chrome.  I'll also look into adding a note to the docs.

**Comment by Aeyoun** [comment]
Thanks for the interest in the problem. :)

I’d love to see it fixed! Not to discourage you, but its not really something for the browsers to fix, is it? I’m not even sure how it could be fixed. [How do you treat 100.000.000](https://twitter.com/Sleavely/status/570577951957360641)? or 100,000,000.00? My suggestion is left-most non-digit is always decimal separator. That is not always the user’s intention, though. Without an intention-reading headband reading off brainwaves its kind of hard to know what the user intended to input. Safari does this, but that is still broken. The non-space thousand separators kind of spoils the day. If you’ve ever tried copying a cell from a period-region Excel document to a comma-region Excel document, you’d just drop dead

A [non-specific spec bug](https://www.w3.org/Bugs/Public/show_bug.cgi?id=28095) was created.

**Comment by Aeyoun** [comment]
@petele, a small victory could be achieved with Firefox, though. They don’t strip leading and trailing whitespace. Big issue when user copies and pastes a number. I’ve not filed a bug on this.
