### ISSUE TITLE
Localization request

### ISSUE THREAD

**Issue by AliMD** [google/WebFundamentals#1125]
I'm a teacher, sr web developer and i want to translate this website for my peoples
Could you please add Persian (fa) support to your project and tell me your guideline to do this
Please mind Persian is a right to left language and we need to add rtl theme,  i can handle it but need your guideline
Thank you in advance

**Comment by PaulKinlan** [comment]
I believe we are mostly sorted (minus a few bugs for rtl).  You should just be able to start translating by creating the file in the fa folder and making sure the directory structure is the same .

**Comment by AliMD** [comment]
Can i any help on the bugs ?

**Comment by petele** [comment]
As Paul mentioned, we already have support for RTL languages, so it would just be a matter of submitting pull requests with the translated files.  

Take a look at the translation guide (https://github.com/google/WebFundamentals/blob/master/TRANSLATION.md) for more details!
