### ISSUE TITLE
Feedback for: /fundamentals/index.html

### ISSUE THREAD

**Issue by seito2014** [google/WebFundamentals#1129]
The link "View Source" in header doesn't work.

**Comment by PaulKinlan** [comment]
This is fixed, but not deployed. We should be live soon.

**Comment by skynet** [comment]
Tangled in Google's bureaucracy?

**Comment by PaulKinlan** [comment]
Heh, no. People went away and some priorities changed for the short term,
no all sorted.

**Comment by skynet** [comment]
Starting to re-gain some trust in the project. Thanks.
