### ISSUE TITLE
how to get the exact non-mobile-friendly pages in my website?

### ISSUE THREAD

**Issue by GeraldineF** [google/WebFundamentals#1130]
Just what I said in the title, how can I get the exact non-mobile-friendly pages of my website? Is there any tools to report me the details of which pages of my website are non-mobile-friendly? I can't download the data in google master of problems detected on non-mobile-friendly pages.

**Comment by PaulKinlan** [comment]
Good question, I don;t know.  I will find out.  In a lot of cases it it is the entire site.

**Comment by pierrefar** [comment]
@GeraldineF Are you referring to the Mobile Usability report in Webmaster Tools? It's described here:

http://googlewebmastercentral.blogspot.co.uk/2014/10/tracking-mobile-usability-in-webmaster.html

If you click on each type of problem in the report, you'll see the pages we found. In reality, most developers would spot a pattern and do a single fix that covers many (if not all) pages.
