### ISSUE TITLE
Build and Node v0.12.0 !== Fun Times

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1135]
There are issues with grunt-sass running on node v0.12.0. When installing I get this issue:

    Error: Module did not self-register.

The fix for this seems to be to use the beta version of node-sass and there is a PR open for this: https://github.com/sindresorhus/grunt-sass/pull/179

I've just tried it but this throws a different error of the grunt file not being able to find the sass module.

No actions can really be taken from this right now, but it will need sorting at some point.

**Comment by wibblymat** [comment]
Yes, right now the answer is to use 0.10. I heartily recommend using nvm anyway, and this is another good reason.

**Comment by arthurvr** [comment]
It's good the nvm instructions were added to the readme for now, but that doesn't solve the actual issue. The build system is complicated enough, so we might first want to try fix the actual issue.

**Comment by gauntface** [comment]
Arthur - there is a number of issues at play - foremost, node-sass doesn't work with newer versions of node, so we can't change anything until that is fixed.

**Comment by arthurvr** [comment]
I agree sometimes you just have to wait for upstreams but to follow that up I'd rather keep this ticket open. I just mean, our build system is complicated enough, if we have the chance to get rid of an extra step we need to do so.
