### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by skynet** [google/WebFundamentals#1136]
View Source link, front page, top right, is "fundamentally" wrong.

https://developers.google.com/web/fundamentals/

![screenshot_1](https://cloud.githubusercontent.com/assets/139233/6148328/946dff1a-b1ce-11e4-86a7-90f6219684dd.png)

**Comment by arthurvr** [comment]
Duplicate of https://github.com/google/WebFundamentals/issues/1132, https://github.com/google/WebFundamentals/issues/1129 and #1133.

**Comment by PaulKinlan** [comment]
I believe this has been fixed and is getting ready for deployment.  We've had a fallow few months in terms of updates and we should be sorting that asap.

**Comment by skynet** [comment]
:+1:
