### ISSUE TITLE
Feedback for: /fundamentals/principles/index.html

### ISSUE THREAD

**Issue by SergeySergey** [google/WebFundamentals#1140]
![default](https://cloud.githubusercontent.com/assets/10985874/6180793/95c32306-b375-11e4-8a4e-a9a133affbfc.png)

**Comment by PaulKinlan** [comment]
Good spot, we will take a look.  It shouldn't be doing this (I suspect it because the title is massive)

**Comment by petele** [comment]
I believe this has been fixed in our latest update.
