### ISSUE TITLE
Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/responsive.html

### ISSUE THREAD

**Issue by gpolyn** [google/WebFundamentals#1141]
your snippets refer to assets I don't see in the starter kit, viz., images. Are you all sure your page 'syncs' with the previous tutorial linked page?

**Comment by PaulKinlan** [comment]
The starter kit and the getting started guide are not the same project.  Starter Kit is a tool for any site builder, the Getting started guide is a very simple step by step....
