### ISSUE TITLE
[IT] Feedback for: /fundamentals/layouts/rwd-fundamentals/use-media-queries.html

### ISSUE THREAD

**Issue by msorgato** [google/WebFundamentals#1147]
Subito dopo l'esempio con le media query per selezionare i diversi file CSS da applicare, la frase "Se l’altezza del browser è superiore all’altezza viene applicato portrait.css." è sbagliata. In particolare, la seconda "altezza" dovrebbe essere sostituita da "larghezza".

**Comment by petele** [comment]
Translation: Immediately following the example with media queries to select the different CSS files to be applied, the phrase "If the height is greater than the height of the browser is applied portrait.css." is wrong. In particular, the second "height" should be replaced by "width".

**Comment by petele** [comment]
Fixed, not 100% sure I got it right, but it's better than it was.
