### ISSUE TITLE
Warning: EMFILE, too many open files 'appengine/build'

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1148]
I've just tried to build WebFundamentals and have to do the following:

- nvm use 0.10
- Do some magical incantation to make "Warning: EMFILE, too many open files 'appengine/build'" shut up <- Which seems to be getting harder and harder to fix.

I know there is something along the lines of: http://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os

Can we just add these steps to the make server script?

What ever works.

**Comment by PaulKinlan** [comment]
We could I suppose, I worry though that that is mucking about with a system
setting that the developer might have already over-ridded.

**Comment by gauntface** [comment]
At the moment I need something, searching over and over is annoying and nvm use is again a massive pain. Even if the only thing we do it show errors - "Oops your on node v 0.X.X <- we need 0.10, try running nvm use 0.10"

The EMFile thing  - a tip to add "launchctl limit maxfiles 2048 2048 " to .bashrc or .zshrc would be handy.

Searching every time is annoying.

**Comment by PaulKinlan** [comment]
gotcha.
