### ISSUE TITLE
in_header false values in the yaml files

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1149]
I'm just looking through the source for WebFundamentals and there are a few cases where the yaml files are declaring in_header: false.

_betterbook-showcase.yaml is a good example. 

		toc:
		- title: "Web <strong>Showcase</strong>"
		  path: /showcase/
		  home: true
		- title: "Case Studies"
		  path: /showcase/case-study/
		- title: "Spotlights"
		  path: /showcase/spotlight/
		- title: Web <strong>Fundamentals</strong>
		  path: /fundamentals/
		  in_header: false
		- title: Web <strong>Starter Kit</strong>
		  path: /starter-kit/
		  in_header: false

Is there any reason behind this? Looks like it's not needed.

**Comment by PaulKinlan** [comment]
You'll have to ask @pbakaus as that is his file, I can't find any references to it.

**Comment by PaulKinlan** [comment]
Acutally, I typed it wrong.

**Comment by gauntface** [comment]
It's not just that file, it's in betterbook-wsk and betterbook

**Comment by PaulKinlan** [comment]
Right, so it is used to determine if it should be placed as a header item in the main bar.  navigation.liquid uses it. 

This should allow us to deploy sub-sections of the site and have them live, but not, importantly have them linked from anywhere.

**Comment by gauntface** [comment]
Right - so its useful adding the links you think you'll want when a site goes live, but otherwise there is no reason.

**Comment by PaulKinlan** [comment]
It controls whether it will be in the header or not, the build normally resolves everything automatically

**Comment by gauntface** [comment]
so no intention to add that link to header === useless having it in the betterbook.

**Comment by PaulKinlan** [comment]
I believe we might use it to stop pages appearing in other categories too.

**Comment by pbakaus** [comment]
I wish the links in the footer would be automatically put in, but currently that's the way of defining them.
