### ISSUE TITLE
[EN] Feedback for: /fundamentals/look-and-feel/index.html

### ISSUE THREAD

**Issue by siavashr** [google/WebFundamentals#1151]
I don't see anything about colors and typefaces. Is it under development?

**Comment by PaulKinlan** [comment]
cc @paullewis

**Comment by petele** [comment]
Personally I'd rather push people towards the Material Design content, although it's Material Design specific, the theory is still valid.

**Comment by petele** [comment]
I think we should be pushing people towards MD spec, need content on this.
