### ISSUE TITLE
[EN] Feedback for: /fundamentals/getting-started/web-starter-kit/setting-up.html

### ISSUE THREAD

**Issue by dturner** [google/WebFundamentals#1153]
"The first step is to go to https://developers.google.com/web/starter-kit/ and download and extract the zip." 

I think it's worth adding that the extracted folder will become the starting point for your project and as such should be renamed and moved into an appropriate location, for example ~/projects/new_project.

**Comment by gauntface** [comment]
@dturner thoughts on this commit?

**Comment by arthurvr** [comment]
Looks good.

**Comment by dturner** [comment]
LGTM. Although you're missing an l off `gem instal`

**Comment by gauntface** [comment]
It's there - BUT it's going away as a requirement in the next release ;)

https://developers.google.com/web/fundamentals/getting-started/web-starter-kit/setting-up?hl=en#sass

**Comment by arthurvr** [comment]
> It's there - BUT it's going away as a requirement in the next release ;)

It is already away in the latest wsk, isn't it?

**Comment by gauntface** [comment]
I think so but don't know for sure - I'm out of the loop on WSK, getting back into this week and will update the docs accordingly.
