### ISSUE TITLE
[IT] Feedback for: https://developers.google.com/web/fundamentals/getting-started/?hl=it

### ISSUE THREAD

**Issue by trimalcione** [google/WebFundamentals#1154]
"Start Your Site with Web Starter Kit" in https://developers.google.com/web/fundamentals/getting-started/?hl=it and all its subsections are not translated in Italian, whereas the right section is available in Italian too.

**Comment by PaulKinlan** [comment]
Yep, we didn't have the resources to do it all, but we needed some critical
pages translated.

P
