### ISSUE TITLE
[FR] Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/responsive.html

### ISSUE THREAD

**Issue by ConsultingBa** [google/WebFundamentals#1156]
Honestly your blogpage is the example of what not to do.... Your page may display well on a smartphone and gets displayed on a desktop but it is by far not adapted for a desktop screen. How can you display a method for multi-screen in a way leaves 2/3 of the desktop screen unused or uses front size 46? If your method for multi-screen is make a smartphone page and display it on a desktop well than no tanks. Your page gets so long that it is a pain to navigate with a mouse scroll. No sidebar for navigation on a web developer page ? really ?

You are a web developer so why not develop something like a table that gets displayed side by side on large screens but one below the other on a small screen.
like 
A1 A2 A3
B1 B2 B3
on desktop and
A1
A2
A3
B1
B2
B3
on smartphone
I don't know something that is really suited for all screens....

**Comment by PaulKinlan** [comment]
It's an example of what you can do and is a good first starting point.  Centering and using a max width is  valid technique to handle larger desktop screens.

We are in no way making a smartphone page and showing on desktop.

You don't need sidebars for navigation if you don't want it.
