### ISSUE TITLE
[EN] Feedback for: /fundamentals/performance/optimizing-content-efficiency/http-caching.html

### ISSUE THREAD

**Issue by yeller62** [google/WebFundamentals#1157]
Although I found some of the information in this article helpful, I think it would have been helpful if they would have specified if you could setup caching for individual files (if you wanted to cache some jpegs but not all).  Further, the apache config information they linked to didn't appear to show how to setup cache-control.

It would have been nice if they had clear examples of what you could and couldn't accomplish with cache-control.

**Comment by petele** [comment]
@igrigorik - can you evaluate and decide if it's worth including, if not please close.
