### ISSUE TITLE
[EN] Feedback for: /fundamentals/getting-started/web-starter-kit/setting-up.html

### ISSUE THREAD

**Issue by ankurmishracse** [google/WebFundamentals#1159]
Hello,
I am not able to set it up, when I run "gulp serve" command I get this page ( http://pbrd.co/1E8odaX ). Please help me.
Thanks.
Ankur

**Comment by PaulKinlan** [comment]
What is the output of the command-line?

**Comment by PaulKinlan** [comment]
It looks like Sass is not running..

**Comment by ankurmishracse** [comment]
Output of command-line is-
root@hp:/var/www/gws# gulp serve
[13:48:31] Using gulpfile /var/www/gws/gulpfile.js
[13:48:31] Starting 'styles'...
{ message: 'spawn ENOENT: Missing the Sass executable. Please install and make available on your PATH.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-ruby-sass',
  __safety: { toString: [Function] } }
[13:48:43] 'styles' all files 0 B
[13:48:43] Finished 'styles' after 12 s
[13:48:43] Starting 'serve'...
[13:48:43] Finished 'serve' after 273 ms
[BS] Local URL: http://localhost:3000
[BS] External URL: http://172.20.117.78:3000
[BS] Serving files from: .tmp
[BS] Serving files from: app



I've followed this link-
https://developers.google.com/web/fundamentals/getting-started/web-starter-kit/?hl=en

**Comment by petele** [comment]
As Paul mentioned, it looks like Sass is not installed.  We'll get the docs updated to include ways to ensure that it is.  Check out http://www.sass-lang.com/install for instructions on how to install Sass.
