### ISSUE TITLE
[EN] Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/responsive.html

### ISSUE THREAD

**Issue by guzie** [google/WebFundamentals#1161]
This is somewhat over my head.  Is there someone we can converse with to help us make our site mobile friendly?  
http://guzmansgreenhouse.com
Paul Guzmamn

**Comment by PaulKinlan** [comment]
It's not going to be easy to convert your site.  Hmm, it might be best using a tool to help you such as squarespace, or adsy.me

**Comment by guzie** [comment]
Thanks for the response Paul.  Both of these sites want us to build a website.  Ours is already built.  We've been online since about 2002.  With great local success.  We have been happy with our search results. We are a small mom and pop gardening retail store.  The adsense ads help with monthly revenue.  It is a shame that Google will penalize our website solely on the mobile issue.
We have been looking for web developers to help us but most are charging more than what we can afford.  Again we ask "Is there someone who can guide us through the right steps" without using technical jargon that is above our expertise.
Regards
Paul Guzman
guzmansgreenhouse.com
