### ISSUE TITLE
What would you say about mobile web apps using websites?

### ISSUE THREAD

**Issue by dewmini28** [google/WebFundamentals#1164]
If you were forcing all users to convert to responsive layouts, whats happening for people who use mobile web apps like 'Duda mobile sites' for their mobile users? Why can't you put some notes/google fundamentals for people to follow guidance for mobile app using websites/etc..????

**Comment by PaulKinlan** [comment]
I don't really want people using transpilers for this, I would rather teach people the fundamentals about how to build great mobile and desktop sites.
