### ISSUE TITLE
Issues with 404 redirects

### ISSUE THREAD

**Issue by Lori1072** [google/WebFundamentals#1166]
On March 18, 2015 I have had several soft 404 redirects and do not know why. If someone is experienced in cheeking this out, would be appreciated, I think it refers to my website, but do not know the connection I have a redirect plug in but this will not suffice for the issue. As always I appreciate your imput Thanks To all..

**Comment by petele** [comment]
Sorry, this issue tracker is for issues with Web Fundamentals. You'll need to work with your web team to figure out what's going on with your site.

**Comment by Lori1072** [comment]
Thank you.!
