### ISSUE TITLE
[PT-BR] Feedback for: /fundamentals/performance/optimizing-content-efficiency/image-optimization.html

### ISSUE THREAD

**Issue by russ-ab** [google/WebFundamentals#1170]
There's a problem after the vector/rasterized image which is crashing all the layout after that.

**Comment by PaulKinlan** [comment]
Thanks for the report. We'll look into it.

**Comment by petele** [comment]
This is fixed in staging already, just need to push live, likely sometime later this week

**Comment by petele** [comment]
https://web-central.appspot.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization?hl=pt-br
