### ISSUE TITLE
[NL] Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/responsive.html

### ISSUE THREAD

**Issue by fjordkonijn** [google/WebFundamentals#1172]
Hi guys,

Thanks for these very interesting guidelines. The translation in Dutch can use some improvement:
"Voeg een viewport" > "Voeg een viewport in"
"Solliciteer eenvoudige stijl" > "Pas eenvoudige stijl toe"
"Stel uw eerste breekpunt" > "Stel uw eerste breekpunt in"
BR,
FK

**Comment by arthurvr** [comment]
Honestly, it can use much more improvements than that :) I'm def. +1 on the changes you suggest.

**Comment by PaulKinlan** [comment]
@fjordkonijn - thanks
@arthurvr - do you have more details?  The translations were provided by an external agency how don't specialize in web development.  The source is open and we happily accept and credit translations to the author.

**Comment by arthurvr** [comment]
I will see if I can PR something.
