### ISSUE TITLE
Web Fundamental project not persuasive

### ISSUE THREAD

**Issue by phronimos** [google/WebFundamentals#1177]
On 3/23/2015 3:03 AM, Paul Kinlan wrote to

https://github.com/google/WebFundamentals/issues/1174

right before closing it:

> Sorry, this isn't a discussion forum to decide on
> whether you should go mobile or not.  This is an
> Issue tracker to deal with issues in the guidance
> of the Web Fundamental project that helps you
> once you've made that decision.

For the record, I didn't come to

https://developers.google.com/web/fundamentals/

for a discussion forum. I came here because Google directed me to come here in order to "Learn about mobile-friendly design" and "Fix mobile usability issues on your site."

It was only after I got here that I read

	"We're just getting started and want your help, if you see
	something amiss or have a suggestion file an issue or submit
	a pull request."
	
which I evidently misinterpreted as an invitation to dialogue.

But that has not been my only disappointment.

The project home page promises to deliver "Best practices for modern web development."

What I actually found here: uninspired, cookie-cutter design solutions which I am apparently too simple-minded to understand and implement properly.

And so I leave you now having decided that Google's "best practice guidance" and design strategy are flawed ... so flawed, in fact, that I would rather forgo higher search engine rankings than comply with the Google-mandated design standards.

In short, I will not be bullied by Google or anyone else into making design trade-offs that I believe will compromise the quality of the educational content that I offer.

I'm not finished complaining about Google's imposition of a dogmatic "mobile-friendly design" standard on all the content creators out there, but I accept that this is not the appropriate forum for that.

Further deliberation of this much bigger issue belongs instead at

	"The Website which Google Search Thinks You Can't Handle"

-- a new label I'm playing with for my website with the 3 pages

http://roses.communicatingbydesign.com/news/RosesNews.html

http://roses.communicatingbydesign.com/FYI_cancer-and-the-retail-economy.html

http://roses.communicatingbydesign.com/ToC.html

which Google Search has designated "not mobile-friendly" and ranked accordingly.

Deborah

**Comment by petele** [comment]
Hi Deborah,

Content should look good on any device your users choose to use, whether it's a desktop, tablet or cell phone. Mobile friendly doesn't mean creating a separate site, removing or paring down content, in fact - we [strongly discourage](http://goo.gl/U4p45J) that, and instead recommend developers use the space available to them more efficiently.

I took a look at your site on my cell phone and found the text in the header too small to read, and the body text is smaller than ideal. The teal margins use valuable space that could be used to expand the content.

This forum is meant for discussion of issues directly related to content in Web Fundamentals, if you have recommendations or specific feedback, I'm happy to take a look at those.  The [Web Masters 
group](https://productforums.google.com/forum/#!forum/webmasters) is a better forum to discuss the changes to search.

Thanks,
PEte

**Comment by phronimos** [comment]
On 3/24/2015 12:40 PM, Pete LePage wrote:
> Mobile friendly doesn't mean creating a separate site, removing or paring down content

I never thought it did. My comments apply directly to the 3 "errors" 
that Google cited me for and I described in my earlier post to

https://github.com/google/WebFundamentals/issues/1173

and give here again now:

1. Touch elements too close.
2. Viewport not configured.
3. Small font size.

These are all issues I've thought long and hard about in the past, and 
I chose to do it the way I've done it not because I didn't know any 
better, but because I felt I was making the best trade-offs I could 
make under the circumstances.

I agree that it's optimal to have as flexible a design as one can 
manage, but I don't agree with the philosophy that it's possible to 
have it all. ;-)

Good designers know all too well that we live in a world of freedoms 
and constraints. Navigating that dialectic is basically what good 
design is all about, and given my purpose and target audience, there 
are limits to how much I'm going to sacrifice readability and visual 
rhetoric on the desktop for ease of use on a mobile phone.

To give just one example: the Web Fundamentals guide emphasizes 
scalability (e.g., percentages instead of a fixed-width viewport, 
etc.). But I deliberately don't do this because I find the outcome on 
my desktop unreadable (and since I regularly read thousands of pages 
of text on my desktop, this kind of thing matters a great deal to me).

I *loathe* trying to read text that scales to fit my 24" monitor (1920 
x 1200 resolution) -- lines of text end up way too long, and I'm 
unable to read comfortably for more than about 5 minutes before I 
suffer eyestrain and get a headache. So I actively avoid any website 
that has made this design choice if at all possible.

Regarding the matter of "Use Legible Font Sizes" (I'm quoting from the 
guide again), this is *really* complicated when one is limited to 
"Web-safe fonts" and having to make all sorts of difficult trade-offs 
because of variations in font metrics ... let alone which fonts 
display italics well, at which sizes ... and lots more concerns I have 
(e.g., I use different font sizes to layer information, and there's no 
way I'm going to set a caption the same size as body text or indented 
quotes).

I am actually very concerned about this issue, have written some about 
it here:

http://she-philosopher.org/home/technical/BrowserProblems.html

and have a companion essay on font metrics "under construction."

Suffice it to say that from my perspective, all things having to do 
with fonts are already impossibly complicated on the desktop, and 
until I can figure out a proper solution for that platform, I'm not 
going to worry about mobile phones. ;-)

... Well, it's been a long day, and I'm too tired to tackle more right 
now.

I apologize for not responding sooner (I just assumed my Issue was 
going to be closed right after I opened it, and so moved onto other 
things; hence, I didn't know you had replied until checking e-mail 
late this evening).

My schedule is such that I won't be able to engage more on this 
tomorrow, but I will come back to it after that if this Issue is still 
open and there is any interest in what more I have to say.

Deborah

**Comment by petele** [comment]
> but I don't agree with the philosophy that it's possible to have it all. ;-)

We believe that it is, and have tried to design Web Fundamentals to give you the skills to accomplish responsive design practices. Unfortunately, forum isn't the place to discuss the the benefits & drawbacks of responsive design.

**Comment by phronimos** [comment]
On 3/25/2015 1:32 AM, Pete LePage wrote:
> We believe that it is, and have tried to design Web Fundamentals to give you the skills to accomplish responsive design practices. Unfortunately, forum isn't the place to discuss the the benefits & drawbacks of responsive design.

But it's not "the benefits and drawbacks of responsive design" that I 
want to discuss either. I only bring this up because the responses to 
my posts keep pushing me in this direction.

 From the beginning, I've been interested in the more granular stuff: 
i.e., Google's design dictates regarding the 3 errors for which my 
website has been cited and given low rankings:

1. Touch elements too close.
2. Viewport not configured.
3. Small font size.

Although it may not seem like it, all of my previous comments and 
complaints have to do with these 3 "errors", and Google's 
determination of which "best practices" I must use to fix them.

Believe it or not, I came to the Web Fundamentals guide to learn (not 
to judge).

But the truth is, I didn't find what I was looking for.

So, on the off-chance that my experience might help address this 
problem (which I am clearly not the only one to have), let me try one 
more time to give you examples of the sorts of problems I face in 
relying on the guide to make my websites "mobile-friendly".

Let's take error No. 2.

First, I went to Google's page on "Mobile Usability", where I read

	"Content not sized to viewport
	"This report indicates pages where horizontal scrolling is
	necessary to see words and images on the page. This happens
	when pages use absolute values in CSS declarations, or use
	images designed to look best at a specific browser width
	(such as 980px). To fix this error, make sure the pages use
	relative width and position values for CSS elements, and make
	sure images can scale as well. Read more in _Size Content to
	Viewport_."
	< https://support.google.com/webmasters/answer/6101188 >

Images sizes are a really big deal for me, so this got my attention -- 
set me to wondering how I could do away with fixed image sizes, and if 
this would improve my content or not. So, from here, on to your "Size 
content to the viewport" page next, where I read:

	"Content should not rely on a particular viewport width to
	render well."

	"... an image that is displayed at a width wider than the
	viewport can cause the viewport to scroll horizontally. You
	should adjust this content to fit within the width of the
	viewport, so that the user does not need to scroll
	horizontally."

	"Setting large absolute CSS widths for page elements (such as
	the example below), will cause the [div] to be too wide for
	the viewport on a narrower device (e.g. a device with a width
	of 320 CSS pixels, such as an iPhone). Instead, consider
	using relative width values, such as [width: 100%].
	Similarly, beware of using large absolute positioning values
	that may cause the element to fall outside the viewport on
	small screens."

	< 
https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/size-content-to-the-viewport 
 >

OK, but I still have the same questions as before -- plus some new 
ones, such as about the "320 CSS pixels" number, which is a completely 
mysterious metric to me -- so I move on next to your "Use CSS media 
queries for responsiveness" page, where I read more general claims I 
find interesting, such as:

	"A key concept behind responsive design is fluidity and
	proportionality as opposed to fixed width layouts. Using
	relative units for measurements can help simplify layouts and
	prevent accidentally creating components that are too big for
	the viewport."
	< 
https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/use-media-queries?hl=en 
 >

but nothing here specific to working with images, which are *so* 
integral to my scholarly content, that you need to win me over here 
first if there's going to be any hope of my adopting your 
"mobile-friendly" "best practices".

I produce a lot of digital facsimiles of 17th-century texts, maps, and 
pictures for serious scholars who need to know exact sizes of digital 
facsimiles in order to correct for 1:1 camera ratios which are easily 
distorted by the different optical technologies. In other words, my 
images need to stand up to the rigors of physical bibliography (e.g., 
detailed studies of antique binding tools or of Aldus's fleurons, and 
detailed comparisons of head- and tail-pieces published in over 100 
different rare books so that scholars can determine whether a 
particular woodblock was passed from printer A to printer B).

Moreover, some of the images I work with are huge. How do I do away 
with fixed-width sizes when we're dealing with an antique map which at 
100% is a 125+ MB file, 9719 x 7203 pixels ??? or the type specimen of 
Christoffel van Dyck, published by his widow in 1681, which at 100% is 
a 281MB file, sized at 8594 x 10877 pixels ???

I also sometimes rely on fixed image sizes to protect copyright 
(images that can't scale well, won't be able to be easily printed on, 
say, a poster).

So for me, at least, at this point in my discovery process, the guide 
has raised more questions than it has answered. Thus, I move on to the 
next section, "How to choose breakpoints".

Again, I agree in principle with general claims such as:

	"Classic readability theory suggests that an ideal column
	should contain 70 to 80 characters per line (about 8 to 10
	words in English), thus each time the width of a text block
	grows past about 10 words, a breakpoint should be considered."
	< 
https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints?hl=en 
 >

But your example -- a weather forecast -- tells me nothing at all 
about how I'm supposed to adapt these guidelines to revise complicated 
page layouts such as that at

http://she-philosopher.org/ib/topics/Pythagoreans.html

(with its assortment of fixed-width images) ... let alone the gallery 
exhibit at

http://she-philosopher.org/gallery/atheniansociety2.html

which (like almost all the gallery exhibits at this website) needs to 
be updated to tableless layouts in the very near future.

I find the challenge of redesigning this website's gallery exhibits 
daunting enough when designing for a variety of 
desktops/laptops/notebooks/ultrabooks/tablets running 
who-knows-how-many different browsers.

And now I'm being told to undergo a very expensive and time-consuming 
gestalt shift to make my websites "mobile-friendly", with little to no 
guidance how I do this.

I don't think it's unnatural for me to actively resist when Google 
Search demands -- as I said before -- that I re-"design content that 
it hasn't even indexed and doesn't understand" (and I know your tone 
in the guide is properly suggestive rather than commanding, but Google 
Search's threats and system of autocratic rankings are anything but).

Nonetheless, I must also admit that now is actually the best time to 
get me to entertain moving to a more "mobile-friendly" design, since 
I'm currently in the process of aggressively redesigning at least 2 
websites.

So, after much debate with myself, I have decided to tackle error No. 
2, and try out "relative width and position values for CSS elements, 
and make sure images can scale as well" at my website with the most 
simple layout.

I am still opposed to your prescribed fixes for errors No. 1 and No. 3.

... But at least 1 out of 3 is better than none, right? ;-)

Deborah
