### ISSUE TITLE
Add content for maintaining aspect ratio on YouTube videos

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1179]
In the Video's section we should include some best practices for maintaining aspect ratio of embedded videos while still be responsive.

**Comment by samdutton** [comment]
Not perfect, but could add something like [this technique](https://youtu.be/j5fYOYrsocs?t=6m49s).

**Comment by gauntface** [comment]
+1 that technique. I think everyone does it.

**Comment by petele** [comment]
This was incorrectly tagged, it's new content that's needed. Assigning to @samdutton to do and push.
