### ISSUE TITLE
label-and-name-inputs.html feedback: method=post mention is incorrect

### ISSUE THREAD

**Issue by paulirish** [google/WebFundamentals#1183]
> Auto-complete only works when the form method is post.

AFAIK this isn't true.

Forked from internal bug 89647407

We can check with thestig to confirm, but I think this is unnecessary. 

@petele

**Comment by PaulKinlan** [comment]
I believe we tested this with a get and it didn't work... Happy to check
again and correct if needed.

**Comment by paulirish** [comment]
GET forms are probably blacklisted, but a parent `form` element isn't mandatory.

The internal bug was concerning a form without a form element.

**Comment by petele** [comment]
Did a quick test with http://jsbin.com/mufozevami/1/edit?html and it looks like they're not required any more. thanks for the update!

**Comment by petele** [comment]
Fixed in a1f0c1fe454691c370e16038858b47921ba86f5a
