### ISSUE TITLE
[EN] Feedback for: /fundamentals/tools/setup/commandlinetools.html

### ISSUE THREAD

**Issue by kwilkinson149** [google/WebFundamentals#1184]
Love the advice that is given to maximise the customer experience. Pity it is not followed. Downloading the web-kit is not a pleasant experience, I would expect it to work straight out of the box. It does not. Plenty of errors, including gulp server not working due to a browser sync error. Beta or no Beta, this should not be the case. I know the software is free and you get what you pay for, but I didn't even get the free version to evaluate. Precious time will now be spent looking for a work around. As an educator, my advice to my students will be to steer clear of this. You might not be interested in my comments - or they might not meet your guidelines, but I am a customer and this is my experience.

**Comment by pbakaus** [comment]
Thanks for your comment. Please file any issues you have with Web Starter Kit in the WSK repository: https://github.com/google/web-starter-kit

I also encourage you to be specific about your issue so they can address it.
