### ISSUE TITLE
[EN] Feedback for: /fundamentals/input/form/label-and-name-inputs.html

### ISSUE THREAD

**Issue by RobBelics** [google/WebFundamentals#1187]
The autocomplete attribute for Address in the table about 2/3 way down is shown as "address-level-1" and "address-level-2". However, those attributes should not have a hyphen after the word "level". 

Should be: "address-level1" and "address-level2".

**Comment by petele** [comment]
Thanks @RobBelics  - I fixed that late Friday and it should go live sometime next week.

**Comment by petele** [comment]
Pushed live.
