### ISSUE TITLE
Case studies should link to why the web when the dev's idea's match ours

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1192]
For instance in https://developers.google.com/web/showcase/spotlight/0hh1 when @mrtnkl says "But honestly, you can go from zero to 88 MPH in no time" we should link to the principles https://developers.google.com/web/choosing-the-web?hl=en#instant-load

**Comment by pbakaus** [comment]
Very good point but closing for now as the page is inaccessible now.
