### ISSUE TITLE
Why the web... "Long lasting"

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1193]
This might need to be changed a bit because all browsers deprecate features etc showModalDialog for example.

**Comment by petele** [comment]
@pbakaus can you please address

**Comment by pbakaus** [comment]
I think this one holds true. Sure, there are exceptions, but very few if you look closely. The paragraph is worded in a way that doesn't explicitely promise backward compability ("it means that your users will probably be able to use your site 20 years from now"), so I think it's OK.

**Comment by pbakaus** [comment]
(accidentally closed, close if you think this addresses your concern).
