### ISSUE TITLE
Change Why the web religious phrasing. [EN] Feedback for: /index.html

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1195]
I am as Atheist as they come but don't like the following phrasing or the association with religious wars:

>There are religious all-out battles between developers who embrace native applications and those that live and die for the openness of the web platform. Unfortunately, both sides are blinded in their beliefs and forget that choosing a platform needs to be a well researched and thoughtful decision that works for your business.

We can still create a strong phrasing. How about:

> There are many philosophical debates between developers who embrace native application development and those who build on the open web platform about why their platform is best.  We believe the web is a good platform to build up for the following reasons:

**Comment by petele** [comment]
@pbakaus can you please address

**Comment by jpmedley** [comment]
The suggested intro is good, but there's still useful material we haven't reused. So...

 "There are many philosophical debates between developers who embrace native application development and those who build on the open web about why their platform is best. We believe the web is a good platform to build up for many reasons."

"Let’s explore why you should choose the web and walk through some of the unique user-facing abilities and features the open web platform provides."

**Comment by PaulKinlan** [comment]
Sgtm.
