### ISSUE TITLE
Emphemeral is not about low friction to use - [EN] Feedback for: /index.html

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1196]
> Ephemeral
> Clicking on a link is effortless compared to installing a native app.

I don't think this captures Ephemeral well.  I like Ephemerality as one of the reasons, therefore I would add another section call "Low Friction" and talk about the low barriers to entry because of no install process.

**Comment by petele** [comment]
@pbakaus - can you please address

**Comment by pbakaus** [comment]
Fair point! Closing for now as the doc is in limbo, but in the internal doc, I renamed Ephemeral to Install Free and added a to do to add a paragraph about Ephemeral when we redeploy.
