### ISSUE TITLE
Change introduction on why the web [EN] Feedback for: /choosing-the-web.html

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1198]
> There are religious all-out battles between developers who embrace native applications and those that live and die for the openness of the web platform. Unfortunately, both sides are blinded in their beliefs and forget that choosing a platform needs to be a well researched and thoughtful decision that works f or your business.

> “Because it’s the right thing to do” is a just not a valid argument, unless we’re talking about ethics. So let’s help you figure out if, and when you should choose the web and walk through some of the unique user-facing abilities and features the open web platform provides.

See issue #1195

**Comment by petele** [comment]
@pbakaus  - can you please address

**Comment by pbakaus** [comment]
This one was fixed by @jpmedley a while ago.
