### ISSUE TITLE
EntityRef Error in ATOM feed

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1200]
https://developers.google.com/web/feed.xml

This looks like we haven't encoded & correctly in the href this is causing some feed readers to fail.  ReadKit for example.

**Comment by petele** [comment]
This'll need to get fixed in /shows/feed.xml and subdir's there too please.

**Comment by PaulKinlan** [comment]
They all seem to refer to the base template iirc.

**Comment by gauntface** [comment]
This was the result of the utm being added.

Needed the ampersand to be &amp;.

{% assign utm = '?utm_source=feed&amp;utm_medium=feed&amp;utm_campaign=shows_feed' %}

**Comment by gauntface** [comment]
Looking at this, I'm probably going to move the utm to be inside the feed.xml template for shows and insert the showid automatically rather than manually like it is now, at the moment this bug is in feed.xml.

**Comment by gauntface** [comment]
Should be fixed by: https://github.com/google/WebFundamentals/commit/8d4072293d0bee85df0ff3a53c77b76bd405064f

**Comment by PaulKinlan** [comment]
It can't be ampersand it needs to be &amp;

**Comment by gauntface** [comment]
That's what the commit does - or am I missing something?

**Comment by PaulKinlan** [comment]
I'll be honest, I was replying to an email that didn't encode &

**Comment by PaulKinlan** [comment]
Although that commit does not reference it.
