### ISSUE TITLE
Increase information density on mobile stylesheet

### ISSUE THREAD

**Issue by mahemoff** [google/WebFundamentals#1202]
The mobile stylesheet for the Web Fundamentals website uses large fonts and a lot of vertical margins. These look great on desktop, but I was trying to read this today inside Nuzzel's chrome and had to Pocket it as there just isn't much content within a screenful. The screenshot is admittedly cherry-picked but conveys the basic issue that applies elsewhere.

I think it just needs a small amount of tweaking the mobile stylesheet to be much more readable on phones.

![2015-03-30_14_46_30_png_and_new_issue_ _google_webfundamentals](https://cloud.githubusercontent.com/assets/55860/6905127/bea38dd0-d71d-11e4-9ab0-aa2407838b78.jpg)

**Comment by PaulKinlan** [comment]
Vertical spacing is something that has frustrated me for a long time. I
like the general font size but headings are certainly way to large

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
