### ISSUE TITLE
Unclear navigation

### ISSUE THREAD

**Issue by paulirish** [google/WebFundamentals#1203]
Today is a good example of how I was confused by our nav structure. Wanted to link to the [new rendering perf content](https://developers.google.com/web/fundamentals/performance/rendering/index?hl=en). 
> "Look, here's the soup-to-nuts rendering perf overview. This'll be the canonical starting point going forward.". 

(In a less Paul Irish-driven usecase, we do need an answer for someone asking "tell me what i need to know to improve the runtime of my webapp".)

but so... how do we recommend linking to this content?

## issue: no highlevel nav 

There's this (very tall) box: 
![](http://i.imgur.com/rLNEMsg.png)

But it turns out the header is actually a link to the overview, which I only attempted because I knew there was one more page I was missing. I wouldn't have tried clicking it if I didn't know.

So this #anchor'd content didnt work for me to link to. 

However linking to https://developers.google.com/web/fundamentals/performance/rendering/ doesnt work either because it's page 1 out of 7, which isn't clear until you get to the bottom of the page and start to read that.

## issue. unclear "continue reading" action.

As I finish reading the intro article I get down to these two big blocks. 

![](http://i.imgur.com/DeraNEJ.png)

I want to continue reading so "Next" feels like the right choice. But these actually make me exit the current content and change into a new topic.

Meanwhile the "guides" is essentially my pagination of this content. But the term "Guides" doesn't make any sense at the bottom of the page.

<hr>

Hopefully that makes sense and you can understand how I get lost as a user reading the content.  I could propose some solutions, but I imagine everyone else has already come up with better ideas than mine.

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.

**Comment by paulirish** [comment]
sgtm

thx!
