### ISSUE TITLE
[EN] Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/content.html

### ISSUE THREAD

**Issue by fullakingi** [google/WebFundamentals#1208]
Positive feedback.

thanks a lot for this resources guys. Really appreciate the language level and the videos are useful.  As a marketer and designer coming into front-end dev, I am trying to achieve blazingly fast google page speed insight scores on the projects i am developing because users demand it. i am 100% self-taught and these videos arent too code-jargony - T H A N K S.  i realise now my development environment sucks.  im editing on brackets on my mac, then uploading my files via ftp and testing. this last process is overly time consuming so I really appreciate sharing some insights around setting up a development environment, workflow and tools. i can see with automation its faster and things like concenation (or whatever that word is for binding files together) and creating unique version names for css uploads allows faster revisions due to avoiding cahcing issue and in the end a way better result for web projects.

these tips and tricks here are awesome.  its gonna take me a while to get my head around grunt and the other one with the coke bottle logo, but hopefully ill figure it out.

**Comment by petele** [comment]
glad you like!
