### ISSUE TITLE
[EN] Feedback for: /fundamentals/index.html

### ISSUE THREAD

**Issue by simonkozmik** [google/WebFundamentals#1209]
I cannot install npm, tried to set permission, nothing... is there an easier way to use the web kit?

tnx

**Comment by arthurvr** [comment]
> I cannot install npm, tried to set permission, nothing...

When exactly is it failing? On what system are you? What node version are you running (`node -v`)? What version of npm are you on (`npm -v`)? Could you post the trace you're seeing?

> is there an easier way to use the web kit?

Sorry but npm will be quite necessary.

**Comment by petele** [comment]
I'd recommend checking out https://github.com/google/web-starter-kit - that's teh site for Web Starter Kit and they may have more help for you there.
