### ISSUE TITLE
Broken layout on provide real time validation page

### ISSUE THREAD

**Issue by cb-josh-c** [google/WebFundamentals#1211]
https://developers.google.com/web/fundamentals/input/form/provide-real-time-validation
![screen shot 2015-04-08 at 9 06 30 am](https://cloud.githubusercontent.com/assets/11300831/7048715/445798d2-ddda-11e4-8fcb-dbe5132652e1.png)

**Comment by petele** [comment]
We've started work on a redesign that will hopefully fix these issues.

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
