### ISSUE TITLE
[EN] Feedback for: /fundamentals/performance/rendering/index.html

### ISSUE THREAD

**Issue by Bnaya** [google/WebFundamentals#1212]
While working on a cordova app we had serious performance penalty from the "rasterise X 13" when looking on the devtools timeline and we couldn't understand what that "rasterise" step is actually about.
It would be nice to have a reference to that step as part of the  "The pixel pipeline"
I assumed its somehow related to uploading the bitmaps to the GPU and threaded compositing

**Comment by petele** [comment]
@paullewis - can you take a look and see if it's something worth adding please?

**Comment by Bnaya** [comment]
Thanks @paullewis !
