### ISSUE TITLE
[EN] Cyrillic domain name : /fundamentals/discovery-and-distribution/optimizations-for-crawlers/url-structure.html

### ISSUE THREAD

**Issue by ybelenko** [google/WebFundamentals#1213]
Let's say I have a domain name http://домен.рф (cyrillic chars). Most of time this name has been converted to http://xn--d1acufc.xn--p1ai/ and looks ugly for anyone. The question is which name I need to use as canonical, because I don't want to split rank of the page into two pages.
And which URL I should use in Google Analytics and other services, maybe your already know about common pitfalls that I'll get. It's obvious that I want to use cyrillic domain name, but I'm expecting that it must be highly supported in the web first.

**Comment by petele** [comment]
I would recommend asking that question over in the WebMaster Tools product forum as there are more experts on that there.

https://productforums.google.com/forum/#!forum/webmasters

Thanks!
PEte
