### ISSUE TITLE
[PL] Feedback for: /fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer.html

### ISSUE THREAD

**Issue by versedi** [google/WebFundamentals#1221]
```
font-family: Roboto Condensed', Helvetica, sans-serif;
```

The included family is lacking of Latin-Extended characters, i.e.
ą,ę,ż,ł,ś,ć. 

Google Fonts has latin-extended characters in font "Roboto Condensed" set so it should be a quick fix to extend the character set. 

![google](https://cloud.githubusercontent.com/assets/7837369/7273668/4a02514c-e8f6-11e4-908e-a49f5155165e.png)

**Comment by petele** [comment]
Fixed in the MDL branch!
