### ISSUE TITLE
Add mission statement to /web page

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1227]
From Marc:
- the main /web page doesn't seem to tell me where I am or why I should care. It has some nice images, "New here?" with links that are already provided at top of page, and "Why the Web?", which is about the diffs between web and native. What's missing for me is a simple statement about what this site is all about and what it can do for me, something like: "/web is Google's one-stop shop for web developers, a place where you'll find all the information you need to understand and build modern, mobile-first web apps."

**Comment by PaulKinlan** [comment]
Spoke with Katie today about something similar. Petr i will catch up with
you on this.
