### ISSUE TITLE
Consolidate 2 getting started docs into one

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1228]
From Marc: 
- "Get Started" features two articles, which seem somewhat similar to me. One focuses on practices and the other focuses on using WSK. It's not immediately obvious which one I should follow and why? I'd suggest consolidating those into one clear, simple path for getting started, with promotion of, and a link to, WSK.

**Comment by PaulKinlan** [comment]
Nope. Disagree. There are different types of getting started guides we need.

**Comment by petele** [comment]
I disagree with your disagree. :)

These two docs serve different purposes; I think we've confused developers by putting WSK docs into WF. I'd like to see the original getting started updated and cleaned up, potentially using WSK as a starter, though I'm not married to that idea.  And the other side of that is that we need a separate WSK getting started doc, that is exclusively about getting started with WSK.

**Comment by PaulKinlan** [comment]
Wsk fine, but the sentiment that there should be only one getting started
guides is not something I agree with. I don't want the responsive design
one poluteted with a Framework that hasn't proven itself as being good or
useful. I also see other getting started guides about converting a
non-reponsive to responsive etc.

**Comment by petele** [comment]
OK - now I agree with your agree, my intent wasn't to reduce things down to a single g-s guide, but the two we have now aren't very clear as to why they are different or who their audience is. We need to fix that.

**Comment by PaulKinlan** [comment]
Sgtm.
