### ISSUE TITLE
add links to other Google web tools - polymer, web components, etc

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1229]
from Marc:
- Where do web components in general and polymer in particular fit into this framework? Seems like those are important web technologies that need to be included under this umbrella. You might consider a "Resources" section, with descriptions and links to things like googlewebcomponents.github.io, polymer-project.org, Material Design Lite (which is coming in early June), and other useful resources. Those things could all be more well integrated into /web over time but for now it would be good if they were at least referenced somewhere so they are part of our story.

**Comment by PaulKinlan** [comment]
Nope.

**Comment by petele** [comment]
@PaulKinlan that feels a lot like a GrumpyCat Nope. :cat: 

To be clear, I think these links should be added somewhere on /web, not directly within WF. They are part of our story and /web is the entry point to our /web story.

**Comment by PaulKinlan** [comment]
For most of what we are doing on /web i believe it needs to link to an
internally consistent narrative. Just linking out to other projects we
happen to run doesn't make sense in my eyes.

**Comment by arthurvr** [comment]
> For most of what we are doing on /web i believe it needs to link to an
> internally consistent narrative. Just linking out to other projects we
> happen to run doesn't make sense in my eyes.

Yeah, I kinda feel that way too.

**Comment by pbakaus** [comment]
Actually, all of our tools, including Polymer, are linked from /web/tools.
