### ISSUE TITLE
[PL] Feedback for: /fundamentals/performance/index.html

### ISSUE THREAD

**Issue by versedi** [google/WebFundamentals#1230]
```
@media only screen and (min-width: 620px)
.guides-list__item .primary-content {
min-height:300px;
max-height:300px;
}
```

to: 
```
@media only screen and (min-width: 620px)
.guides-list__item .primary-content {
min-height:300px;
max-height: 340px;
}
```
![min-height](https://cloud.githubusercontent.com/assets/7837369/7317235/f183036a-ea7e-11e4-91e1-5016df7d7e2e.png)

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
