### ISSUE TITLE
Tools is missing it's icon.

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#1231]
This page: https://developers.google.com/web/fundamentals/?hl=en

**Comment by Meggin** [comment]
+pbakaus@google.com -- did this one get lost in new build?

**Comment by PaulKinlan** [comment]
@pbakaus

**Comment by brianmontana** [comment]
The class has to be changed from icon-wf-tools to icon-tools

**Comment by petele** [comment]
Appears to be fixed
