### ISSUE TITLE
[ES] Feedback for: /fundamentals/layouts/rwd-fundamentals/use-media-queries.html

### ISSUE THREAD

**Issue by 33hops** [google/WebFundamentals#1232]
The examples at https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/use-media-queries are outdated. This type of media query (below) does not work on Chrome 41, at least with developer tools. The worst part is that your online detection tools, that probably decide on the life and death of websites do not detect them either. They are correctly displayed by devices and browsers though.

<link rel="stylesheet" media="(max-width: 640px)" href="max-640px.css">

Only this type of media query, inside the CSS file is detected:

@media (max-width: 600px) {
    body {
        background: red  ;
    }
}

The mentioned article is one of the main references on the web and you are linking directly to it from Webmaster Tools but you are missleading people.

**Comment by petele** [comment]
I tested this in Chrome 43 and it works there. 

If you can provide specific examples of what is broken or what doesn't work, happy to reopen and take a look at this.

thanks,
PEte
