### ISSUE TITLE
Tools content showing up in RSS feeds

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1238]
I subscribe to the Web Fundamentals RSS feed, and I've been seeing some broken links in the feed lately. Well, they're broken from my personal device, but go to in-progress pages from my corp device. Just wanted to put it on your radar.

Here's is what I'm seeing for recent posts. All of these URLs are in the public RSS feed but 404 for me from my personal device.

Google Developers Web Fundamentals:
- Interact with Document from Command Line – Evaluate Expressions (https://developers.google.com/web/tools/javascript/command-line/expressions.html?utm_source=feed&utm_medium=feed&utm_campaign=fundamentals_feed)
- Interact with Document from Command Line – Monitor Events (https://developers.google.com/web/tools/javascript/command-line/events.html?utm_source=feed&utm_medium=feed&utm_campaign=fundamentals_feed)
- Debug – Interact with Document from Command Line (https://developers.google.com/web/tools/javascript/command-line/index.html?utm_source=feed&utm_medium=feed&utm_campaign=fundamentals_feed)
- Interact with Document from Command Line – Command Line API Reference (https://developers.google.com/web/tools/javascript/command-line/command-line-reference.html?utm_source=feed&utm_medium=feed&utm_campaign=fundamentals_feed)

I try to access the pages from my personal laptop and they 404, but looking at them from my corp laptop they show work-in-progress pages.

**Comment by PaulKinlan** [comment]
Ah, they aren't supposed to be visible yet.... We need to fix our feed
logic.

**Comment by PaulKinlan** [comment]
@pbakaus I think has a fix in flight for this.

**Comment by pbakaus** [comment]
I checked the feed and there's no mention of tools in the feed anywhere now (not sure if somebody fixed it in the interim, but it seems so). Closing for now.
