### ISSUE TITLE
[EN] Feedback for: /fundamentals/index.html

### ISSUE THREAD

**Issue by Gizzz** [google/WebFundamentals#1247]
https://developers.google.com/web/fundamentals/ - tools section icon is broken. Tested in chrome, windows 7.

**Comment by ohyouknowwho** [comment]
Yes it's not there across all browsers.

**Comment by flaiker** [comment]
This seems to have been either fixed in master (and not deployed yet) or an deployment issue. Works fine running locally on latest master.

![image](https://cloud.githubusercontent.com/assets/5270359/8042182/b8689bf4-0e1d-11e5-81ad-2d487dd9896e.png)

**Comment by petele** [comment]
should be fixed now.

**Comment by Gizzz** [comment]
yes, it is fixed
