### ISSUE TITLE
YouTube Playlist 

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1275]
@robdodson - remember to remind @gauntface about the YouTube Playlist stuff

https://support.google.com/youtube/answer/171780?hl=en

**Comment by gauntface** [comment]
Is this about being able to embed a playlist?

**Comment by robdodson** [comment]
i think so...? it's been so long i don't recall :P

**Comment by petele** [comment]
Closing - feel free to reopen if you remember what it was.
