### ISSUE TITLE
Many 404s from webmaster tool

### ISSUE THREAD

**Issue by greenido** [google/WebFundamentals#1279]
For more info: https://www.google.com/webmasters/tools/crawl-errors?hl=en&siteUrl=https://developers.google.com/web/fundamentals/

**Comment by petele** [comment]
Most of these look like they're gone or shouldn't have been listed in the first place. I'm going to not worry about this for now.

**Comment by petele** [comment]
Will need to reverify urls prior to launch

**Comment by petele** [comment]
tracked in another bug
