### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by louisyatnam** [google/WebFundamentals#1294]
Got a typo on this page 'https://developers.google.com/web/fundamentals/?hl=en'
![web fundamentals google developers](https://cloud.githubusercontent.com/assets/11924960/7829952/1adeb25e-0465-11e5-85d4-2a5743fab6c9.png)

**Comment by JoshuaChing** [comment]
Are you sure that's a typo? Amiss means something not appropriate or out of place.

**Comment by arthurvr** [comment]
Yep, not a typo.

**Comment by petele** [comment]
Looks ok to me.

Closing for now, if you can be more specific about the type happy to look at it again.
