### ISSUE TITLE
[EN] Feedback for: /tools/polymer-starter-kit/index.html

### ISSUE THREAD

**Issue by mwhayford** [google/WebFundamentals#1303]
I don't know if you guys handle the https://developers.google.com/web/tools/polymer-starter-kit/ website, but the download link is broken on the top banner. It's pointed to https://github.com/google/polymer-starter-kit/releases/latest instead of https://github.com/polymerelements/polymer-starter-kit/releases. Doesn't look like the first one is accessible anymore.

**Comment by PaulKinlan** [comment]
Looks like someone moved the project or something. Will sort.
