### ISSUE TITLE
[EN] Feedback for: /tools/polymer-starter-kit/index.html

### ISSUE THREAD

**Issue by kobione** [google/WebFundamentals#1308]
Excited to get started.  Getting 404 errors when navigating the toolbar of the links on the new site:
"download" and "getting started" links in toolbar all lead to error pages.
https://developers.google.com/web/tools/polymer-starter-kit/?hl=en

Thanks for all the great work!  Looking forward to playing with Polymer 1.0!

Kobi

**Comment by PaulKinlan** [comment]
This should be fixed - removed link to getting started and fixed download

https://developers.google.com/web/tools/polymer-starter-kit/
