### ISSUE TITLE
[EN] Feedback for: /tools/polymer-starter-kit/index.html

### ISSUE THREAD

**Issue by floepi** [google/WebFundamentals#1311]
Getting an error when accessing the dev page

![image](https://cloud.githubusercontent.com/assets/45215/7896995/3fe37580-06cc-11e5-8b43-3bed0f1ec92f.png)

**Comment by PaulKinlan** [comment]
This should be fixed - removed link.

https://developers.google.com/web/tools/polymer-starter-kit/
