### ISSUE TITLE
[EN] Feedback for: /tools/polymer-starter-kit/index.html

### ISSUE THREAD

**Issue by VikramTiwari** [google/WebFundamentals#1317]
Page link: https://developers.google.com/web/tools/polymer-starter-kit/

The link of GitHub on site is wrong. Correct link: https://github.com/polymerelements/polymer-starter-kit/

**Comment by PaulKinlan** [comment]
It was updated to https://elements.polymer-project.org/ iirc, and other links were fixed too.
