### ISSUE TITLE
[EN] Feedback for: /updates/2015/03/push-notificatons-on-the-open-web.html

### ISSUE THREAD

**Issue by agaskell** [google/WebFundamentals#1321]
Many images are broken on https://developers.google.com/web/updates/2015/03/push-notificatons-on-the-open-web

**Comment by PaulKinlan** [comment]
@gauntface can you take a look please.  This is the canonical article now and not the h5r one.

ta.

**Comment by PaulKinlan** [comment]
This should be fixed now.
