### ISSUE TITLE
Accordian Menu [EN] Feedback for: /tools/starter-kit/index.html

### ISSUE THREAD

**Issue by Aflate** [google/WebFundamentals#1324]
Not an issue as such, but many menus for sites contain unordered lists within unordered lists in the menu with an accordion effect so that menu items can be hidden beneath main categories. 
Having an example of such a menu in the web starter kit will help a lot of people develop their site much quicker. 

I look forward to new versions of the web starter kit

**Comment by petele** [comment]
Please file this in the Polymer Starter Kit repo
https://github.com/polymerelements/polymer-starter-kit
