### ISSUE TITLE
[RU] Feedback for: /_langs/ru/updates/index.html

### ISSUE THREAD

**Issue by Gurylev** [google/WebFundamentals#1334]
RSS feed don't work
![RSS feed dont work]
(http://grlv.ru/i/tcfut.png)

**Comment by PaulKinlan** [comment]
They shouldnt have been in the output.

**Comment by pbakaus** [comment]
This is a duplicate of #1338. These are released tips so they correctly appear in the feed (just not currently on the default sort in the homepage).
