### ISSUE TITLE
[EN] Feedback for: /_langs/en/updates/tip/index.html

### ISSUE THREAD

**Issue by standardspace** [google/WebFundamentals#1337]
Clicking on the links on this page
https://developers.google.com/web/updates/tip/?hl=en
show the p[age HTML rather than the rendered page.

**Comment by PaulKinlan** [comment]
Thanks for the report.  I have assigend @pbakaus whose area this is.

**Comment by petele** [comment]
Same as #1338 - closing this one as the other already has the solution listed.
