### ISSUE TITLE
[EN] Feedback for CSS used in all /updates/ articles

### ISSUE THREAD

**Issue by olegstepura** [google/WebFundamentals#1343]
:visited links in all blog entries are coloured the same way as regular text with no other sign of a link. So it's indistinguishable from regular text. It's very inconvenient.

**Comment by beaufortfrancois** [comment]
@gauntface Can we fix this?

**Comment by olegstepura** [comment]
It's ok now :+1: 
However now visited links look the same as non-visited ones.
