### ISSUE TITLE
Updates: Add featured article header to updates

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1363]
the new Updates section could profit greatly from a "Trending" or "Featured" header block (similar to the one in the Showcase) to feature the most recent and/or most popular article.

**Comment by petele** [comment]
Low priority given Matt's other work.

**Comment by gauntface** [comment]
Right now, I want to strip updates right back, at the moment it's too busy. If this request comes up again, then we can readdress and go for something similar to html5rocks.
