### ISSUE TITLE
[KO] Feedback for: /fundamentals/performance/critical-rendering-path/render-tree-construction.html

### ISSUE THREAD

**Issue by jaehong-hwang** [google/WebFundamentals#1378]
마침내 화면에 그릴 노드, 그 노드의 계산 스타일 그리고 형상까지 알아냈습니다. 이제 이 정보를 마지막 단계로 전달해서 렌더트리의 각 노드를 화면 상의 식제 픽셀로 변환합니다. 이 단계를 보통 페인팅(painting) 또는 래스터라이징(rasterizing)이라고 부릅니다.

This part have a typing error, The '식제' '실재' should be.

**Comment by cwdoh** [comment]
:+1:

**Comment by petele** [comment]
@cwdoh - could you submit a PR for this? I'm not sure how to fix myself. ;)

Thanks!

**Comment by cwdoh** [comment]
@petele Sure. :)

**Comment by petele** [comment]
following up on this, is it still an issue?

**Comment by cwdoh** [comment]
@petele this issue should be closed by #1627 :)
