### ISSUE TITLE
[EN] Feedback for: /tools/starter-kit/index.html

### ISSUE THREAD

**Issue by jon67** [google/WebFundamentals#1382]
Well I downloaded the web starter kit and couldnt unzip it.....also the NodeJS wouldnt work for my Toshiba chromebook. NOthing worked. I would really like to make it work but your instructions dont work in reality. Alsogoing to crosh and typing shell didnt work just seems like Im going wrong at every step. 

Seems like and looks like a really great idea and just what I would like to have up and running ......i hope someone can help me. 

Many thanks..

Jon.....lost and confused

**Comment by petele** [comment]
Hey Jon,

Unfortunately NodeJS won't work on a Chromebook, you'll need to do this on a Mac, Windows or Linux machine.
