### ISSUE TITLE
include_code Jekyll snippets don't work in non-WF templates

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1384]
The `{% include_code _code/dev-orientation.html devori javascript %}` Jekyll snippets only work in the standard Web Fundamentals templates, they do not work in updates, shows, showcases, etc.

The `include_code` code expects the template to be formed in a specific way and closes expected divs, when they're not there, it screws up the existing template. 

We'll aim to fix this in the MDL redesign.

**Comment by gauntface** [comment]
Pete do you recall a scenario that shows this breakage?

**Comment by petele** [comment]
Yep - try putting a _code folder in /updates and reference that.
