### ISSUE TITLE
[EN] Feedback for: /fundamentals/principles/orientation-works-best.html

### ISSUE THREAD

**Issue by danielmulvad** [google/WebFundamentals#1390]
There is no "Next Section" in documentation

https://developers.google.com/web/fundamentals/principles/orientation-works-best?hl=en

![screen shot 2015-06-23 at 10 07 54 pm](https://cloud.githubusercontent.com/assets/5993973/8323068/60de4752-19f4-11e5-9769-5c0903394d2a.png)

**Comment by petele** [comment]
Correct, that's by design.
