### ISSUE TITLE
Wrong GIF in the "Quickly edit/view resources from the Elements panel" devtools tip

### ISSUE THREAD

**Issue by izuzak** [google/WebFundamentals#1396]
See https://developers.google.com/web/updates/2015/06/18/quickly-edit-view-resources-from-the-elements-panel -- the GIF doesn't show what's being discussed in the text. 

:microscope: [This](https://github.com/google/WebFundamentals/commit/32491641e49cd81108f8544665b8cf5f7ff5aae1#diff-f2ab451a3cc2af3d62848e85f51ed76eR21) was probably a copy/paste error from [this article](https://developers.google.com/web/updates/2015/05/19/film-strips-in-network-panel).

/cc @umaar

**Comment by PaulKinlan** [comment]
Thanks, @pbakaus will fix.

**Comment by umaar** [comment]
Ah, this article should have the correct text + gif: https://umaar.com/dev-tips/40-open-in-sources-from-elements/

**Comment by PaulKinlan** [comment]
Umar, can you submit a PR and we can get it in. US is on holiday.

**Comment by umaar** [comment]
PR in #1409
