### ISSUE TITLE
[EN] Feedback for: /fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints.html

### ISSUE THREAD

**Issue by mweiner19766** [google/WebFundamentals#1398]
Let me preface this by saying thank you so much for your contribution to the Google Dev Fundamentals! It has been so helpful! It seems as though the links to the examples in these articles are broken. Just wanted to let you know.

**Comment by PaulKinlan** [comment]
Thanks for the heads up.  will investigate.
