### ISSUE TITLE
[EN] Feedback for: /fundamentals/device-access/user-location/obtain-location.html

### ISSUE THREAD

**Issue by gedex** [google/WebFundamentals#1399]
* The DevTools Overrides is not available anymore in recent Chrome. It's now under **Emulation** if you want to override Geolocation.
* On section **Always Handle Errors**, the snippet code:

  ```
  var geoError = function(position) {
    console.log('Error occurred. Error code: ' + error.code);
    // error.code can be:
    //   0: unknown error
    //   1: permission denied
    //   2: position unavailable (error response from location provider)
    //   3: timed out
  };

  ```
 should use `error` instead of `position` in the function arg. Same thing on snippet code of **Reduce the need to start-up geo location hardware** section.

**Comment by PaulKinlan** [comment]
Urgh, good spot.

**Comment by petele** [comment]
@PaulKinlan - did you get a chance to update this?

**Comment by petele** [comment]
Also fixed in MDL branch
