### ISSUE TITLE
[EN] Feedback for: /fundamentals/device-access/user-location/monitor-location.html

### ISSUE THREAD

**Issue by gedex** [google/WebFundamentals#1400]
* On section **Always clear up and conserve battery**

  > Once you have no need to track the user’s position call clearWatch to turn of the geolocation systems.
 
 Should be **turn off** instead of **turn of**

* Give example of `clearWatch` usage. The description is not clear enough how to use it. Maybe simple example like following might help:

   ```
   var watchId = navigator.geolocation.watchPosition(geoSuccess, geoError);
   ...
   navigator.geolocation.clearWatch(watchId);
   ```

**Comment by PaulKinlan** [comment]
Good point.  Will sort.

**Comment by jpmedley** [comment]
Fixed. https://github.com/google/WebFundamentals/commit/3ed2ebd76260adb3abbce06200cf7cebcc2affd2
