### ISSUE TITLE
[EN] Feedback for: /updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API.html

### ISSUE THREAD

**Issue by dimitridarras** [google/WebFundamentals#1403]
Just wondering what the status of this project is and if there are Terms of Usage for the API - I see conflicting information on that subject.

**Comment by PaulKinlan** [comment]
It depends on what you need it for, iirc when in Chrome the ToS are those of Chrome, if you want to integrate it into your own Chromium Build then you have to get an API and agree to the ToS.

What information do you need and in what context?
