### ISSUE TITLE
Article request: Web components and polymer

### ISSUE THREAD

**Issue by AliMD** [google/WebFundamentals#1407]
Lets talk about web components and polymer!
Any plan for write some article about polymer ?
I know there is many good article on the web and the official websites buts we want to have a WebFundamentals ;)
Thank you in advance.

**Comment by PaulKinlan** [comment]
Maybe, we are working out what we do in this area.  Right now the thinking is that we teach people about componentization of apps and sites more effectively and then lead in to Polymer as a core tool that can help.

Still working it out though.

**Comment by AliMD** [comment]
Very well :+1:
