### ISSUE TITLE
[EN] Feedback for: /_langs/en/updates/index.html

### ISSUE THREAD

**Issue by apythoncoder** [google/WebFundamentals#1410]
The 'view source' link on the top-right of the [updates page](https://developers.google.com/web/updates/?hl=en) is broken - it leads to a 404

**Comment by gauntface** [comment]
Good spot.

This is because the index page for updates is automatically generated. Will have a think of how we can address this in the next version.

**Comment by gauntface** [comment]
I've made it so that it will just point to the root of the project on the correct branch if that is an issue.

Please re-open if you think that's a bad idea.
