### ISSUE TITLE
Sitemap - Freq + Priority

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1414]
Just looking through the sitemap and feeds to ensure we don't have anything super hardcoded.

Just looking at the source for the sitemap, we have:

    sitemap:
      changefreq: hourly
      priority: 0.9

Yet in the final output: https://developers.google.com/web/sitemap.xml

1.) Do we need changefreq and priority? If so is hourly and 0.9 correct or is the weekly and 0.5 default values correct?

2.) Can anyone see a scenario where these values change? I can't from the source code: https://github.com/google/WebFundamentals/blob/master/src/_langs/en/sitemap.xml

**Comment by petele** [comment]
I think we can prob change to daily, since we don't publish more than that.  Not sure about priority.

**Comment by PaulKinlan** [comment]
Was about to say daily too.

**Comment by PaulKinlan** [comment]
Would like to make sure that we get picked up as soon as we publish, but I am not sure how much we are affected by hardcoded value vs default.

**Comment by gauntface** [comment]
At the moment the hardcoded values don't seem to work, so I'm going to just make it daily, any concerns of me pulling out the priority field?

**Comment by PaulKinlan** [comment]
none, I actually thought it was for specific important content on your site and if you have 0.9 everywhere it is just treating everything equally.

**Comment by gauntface** [comment]
Coolio, I've dropped it completely for now, we can re-add it later on if needed.
