### ISSUE TITLE
Possible to make URL's case-insensitive?

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1419]
A report from a viewer on youtube:

'FYI: Some of the links in the description are truncated - and have been for past videos as well.

Learn more on the TTT site: https://developers.google.com/web/shows/ttt/

Subscribe by email: https://feedburner.google.com/fb/a/mailverify?uri=TotallyToolingTips&loc=en_US

RSS feed: https://developers.google.com/web/shows/ttt/feed.xml

The paths are also unfortunately case-sensitive, so 'TTT' 404s.'

**Comment by petele** [comment]
No - unfortunately DevSite is case sensitive. We'll need figure out how to fix this.
