### ISSUE TITLE
[RU] Feedback for: /fundamentals/look-and-feel/animations/custom-easing.html

### ISSUE THREAD

**Issue by SergeyKozyrkov** [google/WebFundamentals#1420]
Ошибка, лишний мягкий знак в слове "**говорится**" во фразе "В действительности, ключевые слова ease, ease-in, ease-out и linear сопоставляются с заранее заданными кривыми Безье, о чем подробно **говориться** в статье Определение переходов CSS."

**Comment by petele** [comment]
Sorry, my Russian is non-existent, would you please refile this in English. :(
