### ISSUE TITLE
[EN] Feedback for: /_langs/en/updates/tip/index.html

### ISSUE THREAD

**Issue by Yonet** [google/WebFundamentals#1421]
Hi Team,

It is so hard to look at this page as a person suffering from migraine. It is very dizzying with all the gifs going on at the same time. Is there a way to stop them. If not, would you please consider allowing a way to not play the gifs. 

Thanks.

**Comment by petele** [comment]
@pbakaus - please take a look

**Comment by pbakaus** [comment]
Definitely a valid concern, but hard to do.

Probably need imagemagick to extract the first pic out of the gif (unless we want to take a screenshot of every single tip). Might not be able to get to it soon.

**Comment by PaulKinlan** [comment]
Does plain video solve this? I.e, click to play.

**Comment by pbakaus** [comment]
It does, but I have no control over it (Umar records these as animated gifs, and our CMS imports them). Whenever I put in tips myself, I'll do videos.

**Comment by gauntface** [comment]
@pbakaus Any updates on this?

**Comment by pbakaus** [comment]
Well tips are currently gone, so I'm waiting for them to come back first. But yeah, in the new version we'll likely not autoplay the gifs and have additional screenshots. Closing this for now therefore.
