### ISSUE TITLE
/web/updates 404's

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1423]
Would be nice if this ultimately went to /web/updates/

**Comment by petele** [comment]
On which domain, I tried this on developers.google.com/web/updates and devsite.googleplex.com/web/updates, web-central.appspot.com/web/updates and all work just fine. Where are you seeing this?

**Comment by gauntface** [comment]
Will close for now. Was seeing on developers.google.com, but now seem to be unable to even get chrome canary to go to developers.google.com/web/updates without it doing a search.
