### ISSUE TITLE
[EN] Feedback for: /tools/material-design-lite/index.html

### ISSUE THREAD

**Issue by Poorchop** [google/WebFundamentals#1430]
I am coming from Angular Material, which I can no longer use as I am moving to a different JavaScript framework. The smaller degree of modularity in MDL means that I can't use it in my web application. My particular issue is that I can't drop in a sidenav in one view and a fixed header in a child view. Creating a main view with only a sidenav and then a child view with a header and main page content means that the header disappears when the page is shrunk to a smaller size.

I was kind of hoping for the same experience as Angular Material but without the ties to a specific framework. Angular Material and MDL are some of the only frameworks I've found that include a responsive side menu, which is essential for me, but unfortunately the behavior in MDL is quite different so I'm unable to use it in my project.

The `flex` attribute and Angular Material was also extremely convenient and I think MDL would benefit from something similar. I could easily create the perfect layout by specifying the layout type (row/column) and then dropping the `flex` attribute as needed.

**Comment by petele** [comment]
Hi,

This is for Web Fundamentals and it's sites only, please file this issue in the MDL repo at https://github.com/google/material-design-lite

Thanks - and good luck!

**Comment by Poorchop** [comment]
Sorry about this. I saw the feedback button and the words "Material Design Lite" so I absentmindedly made this issue without really realizing where I was posting.

**Comment by petele** [comment]
no worries! you're not the first, and i'm sure won't be the last ;)
