### ISSUE TITLE
Autofill update article responsive layout doesn't work.

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1437]
See report from @stopsatgreen https://twitter.com/stopsatgreen/status/620992522496643073 - currently the layout might only be broken for the latest article, however it could be broken in other places

cc @gauntface @petele

**Comment by stopsatgreen** [comment]
This page: https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

See attached. Other articles don’t have this problem, AFAICT.

Firefox 40, OSX 10.10.4.

<img width="1505" alt="screen shot 2015-07-14 at 17 32 38" src="https://cloud.githubusercontent.com/assets/98774/8678768/5d8e7076-2a4e-11e5-80dd-aae584c72318.png">

**Comment by petele** [comment]
this is a problem with this specific article.

**Comment by PaulKinlan** [comment]
Ok. @greenido can fix

**Comment by greenido** [comment]
@petele is it being fetch from html5rock's feed?

**Comment by PaulKinlan** [comment]
No.

**Comment by petele** [comment]
@greenido - is this fixed? if not can you provide an update?
