### ISSUE TITLE
Misleading statements about "unnecessary pixels" on HiDPi screens

### ISSUE THREAD

**Issue by WebReflection** [google/WebFundamentals#1444]
The whole _downscaling_ image problem  makes sense only on screens that have a pixel ratio of **1** or lower. In every other case, which nowadays is the most common case on both mobile and desktop/laptop, browsers have to **upscale instead**.

When an image is shown, as example, at 200x150, but the display uses **2x** device pixel ratio, we have similar CPU stress due upscaling, and also bad UX due user eyes "stress" 'cause the final result will be a blurry image, instead of a sharp one.

In most cheap smart phones the device pixel ratio is 1.5 and images served at 2X of their size will have actually around 25% of waste but will look sharper than images served at 1x.

On the other hand, every other **modern browser** with device pixel ration 2X or higher will actually have minimum scaling stress but will show images more pleasant for human eyes.

Accordingly, whenever an image tag is used instead of a picture element with all its possible sources and media queries capable of serving the right HiDPi image, using 2x images will grant better results across the majority of nowadays browsers.

This assuming there's no User Agent sniffing on  the  server side, capable of recognizing the right DPR and serve an image accordingly ( technique that I wouldn't recommend at all ).

Last, but not least, the whole scaling can be considered a feature when we use images for backgrounds or any other way that does not need a static size.

As bug summary: please update the following page with at least some of these info, thank you:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization?hl=en#delivering-scaled-image-assets

Thank You!

**Comment by WebReflection** [comment]
Follow up: I see there is some  mention/improvement about [HiDPI screns](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization?hl=en#implications-of-high-resolution-screens) but again there's some  misleading guide in there.

  * vector images can be too heavy compared against just higher definition image. for instance, [mexican flag](https://twitter.com/zachleat/status/621739975923630080) vector is the equivalent of a 5500px wide PNG
  * serving at least 2X grants widely enhanced images experience because human eyes cannot really spot so easily  the difference between a retina 2X and a retina 3X and the concept is sharpness. Half of the page talks about pixels, when it comes to small images, and I am not talking  about background/big images that are  just fine 1X, using 2X will look sharp in 80% of modern devices.
  * banners at 320x200 with blurry text in it per each retina MacBook/Pro or modern Laptop are just ridiculous and companies are using these guidelines to say they are doing the right thing ... **please** don't spend just few words on the most important graphic topic of these years and add some extra hint for designers and developers looking for the best solution

Thank You!

**Comment by petele** [comment]
@igrigorik - can you comment or lmk if there's work necessary here please?

**Comment by igrigorik** [comment]
@WebReflection thanks for the feedback, and apologies about the delay.

> The whole downscaling image problem makes sense only on screens that have a pixel ratio of 1 or lower. In every other case, which nowadays is the most common case on both mobile and desktop/laptop, browsers have to upscale instead.

Higher resolution screens do not prevent downscaling. Lots of sites serve large high-resolution assets that need to be downscaled even after accounting for the DPR of the screen.. and incur even higher overhead than 1x screens. The key takeaway for developers is to serve _scaled assets_: the display dimensions should match the natural+DPR-adjusted dimensions of the resource (or be as close as possible).

> Accordingly, whenever an image tag is used instead of a picture element with all its possible sources and media queries capable of serving the right HiDPi image, using 2x images will grant better results across the majority of nowadays browsers.

Making recommendations about "serve 2x for best overall results" is subjective and doesn't account for preferences of various users: some are very bandwidth sensitive and are more than willing to look at slightly blurry pictures (or none at all).

The right answer here is that developers should specify `sizes` and/or use `picture` to provide the best experience for various screens. Alternatively, they can [use Client Hints](https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints).

---

As far as updates go, I do think we can improve the content a bit. Specifically:

- add a note about adjusting for DPR when performing the "serve scaled images" calculation.
- add a note about using sizes+picture to specify correct resources.

@petele does that sound reasonable?

**Comment by WebReflection** [comment]
whatever would work as long as it's not ad-hoc for 1:1 ratio displays.

Thanks

**Comment by petele** [comment]
@igrigorik - yep, absolutely, thanks!
