### ISSUE TITLE
Simpler maintenence for customization of colors for MDL

### ISSUE THREAD

**Issue by Frozenfire92** [google/WebFundamentals#1450]
[This customization](http://www.getmdl.io/customize/index.html) page offers a great way to change your primary and secondary color. However the only option provided is to download the whole css library with the customized colors. I believe most users (like myself) will use a package manager such as bower to maintain their libraries to the most recent versions. By adding an option to just download (or copy) the css snippet that overrides the colors will make things much more maintainable for typical projects

**Comment by petele** [comment]
Hey @Frozenfire92 - this repo is for Web Fundamentals. Better to file this issue in the Material Design Lite repo at https://github.com/google/material-design-lite

**Comment by Frozenfire92** [comment]
Hey @petele 

I figured as much, however the [contribution guide](https://github.com/google/material-design-lite/blob/master/CONTRIBUTING.md#-want-a-feature) on material design lite explicitly says to post website related issues here. Forgive me for posting in the wrong spot, just wanted to follow the guide to avoid wasting peoples time. Unfortunately it looks like that was in error, I will submit an issue surrounding that aswell
