### ISSUE TITLE
Comments number is not properly vertically aligned

### ISSUE THREAD

**Issue by beaufortfrancois** [google/WebFundamentals#1451]
Go to https://developers.google.com/web/updates/2015/06/mse-gapless-audio, scroll to bottom, see below:
![screenshot 2015-07-20 at 10 41 47 am](https://cloud.githubusercontent.com/assets/634478/8772366/f386ddd0-2ecb-11e5-9935-b5394e52c52a.png)

**Comment by petele** [comment]
Looks fine for me right now. If this still occurs, can you re-open and include browser details. Likely there's not a lot we can do though because this is an iframed component that we're pulling in.

**Comment by beaufortfrancois** [comment]
Sorry for not being specific there @petele. This happens in Chrome Canary.
I guess Chrome changed its behavior regarding `<span>` inside `<h2>`.

**Comment by petele** [comment]
@beaufortfrancois - no problem, I see it now too. Hopefully they'll fix it before it gets to beta, but if not, we'll need to file a bug with either the Chrome team or the Plus team as it's in an iframe and not something we can change.
