### ISSUE TITLE
Add a custom preview image for social networks on a post

### ISSUE THREAD

**Issue by beaufortfrancois** [google/WebFundamentals#1468]
It would be nice to be able to customize `<meta property="og:image">` content for a post/updates/news.

**Comment by petele** [comment]
@gauntface - we should do this for the MDL update.

**Comment by gauntface** [comment]
I have a yaml variable which is currently used called 'html_head_social_img'.

I'll make that settable from the markdown files.

Pete, please reopen or change the name if you aren't a fan (Just needs tweaking in the valid yaml files in WFPage.rb).
