### ISSUE TITLE
Can I ever be forgiven?

### ISSUE THREAD

**Issue by ep0ch** [google/WebFundamentals#1478]
I have around 150 websites I've built which I feel would do extremely well with my organic traffic.  However, 10 years or so ago (A VERY LONG TIME AGO) I was banned from adsense for participating in a click ring on "IRC"

I have since grown past those idiotic blackhat techniques and now use strictly organic traffic to my 150+ websites to generate revenue via CPA & Adgum.  I would much rather use Adsense.

Yours truly,
Jason

**Comment by petele** [comment]
Sorry, you'll need to work with the AdSense team to figure this out, we can't help you here.
