### ISSUE TITLE
Remove hack added in PR #1483

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1486]
This was put in as a temporary hack to fix an issue with FF and will need to be removed.

**Comment by petele** [comment]
Please remove #1483 when it's fixed in FF

**Comment by pbakaus** [comment]
Sounds good, will track fix in FF.

**Comment by petele** [comment]
@pbakaus - can you provide an update here?

**Comment by pbakaus** [comment]
As far as I'm aware, the issue hasn't been fixed in FF yet. Will update when I know more.

**Comment by gauntface** [comment]
Can we close this given that MDL refresh will launch before this is addressed?

**Comment by petele** [comment]
Yep
