### ISSUE TITLE
[EN] Feedback for: /_langs/en/updates/index.html

### ISSUE THREAD

**Issue by AndrewBarfield** [google/WebFundamentals#1490]
Shouldn't there be a way to subscribe to such an important page? Can I use Google Alerts to do this?

Thank you

**Comment by AndrewBarfield** [comment]
I have a Google Alert set for: `inurl:developers.google.com/web/updates/`. I'll update if i get a 'hit'.

**Comment by PaulKinlan** [comment]
We have RSS and atom feeds for this that are referenced in the source.

**Comment by AndrewBarfield** [comment]
Thank you!
