### ISSUE TITLE
[EN] Feedback for: /fundamentals/performance/optimizing-content-efficiency/image-optimization.html

### ISSUE THREAD

**Issue by Prasanthquick** [google/WebFundamentals#1491]
Hi ,

This is a typo error found in the page. Please check.
![google typo](https://cloud.githubusercontent.com/assets/13111996/8978583/0666b0a4-36c1-11e5-94db-a00b84b0eb2e.png)

**Comment by petele** [comment]
this should go live in the next day or so.
