### ISSUE TITLE
[EN] Feedback for: /fundamentals/resources/samples/index.html

### ISSUE THREAD

**Issue by markcharter** [google/WebFundamentals#1493]
There is a typo at line 298 of
https://googlesamples.github.io/web-fundamentals/samples/layouts/navigation-patterns/appbar-navdrawer-sample1.html
where
tranform: none
should be
transform: none
and similarly in appbar-navdrawer-sample2.html.
I haven't checked any other sample files.

Mark Charter
mark@nctr.co.uk

**Comment by petele** [comment]
this should go live in the next day or so.
