### ISSUE TITLE
[EN] Feedback for: /updates/2015/07/measuring-performance-in-a-service-worker.html

### ISSUE THREAD

**Issue by DavidWells** [google/WebFundamentals#1494]
I'd like to subscribe to updates like this on the blog. 

Couldn't find an RSS feed though.

Is there one?

Thanks

**Comment by petele** [comment]
Yep - RSS feed is at https://developers.google.com/web/updates/rss.xml and the ATOM feed is at https://developers.google.com/web/updates/atom.xml
