### ISSUE TITLE
Icons with inset shadows show visual artifacting when rendered. 

### ISSUE THREAD

**Issue by brianmontanaweb** [google/WebFundamentals#1499]
Happens on Chrome for Windows, there is visual artifacting happening with the box-shadow inset white that's applied to the icons. Can I make an update for box-shadow black -inset when hovering on an icon?

https://developers.google.com/web/fundamentals/

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
