### ISSUE TITLE
[EN] Feedback for: /fundamentals/performance/optimizing-content-efficiency/http-caching.html

### ISSUE THREAD

**Issue by VikramTiwari** [google/WebFundamentals#1500]
While the article in itself is very much complete and descriptive, it does not provide a way of implementation for the end developer.

For example the article about [compression ](https://developers.google.com/speed/docs/insights/EnableCompression) provides ways in which apache or nginx developers can configure it on their end.

**Comment by igrigorik** [comment]
There is a _large_ number of server implementations out there, each with their own configuration syntax. The decision to avoid specific configuration tips in WF was intentional -- please refer to the docs of your app/proxy/CDN.

I'm inclined to close this as a wontfix.
