### ISSUE TITLE
[EN] Feedback for: /shows/ttt/index.html

### ISSUE THREAD

**Issue by MaxFreak** [google/WebFundamentals#1501]
The blond guy on ttt is very difficult to understand. It is possible to speak more clearly? I follow google dev videos for a long time and I like them alot but I had never such problems...

Thanks in advance
Bernd

**Comment by gauntface** [comment]
Sorry @MaxFreak that's just how I normally speak. Will try to be more mindful of it in future. Hopefully we'll be better at writing up the content so that could be a better option.
