### ISSUE TITLE
[EN] Feedback for: /tools/chrome-devtools/index.html

### ISSUE THREAD

**Issue by bransbury** [google/WebFundamentals#1511]
'DevTools' link is broken - goes to 'https://developers.google.com/web/chrome-devtools/' (missing 'tools' subfolder, i.e. https://developers.google.com/web/tools/chrome-devtools/)

![image](https://cloud.githubusercontent.com/assets/8886969/9195299/b4942dbc-4019-11e5-8ce8-2a06f3863dfd.png)

**Comment by pbakaus** [comment]
Thanks for the report! Duplicate of #1519.
