### ISSUE TITLE
[EN] Feedback for: /tools/polymer-starter-kit/index.html

### ISSUE THREAD

**Issue by mharris7190** [google/WebFundamentals#1518]
All buttons seem to have a strange double tap behavior (sometimes the tap won't even register) on mobile devices (touch events supposedly). Is there a workaround or bugfix for this in the works?

**Comment by petele** [comment]
@gauntface - can you take a quick peek and determine if there's work necessary here?

**Comment by gauntface** [comment]
@mharris7190 The only button I see on that page is the one for navigation and download polymer starter kit.

Could you give reproducible steps + browser you are seeing it on.

**Comment by mharris7190** [comment]
@gauntface 
After installing the polymerStarterKit and starting it up with 
~$ yo polymer
....
~$ gulp serve
I see this weird double tap thing when visiting the page (ip address and port) from a mobile device.

**Comment by gauntface** [comment]
cc @robdodson 

This is an issue with Polymer Starter Kit not the docs (sorry), can you reopen the bug on this repo: https://github.com/PolymerElements/polymer-starter-kit

Just mention everything you said in the previous report.

It sounds like a Webkit issue.
