### ISSUE TITLE
[EN] Feedback for: /tools/chrome-devtools/index.html

### ISSUE THREAD

**Issue by mnot** [google/WebFundamentals#1520]
The old devtools site had an easy-to-find "Contribute to Devtools" page. How to do so isn't readily apparent on the new site.

**Comment by petele** [comment]
@pbakaus - can you please comment or close.

**Comment by pbakaus** [comment]
This is indeed missing an a fair request. Let's leave it open so we can work on it.

**Comment by pbakaus** [comment]
This will be fixed with the push going out on Monday.
