### ISSUE TITLE
[EN] Feedback for: /fundamentals/performance/optimizing-content-efficiency/image-optimization.html

### ISSUE THREAD

**Issue by vaisakhpc** [google/WebFundamentals#1522]
![strong html tags seen](https://cloud.githubusercontent.com/assets/9882248/9248746/26280f34-41dc-11e5-992b-efa6f588cd87.png)

Please check on hover on the web dropdown menu items,we can see the <strong> tags . Please check it. it may be small issue,but doesn't look good

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
