### ISSUE TITLE
Remove "Web Fundamentals" from page title in /tools and other sections

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1523]
Currently most pages have "– Web Fundamentals" attached to the end of the page title. The tools section, such as all other sections, should have something different instead, i.e. "Google Web Tools".

Proposal: Create a system/map that works based on the url/folder tree, so you can easily map /tools/* to use a different title suffix.

This has a high priority because it actively hurts SEO.

**Comment by gauntface** [comment]
This has been reworked for the material branch - would love feedback on the approach (essentially you can't add a new section without adding the relevant info). Only downside is that this needs to be done in ruby

**Comment by pbakaus** [comment]
Nice, I'll take a look! Ruby dependency is fine, I need Ruby for all sorts of stuff anyway (update generation, tag generation etc.)
