### ISSUE TITLE
[EN] Feedback for: /_langs/en/updates/tools/index.html

### ISSUE THREAD

**Issue by Puddingsan** [google/WebFundamentals#1535]
This isn't an issue, but I have constructed an interesting programme that shows the actual support for HTML elements and their attributes dependent on the user agent being used.

The page may be found here: 

http://www.innovaweb.co.uk/tools/html_elements_and_attributes_support.html

I do hope some people find it a useful resource.

Kind regards, Nick (Puddingsan)

**Comment by PaulKinlan** [comment]
Interesting, but I get a 404 not found.  It looks similar to iwanttouse.com

**Comment by Puddingsan** [comment]
Hi again, it may have been a typo, but this was  taken from the address bar:

http://innovaweb.co.uk/tools/html_elements_attributes_support.html


Iwanttouse looks to work pretty well. My programme lists current and extant
elements and their attributes and checks for support in the browser being
used to view the page.

I also give details of when attributes were deprecated and made obsolete,
and produce a summary of support as the page loads, complete with links to
access details about elements and attributes. There is also a 'div of
shame' where elements that are missing valid current attributes can be seen.


This is still a work in progress. Currently working on a comparison
function to compare with other browser results, popup info for each
attribute and who knows what else I can come up with between now and then
... any ideas/comments would be greatly appreciated.

Regards, Nick (Puddingsan)

On 21 August 2015 at 10:24, Paul Kinlan <notifications@github.com> wrote:

> Interesting, but I get a 404 not found. It looks similar to iwanttouse.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/WebFundamentals/issues/1535#issuecomment-133346713>
> .
>



-- 
----------------------------------------------------
This message was printed on 100% recycled electrons.
----------------------------------------------------
