### ISSUE TITLE
[EN] Feedback for: /fundamentals/principles/orientation-works-best.html

### ISSUE THREAD

**Issue by usrbowe** [google/WebFundamentals#1549]
There is missing "Next Sections" box at the end of this article, as other articles had :+1: 
![keep_menus_short_and_sweet_ _web_fundamentals](https://cloud.githubusercontent.com/assets/5339061/9425440/e21c4102-4910-11e5-8c7c-ccebb3084dcd.jpg)

**Comment by arthurvr** [comment]
Dupe of #1327.

**Comment by petele** [comment]
I'm going to close this for now since we're just about three weeks from launching the MDL redesign and this will be a moot issue then.
