### ISSUE TITLE
[EN] Feedback for: /tools/chrome-devtools/index.html

### ISSUE THREAD

**Issue by MHerbst** [google/WebFundamentals#1550]
I am using Chrome Development Tools in Chrome version 44.0.2403.157 m (64-bit) on Windows 10. Today I have used the developer tools for the first time on Windows 10 (I think) and in the elements view some strange characters appeared, that you can see here in the screenshot:
![image](https://cloud.githubusercontent.com/assets/616792/9425646/95be97cc-4917-11e5-8a75-50f3b7fb6e48.png)

**Comment by Garbee** [comment]
If you can still replicate this issue then please file a bug with the [Chromium issue tracker](http://crbug.com). This repository is for documentation-specific  issues and not issues with the DevTools itself.

Thank you.

**Comment by MHerbst** [comment]
Sorry for posting in the wrong repository. Will post it in the Chromium tracker.
