### ISSUE TITLE
Headings that aren't headings

### ISSUE THREAD

**Issue by jakearchibald** [google/WebFundamentals#1551]
I'm a little concerned about the use of headings with flowing text content, eg:

https://github.com/google/WebFundamentals/blob/master/src/_langs/en/tools/index.html#L19

```html
Discover our&nbsp;<h1>tools</h1>&nbsp;and kickstart your development.
```

It's been suggested this is for SEO reasons? I spoke to the GWS team and they'd consider it a bug if that gave the page a ranking bump.

Furthermore, if a screenreader user is navigating by headings, they're going to get "tools and kickstart your development", which lacks context.

To produce a meaningful heading structure, the active tab item could be an H1, or "Get productive" could be replaced by "Tooling" and become an H1. If absolutely necessary, you could have `<h1>Get productive <span>with tooling</span></h1>` where the span is hidden.

**Comment by jakearchibald** [comment]
+@pbakaus

**Comment by gauntface** [comment]
I intend on removing this for the material redesign - feels like bad practice and not necessary to me.

**Comment by pbakaus** [comment]
Yeah the idea was indeed to optimize for SEO, but agree it's a little nasty. Thanks for fixing it in the material redesign branch, @gauntface.

**Comment by petele** [comment]
Moving to @gauntface to fix in the MDL refresh.

**Comment by gauntface** [comment]
Totes removed.
