### ISSUE TITLE
No one knows about our social channels (Twitter mainly) - add a link in header

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1558]
I would love to get a link to ChromiumDev account in the header or some other prominent place across all pages.

**Comment by gauntface** [comment]
I was thinking we could do something like this, except with logos instead of text, thoughts?

<img width="1097" alt="screen shot 2015-09-17 at 15 36 51" src="https://cloud.githubusercontent.com/assets/139760/9943870/fcf26bb4-5d51-11e5-8779-aef3c6146725.png">

**Comment by petele** [comment]
Yah, I think that looks good. Potential concern - what about on pages where there's an author/date, think that people might think those are the authors social network links?

Maybe not in that order though.
