### ISSUE TITLE
[EN] Feedback for: /tools/index.html

### ISSUE THREAD

**Issue by alvaroillanes** [google/WebFundamentals#1562]
Estimados amigos, estoy instalando el web startet kit, y me arroja el siguiente error:

Error: Cannot find module './oauth2client.js'

Como podré solucionar este problema.

Utilizo UBUNTU 15.04

Saludos cordiales

**Comment by Garbee** [comment]
Issues for WSK should be filed in the [WSK issue tracker](https://github.com/google/web-starter-kit/issues).

**Comment by arthurvr** [comment]
And preferably in English ;)
