### ISSUE TITLE
[EN] Feedback for: /tools/setup/remote-debugging/remote-debugging.html

### ISSUE THREAD

**Issue by massimocode** [google/WebFundamentals#1563]
The article says: "Unfortunately there is no way to debug a site on Windows Phone"

That's not true, you can use Visual Studio to connect to a Windows Phone and debug the mobile IE.

I've done it several times before and it's a nice smooth experience (it's been smoother than the Android one where the Samsung Tab 4 just doesn't get detected by Chrome, even with the samsung special usb drivers!)

**Comment by PaulKinlan** [comment]
Cc @pbakaus
