### ISSUE TITLE
[EN] Feedback for: /tools/javascript/console/index.html

### ISSUE THREAD

**Issue by rodofatos** [google/WebFundamentals#1580]
Hello,
i just wanna suggest an improvement that i think will ease our life working with CSS styles.
When you have multiple classes for a dom object(span, div and so on) and their styles are messed up(or maybe they receive styles from parents) its really annoying to search where is the main property. Can we have something like hovering on a crossed css property will display the class/id of the main property from where it is inherited ?

**Comment by petele** [comment]
@paulirish @pbakaus can you guys take a look at this suggestion. 

closing for now since it's not a WF issue.

**Comment by paulirish** [comment]
@rodofatos can you head to crbug.com and file this there?  (even though its a feature request, you can file it as a bug.)

**Comment by paulirish** [comment]
@rodofatos can you head to crbug.com and file this there?  (even though its a feature request, you can file it as a bug.)
