### ISSUE TITLE
Build process shouldn't need to update RSS feed files if nothing has changed.

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1581]

**Comment by gauntface** [comment]
@PaulKinlan  When you say build process - are you referring to Gulp, Jekyll or Staging / Deployment scripts?

The feeds at the moment are built by Jekyll, which means if Jekyll builds, it's going to create those pages. To the best of my knowledge @wibblymat made the staging and deployment scripts only commits pages which have a different final output compared to the currently deployed page.

Given these two things, I'm note sure a.) what the exact problem is b.) not sure there is anything we can do if it is just that the page is getting rebuilt.

**Comment by petele** [comment]
Maybe instead of using the current date/time for the feeds last updated, we use the date/time of the most recent item in the feed. Thus if the content hasn't changed, the feed date will remain the same, even on rebuild.
