### ISSUE TITLE
[EN] Feedback for: /tools/setup/device-testing/devtools-emulator.html

### ISSUE THREAD

**Issue by gujjar777** [google/WebFundamentals#1586]
https://developers.google.com/tools/chrome-devtools?hl=en

This link is broken. Please verify.

**Comment by petele** [comment]
What page linked you to this?

**Comment by beattidp** [comment]
I found the bad link at https://developers.google.com/web/tools/?hl=en
 'Chrome DevTools' (404 https://developers.google.com/tools/chrome-devtools )

The proper link should be
  https://developers.google.com/web/tools/chrome-devtools/?hl=en

**Comment by petele** [comment]
Fixed.
