### ISSUE TITLE
Add styles for nextarticle.liquid to match MD spec site

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1590]
Add styles to make content in nextarticle.liquid match the Previous/Next from the Material Design Spec site. See the bottom of https://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-radial-action

**Comment by gauntface** [comment]
Posted screenshot in this bug: https://github.com/google/WebFundamentals/issues/1623

Repost here:

<img width="1437" alt="screen shot 2015-09-11 at 12 47 52" src="https://cloud.githubusercontent.com/assets/139760/9821349/bf5cfcfc-5887-11e5-9786-6de6387bcd35.png">
