### ISSUE TITLE
Font spacing and padding in TL;DR's is too big and too tight

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1597]
![screen shot 2015-09-09 at 7 06 29 pm](https://cloud.githubusercontent.com/assets/718038/9776409/f0ff29aa-5725-11e5-92aa-01975f7cbe41.png)

**Comment by gauntface** [comment]
I've made it such that these are easier to alter together and made some changes.

Is this better?

<img width="955" alt="screen shot 2015-09-16 at 15 14 36" src="https://cloud.githubusercontent.com/assets/139760/9915559/bcd12a2e-5c85-11e5-8c19-cbffea4d3ff0.png">
