### ISSUE TITLE
Include index.html in page.previousPage/nextPage when order is defined

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1623]
I think this might be left over from the existing stuff, but if I have a collection of pages where I've set the order, I can never get back to the `index.html`.

Repro Steps:
1. Open [page](https://material-dot-web-central.appspot.com/web/fundamentals/performance/rendering/optimize-javascript-execution) and scroll to bottom
2. Look for previous and next link

Expect: previous and next link

Actual: only next link, even though index.markdown exists and has `order: 1`

For example: 
index (with `order: 1`) - https://github.com/google/WebFundamentals/blob/material-branch/src/content/en/fundamentals/performance/rendering/index.markdown
second page (with `order: 2`) - https://github.com/google/WebFundamentals/blob/material-branch/src/content/en/fundamentals/performance/rendering/optimize-javascript-execution.markdown

I **think** this is because the old system considered index.markdown to be part of the page one folder up (so you could set the order on deep linked pages)

**Comment by gauntface** [comment]
Thoughts? 

On mobile it collapses down to just the arrow for previous article while keeping the title on the next article.

![Uploading Screen Shot 2015-09-11 at 12.47.52.png…]()

**Comment by petele** [comment]
perfect!
