### ISSUE TITLE
Add search box to web fundamentals

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1625]
Because we can't add JS to the site, I took a look at what is need to get search on our site.  It looks like the following simple HTML will get us 90% of the way to what we need.
```
<form class="devsite-search-form" action="/s/results" method="GET" id="top-search">

<input placeholder="Search" type="text" class="devsite-search-field devsite-search-query" name="q" value="" autocomplete="off">
<input type="hidden" name="p" id="search_project" value="/android" data-project-name="Google APIs for Web" data-project-path="/web" data-query-match="">

</form>
```

cc @gauntface @petele - I see this as a P0, I get asked about it all the time and it is hard to navigate the site without it (even in the new layout)

**Comment by gauntface** [comment]
Should be done in https://github.com/google/WebFundamentals/commit/29ccf2610868330c80e1d61c4a3011ef987b82e1

Going to close this and add an item to the checklist to test before launch.
