### ISSUE TITLE
Remove date yaml from episode pages in shows use written_on instead

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1626]
Instead of sorting on the date field, we should use `written_on` (or `updated_on`) so that we can reduce the YAML foot print

See this [ttt](https://raw.githubusercontent.com/google/WebFundamentals/material-branch/src/content/en/shows/ttt/series-1/cmd-line-shortcuts.markdown) as an example of the date attribute.

**Comment by gauntface** [comment]
Would you be up for changing written_on to publish_date, the reason for this is that written_on != video publish date, if we can do that, I'm happy to make this change in the infra.

**Comment by petele** [comment]
Fair point, what about a more drastic change? :)

What about doing:
```
date:
  published: 2015-01-01
  updated: 2015-02-20
```

**Comment by gauntface** [comment]
I don't really see the benefit of nesting here - it's an extra thing that could go wrong.

Happy with just published and updated.
