### ISSUE TITLE
Add author and date info to page header

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1633]
I like the look of the current updates site and would like to see something similar to this (though less hacky)...

![screen shot 2015-09-10 at 6 40 21 pm](https://cloud.githubusercontent.com/assets/718038/9802872/8a62b13c-57eb-11e5-9d7b-781437a39ba4.png)

**Comment by gauntface** [comment]
Implemented this - if you are happy with it then please close this issue and we can open up any further issues if bugs arise.

<img width="1190" alt="screen shot 2015-09-11 at 15 28 43" src="https://cloud.githubusercontent.com/assets/139760/9817297/e2550260-5899-11e5-9fac-9da12d44989a.png">

**Comment by petele** [comment]
<3
