### ISSUE TITLE
[EN] Feedback for: /fundamentals/getting-started/web-starter-kit/setting-up.html

### ISSUE THREAD

**Issue by LibraSun** [google/WebFundamentals#1635]
Under Windows 10 64-bit, I received all kinds of ERR and WARN messages during first attempt at performing steps outlined in "Set Up" section. Final message suggested retrying with Administrator privileges.

I re-opened a COMMAND window with "Run As... Administrator" selected from Start menu.

Second attempt at "> npm install" process succeeded without error messages.

Recommend updating "Set Up" section to reflect expected behavior under Windows, especially so as to differentiate it from (what appears to be) assumption that user's default operating system of choice would be Linux – insofar as other support links speak of 'sudo' – or OS X.

**Comment by petele** [comment]
@pbakaus - please triage and either assign to someone or close, thanks!

**Comment by gauntface** [comment]
I'll go through this guide next week and see what needs updating (including references for tweaks on Windows).

**Comment by LibraSun** [comment]
Thx! For the record, even once installation proceeded to fruition, my first
attempt to execute "gulp serve" resulted in "libsass errored... try
reinstalling node-sass?"

This appears to stem from my (n00b) attempt simply to repeat the "npm
install" procedure (without uninstalling first) shown on your page.
Googling revealed others with this same first-run issue, the solution to
which involved:

   - add NODE_PATH system variable in Windows > Advanced System Settings >
   Environment Variables... with the value of %AppData%\npm\node_modules

   - perform the steps offered in the Aug 28 entry of
   https://github.com/dlmanning/gulp-sass/issues/174

Note that I did both these operations and my very next try at "gulp serve"
worked perfectly!

Thought you should know. THANKS AGAIN!

**Comment by LibraSun** [comment]
Correction: "Apr 28" entry of
https://github.com/dlmanning/gulp-sass/issues/174, not "Aug".

**Comment by petele** [comment]
@gauntface ping
