### ISSUE TITLE
[EN] Feedback for: /fundamentals/layouts/rwd-fundamentals/index.html

### ISSUE THREAD

**Issue by hipe** [google/WebFundamentals#1656]
the subject page links to an example static html page. *that* page has an incorrect URL for its stylesheet, thus rendering the page without styling and defeating its pedagogic purpose.

"*that*" page:
  https://googlesamples.github.io/web-fundamentals/samples/layouts/rwd-fundamentals/vp-fixed.html

the above page loads, but its stylesheet fails to load. To fix this:

the incorrect URL:
  "/layout/vpdemo.css"

the correct URL:
  "vpdemo.css"
(that is, it should be relative, not absolute; and there is no "layout" directory.)

when it is fixed it should appear as the image in the tutorial:

![image](https://cloud.githubusercontent.com/assets/22006/9841599/bd55d7fa-5a6f-11e5-8849-0ba45334dd8d.png)

Thanks!

**Comment by petele** [comment]
Also ported to MDL
