### ISSUE TITLE
translated files should pull some yaml attributes from english master

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1661]
for example:
- order
- layout
- authors

**Comment by petele** [comment]
please add `written_on`

**Comment by gauntface** [comment]
This changed in https://github.com/google/WebFundamentals/commit/43a27d81bfedf226650431f4460d6d8ff3f32e52

We should now copy over any remaining issues and the YAML Validation has a list of keys which are only valid in the primary language.
