### ISSUE TITLE
[RU] Feedback for: /fundamentals/input/form/label-and-name-inputs.html

### ISSUE THREAD

**Issue by Agrishanin** [google/WebFundamentals#1695]
Hello.
There is a mistake in the followin sentence:
 "Обозначайте пола ввода надлежащим образом" but sould be lika so:  "Обозначайте пол**Я** ввода надлежащим образом"

**Comment by petele** [comment]
Good catch - we'll fix in the next update, thanks!

**Comment by petele** [comment]
Also ported to MDL branch
