### ISSUE TITLE
Create card & grid includes

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1696]
Ideally would be able to do something like:

    {% include shared/card.liquid title="something" text="the supporting text" 
               author="plepage" date=2015-01-01 link_desc="Learn more" link="url" 
               tags=['apple', 'banana', 'raspberry'] %}

I like @pbakaus's implementation on showcases, but also want to maintain as close to material as possible.

**Comment by gauntface** [comment]
I have committed first version of this for shows - see what you think, and alter or feedback away.
