### ISSUE TITLE
Provide tag functionality across the entire site

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1705]
All pages should be able to be tagged with appropriate keywords so that related content (based on tags) can be semi-automatically generated.

**Comment by gauntface** [comment]
Going to move ahead with idea of "site.pageGroups" as discussed.

**Comment by gauntface** [comment]
In your markdown YAML you can include:

    pageGroups:
      - front-page-feature

Then in your liquid template:

    {{ site.data.pageGroups['front-page-feature'] }}

Sorted by order or published_on variables.
