### ISSUE TITLE
[EN] Feedback for: /tools/profile-performance/rendering-tools/analyze-runtime.html

### ISSUE THREAD

**Issue by joelcoxokc** [google/WebFundamentals#1712]
When on this page the `main-nav__item main-nav__item--chrome-devtools`
Main Nav `Chrome DevTools` link goes to the URL `https://developers.google.com/tools/chrome-devtools`

The correct URL should be `https://developers.google.com/web/tools/chrome-devtools/`

**Comment by petele** [comment]
Fixed
