### ISSUE TITLE
Add subscribe to channel link to shows pages

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1734]
Not sure where to add, but would like to see on all pages under /shows

`<a class="mdl-button mdl-js-button mdl-button--raised" href="https://www.youtube.com/user/chromedevelopers?sub_confirmation=1">Subscribe</a>`

**Comment by gauntface** [comment]
We have a bug to redirect people to twitter and I've added G+ and YT into that, so would rather encourage people to the YT channel that way and for shows encourage people to subscribe to the RSS feeds for shows or drop the shows feeds and only encourage subscription of YT.

What do you think?

OR do we drop shows now that web shows are separate?

**Comment by gauntface** [comment]
@PaulKinlan for thoughts on this

**Comment by PaulKinlan** [comment]
I would like to see the feed present and discoverable via feed readers, but
if we have any UI on the page I would much prefer to get people to sub to
YT as quickly as possible.

**Comment by gauntface** [comment]
cc @PaulKinlan @petele 
I'm just thinking that Shows is a struggle to maintain and the only major advantages was to separate web shows and offer a feed.

If we are driving people to YT subscribe - let's just do that.

We can build something that generates a feed using the Youtube API if needs be.

**Comment by PaulKinlan** [comment]
We have that tool already.

I really want /web/shows to exist because it increases the surface area for
discovery and extra content.

**Comment by gauntface** [comment]
Discussion points with @petele:
- Integrate auto generation into shows (i.e. there are no markdown files).
    - Would need to move written content into something else (i.e. medium) and then link from YT description to medium post.
- Rather than a page for every show have a page with a single embed for the season playlist

Thoughts?

**Comment by gauntface** [comment]
I've just built a generator in node that has a interface on the command line to make it easier to add files.

I'll add in the subscribe button into the layout tomorrow.

![2015-09-21 17_31_42](https://cloud.githubusercontent.com/assets/139760/9997923/aef35512-6086-11e5-96b4-2ab8530a3f95.gif)

**Comment by gauntface** [comment]
@PaulKinlan @petele thoughts on this?

<img width="1338" alt="screen shot 2015-09-22 at 18 10 07" src="https://cloud.githubusercontent.com/assets/139760/10025664/3cac6208-6155-11e5-8373-7cb7c0ca80d6.png">

**Comment by petele** [comment]
Can we make it a little tighter? All on one line.

![screen shot 2015-09-24 at 10 23 24 am](https://cloud.githubusercontent.com/assets/718038/10075896/58e01454-62a6-11e5-8895-e5471c676eb9.png)

Suggested code:
```
{% if page.feedUrl %}
{% assign colwidth="mdl-cell mdl-cell--4-col" %}
{% else %}
{% assign colwidth="mdl-cell mdl-cell--6-col" %}
{% endif %}
<div class="wf-shows-subscribe mdl-grid">
  <h3 class="wf-shows-subscribe__title mdl-cell mdl-cell--12-col">Keep Up to Date</h3>
  <div class="mdl-cell {{colwidth}}">
    <div class="wf-shows-subscribe__yt-btn mdl-button mdl-js-button">
      <div class="wf-shows-subscribe__icon">
        {% include svgs/youtube.svg %}
      </div>
      <a href="https://www.youtube.com/user/chromedevelopers?sub_confirmation=1">Subscribe to Our Channel</a>
    </div>
  </div>

  <div class="mdl-cell {{colwidth}}">
    <div class="wf-shows-subscribe__feed-btn mdl-button mdl-js-button">
      <div class="wf-shows-subscribe__icon">
        {% include svgs/rss-icon.svg %}
      </div>
      <a href="{{site.WFBaseUrl}}/shows/feed.xml">Follow our Shows Feed</a>
    </div>
  </div>

  {% if page.feedUrl %}
  <div class="mdl-cell {{colwidth}}">
    <div class="wf-shows-subscribe__feed-btn mdl-button mdl-js-button">
      <div class="wf-shows-subscribe__icon">
        {% include svgs/rss-icon.svg %}
      </div>
      <a href="{{page.feedUrl}}">Follow the {{page.feedName}} Feed</a>
    </div>
  </div>
  {% endif %}
</div>
```

**Comment by gauntface** [comment]
Subcribe | Shows | <Show name>

**Comment by petele** [comment]
I'm OK with that, you ok with the code or want to do do something different?
