### ISSUE TITLE
Linked translation pages in head isn't working

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1752]
From: **open-page.liquid** line: 22

    
    {% for translated_page in page.translations %}
    <link rel="alternate" hreflang="{{translated_page.langcode}}" href="{{translated_page.canonical_url}}" />
    {% endfor %}

translated_page is returned as:
```
en<p class="intro">
  Building multi-device experiences is not as hard as it sounds.
  By following this guide, we will build an example product landing page for...
```

thus, it can't find translated_page.langcode and so we end up with a bunch of empty lines there.

**Comment by gauntface** [comment]
This is because of the change of translations to a hashmap rather than an array.
