### ISSUE TITLE
Page titles/descriptions are not being set in document head properly

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1753]
Instead of using the document `title`, it always uses the `html_head_title`

**Comment by petele** [comment]
See the suggestion I did in #1754, we need to do this for all sections.

**Comment by gauntface** [comment]
I've moved the logic to WFPage.rb - this applies to all pages.

If checks if the YAML defines a HTML_HEAD_TITLE should we ever want to allow that, if it's null it uses the title and finally fallsback to a default value.

The default value can be altered for a specific page type by overriding the class variables, like in FundamentalsPage.rb:

    DEFAULT_HEAD_TITLE = 'Web Fundamentals - Google Developers'
    DEFAULT_HEAD_DESCRIPTION = 'Google Developers Web Updates ' +
      'contains the latest news from the Chrome, looking at new features ' +
      'on the open web and in Chrome DevTools.'

**Comment by gauntface** [comment]
Added defaults to the other pages after discussing with pete seperately.
