### ISSUE TITLE
Lower visual priority of authorship

### ISSUE THREAD

**Issue by paulirish** [google/WebFundamentals#1767]
I don't know any other sites that publish the authorship data prominently at the top of the site.

But moreover, I think it detracts from the experience because it makes things look like blog content rather than living documentation.

Perhaps there are other visual presentations of authorship we can consider?

**Comment by gauntface** [comment]
@paulirish Totally ok with moving author details to somewhere else two Q:

1.) Would you like this to change everywhere or keep it in updates?
2.) Any ideas of what you'd like authorship to look like and where you'd like it to live?

I'm more than happy just ripping it out it entirely from the final doc.

**Comment by PaulKinlan** [comment]
I'm the opposite. I want people to know that it was written by an expert on
the topic.

**Comment by gauntface** [comment]
a.) Do people know who we are?
b.) Does it discourage someone else from just making edits when needed on the doc?
3.) It could easily still be there

**Comment by PaulKinlan** [comment]
1) Some do, and you should be then able to follow what else we have written
and it is part of role to be more visible and build credibility.
2) No.
3) Good. I don't mind where it is, something subtle is cool.

**Comment by gauntface** [comment]
The question remains - ideas for UI please.

**Comment by PaulKinlan** [comment]
I don't believe this Issue is against the material branch which is a lot
more subtle.

**Comment by gauntface** [comment]
@paulirish was this on material-branch or the current site?

**Comment by paulirish** [comment]
Material Branch.

**Comment by gauntface** [comment]
I'm just going to stuff authors at the bottom.
