### ISSUE TITLE
Leftnav doesn't indicate selected article

### ISSUE THREAD

**Issue by paulirish** [google/WebFundamentals#1768]
In the material redesign, the leftnav doesnt' communicate which item is currently selected.

[example](https://cloud.githubusercontent.com/assets/39191/10001368/41296f24-6056-11e5-991b-49475f6c6bd7.png)

It also lacks hover states on desktop, which makes it feel a bit flat and stodgy.

**Comment by petele** [comment]
Agreed, I'd like to get this done for v1, but OK to push to vs
