### ISSUE TITLE
Podcast static files aren't copied over to podcast dir

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1770]
See `src/content/en/shows/http203/podcast/`

It copies the `jpg`, but not the `feed.xml` or the `mp3`

**Comment by petele** [comment]
see #1771

**Comment by gauntface** [comment]
Got a fix in flight for the Fix is in place - somewhat fearful that the decision to hand update the podcast is going to be tiresome, but not sure if there is a better way.
