### ISSUE TITLE
Add MDL JS Library to DevSite

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1773]

**Comment by petele** [comment]
completed and checked in to DevSite

**Comment by petele** [comment]
Reopening - this was reverted in 127b695a849f9e4807982ad188fb987a3afbc062 because it broke nav and caused other issues (#1827).

We need to wait for MDL 1.0.5

**Comment by petele** [comment]
https://developers.google.com/_static/js/material_design_lite-bundle.js

**Comment by addyosmani** [comment]
1.0.5 should be getting tagged Monday. cc @sgomes so we inform you as soon as available.

**Comment by sgomes** [comment]
@petele Could you make sure that the [mdl-1.0 branch](https://github.com/google/material-design-lite/tree/mdl-1.0) has the fix you need? That's what we'll be tagging on Monday, aside from any other fixes we finish in the meantime.

**Comment by petele** [comment]
@gauntface will know for sure, he's been elbows deep in the mdl stuff.

**Comment by sgomes** [comment]
@petele Ah, then it would likely be the fix we've talked about already. I'll check with him, thanks!

**Comment by gauntface** [comment]
Yeah it's the same, will confirm on Monday

**Comment by gauntface** [comment]
Just to note, tested what is current in mdl-1.0 and everything is working - just need that to be made available in production.

**Comment by sgomes** [comment]
Fantastic, thanks @gauntface, that will happen soon :)

**Comment by gauntface** [comment]
@sgomes do you know if 1.0.5 is uploaded internally?

**Comment by sgomes** [comment]
@gauntface Not internally, no. That may take a few days.

**Comment by petele** [comment]
@gauntface says it's in.
