### ISSUE TITLE
Web Updates: Typography issues

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1783]
General issues

* Extremely odd that the section heading (h1) is much smaller than every other heading.
* Post titles on https://material-dot-web-central.appspot.com/web/updates/ are way too large and use too much real estate, plus make the block not look "contained" in itself, the heading is almost free floating. Bringing back the featured images will help a little.

Per post issues:

Compare https://developers.google.com/web/updates/2015/07/23/devtools-digest-aggregated-timeline-details-color-palettes-and-more with https://material-dot-web-central.appspot.com/web/updates/2015/08/devtools-digest-aggregated-timeline-details.html.

* In the old layout, the title is front and center and bigger than the rest, in the new layout it's folded into the very top that's usually the section header, a place that my eyes ignore.
* In the old layout, the one sentence description below the header gives a quick TL;DR, in the new page, it's missing.
* In the old layout, the left hand category navigation bar offers not only further navigation but also shows the current posts type. This is missing in the new layout.
* In the old layout, sub headings are balanced with the rest of the content. The size and margins are carefully picked and handcrafted over a multi-hour process to make sure every paragraph and sub topic has room to breathe. In the new layout, sub headings are way too large compared to the paragraphs and have way too less margin. Everything looks cramped.

**Comment by petele** [comment]
Replaced by #1814 #1743 #1816
