### ISSUE TITLE
Showcase: Case studies need to be front and center on homepage

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1784]
Compare https://developers.google.com/web/showcase/?hl=en with https://material-dot-web-central.appspot.com/web/showcase/.

In the old layout, the case studies are front and center with a featured case study at the top, and again appearing in the cards below as double-wide item. This is deliberate. Case studies are much more important to highlight than spotlights.

Please bring back the higher visual priority for case studies.

**Comment by petele** [comment]
Replaced by #1813 and #1810
