### ISSUE TITLE
Showcase: Spotlight card images look cut off, images for case studies missing

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1787]
Spotlight card images look weirdly cut off, and images for case studies are missing:

![bildschirmfoto 2015-09-22 um 10 32 01](https://cloud.githubusercontent.com/assets/43004/10026186/2fa7bbd8-6115-11e5-867a-9a41bd2c03d9.png)

Compare to old design:

On homepage:
![bildschirmfoto 2015-09-22 um 10 33 02](https://cloud.githubusercontent.com/assets/43004/10026222/584832de-6115-11e5-9419-421d75901d3f.png)

On sub page (spotlights):
![bildschirmfoto 2015-09-22 um 10 33 43](https://cloud.githubusercontent.com/assets/43004/10026241/6c9b3236-6115-11e5-86b3-522fc8a5e477.png)

**Comment by petele** [comment]
Fixed many of these and have added new bugs.
