### ISSUE TITLE
Showcase: Spotlight template is broken or unfinished

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1791]
I can only assume that the spotlight template is incomplete. Compare the old layout of https://developers.google.com/web/showcase/spotlight/hummingbirdlibrary to https://material-dot-web-central.appspot.com/web/showcase/hummingbirdlibrary

Missing:

* Big app screenshot
* Related guides
* Nice visual separation of our written thoughts and Q&A (see yellow block on old page)
* Typo all over the place, margins lacking.

**Comment by petele** [comment]
Fixed missing screen shot, related guides.

**Comment by petele** [comment]
Fixed some parts and replaced by #1811
