### ISSUE TITLE
Showcase: Case study template is broken or incomplete

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1792]
Compare https://developers.google.com/web/showcase/case-study/chrome-dev-summit to https://material-dot-web-central.appspot.com/web/showcase/chrome-dev-summit. I can only assume this template hasn't been touched.

Issues:
* Metadata block not formatted in any meaningful way
* Images missing
* Latest spotlights should be Latest case studies
* Typo all over the place

**Comment by gauntface** [comment]
Typo's shouldn't exist so either the doc is out of date (which I highly doubt) or the auto manipulation script is playing havoc.

We are merging case studies and showcases so I'll look at the yaml - chances are that we need to figure out the structure of the two.

**Comment by petele** [comment]
Replaced by #1813 #1811 #1810

**Comment by pbakaus** [comment]
@gauntface sorry, typo stands for typography here, my mistake :)
