### ISSUE TITLE
Chrome DevTools page completely broken

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1794]
Compare old page at https://material-dot-web-central.appspot.com/web/tools/chrome-devtools to new page here: https://material-dot-web-central.appspot.com/web/tools/chrome-devtools. 

Some highlighted issues:

* DevTools Digest block is missing
* CSS is missing and all over the place
* Social images are missing
* Tips are missing
* Main description isn't hidden by default

**Comment by petele** [comment]
Yep - looks like we missed this page in our updates. Will fix most items here and discuss others.

**Comment by petele** [comment]
Replaced by #1808
