### ISSUE TITLE
Add add MDL JS component libraries to wrapper.tpl

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1795]
Currently only includes:
    <script src="/web/scripts/material-design-lite/src/mdlComponentHandler.js"></script>
    <script src="/web/scripts/material-design-lite/src/layout/layout.js"></script>

Should include all of the components.

**Comment by gauntface** [comment]
Note: This should be the compiled version of all MDL scripts if we want to do this.

We could use the cloud storage version: <script src="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.min.js"></script>

**Comment by petele** [comment]
I'd rather use a local copy, only so that on an airplane or non-internet connection, i'm not broken.

**Comment by petele** [comment]
Fixed.

Put a non-minified version into the mdl folder and referenced that.
