### ISSUE TITLE
[EN] Feedback for: /tools/chrome-devtools/index.html

### ISSUE THREAD

**Issue by antoops** [google/WebFundamentals#1806]
In the menu, its confusing. for example, if i select Tools from web, it will show tools like polymer, web starter, dev tools. But when i click on any of those, there is no easy or standard way to come back to the tools page to select another tool. Please check.

**Comment by petele** [comment]
Agreed! We're about two week away from a complete redesign and this should be fixed with that.

You can get a sneak peek at the work in progress at https://material-dot-web-central.appspot.com/web/tools/chrome-devtools/
