### ISSUE TITLE
Need better featured images for show case home page

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1811]
- [ ] Hummingbird Library
- [ ] Madeon Adventure
- [ ] Adsy.me
- [ ] Little Alchemy
- [ ] Hacker News Reader
- [ ] Web Filter
- [ ] Merry Pixmas
- [ ] Chrome DevSummit
- [ ] SVGOMG
- [ ] OHH1

**Comment by gauntface** [comment]
@pbakaus any updates on this or ideas of what you want?

**Comment by pbakaus** [comment]
I'm a little stuck on this. The 5/3 format (or something) obviously doesn't work terribly well for a mobile screenshot. Open to suggestions.

**Comment by gauntface** [comment]
For now I don't think it's a problem, if more people raise this as an issue we can look at alternatives.
