### ISSUE TITLE
Add a .intro class used at the top of articles for the intro paragraph

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1816]
Most articles have a 
```
<p class="intro">
blah blah blah
</p>
```
This should be formatted in a slightly different way to teh rest of the content along the lines of what we had before.

**Comment by gauntface** [comment]
Reopen if you want something different.

At the moment its larger font with more line height.

![screen shot 2015-09-30 at 11 58 24](https://cloud.githubusercontent.com/assets/139760/10191298/9616c43a-676a-11e5-894f-51bc269cc271.png)
