### ISSUE TITLE
NAV when in narrow mode does not show

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1827]
@gauntface - i prob broke this when I replaced the JavaScript file. We should check to understand why, it may also happen on DevSite.

**Comment by gauntface** [comment]
Yup it broke with that change.

I put fixes into MDL's layout.js (both locally and to the MDL repo) meaning we wouldn't need to use the entire icon font, we could just inline svg's we needed.

This hasn't made it to pre-compiled JS yet, I'll follow up with team on release timeline etc for 1.0.5 and when that will make it into internal stuff for devsite.

In the mean time I've reverted your change with a comment as to why.
