### ISSUE TITLE
NAV does not scroll when its extends beyond screen

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1828]
When left nav is visible, if it's longer than the screen length, it doesn't scroll

@gauntface - may have broken this one too with the change to the mdl library in the template.

**Comment by gauntface** [comment]
I see scrollbars (after fixing issue with js).

![screen shot 2015-09-24 at 12 11 09](https://cloud.githubusercontent.com/assets/139760/10071921/6c6f7abe-62b5-11e5-9b3a-f3c68d992cdb.png)
