### ISSUE TITLE
Flash required to view video

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/WebFundamentals#1830]
Flash is required to view the video on this page:

https://material-dot-web-central.appspot.com/web/tools/setup/device-testing/devtools-emulator

![screen shot 2015-09-24 at 12 22 14 pm](https://cloud.githubusercontent.com/assets/51244/10072111/ef018cbe-62b6-11e5-9059-4d02e996365c.png)

(Safari screenshot, but Chrome has the same problem.)

**Comment by ithinkihaveacat** [comment]
Looks like `src/_langs/en/updates/2015-08-20-using-poster-images-on-plugin-content.markdown` might also have the same problem.

**Comment by gauntface** [comment]
It looks like a bad YouTube embed in the first example :( Thanks for highlighting.

That blog post you links to doesn't have any flash or embed just code snippets, please reopen if you can share more info / see the problem.

**Comment by ithinkihaveacat** [comment]
Ah, my bad re the second link, I just grepped for `x-shockwave-flash` but it's just in a code snippet.
