### ISSUE TITLE
Same link text used for distinct pages 

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/WebFundamentals#1832]
On https://material-dot-web-central.appspot.com/web/updates/, the same link text ("VIEW") is used for every link in the body of the page. I think this will impair accessibility, see e.g. http://www.w3.org/TR/WCAG20/#navigation-mechanisms-refs.

**Comment by gauntface** [comment]
I've made the change from a separate issue about the image / title being clickable, which would give more context on the link.

Do you think that would enough? Otherwise I'm not sure what we could replace view with, any ideas / recommendations?

**Comment by ithinkihaveacat** [comment]
Maybe it doesn't need "VIEW" at all? Perhaps the link will be obvious enough without it?

**Comment by gauntface** [comment]
@petele thoughts?

**Comment by petele** [comment]
Got it.

**Comment by petele** [comment]
Fixed in #1970
