### ISSUE TITLE
Left Nav Title is inconsistent and repeated multiple times

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1840]
The page title repeats feel odd — same for other sections. 

![image](https://cloud.githubusercontent.com/assets/205226/10079387/6322f876-6307-11e5-9588-50c61b19de67.png)

**Comment by petele** [comment]
Agreed this is odd, suggestions on how to fix?

@gauntface @PaulKinlan

**Comment by gauntface** [comment]
What do you want the solution to be?

Consider this:

![screen shot 2015-09-30 at 11 56 41](https://cloud.githubusercontent.com/assets/139760/10191265/5d0a2baa-676a-11e5-941b-49bb167fa0eb.png)

I'm happy to just remove the heading, but some has said that.

**Comment by samdutton** [comment]
This looks fine, but I think the whole site should be called Web Fundamentals, and the Web Fundamentals 'section' should be renamed Get(ting) Started (or whatever).

Either that or we have to rename the whole site 'Slash Web' or whatever — but then we lose the brand value of Web Fundamentals.

**Comment by gauntface** [comment]
Just removed the heading.

**Comment by samdutton** [comment]
So does the whole site have a name, since Web Fundamentals is a section of it?

**Comment by petele** [comment]
@samdutton - officially, it's slash web. ;)

**Comment by samdutton** [comment]
OK :).

Actually — the written name `/web/` is quite cool.
