### ISSUE TITLE
Web Fundamentals as site name and section name

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1841]
The site is called Web Fundamentals, but also has a section called Web Fundamentals.

I think that's odd — the section should be renamed something like Resources (or whatever).

**Comment by petele** [comment]
Do you mean on the /web page? Of so, ignore. Otherwise, can you include a specific URL/example we can reference?

**Comment by samdutton** [comment]
I meant that (for all pages) the site has a section called Web Fundamentals. It's odd having that as a section name as well as Web Fundamentals being the name of the whole site.

For example, on https://material-dot-web-central.appspot.com/web/showcase/:

![image](https://cloud.githubusercontent.com/assets/205226/10082820/4adf2778-6319-11e5-83ab-238257f837da.png)

**Comment by petele** [comment]
"Web Fundamentals" is the name of the section, but the whole site is essentially /web. I often use "WF" to refer to everything which can be confusing. Understanding this, is this still an issue?

**Comment by samdutton** [comment]
> Understanding this, is this still an issue?

Will the name/brand of the site as a whole be Web Fundamentals (i.e. not 'slash web')? If so, yes.
