### ISSUE TITLE
Navigation items change order as you change sections - they shouldn't

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1842]
I don't think the navigation should swap order when you click on a section.

I tend to agree with the old-fashioned UI rule that things shouldn't move — and people are pretty used to expanding menus.

**Comment by petele** [comment]
This is one @gauntface and I disagree on, I prefer that they remain in a consistent order, he prefers the change.  CAGE FIGHT.

@gauntface - what are your reasons for keeping it as is?

**Comment by gauntface** [comment]
If thats what you want then fine.

I question how often users will jump between sections and I hate the idea of putting a set of highlevel navigation above the title of the current section.

BUT if you want it can change.

**Comment by petele** [comment]
Let's leave as is for now, keep this bug open, and ask the material folks when they do the review @addyosmani asked them to do.

**Comment by kaycebasques** [comment]
I opened a dupe on the topic. Here's my text from the dupe:

The new nav menu seems unconventional (in terms of UX).

<img width="536" alt="screen shot 2015-09-24 at 2 39 33 pm" src="https://cloud.githubusercontent.com/assets/4713486/10087668/2680183c-62ca-11e5-9523-29b2b940bac5.png">

Clicking on *Showcase* in the screenshot above effectively transports the user to the Showcase section of the site. With *Showcase* in place of *Web Fundamentals* and the top-level Showcase documents listed beneath. 

Pure first impression: As a user I was lost for a couple of seconds. I've never seen a nav UI like this. It took (literally) a couple seconds for me to understand what was going on. 

An accordion-style nav menu seems more conventional to me. 

I *think* the current UI could work, if the site provides a little more visual feedback. Take the screenshot above again for example. When I click on Showcase, some sort of animation that replaces the *Web Fundamentals* link, and then populates the list with the Showcase pages, and then moves *Web Fundamentals* down to the bottom of the nav, would probably be sufficient for me to understand what just happened.

LMK if that all makes sense :+1:

**Comment by kaycebasques** [comment]
:+1: to the UI rule that "things shouldn't move"

**Comment by gauntface** [comment]
Ok will change. Thanks for feedback.

**Comment by gauntface** [comment]
I've made this change.

@petele @kaycebasques @samdutton thoughts on this change?
