### ISSUE TITLE
Needs more visual focus on content

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1844]
I'd like more visual focus on content. Lots of page have very little content visible on page load.

![image](https://cloud.githubusercontent.com/assets/205226/10079879/201ec0e8-630a-11e5-884d-6c0a3c7dcb95.png)

![image](https://cloud.githubusercontent.com/assets/205226/10079908/496bdabc-630a-11e5-831f-e097dfad2d54.png)

**Comment by petele** [comment]
Can you be specific here? Call out the issues that need to be fixed.

**Comment by samdutton** [comment]
If you look at these two examples (article pages are similar) there's not much actual content visible — as opposed to whitespace, space devoted to navigation, banner, etc. 

There's no specific rule, but successful sites on similar topics all put visual focus on content.

**Comment by petele** [comment]
For https://material-dot-web-central.appspot.com/web/fundamentals - the page is still in progress and needs a LOT of work. I've added a call out to that regard and an issue filed to complete that page.

I'm not sure what you mean by article pages.

**Comment by samdutton** [comment]
> I'm not sure what you mean by article pages.

I mean pages that have content, rather than top level section pages, etc.: pages like [this](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/input/forms/).

Only about half this page is information: the rest is banner, author image/link, etc.

![image](https://cloud.githubusercontent.com/assets/205226/10116793/388d2c08-6438-11e5-907e-f32ace66bb91.png)

**Comment by gauntface** [comment]
This is what an iphone 4 looks like with intro tweaks.

![screen shot 2015-09-29 at 17 44 33](https://cloud.githubusercontent.com/assets/139760/10171379/d18efa58-66d1-11e5-8311-b024d7dd9209.png)

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
