### ISSUE TITLE
Update subsections need better titles

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1850]
Right now the titles are pulled from the folder name, but it'd be nice to be able to provide a more friendly name, for example "Web platform news" and "Chrome DevTools updates"

/cc @Meggin

**Comment by gauntface** [comment]
I'm struggling to think of a same way to approach this.

The way updates is currently built (in both this and the previous version) doesn't lend itself to this now that we auto-generate the better book..

**Comment by gauntface** [comment]
This is a duplicate of another bug and titles have changed as is.
