### ISSUE TITLE
Verify all feeds (rss & atom) work

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1851]
- [ ] fundamentals
- [ ] showcase
- [ ] shows (all)
- [ ] shows (each individual show)
- [ ] tools
- [ ] updates (all)
- [ ] updates (devtools)
- [ ] updates (news)
- [ ] global

**Comment by gauntface** [comment]
I believe I've done the following:

- [x] fundamentals
- [x] showcase
- [x] shows (all)
- [x] shows (each individual show)
- [x] tools
- [x] updates (all)
- [ ] updates (devtools)
- [ ] updates (news)
- [x] global

Will tackle updates.

**Comment by gauntface** [comment]
I think this is all up and running and in the right order.
