### ISSUE TITLE
Move Response Web Design Basics to Top-level category in WF

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#1854]
Responsive Web Design Basics is currently located in a Responsive sub-category in Design and UI.

It's very important part of building your site-- having a viewport is a super-basic necessity.

I've created a related issue to re-title 'Guides' to 'Get Started', and I see 'Responsive Web Design Basics' as part of the 'Get Started' experience.

Related issue: https://github.com/google/WebFundamentals/issues/1853

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
