### ISSUE TITLE
Move Starter Kits to Top-level category in WF

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#1855]
Currently there are links in the left-side navigation in /web/tools to the Web Starter Kit and Polymer Starter Kit.

This is a suggestion to create a new subsection called Starter Kits in the WF top-level category, and have  links within that to Web Starter Kit and Polymer Starter Kit.

This makes the focus in /web/tools much clearer.

Also, if 'Guides' was renamed to 'Get Started', then 'Starter Kits' would fit nicely into the higher level category.

**Comment by petele** [comment]
Closing due to age, feel free to re-open if action is required.
