### ISSUE TITLE
Rename Showcase to Case Studies and clarify filters

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#1856]
Can we renamed Showcase to Case Studies?

Also, what is the main difference between Spotlights and Case Studies? They both seem very similar.
Can we clarify what these are specifically and somehow distinguish them a bit better in the UI?

Visually the presentation of the two are exactly the same, so it's hard to understand why they are filtered.

**Comment by PaulKinlan** [comment]
One is deep (case studies) and one is short and a quick answer three
questions

**Comment by gauntface** [comment]
Do we have a pipeline of case studies?

**Comment by pbakaus** [comment]
We do (it's light though). Next case study is almost done.

**Comment by petele** [comment]
Closing due to age, feel free to re-open if action is required.
