### ISSUE TITLE
Show tags on pages in Updates section

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#1857]
The Updates section as a new filter by tag. However, when you go to a page based on a selected filter, you can't see it's related tags. Arthur Evans actually spotted this-- I'm just raising the issue for speedy sake.

**Comment by gauntface** [comment]
Where would you like them put?

We've seen low usage of tags hence why they aren't current on updates.

**Comment by petele** [comment]
Centralizing the conversation on #2040
