### ISSUE TITLE
Re-think API Primers

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#1858]
We've identified a need for a section that includes a range of high-level conceptual docs that many of the web fundamentals docs will reference.

It's currently been titled API Primers, which lives inside of WF. I did a search for API primer, and the content that comes up doesn't validate a clear understanding of what this might mean in the developer community (try it out and see).

Also, we currently don't have a lot of content in API primers. I would like to propose that we actually create an 'Offline' section, which will include service worker docs, and maybe another section 'Asynchronous JavaScript Basics', which could include promises. These could both be sections within the WF UI, at the same level as Performance, Design and UI, etc.

I'm also open to a new section called 'Key JavaScript Concepts' or something like that. But I'm wary, as where do we begin and end with this?

**Comment by petele** [comment]
Moved into Getting Started in the new IA
