### ISSUE TITLE
Typography work needed on article pages

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1859]
I think article pages like [this](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/add-a-video) need some work on the text:

* On desktop the intro paragraph ('Learn about …') needs more visual weight: it gets a bit lost with all the text below it. 
* As it is, the languages navigation + Intro + Contents + TL;DR feels cluttered — doesn't draw your eye down the page. I think these sections could be better differentiated visually, maybe by adding a coloured background to Contents or TL;DR (or whatever). 
* Items in TL;DR and Remember sections should have more line-height (i.e. leading) or a smaller font size.

![image](https://cloud.githubusercontent.com/assets/205226/10089903/c3ce51b8-6346-11e5-928e-8d831ff0ef25.png)

![image](https://cloud.githubusercontent.com/assets/205226/10090042/2d678b20-6348-11e5-9417-16430581e7d7.png)

**Comment by gauntface** [comment]
Intro has been given larger font size.

The line height and style of tldr and contents has changed.

The only remaining thing is decluttering this. The translations are now in the bottom right on the page.

I'm not sure how best to approach decluttering the contents and tl;dr, but I agree having both is too much.

**Comment by samdutton** [comment]
Looking good.

Nitpick: I think the line height of the intro para could be a bit more (1.2em) and the text size a bit less (say 18 or 17px).
