### ISSUE TITLE
{% highlight html %} are using the wrong font

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1860]
Some pages like [this](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/add-a-video) have some code samples in Times, not Courier. Seems like the class and data-lang attributes are going wrong somewhere.

![image](https://cloud.githubusercontent.com/assets/205226/10090157/9021b65e-6349-11e5-896a-99eaa312898d.png)

**Comment by petele** [comment]
It looks like it's a difference between the snippet embed types.
`{% highlight html %}` is using Times while `{% include_code ...` is using the correct font.

**Comment by gauntface** [comment]
I literally see no difference between this bug and https://github.com/google/WebFundamentals/issues/1861

Has anyone touched anything to do with the code styling?

1.) I don't see the times samples as Sam has screenshotted
2.) I've moved everything to Roboto Mono

If someone can confirm that is the case for https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/add-a-video and close this bug and the other bug (https://github.com/google/WebFundamentals/issues/1861) I'd appreciate it.

**Comment by petele** [comment]
Fixed! Whee!
