### ISSUE TITLE
Suggestion - use Courier New, not Courier for code blocks

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1861]
Just a nitpick, but I think Courier New is clearer than Courier (examples below are on Mac, but you get similar results for Windows, Android and other platforms). Courier New is widely supported, and we can add a fallback.

Courier:
![image](https://cloud.githubusercontent.com/assets/205226/10090266/2a5207b4-634b-11e5-89f3-cd7ad6be5005.png)

Courier New:
![image](https://cloud.githubusercontent.com/assets/205226/10090263/1a358900-634b-11e5-88c9-deece2c2984e.png)

**Comment by petele** [comment]
This is essentially the same as #1860

**Comment by samdutton** [comment]
No — the other bug is a glitch.

What I'm suggesting here is that we make a change and use Courier New
instead of Courier.

**Comment by petele** [comment]
We should check to see what DevSite uses as well.

**Comment by gauntface** [comment]
I don't see the difference between this bug and #1860

Please see other bug.

**Comment by petele** [comment]
We're using Roboto Mono instead as it's the devsite official font.
