### ISSUE TITLE
TL;DR missing on size videos correctly

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1862]
Like [this one](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/size-videos-correctly.html).

![image](https://cloud.githubusercontent.com/assets/205226/10090302/938dfad0-634b-11e5-990f-14bddad34c1b.png)

**Comment by petele** [comment]
Can you list all the pages where you've seen this?

**Comment by samdutton** [comment]
Can't find it anywhere else.

**Comment by petele** [comment]
Fixed in #1879
