### ISSUE TITLE
Starter kit pages needs overall design work

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1863]
On pages like [this](https://material-dot-web-central.appspot.com/web/tools/starter-kit/): 

* Heading line height (leading) is too tight.
* The centred/left-aligned combination looks odd.
* Text below headings should align vertically.
* I don't understand the difference in heading size between the items at the top and at the bottom.

![image](https://cloud.githubusercontent.com/assets/205226/10090328/e9d51072-634b-11e5-91be-3721cb5a6f30.png)

**Comment by gauntface** [comment]
I've tweaked styles and the content to something like this:

![screen shot 2015-09-28 at 16 48 05](https://cloud.githubusercontent.com/assets/139760/10140706/c22c45d8-6600-11e5-8e37-2e813a29955d.png)

Thoughts? cc @addyosmani

**Comment by samdutton** [comment]
Couple of things:

* The body of each item should align vertically with the items next to it: for example, the top of 'Reload the browser ...' should align vertically with 'Synchronize clicks...'. 

* The line-height in the heading for each item still looks too tight: letters like g and p will bump into capital letters and letters like b and d. Line height is currently 1 whereas 1.2em should be about right.


![image](https://cloud.githubusercontent.com/assets/205226/10141572/3c53b252-6605-11e5-99a8-10e6bb60bab2.png)

**Comment by gauntface** [comment]
This is no different to what the current design does in terms of titles.

Sam can you think of a good way of doing this?

**Comment by samdutton** [comment]
As discussed offline — I guess the simplest option is to set the height of the title, but that could go wrong for 3–4-line titles. 

Instead, you could something crazy like putting the titles in a div and the text in a div below, getting the titles to float left, with the same relative width as the text below them...

    <div class='foo'>
      <h3>This is title No.1</h3><h3>This is another title No.2</h3><h3>This is a really really really long title No.3</h3>
    </div>
    <div class='bar'>
      <div>Text below title 1</h3><h3>This is blah blah blah text for title 2</h3><h3>This is text for title 3</h3>
    </div>

**Comment by gauntface** [comment]
Added a height to the headings.
