### ISSUE TITLE
Link underline and hover

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1864]
Links should have a hover state, e.g. change of colour or underline.

All links should be underlined (or not): language choice links, etc., don't have underline.

**Comment by gauntface** [comment]
Peoples thoughts on this?

Links have the different cursor state.

Where color difference isn't enough, we have underline (by default all links are underlined and additional styles are added to remove the underline).

Regarding hover state - we can add this in, but I'm rarely a fan of this - peoples thoughts?

**Comment by gauntface** [comment]
@PaulKinlan @petele

**Comment by samdutton** [comment]
I'm OK with the current combinations.

I think it's clear what the links are: mostly that the colour is consistent.
