### ISSUE TITLE
Overhaul: Principles of site design text is too big

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1865]
...which makes text run onto two lines awkwardly.

![image](https://cloud.githubusercontent.com/assets/205226/10090468/6e841588-634d-11e5-8ed7-ceaa651adfaf.png)
![image](https://cloud.githubusercontent.com/assets/205226/10090500/c879a4fe-634d-11e5-9f95-b731ef712782.png)

**Comment by petele** [comment]
this page is a work in progress, there's another open issue on it already.
