### ISSUE TITLE
Header flashes and moves on mobile

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1869]
Open a page like [this](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/) on mobile and you get a brief 'half load' while the banner appears from the right. 

Maybe this is intentional, but it feels odd.

![image](https://cloud.githubusercontent.com/assets/205226/10107869/bad1a0f0-63b5-11e5-8577-51f3ab738db4.png)

**Comment by petele** [comment]
You can see this happen in the emulator as well, it just happens more quickly. I have the feeling this is an MDL issue though.

**Comment by gauntface** [comment]
This is an MDL issue - just had a chat with Sergio, hopefully this will be fixable in 1.0.5 - if not we can probably do a custom fix.

Assigning to sergio for now.

**Comment by gauntface** [comment]
I've cherry picked the fix from MDL into our branch - hopefully it should be good to land into MDL 1.0.5.
