### ISSUE TITLE
Indicator when code sample overflows viewport required

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1870]
Code overflows when viewing pages like [this](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/add-a-video) in a smaller viewport.

Not sure what the answer is, but we need somehow to signify that the code samples can be scrolled horizontally.

![image](https://cloud.githubusercontent.com/assets/205226/10108019/7dd7c908-63b6-11e5-8814-b7c1446b2365.png)

**Comment by petele** [comment]
This happens in the existing version as well, but I'll update this to add an indication content can be scrolled.

**Comment by gauntface** [comment]
Anyone have any idea how to add an indicator?

**Comment by gauntface** [comment]
Discussed in person - this is not possible without JS so not going to add anything.
