### ISSUE TITLE
Bullet list before modules/remember.liquid causes rest of the page style to break.

### ISSUE THREAD

**Issue by johyphenel** [google/WebFundamentals#1873]
Including a bullet list before a module/remember.liquid causes a visible "</div>" to be added to the page, and the rest of the guide becomes indented from that point forward.

---Markup----
<code>
`*` expected

text is required here... :(

{% include modules/remember.liquid title="Note" list=page.notes.test %}

This text is indented as expected

`*` Unexpected

{% include modules/remember.liquid title="Note" list=page.notes.test %}

Even after the note, the text stays indented :/
</code>
---Screenshot---
![image](https://cloud.githubusercontent.com/assets/288094/10120221/fc516514-6465-11e5-8094-14d210410aca.png)

**Comment by johyphenel** [comment]
Adding `<span></span>` after the list seems to be a viable workaround.

---Markup---
<code>
`*` span fix?

<span></span>

{% include modules/remember.liquid title="Note" list=page.notes.test %}

indent fixed!
</code>

---Screenshot---
![image](https://cloud.githubusercontent.com/assets/288094/10120244/239abb24-6467-11e5-882e-a7f8dc2ead5d.png)

**Comment by petele** [comment]
@johyphenel - is there a specific page where this is happening now?

**Comment by johyphenel** [comment]
Tagged you in #1875.

**Comment by petele** [comment]
See fixing-mixed-content.markdown around line 200.

**Comment by gauntface** [comment]
Ignore my prev commit 0 wrong issue ID
