### ISSUE TITLE
When scrolling away the header, the page body should not jump around

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1894]
Right now, when loading a page such as http://localhost:7331/web/tools/setup/workspace/setup-buildtools, the page does a jump when you scroll down and it's very irritating. Let's solve this without jumpy jump jump.

**Comment by PaulKinlan** [comment]
This is material, no?

**Comment by petele** [comment]
Nope - other awkward jump.

**Comment by gauntface** [comment]
This is MDL issue - opened here: https://github.com/google/material-design-lite/issues/1658
