### ISSUE TITLE
Language picker interferes with wf-subheading blocks

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1903]
See attached

![screen shot 2015-09-29 at 9 21 29 am](https://cloud.githubusercontent.com/assets/718038/10158665/87156354-668b-11e5-9221-85c1e0c87fb8.png)

I'd like to see if we can put the lang picker at the bottom of the page in a drop down list, but we'll need to see how much code it involves.

**Comment by gauntface** [comment]
Moved this to bottom right - so this is no longer an issue.
