### ISSUE TITLE
In narrow author & date should left align

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1905]
Currently there's ~80px left margin.

![screen shot 2015-09-29 at 9 26 08 am](https://cloud.githubusercontent.com/assets/718038/10158824/6b206576-668c-11e5-915b-a8809e7ba198.png)

**Comment by petele** [comment]
Also notice we lose part of the G+ social logo

**Comment by gauntface** [comment]
Dropped the author on mobile
