### ISSUE TITLE
TL;DRs need more margin/padding to between each element

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1906]
There are three separate TL;DRs listed here, but you can't easily differentiate them.

![screen shot 2015-09-29 at 9 29 59 am](https://cloud.githubusercontent.com/assets/718038/10158881/ba2b31e6-668c-11e5-94ec-14e7dfe09f78.png)

This also goes for Remember blocks as well.

**Comment by petele** [comment]
In v1 we did this by using bullets, we can use bullets again, or whatever else. I'm open.

**Comment by gauntface** [comment]
Updated here: https://material-dot-web-central.appspot.com/web/resources/jekyll/useful-and-common-tags

Reopen if disagree

![screen shot 2015-09-29 at 15 05 04](https://cloud.githubusercontent.com/assets/139760/10166343/7f74c614-66bb-11e5-9413-2d301a3ec6be.png)
