### ISSUE TITLE
Try Sample buttons need more padding or smaller text

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1907]
The TRY FULL SAMPLE buttons below `{% include_code ...` blocks need some TLC. Either the font size needs to be made a touch smaller, or they need more horizontal padding.

See https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/add-a-video

![screen shot 2015-09-29 at 9 32 21 am](https://cloud.githubusercontent.com/assets/718038/10158976/394c8ce0-668d-11e5-977d-16cbf0f4748e.png)

**Comment by gauntface** [comment]
I reduced the font size from 16 - 14px in the typography tweaks.
