### ISSUE TITLE
Title for previous article not appearing in narrow view

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1908]
The bottom prev/next nav that shows the previous/next article shows the title of the next article, but not the previous one.

See https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/provide-alternatives-for-legacy-platforms.html

**Comment by gauntface** [comment]
This is to give the next section title width to actually to display.

Would you rather I remove all text on narrow?

**Comment by petele** [comment]
Hm, it feels odd to only show one way. Will it look too odd to make the text smaller?
