### ISSUE TITLE
Wide tables in narrow view need to scroll side to side

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1910]
Right now, part of the content is cut off, and there's no way to see anything on the right.

For [example](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/input/forms/label-and-name-inputs.html) on a Nexus 5:
![screen shot 2015-09-29 at 9 40 14 am](https://cloud.githubusercontent.com/assets/718038/10159091/1cc908c2-668e-11e5-8f09-4942a4afe573.png)

**Comment by petele** [comment]
Issue [1660](https://github.com/google/material-design-lite/issues/1660) filed with MDL git repo

**Comment by gauntface** [comment]
For now I've added:

    display: block;
    overflow: auto;

This allows the tables to scroll, but this could be better with proper responsive tables.
