### ISSUE TITLE
Scrub site for titles on remember.liquids

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1913]
Remove the title so that we can more easily localize.

**Comment by gauntface** [comment]
Trying to action this bug.

What is the request here? Assign different includes and make it impossible to set the title? Or go through the content and ensure every title is using localize string?

**Comment by petele** [comment]
I take care of this, essentially it's a content scrub to find instances of `{% include shared/remember.liquid` and verifying they do not include a title, it should be provided in the include.

**Comment by marccantin** [comment]
STOP YOUR SPAM GRRRRRRRRRRRRRRRRRRRRR

2016-09-23 12:14 GMT-04:00 Pete LePage <notifications@github.com>:
