### ISSUE TITLE
Need way to show additional authors on article

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1916]
Currently only the first author is shown, if multiple authors are present, we should show them all.

This doesn't need to be at the top, but should be somewhere else within the article.

**Comment by gauntface** [comment]
Any ideas of where?

There is a seperate issue here (https://github.com/google/WebFundamentals/issues/1767) which suggests lowering the priority of authors.

**Comment by gauntface** [comment]
Fixed this.

Build also throws and error if the author name is invalid.
