### ISSUE TITLE
Overhaul: Author image and date not visible on mobile

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1934]
Pages like [this](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/video/add-a-video#specify-a-start-and-end-time). Fine on desktop.

![image](https://cloud.githubusercontent.com/assets/205226/10171153/821fc1b0-66d0-11e5-8cc4-249abc99d8a0.png)

**Comment by petele** [comment]
We've moved author & date to the bottom of the page.

**Comment by samdutton** [comment]
Good idea. Only problem is that the banner now (I think) has too much empty space.

On pages like [this](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/media/), I think the title could go in the banner and the links and search could go on one line:

![image](https://cloud.githubusercontent.com/assets/205226/10195519/f1012e56-6785-11e5-859f-c82dc536b76e.png)
