### ISSUE TITLE
Banner layout suggestions

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1942]
* I think it's odd to have the developers.google.com icon/link next to the search. If the search is for the whole of developers.google.com, it should say so ('Search Google developer resources' or whatever). Otherwise the icon/link should go to the right of the G+ link.

* The SVG icons should have title elements.

* On pages like [this](http://localhost:7331/web/fundamentals/guides/push-notifications/index.html) where there's no date of author image, I think the banner has too much empty space: 

![image](https://cloud.githubusercontent.com/assets/205226/10189708/ea322ce0-675f-11e5-84a7-14983ce8d9aa.png)

**Comment by gauntface** [comment]
This is based on the old redesign.
