### ISSUE TITLE
Codelabs have empty contents section

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#1944]
On codelab pages like [this](http://localhost:7331/web/fundamentals/guides/your-first-offline-web-app/step-2), the contents section is empty (because there are no H2 elements) and shouldn't be displayed:

![image](https://cloud.githubusercontent.com/assets/205226/10190369/f8e5f02e-6763-11e5-898b-bd08637711d5.png)

Also, the font size of H2 elements is too large and content tends to run on (just) to the following line::

![image](https://cloud.githubusercontent.com/assets/205226/10191912/4de209a8-6770-11e5-8d77-e9f25187b6ae.png)

(View image full size.)

**Comment by petele** [comment]
fixed in #1953
