### ISSUE TITLE
Related Guides font is too small

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#1948]
https://material-dot-web-central.appspot.com/web/showcase/spotlight/hummingbirdlibrary

<img width="742" alt="screen shot 2015-09-30 at 3 19 47 pm" src="https://cloud.githubusercontent.com/assets/45510/10195709/dbfb1868-6786-11e5-8fff-666af2e9c1f1.png">

**Comment by petele** [comment]
Yep - and also lost the line breaks.
