### ISSUE TITLE
[EN] Feedback for: /tools/iterate/inspect-styles/shortcuts.html

### ISSUE THREAD

**Issue by ali-bugdayci** [google/WebFundamentals#1952]
Hi,

I love chrome dev tools. Most of the time I wrote code on the "Sources" section.

I used lots of different editors including: WebStorm, IntelliJ, Atom, Sublime Text, Eclipse etc.

I believe moving inside the sources tab is critical. I think the following shortcuts are necessary:

Ctrl + Page UP => Previous file
Ctrl + Page Down => Next file
Ctrl + 1..9 => 1st file... last File
Ctl + Alt + UP Arrow -> Previous Function
Ctl + Alt + UP Down -> Next Function

Refactoring:
Ctrl+Shift+ R = Rename
...

**Comment by pbakaus** [comment]
Thanks for your suggestion. Please file a bug at http://crbug.com/new for anything DevTools-related. This bug tracker is just for the documentation of DevTools.
