### ISSUE TITLE
gulp default task failing because of missing dependency for nokogiri gem.

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#1961]
Judging by Pete's surprise, I'm guessing that nokogiri may not actually be a dependency for WebFu. It's possible the solution for us is to remove said gem as a dependency.

In the meantime, I've posted my solution to the dependency problem here: <http://stackoverflow.com/questions/32874785/install-of-nokogiri-fails-though-libxml2-confirmed-installed>

**Comment by petele** [comment]
@jpmedley - did you get it to work? If so, what's the bug here?

**Comment by gauntface** [comment]
These may be stupid questions, so please bare with me:

1.) What OS are you using? OS X Yosemite presumably?
2.) Did you follow the steps on: https://github.com/google/WebFundamentals/tree/material-branch
3.) Was the problem only apparent when you ran gulp - i.e. there were no errors on from following instructions?
4.) What makes you think it isn't a dependency? Our dependencies are listed here: https://github.com/google/WebFundamentals/blob/material-branch/Gemfile
