### ISSUE TITLE
Add recommendations for icon size on Web Push

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1966]
We have a few docs incoming for push so not sure exactly what docs need this.

AT the moment little to no guidance on icon size is given. Peter Beverloo has suggested that an icon size of 192x192 pixels for the current state of devices would be good for notifications (this is basically from the Android notification size of 64dp - 64 x 3 (3x density screen) = 192px).

cc @petele @jpmedley

**Comment by petele** [comment]
Do you mean specifically for push or icons in general? 

We have stuff about icons [Icons and colors for the browser](https://material-dot-web-central.appspot.com/web/fundamentals/design-and-ui/browser-customization/great-icons) and in the [manifest](https://material-dot-web-central.appspot.com/web/fundamentals/engage-and-retain/simplified-app-installs/web-app-install-banners) stuff.
