### ISSUE TITLE
Icons not consistent across browsers and devices

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/WebFundamentals#1975]
The web fundamentals icon takes on different appearances depending on where it's viewed (add to homescreen, bookmark, iOS, desktop, etc.).

Android:

![adb-screenshot-20151001142107](https://cloud.githubusercontent.com/assets/51244/10223428/d743a54a-6850-11e5-8336-a0365dd9377d.png)
![adb-screenshot-20151001142140](https://cloud.githubusercontent.com/assets/51244/10223430/da5d7a26-6850-11e5-9ff5-54fdd47bb26f.png)
![adb-screenshot-20151001143247](https://cloud.githubusercontent.com/assets/51244/10223593/b9f183f8-6851-11e5-864e-16b6d670c4d9.png)

Chrome desktop:

![screen shot 2015-10-01 at 3 27 14 pm](https://cloud.githubusercontent.com/assets/51244/10223451/efa98d2a-6850-11e5-8182-f7e5b29fc94c.png)

iOS:

![img_3593 1](https://cloud.githubusercontent.com/assets/51244/10223529/4be9e72e-6851-11e5-822f-f08c1a09e542.PNG)
![img_3595](https://cloud.githubusercontent.com/assets/51244/10223536/57586a36-6851-11e5-82ab-1f749f22e13c.jpeg)

**Comment by petele** [comment]
Lovely - good call. we'll have to take a deeper look at this.

**Comment by petele** [comment]
I think this is fixed in MD, but will need to properly verify
