### ISSUE TITLE
Intro paragraph in /web/fundamentals/primers/push/on-the-server doesn't make sense

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1992]
Current: The service worker running on the server is responsible for taking the data provided in the push message and actually forwarding it to the user as a notification.

There is no service worker running on the server. Should this read:
A service running on the server is responsible for taking the data provided in the push message and actually forwarding it to the user as a notification.

**Comment by dgash** [comment]
Intro corrected 2 Oct. 2015
