### ISSUE TITLE
[EN] Feedback for: /tools/javascript/breakpoints/step-code.html

### ISSUE THREAD

**Issue by WolfieWerewolf** [google/WebFundamentals#2019]
Guys, great documentation, I just noticed a few items that didn't flow for me.  

https://developers.google.com/web/tools/javascript/breakpoints/step-code?hl=en#stepping-in-action
The code in the two screenshots below is functionally equivalent.  _Is_ "code" not plural?   It's correct everywhere else, just not initially.

-- is 
++ are.

This next item isn't incorrect it's just that, to me, the conjunction "and" is a little ambiguous.  

https://developers.google.com/web/tools/setup/workspace/setup-devtools
The Sources panel lets you debug your JavaScript code using breakpoints. As the complexity of JavaScript applications increase, developers need powerful debugging tools to help quickly discover the cause of an issue and fix it efficiently.

-- to help quickly discover the cause of an issue and fix it efficiently.
++ to help quickly discover the cause and efficient resolution of an issue. ||
++ to help quickly discover the cause and efficient fix for an issue.

Again, this is not incorrect, just a suggestion:
https://developers.google.com/web/tools/javascript/breakpoints/step-code?hl=en#stepping-in-action

Observing and pausing the executing code helps you locate errors, and live editing allows you to quickly preview changes without the need for reloading.

-- without the need for reloading.
++ without the need to reload.

Just my 2p, I think both the DevTools and the documentation are incredible!

All the best.  /W

**Comment by petele** [comment]
@Meggin - can you review and assign to a writer

**Comment by petele** [comment]
@kaycebasques - has this been addressed? If so, can you please close.

**Comment by kaycebasques** [comment]
Thanks @WolfieWerewolf... the setup-devtools doc is no more, but I made your suggestions in step-code in the referenced branch
