### ISSUE TITLE
Material design: scrolling page, header bar jumps instead of transitions 

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#2021]
Scrolling the page, the header quickly jumps to its smaller fixed position. It doesn't feel right and isn't the MD spec. Instead, the bar should ease/transition to it's final state.

Something like:
https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/index.html

**Comment by petele** [comment]
We're trying to use the Material Design Lite library, which doesn't have support for this right now.

**Comment by ebidel** [comment]
That is a bummer. Looks janky. cc @addyosmani

**Comment by gauntface** [comment]
We've dropped the waterfall header based on feedback and raised a bug on MDL.

https://github.com/google/material-design-lite/issues/1658

**Comment by addyosmani** [comment]
We'll be refactoring the layout components and ensuring high-performance as a baseline for a future release. Sorry about the jank in the current version!
