### ISSUE TITLE
Material: Sidenav feels a bit lifeless

### ISSUE THREAD

**Issue by paulirish** [google/WebFundamentals#2028]
Material spec's strongsuit is touch. On desktop, the lack of hover feedback feels drab.

Would love some sort of feedback as I hover. In addition to it matching the general desktop web experience, it helps the user easily differentiate nav items when there is text wrapping: 

<img src="https://cloud.githubusercontent.com/assets/39191/10289922/f0dbd24a-6b55-11e5-8109-b3ad638ac78b.png" width=150>

**Comment by petele** [comment]
Moving to v2

**Comment by gauntface** [comment]
Added some underlining to the links.

I reckon to add colors would require reworking the current styles for the menu to pad the anchors rather than the list items.

Reopen if you would prefer the latter option.
