### ISSUE TITLE
Add dgash to Contributors in material-branch

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#2029]
Dave Gash is the author of the push notifications primer and the new performance codelab docs.

Can we add him to the list of contributors so I can add him as an owner?

Thanks.

**Comment by petele** [comment]
He's already in the _contributors.yaml file. I see him on line 196. Are you not seeing him?

**Comment by petele** [comment]
I see him in there, so closing. If you don't see him, be sure to sync your branch with the main material-branch
