### ISSUE TITLE
Shorten lag time in staging server

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#2032]
Hey, guys

How long is there between when a commit happens and the staging server gets updated?

It would be great to get this time down as quickly as possible.

Pete delivered some changes to the performance codelab just after I fetched, about 4 hours ago,
and I still don't seem them live.

Meggin

**Comment by petele** [comment]
Unfortunately this is a function of [Travis](https://travis-ci.org/google/WebFundamentals/builds), so there isn't much we can do about it when they're system is backed up without major changes to our deployment system. :(

cc - @gauntface

**Comment by gauntface** [comment]
There isn't anything we can do for the automated deployment to staging.

What we might be able to do is add in the ability to push a local version to the staging the server.

Down sides are:
- You'll be pushing changes that are local (not necessarily committed)
- The local branch might not actually work & break staging (kind of covered by this on travis)
- People could override other peoples work.

That said, I can't imagine it would be too often for these to occur and worse case scenario, Travis will eventually overwrite with a working version.

Other alternative, we have a third site labelled "playground" or something that anyone can push to, the major down side of this is it's another thing to look after and will suffer down sides of above.

Thoughts?

**Comment by PaulKinlan** [comment]
A couple of other options:

* just test locally
* deploy to your own app engine site and have a simple script that does it.
* create a new CI system - think @crhym3 is playing in that area now although not sure.

**Comment by crhym3** [comment]
Yeah, for instance, we left MDL CI as is, the one I set up initially before they went public: ci.cloudware.io/github.com/google/material-design-lite, mainly because it's much faster.

I can do the same for WF if you guys want.

**Comment by gauntface** [comment]
@crhym3 yes please.
