### ISSUE TITLE
Question about pull request process

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#2034]
Hey,

I've been working in a Fork to create pull requests, figuring we are not meant to create branches.

But it's super ick keeping a local branch of fork up to date with branch off main.

Is it OK to just have a local branch off master, and I push to it, and create PR from that? The reviewer of the PR then just has to click the button to delete the extra branch.

Such an easier project. What do you think? Or maybe this is OK anyway?

**Comment by jpmedley** [comment]
That's what I've done for every PR in the last week. No one has complained.

Joe Medley | Technical Writer, DevPlat | jmedley@google.com | 816-678-7195

**Comment by petele** [comment]
Personally I prefer working in a fork and have a little bash script `gitup.sh` (below) that updates my fork with the latest. As long as you clean up your branches, I don't really care either way.

```
git fetch upstream
git merge upstream/material-branch
git push
```

**Comment by petele** [comment]
@gauntface - thoughts?

**Comment by gauntface** [comment]
No real preference to be honest. Happy for people to create branches and if it becomes a problem we can address it then, in mean time go with what is easiest for you.

**Comment by PaulKinlan** [comment]
Side note, branches off this repo makes it easier for TW to review and edit PR's in place.
