### ISSUE TITLE
Updates: Red color profile is very harsh to the eyes

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#2041]
The red-orangy color profile in the Updates section is makes me and many others cringe. Its tolerable on a calibrated Mac display, but looks terrible on a connected screen.

Suggestion: Don't use red or orange, those should be used sparingly. Use a decent Material color.

**Comment by petele** [comment]
Those are material colors - picked based on the HTML5Rocks orange. Other suggestions?

**Comment by pbakaus** [comment]
Red or Orange usually only works as accent colors IMHO, which is why they work for the small strip on HTML5Rocks. I experimented a little, Amber might be a good alternative. Not completely happy with it either but it's much softer on the eye (again, using official Material colors):

![image](https://cloud.githubusercontent.com/assets/43004/10324917/58b52ea6-6c42-11e5-993b-b24de13f8af4.png)

**Comment by pbakaus** [comment]
Probably can be one shade darker.

**Comment by petele** [comment]
The orange we're using is a material design color. Will investigate further.

**Comment by petele** [comment]
Used amber for v1. Happy to re-review colors for v2, please file a new issue along with suggested colors.

**Comment by pbakaus** [comment]
Cool thanks much!
