### ISSUE TITLE
[EN] Feedback for: /fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer.html

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2056]
The title needs to be re-done, it is way too long and doesn't fit in well.

https://material-dot-web-central.appspot.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer

**Comment by petele** [comment]
Fixed in #2057
