### ISSUE TITLE
Move MP3s/PodCast files to Google Cloud Storage

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#2058]
Right now the MP3 files are sitting in the Git repo, we should move them to a separate storage location that has better deployment support and has the CORS headers.

cc - @paullewis

**Comment by PaulKinlan** [comment]
Hmm. I am loath to have things in another place. If we do this we need to
maintain control over them and have them version controlled in once place
too.

**Comment by petele** [comment]
Understood, and I agree about the control part. My biggest concern right now is that by putting all of these MP3 files into the repo, we're going to blow the repo up. It's already pretty huge, the first pull is PAINFUL.  We also have no control over the headers and can't add CORS headers to the files right now, which makes Paul's podcast player a sad panda.

**Comment by gauntface** [comment]
@paullewis are you happy to take this on?

**Comment by paullewis** [comment]
Can you assign to @jakearchibald instead? He said he's happy to do this.

**Comment by jakearchibald** [comment]
https://github.com/google/WebFundamentals/pull/2197
