### ISSUE TITLE
Web Push Article Feedback

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#2062]
The documentation site for Google Cloud Messaging has a different naming to the Web Push API - should be called out before link out to it.

The GCM docs have been updated so the link no longer goes to something meaningful.

It's easy to overlook the step of enabled GCM for Android rather than GCM for Chrome.

**Comment by petele** [comment]
@dgash - I believe this is in the stuff you wrote. Would you review and make the necessary updates.

cc @jpmedley - fyi as some of the content may be yours.

**Comment by petele** [comment]
@dgash / @jpmedley - can you two figure out who needs to take this? Please assign it to yourself and then update as soon as it's fixed.  Thanks!

**Comment by gauntface** [comment]
I've updated after this and requests for numerous changes.

The doc is insanely outdated by this point. Should be good now. TW review of the new doc would obviously be much appreciated
