### ISSUE TITLE
[EN] Feedback for: /tools/chrome-devtools/index.html

### ISSUE THREAD

**Issue by narcolepticinsomniac** [google/WebFundamentals#2098]
Latest Chrome stable (46) devtools have a bug. Right click/inspect element, at the very bottom click any element to the left and devtools glitch. Sometimes it fixes itself, sometimes it gets stuck.

**Comment by petele** [comment]
Please file Chrome issues on the Chrome bug database at https://code.google.com/p/chromium/issues/list
