### ISSUE TITLE
[EN] No image for a person, slightly broken rendering

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2099]
When a person doesn't have a photo there is a dead image

<img width="785" alt="screen shot 2015-10-14 at 5 27 46 pm" src="https://cloud.githubusercontent.com/assets/45510/10490433/eadbd03a-7298-11e5-8e89-27bc985d2e94.png">
/web/fundamentals/security/encrypt-in-transit/enable-https-on-your-servers

**Comment by petele** [comment]
This is a side effect of #2100 - the image path is hard coded to https://developers.google.com/.

It will resolve itself on prod, but we need to fix #2100 as well.
