### ISSUE TITLE
Need a seperate canonical url with and without the domain

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#2100]
We need canonical links with the domain for use in the header, but need it without the domain for use in the docs.

This breaks pages when the are on DevSite staging because it redirects users from DevSite Staging to DevSite production.

**Comment by petele** [comment]
Also note - canonical url with domain should be https

**Comment by gauntface** [comment]
canonical url using https is easy enough.

The links is a seperate issue - use relative_url insteand of canonical_url in pages, layouts, includes etc and this should be fixed.
