### ISSUE TITLE
Sample Builder doesn't insert template header & footers

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#2102]
In the old system, you could put `<!-- // [TEMPLATE header_full] -->` into a _code sample file, and it would automatically inject the corresponding file from `src/jekyll/_includes/codesamples/sample_xxx`

**Comment by gauntface** [comment]
The original class for this always overrode the write method of Jekyll Static File class, I was using the wrong class for HTML files.

Should be fixed now.
