### ISSUE TITLE
Update date of latest DevTools Digest

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#2103]
https://devsite.googleplex.com/web/updates/2015/10/devtools-digest-reordering-tabs says "Oct 5th", but with the new launch schedule, it's Oct 15th. I'll prepare a PR.

**Comment by petele** [comment]
we'll take asap, may be today, may be tomorrow

**Comment by petele** [comment]
did you submit a PR for this already? I don't see anything noted in this issue about it?

**Comment by pbakaus** [comment]
you merged it already, all good :)
