### ISSUE TITLE
Comment section not showing up for updates

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#2106]
https://developers.google.com/web/updates/2015/10/splashscreen

No comment block at the bottom of the page

**Comment by gauntface** [comment]
This is weird.

It works locally and on appengine instance.

The div with ID's are there and the JS looks like it should work on live site.

**Comment by petele** [comment]
I bet it's the failing JS... I'll get it fixed in an update today.

**Comment by petele** [comment]
Fixed with the update to the template.
