### ISSUE TITLE
Banner needs a little more margin below it

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2117]
Just a nitpick...

On pages like [this](https://developers.google.com/web/fundamentals/primers/promises/) there needs to be a little more vertical margin between the banner and the first line of text. (There should be at least as much margin between the banner and the first line of text, as between each paragraph.) 

Adding 1.3em bottom margin to the header worked for me — or your could add class="intro" the first paragraph to add top margin to that.

![image](https://cloud.githubusercontent.com/assets/205226/10509187/533efe56-7323-11e5-93bc-1d9c3bb6e148.png)

**Comment by gauntface** [comment]
Not a simple fix - needs consideration across the entire site - i.e. there are a tonne of sites with different subheadings and now banners, not sure what all of them should look like.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
