### ISSUE TITLE
developers.google.com/web/updates results in 404

### ISSUE THREAD

**Issue by kdzwinel** [google/WebFundamentals#2119]
https://developers.google.com/web/updates (without a trailing slash) results in 404. Haven't seen anything linking to that page though. I discovered it because I typed the URL myself into the mobile browser.

**Comment by PaulKinlan** [comment]
I suspect we might need to put a redirect in for that cc @petele @gauntface

**Comment by gauntface** [comment]
It works for /web/fundamentals

Is this something specific to the prod build?

**Comment by petele** [comment]
I've updated the _redirects file to redirect naked urls to their appropriate directories. This should roll out in the next couple of hours.
