### ISSUE TITLE
Article title hidden under the menu during page load

### ISSUE THREAD

**Issue by kdzwinel** [google/WebFundamentals#2120]
That's how every page looks when it's loading:
<img width="444" alt="screen shot 2015-10-15 at 12 36 21" src="https://cloud.githubusercontent.com/assets/985504/10511700/6a1a2a20-733b-11e5-8c71-0d8785549d39.png">

Title moves right as soon as page loads.

**Comment by gauntface** [comment]
This is super sucky and I believe it's an issue with MDL's layout.

Will leave this open to see if I can diagnose and raise a helpful bug on MDL.

**Comment by petele** [comment]
This is a MDL 1.0.4 issue, it went away when were running 1.0.5 in development.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
