### ISSUE TITLE
Mobile: menu doesn't work while page is loading

### ISSUE THREAD

**Issue by kdzwinel** [google/WebFundamentals#2121]
Menu doesn't show up on hamburger icon click while page is loading. Especially noticeable on resource heavy pages like https://developers.google.com/web/updates/devtools/ (~9MB)

**Comment by gauntface** [comment]
Ta for raising the bug.

You can super easily replicate this by switching to 2G on the network panel.

**Comment by petele** [comment]
A 10meg page? <cries>

**Comment by kdzwinel** [comment]
Umar's gifs are loaded as article covers.

**Comment by gauntface** [comment]
This could easily be solved by not using gifs in this page and using plain old images.

On good 3G connection ti was just under 50s to get the page loaded such that the nav drawer could be opened.
