### ISSUE TITLE
Devtools link in Hot off the press don't work

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2125]
https://developers.google.com/web/tools/chrome-devtools/ - they go to the update/DevTools/ page.

<img width="899" alt="screen shot 2015-10-15 at 1 57 39 pm" src="https://cloud.githubusercontent.com/assets/45510/10514275/c9d80f64-7344-11e5-9abf-97d05a39797c.png">

**Comment by gauntface** [comment]
This is a larger issue of finding a way to share tagged pages across all of the site. I have an idea of how to approach this that should be sane, but will need some time to get around to it.

**Comment by PaulKinlan** [comment]
coolio.  This just fixed the fact that the links had /DevTools/ in and we got rid of that in the end.

**Comment by PaulKinlan** [comment]
This should be fixed now.
