### ISSUE TITLE
Broken images at https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web

### ISSUE THREAD

**Issue by asos-giovannip** [google/WebFundamentals#2128]
All the images are broken in the article guys.

**Comment by asos-giovannip** [comment]
Eg. https://developers.google.com/updates/images/2015-03-04-push-on-the-open-web/enabled-disabled-push-ux-chrome.png

Should be:
https://developers.google.com/web/updates/images/2015-03-04-push-on-the-open-web/enabled-disabled-push-ux-chrome.png

You miss /web/ in the path.

**Comment by PaulKinlan** [comment]
Looking at it now.

**Comment by PaulKinlan** [comment]
@gauntface it looks like {{site.baseurl}} is not set and it is used quite heavily on the site.

**Comment by PaulKinlan** [comment]
@gauntface just fixing now WFBaseUrl

**Comment by gauntface** [comment]
This PR has been merged (ta PK) so should be fixed in the next build - sorry it got through and thank you for the bug report :)

**Comment by asos-giovannip** [comment]
Thanks to you guys @PaulKinlan @gauntface
