### ISSUE TITLE
Set material-branch as default branch

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#2133]
https://help.github.com/articles/setting-the-default-branch/

1. Click **Settings** icon for repository.
2. Click **Branches**.
3. In **Default Branches** sidebar select `material-branch`.

Close this ticket if you are planning on eventually merging `material-branch` into `master`.

**Comment by petele** [comment]
@gauntface  and I need to figure out the next steps on this, not sure if we want to migrate to master or where next.

**Comment by gauntface** [comment]
I thought the end goal was to migrate to master.

General plan:
1.) Tag a master release
2.) Delete master code and replace with material-branch
3.) Delete material-branch

I'm pretty sure this will lose history if commits somewhere, but would be the most basic path forwards.

**Comment by PaulKinlan** [comment]
$ git checkout master
$ git tag old-master
$ git reset --hard material-branch
$ git merge -s ours origin/master
$ git push origin master

**Comment by gauntface** [comment]
Thanks Kinlan - @petele, post this staging working, happy for me to give this a shot?

**Comment by petele** [comment]
Yep - absolutely.

**Comment by gauntface** [comment]
Just done this.
