### ISSUE TITLE
Tables not rendering properly on production site

### ISSUE THREAD

**Issue by greenido** [google/WebFundamentals#2134]
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill?hl=en

**Comment by gauntface** [comment]
@greenido 

Looking at the old HTML:

<table>
<tr>
<td markdown="block">
**name attribute**
</td>
<td markdown="block">
**autocomplete attribute**
</td>
</tr>
<tr>
<td markdown="block">
ccname<br>
cardnumber  
cvc  
ccmonth  
ccyear  
exp-date  
card-type
</td>
<td markdown="block">
cc-name  
cc-number  
cc-csc  
cc-exp-month  
cc-exp-year  
cc-exp  
cc-type
</td>
</tr>
</table>

And then comparing to what we have now:

<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th>
        name attribute
      </th>
      <th>
        autocomplete attribute
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        ccname<br>
        cardnumber  
        cvc  
        ccmonth  
        ccyear  
        exp-date  
        card-type
      </td>
      <td>
        cc-name<br>
        cc-number  
        cc-csc  
        cc-exp-month  
        cc-exp-year  
        cc-exp  
        cc-type
      </td>
    </tr>
  </tbody>
</table>

It looks like the table is rendering in a semi-reasonable state.

What exactly was the intended look for this?

Did you actually intend to write the following:

<table class="mdl-data-table mdl-js-data-table">
  <thead>
    <tr>
      <th>
        name attribute
      </th>
      <th>
        autocomplete attribute
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        ccname
      </td>
      <td>
        cc-name
      </td>
    </tr>
    <tr>
      <td>
        cardnumber
      </td>
      <td>
        cc-number 
      </td>
    </tr>
    <tr>
      <td>
        cvc
      </td>
      <td>
        cc-csc  
      </td>
    </tr>
    ....

**Comment by petele** [comment]
There's either an issue in 1.0.4 of MDL or in the Google3 build of MDL, the table module isn't included.

Compare [live](https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill?hl=en) vs [staging](https://material-dot-web-central.appspot.com/web/updates/2015/06/checkout-faster-with-autofill?hl=en)

<img width="787" alt="screen shot 2015-10-16 at 9 37 30 am" src="https://cloud.githubusercontent.com/assets/718038/10547498/bef4013e-73e9-11e5-8c84-fb2801fb6433.png">

**Comment by petele** [comment]
After investigating further, it looks like the second set of tables do not include <thead>'s which is why they're rendering incorrectly. 

@greenido - assigning to you to fix.

**Comment by kaycebasques** [comment]
@petele @gauntface what's the canonical markup for tables? I'm seeing render problems on tables too. On page load, the table is laid out correctly, but dividing lines are not displayed. Video: https://vid.me/wRvb

**Comment by petele** [comment]
Canonical markup is the MDL stuff - http://getmdl.io/components/index.html#tables-section.
