### ISSUE TITLE
The 'View Source' link is broken

### ISSUE THREAD

**Issue by greenido** [google/WebFundamentals#2135]
How to reproduce:
1. Open: https://github.com/Google/WebFundamentals/tree/master/src/content/en/updates/posts/2015/06/checkout-faster-with-autofill.markdown
2. Click on 'View srouce' on the bottom-left corner.

You are getting a github 404 page.

**Comment by petele** [comment]
Works fine for me:
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill - redirects me to the right page.

If it's still an issue, please reopen with the correct URL
