### ISSUE TITLE
Example jekyll code is rejected by DevSite

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#2139]
The following files contain jekyll template examples that makes DevSite cranky.

/en/resources/jekyll/custom-jekyll-variables.html
/en/resources/jekyll/custom-tags.html
/en/resources/jekyll/useful-and-common-tags.html
/en/resources/styleguide/index.html

**Comment by gauntface** [comment]
Cranky in what way?

**Comment by petele** [comment]
When trying to stage `custom-jekyll-variables.html` it dies with the following error:

`Template syntax error: Invalid block tag: 'raw'`

**Comment by petele** [comment]
In the previous system, we manually escaped things, for example:

`{{ "&#123;% include_code _code/test.html testhtml html %&#125;" }}`

**Comment by gauntface** [comment]
Okies, shame it doesn't work but it'll rarely be used.

**Comment by gauntface** [comment]
Should be fixed now. Please reopen if on next push you still have this issue.
