### ISSUE TITLE
"What is mixed content?" article doesn't have a definition of mixed content anymore

### ISSUE THREAD

**Issue by johyphenel** [google/WebFundamentals#2140]
Per conversation with @petele offline.

I noticed the initial paragraph from "what is mixed content?" got moved to a new really small page "prevent mixed content". This leaves my "what is mixed content?" article without a definition of what mixed content is.

https://developers.google.com/web/fundamentals/security/prevent-mixed-content/
vs
https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.

https://petele-scratch.appspot.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content

**Comment by johyphenel** [comment]
Awesome! Thanks! :)
