### ISSUE TITLE
Refactor Top of Pages in Case Studies to Allow for Use of TOC

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#2162]
In the current version of the [Case Studies](https://developers.google.com/web/showcase/case-study/?hl=en) section the header material on each case study is rather large. Not only does this make it unlikely that case study content will appear above the fold, it also leaves little room for a page toc.

These pages badly need toc's.

The request is to refactor or redesign the tops of these pages to make room for more visible content and for toc's.

**Comment by jpmedley** [comment]
The [Spotlight](https://developers.google.com/web/showcase/spotlight) section shares the same problem.

**Comment by gauntface** [comment]
@jpmedley what do you see being the contents of the TOC?

I assumed the cards were essentially the table of contents.

**Comment by jpmedley** [comment]
@gauntface 

One level down for there. For example: https://developers.google.com/web/showcase/case-study/service-workers-iowa?hl=en

This probably needs to be done with many other pages on the site. I'll take on an AI to make a list.

**Comment by gauntface** [comment]
You can add:

    {% include shared/toc.liquid %}

to the documents in case study and it'll work because the content is written in normal markdown.

The thing it to figure out where in the doc you'd like it.

For case studied that requires a rework of the way things are current written.
