### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/?hl=en

### ISSUE THREAD

**Issue by JuliaPoberezhnaya** [google/WebFundamentals#2166]
Hi, 
i've seen, you have changed the Google Developers Interface. It seems good, but i would like to see the different languages (not only English) of the articles. Ist it  / will it be possible?
Thanks,
Julia

**Comment by PaulKinlan** [comment]
Bottom right of the screen is a globe, they are there. We need to make this
clearer, sorry for confusion.

**Comment by petele** [comment]
Yep - we've tried to match the rest of Google Developers and have put the language picker in the bottom right corner.
