### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/engage-and-retain/push-notifications/notifications?hl=en

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#2171]
Getting quite a bit of feedback that is' pretty hard to set up a google developer project via the console for push notifications on the web.

At the moment we recommend the Android or iOS guides which I don't think are particularly helpful.

I think adding a section of setting the console up would be our best bet until the web push protocol is the best approach.

**Comment by PaulKinlan** [comment]
Big +1
