### ISSUE TITLE
Remove the word "sexy" from: /web/updates/2015/10/devtools-digest-reordering-tabs?hl=en

### ISSUE THREAD

**Issue by Jenn** [google/WebFundamentals#2172]
There's really nothing "sexy" about underlines. A lot of us are trying to stop the spread of using "sexy" to describe interfaces. A good practice is to replace it with a synonym and see if you would still use it. "hot underlines" "provocative underlines" "sensuous underlines" "seductive underlines", etc. It's a word that can make people feel uncomfortable. Perhaps what we are really looking for when we use "sexy" in this way is something more like "nifty underlines" or "slick underlines"

![image](https://cloud.githubusercontent.com/assets/69822/10581014/830cc5a4-764e-11e5-9c9d-d365a52a7e32.png)

**Comment by PaulKinlan** [comment]
@Jenn - apologies, will sort this asap. @pbakaus can you fix.

**Comment by pbakaus** [comment]
Thanks for flagging this @Jenn, my apologies (as the who wrote it).

PR to address it is ready to go: https://github.com/google/WebFundamentals/pull/2175

**Comment by Jenn** [comment]
@pbakaus @PaulKinlan Thanks for addressing it. I'm constantly correcting myself with some other language choices and trying to break old habits. We're all in this together :)

**Comment by Meggin** [comment]
I know it's not good practice to +1 in issues, but seems kind of relevant
here. So yeah, +1.

**Comment by PaulKinlan** [comment]
This should be deployed in the next push so I will close for now.  Sorry for any issues caused and thanks for raising it.
