### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by fuckyourgaypopupbox** [google/WebFundamentals#2176]
This STUPID BOX keeps popping up every time I type something and it is driving me nuts, I want to disable it PERMANENTLY. If you can show me how to do that I would greatly appreciate it.

**Comment by petele** [comment]
Hi,

I'm not sure what pop up box you're referring, and without more details, I am going to close this. Please consider changing your username before posting about this or other errors again, as it's use of inappropriate language and slurs is unnecessary.
