### ISSUE TITLE
RSS/Atom URL is being reported incorrectly

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2177]
This might be the old issue we had and peoples feeds haven't updated but I am seeing traffic on rsshttps: and atomhttps: - it might just be the way we report but it would be good to investigate

<img width="909" alt="screen shot 2015-10-20 at 9 03 33 am" src="https://cloud.githubusercontent.com/assets/45510/10601484/05e79aba-770a-11e5-8d9b-9bdb191a0db5.png">

**Comment by petele** [comment]
Thankfully just a small analytics issue, will get fixed today.

**Comment by petele** [comment]
Fixed in #2183
