### ISSUE TITLE
RSS Feed for updates is invalid

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2190]
https://developers.google.com/web/updates/rss.xml

No title, no link etc

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdevelopers.google.com%2Fweb%2Fupdates%2Frss.xml

**Comment by gauntface** [comment]
Should be fixed in the next version - need a way to monitor this stuff with ease.

It's frustrating having no automated way of testing the entire site.

**Comment by gauntface** [comment]
Any this bug should be fixed in master now.
