### ISSUE TITLE
Better URL naming?

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#2192]
This seems to be an ongoing pain point at the moment.

Originally we had a set of custom filters than would add on the ?hl=<langcode> to the end of a url if the person creating the content remembered to include it and we had a good number of places adding the '/web/' to the start of urls (both hardcoded and using the config variable).

To make this consistent I added a set of custom variables dedicated to URLs in WFPage.rb (See https://github.com/google/WebFundamentals/blob/material-branch/src/jekyll/_plugins/pages/WFPage.rb#L378) and removed the custom liquid filters.

Jake just raised an issue where the content had code along the lines of: 

    <figure>
      <img src="{{page.relative_url}}imgs/promise3.gif">
    </figure>

This equates to:

    <figure>
      <img src="/web/fundamentals/primers/promises?hl=enimgs/promise3.gif">
    </figure>

The fix is to simply reference the images relatively like so:

    <figure>
      <img src="imgs/promise3.gif">
    </figure>

Are we happy with this being the case? I'm scared at the amount of confusion / the number of problems this seems to be creating.

**Comment by petele** [comment]
Yep - works for me.

**Comment by petele** [comment]
@gauntface - Can you update the bug title, tags, etc, along with the work so we can track what's on tap please?

**Comment by gauntface** [comment]
@petele There is no work here if we are happy with the relative url of src="img/...." I just want to make sure we are

**Comment by petele** [comment]
OK - yes, absolutely happy with that, seems the easiest way to go.
