### ISSUE TITLE
Site needs some urgent design attention -_-

### ISSUE THREAD

**Issue by TEHEK** [google/WebFundamentals#2204]
This website
https://developers.google.com/web/showcase/?hl=en

(l initially landed on this page:
https://developers.google.com/web/updates/2015/04/cut-and-copy-commands?hl=en)

1) Too much contrast everywhere. Contrast used to navigate user's attention. And in this case it just smears the attention across the entire page

2) Colors are poisonous. This is my grudge with material thing in general, but some pages look ok (https://developers.google.com/web/), some pages do not (https://developers.google.com/web/updates/?hl=en)

3) Stuff is not aligned... This makes my eye twitch:
https://developers.google.com/web/showcase/?hl=en

4) Images are downscaled by browser making text look horrible: https://screenshot.googleplex.com/qd4ZEbH0baw.png
vs
https://screenshot.googleplex.com/PQfBLCwiLzO.png

5) Wrong font used here (names are in Helvetica, should be Roboto): https://developers.google.com/web/updates/?hl=en

6) Broken vertical rhythm pretty much everywhere... Also, look at the footer -_-

Not the google quality.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
