### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/10/display-mode?hl=en

### ISSUE THREAD

**Issue by jeffposnick** [google/WebFundamentals#2208]
CC: @petele @PaulKinlan 

There are a few bad links in https://developers.google.com/web/updates/2015/10/display-mode:

- [Service Worker](https://developers.google.com/web/fundamentals/primers/service-workers/) points to an incomplete page by @jpmedley. There are a couple of intro paragraphs, but the rest of the content isn't present.
- [Web App Manifest](https://developers.google.com/web/updates/2015/10/web/fundamentals/engage-and-retain/simplified-app-installs) returns a HTTP 404.

**Comment by PaulKinlan** [comment]
I'll update this one.  I need to sort out Kenneths name.
