### ISSUE TITLE
Font doesn't support unicode example characters

### ISSUE THREAD

**Issue by mrwweb** [google/WebFundamentals#2223]
(Originally tweeted: https://twitter.com/MRWweb/status/657294240234369024)

On https://developers.google.com/web/fundamentals/design-and-ui/media/images/use-icons?hl=en, there is the followiing:

> Beyond the normal character set, unicode may include symbols for number forms (⅐), arrows (←), math operators (√), geometric shapes (★), control pictures (▶), braille patterns (⠏), music notation (♬), Greek letters (Ω), even chess pieces (♞).

At least on Chrome on Windows 8.1, number forms and braille patterns show up as the dreaded box character. (My guess is that this is because Helvetica is the top of the font-stack). This page should either ensure the font used supports all the characters across all platforms, or use unicode characters with better support across the entire font stack.

**Comment by petele** [comment]
Fixed
