### ISSUE TITLE
Some case studies won't have Speed Index scores : BTR 

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2224]
For some of the case studies it doesn't make sense to have the speed index and pagespeed insights score.

If the YAML data doesn't exist then we shouldn't show it.

**Comment by gauntface** [comment]
This is a minor fix in the template - Assigning to @PaulKinlan .

**Comment by gauntface** [comment]
Why does it not make sense to have a pagespeed insights score for a site?

**Comment by PaulKinlan** [comment]
Because in some cases they aren't good and it detracts from the case study
in some cases it doesn't make sense to have them for example BTR

As a side note I am keen to refactor case studies.
