### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/10/splashscreen?hl=en

### ISSUE THREAD

**Issue by LCallaghan84** [google/WebFundamentals#2225]
background color and icon size is not working correctly

**Comment by PaulKinlan** [comment]
In what way?

**Comment by LCallaghan84** [comment]
well i set the background color to 212121, and its showing the smallest icon size for the splash screen
but its showing the white background color instead

**Comment by LCallaghan84** [comment]
nevermind, i fixed the issue myself.
