### ISSUE TITLE
Remove useless dev menu

### ISSUE THREAD

**Issue by littleguga** [google/WebFundamentals#2226]
In previous versions i had to use one click to change dev panel position. Now i must use two annoying  clicks. Why? It is stupid. 

![image](https://cloud.githubusercontent.com/assets/12018713/10712944/3eaa8546-7ab2-11e5-819d-0d6f0b02d0e9.png)
![image](https://cloud.githubusercontent.com/assets/12018713/10712945/41ef3288-7ab2-11e5-9841-863db92e5874.png)

**Comment by petele** [comment]
Hi @littleguga - Looks like this is an issue with Chrome, not our docs. Please file it at https://crbug.com
