### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by crypticsymbols** [google/WebFundamentals#2233]
Hi. I've noticed lately that the dev tools pane snaps back and forth between a split-horizontal and split-vertical layout depending on the width on the pane.

This is really, really annoying. I want vertical only, all the time. Is there a way to disable this behavior?

Thanks!

**Comment by pbakaus** [comment]
Please file a bug at https://crbug.com. This repo is for bugs in the documentation only.
