### ISSUE TITLE
[EN] Feedback for: /web/shows/ttt/series-2/es2015?hl=en

### ISSUE THREAD

**Issue by paullewis** [google/WebFundamentals#2234]
If you take videos to full screen they don't show the video.

**Comment by patrickhlauke** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/895831/10741511/128912a6-7c20-11e5-818b-5fbaff5797bb.png)

**Comment by petele** [comment]
@gauntface investigated this a bit, and thinks it's an MDL issue.

**Comment by paullewis** [comment]
Tagging in @surma and @sgomes... just like #2235 :+1:

**Comment by sgomes** [comment]
That's an interesting one, thanks! @gauntface: let me know if you need any help debugging this one.

**Comment by gauntface** [comment]
Duplicate of #2189.

I think this is something weird with the layout thing is my guess.
