### ISSUE TITLE
Menu needs to allow for scrolling

### ISSUE THREAD

**Issue by paullewis** [google/WebFundamentals#2235]
When the list is long and the screen isn't tall enough we should allow people to scroll.

<img width="933" alt="totally_tooling_tips___web_shows_-_google_developers" src="https://cloud.githubusercontent.com/assets/617438/10741599/8701a12a-7c20-11e5-8d69-6332e2d388c6.png">

**Comment by petele** [comment]
Known issue with MDL - we're waiting for the next update.

@gauntface - any updates?

**Comment by paullewis** [comment]
Tagging in @surma and @sgomes as an FYI

**Comment by sgomes** [comment]
Yup, it's a known bug. Fix will come out in 1.0.6.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
