### ISSUE TITLE
Fixing the instructions on installation

### ISSUE THREAD

**Issue by greenido** [google/WebFundamentals#2243]
Docker installation on mac needs these extra steps:
https://greenido.wordpress.com/2015/10/28/macos-docker-installation-problems/
until they will fix this issue (it's from 8/20/2015)

And this is deprecated: 
==
Using boot2docker and Mac OS X
After running tools/docker.sh grunt develop, the Web Fundamentals website will be running on your local Docker instance. However, to view the website from a browser, you need to get the IP address of boot2docker (NOT your Docker instance):

$ boot2docker ip
192.168.59.103
==

**Comment by petele** [comment]
Since we don't have a docker setup right now, it's not really needed ;)

**Comment by greenido** [comment]
It will be good/great to have a docker installation. The current process without it is... painful.
