### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/remote-debugging/?hl=en

### ISSUE THREAD

**Issue by agenobarb** [google/WebFundamentals#2246]
Hi! I was trying to use this remote debuging of Android behavior towards my site and failed to see the http/https requests for video content for some reason. I can see I think all requests except video (which was simple mp4 file downloading). I have verified agains Youtube and got the same result. At the same  time I can see all the requests from my laptop and local Chrome developer tool.
Can you please advice what seems to be an issue?
Thanks!

**Comment by pbakaus** [comment]
Looks like you're talking about an actual issue in DevTools, not in the documentation. Please go to https://crbug.com/new to file your bug.
