### ISSUE TITLE
Fix Typo in Web install banner's page

### ISSUE THREAD

**Issue by filipedelmonte** [google/WebFundamentals#2251]
just a typo fix

**Comment by gauntface** [comment]
@filipedelmonte could you add info on the exact phrase with the typo and the URL of the page with it?

**Comment by filipedelmonte** [comment]
Sure,

**typo url**:
https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en

...onbeforinstallprompt event ...
