### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-offline-web-app/step-4?hl=en

### ISSUE THREAD

**Issue by sgomes** [google/WebFundamentals#2257]
The content for this step is the same as the previous one, with just a few wording changes. Oversight?

**Comment by rupl** [comment]
Seeing this too.. Step 3 and Step 4 seem to be the same. I noticed while using the "next step" button in between the content and the persistent footer.

Additionally the tutorial continues on without advising the reader to switch away from the final `master` branch. The last line in Step 4 says:

> We are now going to remove all offline support and you are going to learn how to use Service Worker offline by adding it back into this application.

Perhaps Step 4 should be instructions on how to remove the support so the reader can begin with Step 5, creating `sw.js` at the root of the app. I notice there's a branch called `code-lab` in the airhorn repository which does not contain the Service Worker. It seems to be the starting point.

**Comment by rupl** [comment]
I'm in Thailand (without stellar signal) so I couldn't clone the repo to test this, but I tried to draft some content in the GitHub UI.
