### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/device-mode/emulate-mobile-viewports?hl=en

### ISSUE THREAD

**Issue by joenil** [google/WebFundamentals#2262]
https://www.reddit.com/r/webdev/comments/3lu0ui/chrome_dev_tools_iphone6_emulator_adding_black/
Why iPhone6 and Goggle Nexus5 and other some devices had this problem？

**Comment by petele** [comment]
@pbakaus - can you please review and comment

**Comment by pbakaus** [comment]
This seems to be a bug with the DevTools themselves, not the documentation. Please file the bug at https://crbug.com/new instead.
