### ISSUE TITLE
[EN] A questionnaire for my bachelor thesis

### ISSUE THREAD

**Issue by Mispulin** [google/WebFundamentals#2267]
Please, take a minute to answer two questions about responsive web design. It is for my bachelor thesis. Thank you very much! http://www.survio.com/survey/d/A9X4X1Z9A3F8T8Q1C

**Comment by Meggin** [comment]
Hey, I'd like to help-- is there an English version?

**Comment by Mispulin** [comment]
I translated every question and answers, where is the problem?


---------- Původní zpráva ----------

Od: Meggin Kearney <notifications@github.com>

Komu: google/WebFundamentals <WebFundamentals@noreply.github.com>

Datum: 4. 11. 2015 21:05:03

Předmět: Re: [WebFundamentals] [EN] A questionnaire for my bachelor thesis (
#2267)


"

Hey, I'd like to help-- is there an English version?

—

Reply to this email directly or view it on GitHub
(https://github.com/google/WebFundamentals/issues/2267#issuecomment-153847641)
. 





"=

**Comment by Meggin** [comment]
Maybe it's linking to a different version?

**Comment by Mispulin** [comment]
There's only one version. 



http://www.survio.com/survey/d/A9X4X1Z9A3F8T8Q1C






---------- Původní zpráva ----------
Od: Meggin Kearney <notifications@github.com>
Komu: google/WebFundamentals <WebFundamentals@noreply.github.com>
Datum: 4. 11. 2015 21:58:30
Předmět: Re: [WebFundamentals] [EN] A questionnaire for my bachelor thesis (
#2267)

"
Maybe it's linking to a different version?

On Wed, Nov 4, 2015 at 12:56 PM, Mispulin <notifications@github.com> wrote:

> I translated every question and answers, where is the problem?
>
>
> ---------- Původní zpráva ----------
>
> Od: Meggin Kearney <notifications@github.com>
>
> Komu: google/WebFundamentals <WebFundamentals@noreply.github.com>
>
> Datum: 4. 11. 2015 21:05:03
>
> Předmět: Re: [WebFundamentals] [EN] A questionnaire for my bachelor thesis
> (
> #2267)
>
>
> "
>
> Hey, I'd like to help-- is there an English version?
>
> —
>
> Reply to this email directly or view it on GitHub
> (
> https://github.com/google/WebFundamentals/issues/2267#issuecomment-
153847641
> )
> .
>
>
>
>
>
> "=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/WebFundamentals/issues/2267#issuecomment-
153862705>
> .
>

—
Reply to this email directly or view it on GitHub
(https://github.com/google/WebFundamentals/issues/2267#issuecomment-153863281)
. 





"
=
