### ISSUE TITLE
[EN] Feedback for Translations

### ISSUE THREAD

**Issue by Alevale** [google/WebFundamentals#2269]
Please do not translate automaticly a page that has relevant information for proggrammers, and if you do, please leave always a button at somewhere to easily change it.
I went automaticly into the spanish version of the page (even if I was using the english one previously)

Do something well, you are google, let's make a standard for making a live easyer, let's keep all programming tools in english as default.

There was no easy way to translate the page (unless using `?hl=en` in the URL)

**Comment by petele** [comment]
Many developers have asked us to provide Web Fundamentals in their native language, especially given that not everyone speaks English. 

If you'd prefer to use the English (or any other version), you can change it by clicking on the globe icon towards the bottom part of the page - it'll show you the list of available languages for that page.
