### ISSUE TITLE
[EN] Feedback for: /web/resources/?hl=en

### ISSUE THREAD

**Issue by merrua** [google/WebFundamentals#2272]
1. go to https://developers.google.com/web/resources/
2. click on the link 1. Base Styleguide
it goes to https://developers.google.com/web/resources/styleguide/?hl=en 
which has a 404

**Comment by vitorinoaraujo** [comment]
Also in the same page, the menu in the left side of the page has the same problem. 
Base Styleguide link under the Resources Menu returns a 404

**Comment by vitorinoaraujo** [comment]
Duplicate issue, already reported in #2275
