### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/remote-debugging/webviews?hl=en

### ISSUE THREAD

**Issue by GrahamFirst** [google/WebFundamentals#2273]
The following code has a horrible bug:

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    if (0 != (getApplicationInfo().flags &= ApplicationInfo.FLAG_DEBUGGABLE))
    { WebView.setWebContentsDebuggingEnabled(true); }
}
```

The operator '&=' will modify the flag, resulting in such strange consequences as RTL support breaking.

**Comment by petele** [comment]
@pbakaus - can you please review and address

**Comment by pbakaus** [comment]
This seems to be a bug with the DevTools themselves, not the documentation. Please file the bug at https://crbug.com/new instead.
