### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/?hl=en

### ISSUE THREAD

**Issue by vmajor** [google/WebFundamentals#2275]
Guys (gilrs),

I am so lost in your new UI. I have no idea where to find my developer console listing the applications that I have created or am creating. I wasted 30 minutes just trying to start. Stop trying to sell me more stuff or get me to learn new stuff, or attend conference or whatever. I just want to go to my workbench.

Apply your own grand advice on good website design - users want to get to where they want quickly and easily. So far your UI is completely useless in this regard. I am still lost.

**Comment by petele** [comment]
Thanks for the feedback, we're still working to make things better, so stay tuned!
