### ISSUE TITLE
Headline cutoff while loading

### ISSUE THREAD

**Issue by paulirish** [google/WebFundamentals#2279]
![image](https://cloud.githubusercontent.com/assets/39191/11097239/2ff05d6a-8853-11e5-8d08-d571b346529f.png)

My page was like this for about 10 seconds. 

IIRC, this is due to the lazy instantiation of MDL, but seems like a big risk to defer applying styles so long.

**Comment by paulirish** [comment]
Oops, wrong paste. I meant this image:

![image](https://cloud.githubusercontent.com/assets/39191/11097321/92eed98c-8853-11e5-8393-e7bda1230829.png)

**Comment by petele** [comment]
There's a bug with MDL 1.0.4/5 that seems to cause this to happen. I'll give the team a nudge to see when we'll get something newer.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
