### ISSUE TITLE
[EN] Feedback for: DevTools - Feature suggestion

### ISSUE THREAD

**Issue by Aeggy** [google/WebFundamentals#2282]
Hey @Google,

thanks for building such great tools! I enjoy them every day.

InYou allow go to line numbers by:
- Press Ctrl+G 
- Insert a line number:#LineNumber

What about allowing people to jump directly to functions what line number they ever have:
- Press Ctrl+G 
- Insert part of function name the function name starts with
- Instead of search that just jumps to where it is called or defined, this could jump directly to the definition
- This would be great when you have single files locally but a merged JS library at the browser 
- It should support the following patterns:
  * function #NameOfFunc (…
  * #NameOfFunc: funtion(
  * var #NameOfFunc = function(

**Comment by pbakaus** [comment]
This seems to be a bug with the DevTools themselves, not the documentation. Please file the bug at https://crbug.com/new instead.
