### ISSUE TITLE
[EN] Feedback for: /web/showcase/case-study/googleplus?hl=en

### ISSUE THREAD

**Issue by JHamberg** [google/WebFundamentals#2296]
Second part of the "Challenges" paragraph is using `&mash;` instead of `&mdash;`

See attached image:

![image](https://cloud.githubusercontent.com/assets/3019559/11231004/12bdcfac-8dad-11e5-993b-bdd206c1c6c7.png)

**Comment by petele** [comment]
thanks @vitorinoaraujo
