### ISSUE TITLE
Videos not showing as full screen in new MDL template

### ISSUE THREAD

**Issue by PowerlinxJetfire** [google/WebFundamentals#2297]
If I click the full screen button in the embedded YouTube video, the page's frame goes full screen, and I can't see the video (nor any of the article's text content). Exiting full screen dumps me back at the top of the article.

![image](https://cloud.githubusercontent.com/assets/4098714/11232371/4b47245e-8d80-11e5-9633-d27c36265d6e.png)

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
