### ISSUE TITLE
[JA] Add a translation for the index page of the "Design and UI" section.

### ISSUE THREAD

**Issue by kkas** [google/WebFundamentals#2307]
I would like to contribute Japanese translation for index.markdown under /design-and-ui.
Since this is my first contribution, I would like to start a small piece of translation.

**Comment by kkas** [comment]
I have the translated version ready in my hand.
Please let me know if I need to do something else (e.g. If a commit for translation should be bigger portion).

Thank you!!

**Comment by petele** [comment]
Closing due to age, feel free to re-open if action is required.
