### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by andrewzen** [google/WebFundamentals#2309]
Can you please amend the Open Developer Tools keyboard shortcut listed in the Chrome DevTools header?

That is, change "Ctrl/Cmd + Shift + I"  to something like:
  * "Ctrl/Cmd + Shift/Opt + I", or 
  * "Ctrl/Cmd + Shift/Opt + I (on Windows/on Mac)", or
  * "Ctrl + Shift + I (on Windows) / Cmd + Opt + I (on Mac)"

Because "Cmd + Shift + I" in Chrome (Version 46.0.2490.86, 64-bit) on my iMac (OS X Yosemite, Version 10.10.5) doesn't open Chrome DevTools (it opens my Mail app).

It's not a big issue, but it may be a stumbling block for people that are new to DevTools.

**Comment by pbakaus** [comment]
@paulirish can you confirm?

**Comment by andrewzen** [comment]
BTW, "Cmd + Opt + I" is listed as the Mac keyboard shortcut on https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/shortcuts in the Accessing DevTools section.
