### ISSUE TITLE
View Source button is 404ing

### ISSUE THREAD

**Issue by blainesch** [google/WebFundamentals#2310]
On [this page](https://developers.google.com/web/updates/2015/11/devtools-digest-cds-edition) if I click the "view source" I go to a page url that looks like:

https://github.com/Google/WebFundamentals/tree/material-branch/src/content/en/updates/posts/2015/11/devtools-digest-cds-edition.markdown

The problem is the branch `material-branch` which doesn't include the new post, but it does exist on master. This could be as simple as merging master into `material-branch`.

Related to #2304

**Comment by gauntface** [comment]
Thanks for the bug report.

The config files need updating to master:

https://github.com/google/WebFundamentals/search?utf8=%E2%9C%93&q=WFGithubBranch

**Comment by PaulKinlan** [comment]
I have a bug fix coming in for this.

**Comment by PaulKinlan** [comment]
@gauntface shall we still keep staging at material-dot ?
