### ISSUE TITLE
Text is not selectable in the main article panel in Chrome 49

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#2312]
For example https://developers.google.com/web/updates/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android?hl=en. I cannot select text in the main content.

**Comment by PaulKinlan** [comment]
Odd. It was ok for me the other day...

**Comment by PaulKinlan** [comment]
![screen shot 2015-12-01 at 10 38 08 am](https://cloud.githubusercontent.com/assets/45510/11498489/aa00ea42-9817-11e5-87c1-557eded64631.png)

**Comment by PaulKinlan** [comment]
Oddly, I see this on Chrome OS and trying to select text....

**Comment by ebidel** [comment]
Works in stable. Not selectable in Canary

**Comment by petele** [comment]
This should be fixed now. Sorry about that!!
