### ISSUE TITLE
Impossible to find sub-sections of content in /web/fundamentals.

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2313]
We need to fix the navigation inside the content, it is nearly impossible to find any further articles past the first page.  I'll break down my issues based on [this page](https://developers.google.com/web/fundamentals/engage-and-retain/simplified-app-installs/?hl=en):

The menu is fine
<img width="235" alt="screen shot 2015-12-01 at 11 31 15 am" src="https://cloud.githubusercontent.com/assets/45510/11499607/14412604-981f-11e5-8dc5-2f069fb89744.png">

however when I click on it, there is no indication that this is multiple chapters of content (from the menu)

Then when you go in page you see a high-level toc for the page

<img width="510" alt="screen shot 2015-12-01 at 11 32 23 am" src="https://cloud.githubusercontent.com/assets/45510/11499632/45f7c838-981f-11e5-9992-bc98574c67c9.png">

Kinda cool, but then I get to what I think is the natural end of the aritcle and I see

<img width="1315" alt="screen shot 2015-12-01 at 11 33 10 am" src="https://cloud.githubusercontent.com/assets/45510/11499642/5c73b248-981f-11e5-9d57-ef9a2228faa1.png">

Huh, is that it, there is not much information in there?

Well it turns outs there is the following:

<img width="1068" alt="screen shot 2015-12-01 at 11 33 45 am" src="https://cloud.githubusercontent.com/assets/45510/11499647/732fef38-981f-11e5-882f-6d8c20b86f41.png">

* It is incredibly low contrast so I miss it
* It is hidden at the bottom of the page beneath the author so I don't scroll to this - I really miss the author being at the top of the page (but hey-ho).
* It is not clear in the article that there is a bunch of stuff we want people to read and as such people aren't following it.
* When you are in an article page, the two above bullets also mean that I don't know that there is information prior to or after this that forms part of the overall narrative.

I see https://developers.google.com/web/fundamentals/engage-and-retain/simplified-app-installs/?hl=en as the landing page for all of the other articles and content relating to "installs". 

I would like to see the following:

* The main menu on the left should list the content inside this section
* The landing page for the entry in "Using app install banners" should also have a toc.
* Each article should have a very clear "Next" and "Previous" and it's position in the overall section (so a toc like we had on the old site)

**Comment by gauntface** [comment]
Just spoke with @mustafa-x about this and he's uber kindly offered to take a look.

The type for the site is wonk as is the navigation but I really do struggle with getting everything pulled together, so more experienced eyes are needed.

**Comment by PaulKinlan** [comment]
Awesome, would be amazing to get @mustafa-x on-board.

**Comment by mustafa-x** [comment]
Ill take a look at it ASAP.

**Comment by pbakaus** [comment]
Want to bring this to everyone's attention, as this is still a pretty severe issue.

We now have a "topics" block at the end of the page, but it's not explained that "Topics" and "Contents" are different things (the lists look pretty much the same), and the topics are very easy to miss at the bottom of the page.

I have two proposals on how to fix it:

  1) Add another level in the navigation
  2) Move the "Topics" thing up top, and make extra prominent, rename to something like "Pages"

I vote for combining the two. For the DevTools section, we really really want that extra nav level.

/cc @Meggin @paulirish

**Comment by gauntface** [comment]
I had started work on a fix for this but it looks like we may be moving back into DevSite, is there any more movement / decisions on that?

**Comment by Meggin** [comment]
We've got three levels in the navigation (left-side).

It's not common to have 4 levels in the left-side navigation. Usually this
means breaking up site into parts with multiple left-navigations, and you'd
access them from a top menu.

I'm not saying this is the way to go, but definitely see 4 levels in
left-side as one too many. Various techniques to change navigation when
site grows. So I think investigating this is our only real option.

Meggin

**Comment by PaulKinlan** [comment]
We haven't made a decision to move back into devsite and I am still not
agreeable to it :)

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
