### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by amillward** [google/WebFundamentals#2316]
With experiments turned on, and 'Layers panel' enabled, whenever I have a breakpoint in my javascript my CPU usage goes up so much that my machine overheats, hits 100 deg. C and powers off.

**Comment by pbakaus** [comment]
That's pretty crazy! But here's not the right place to file a bug about the DevTools themselves. Please refile your bug at https://crbug.com/new.
