### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/10/chrome-47-webrtc?hl=en

### ISSUE THREAD

**Issue by dodortus** [google/WebFundamentals#2328]
Recording Sample Donwload 2 Error.
L66 - Uncaught TypeError: Cannot read property 'size' of null
L127 - a.style = 'display: none';

Bye~!

**Comment by PaulKinlan** [comment]
cc @samdutton

**Comment by samdutton** [comment]
Thanks for reporting.

I can reproduce this in Chrome 47.0.2526.8 on Mac OS (but not in Canary 49.0.2591.0). 

I've created an issue on the WebRTC samples repo: https://github.com/webrtc/samples/issues/715.

I'll do a patch.

**Comment by samdutton** [comment]
Fixed in https://github.com/webrtc/samples/pull/716.

Please let us know if you still have any problems with this demo.
