### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/01/ES6-Template-Strings?hl=en

### ISSUE THREAD

**Issue by tomcss** [google/WebFundamentals#2329]
console.log(`The number of JS MVC frameworks is ${2 * (a + b)} and not ${10 * (a + b)}.`);
    //=> The number of JS frameworks is 20 and not 2000.

That should be
    //=> The number of JS frameworks is 40 and not 200.

**Comment by PaulKinlan** [comment]
Thanks for the report, hopefully live soon.
