### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by Luke-McRedmond** [google/WebFundamentals#2348]
Stop messing with DevTools, 

I hate the changes to find in all files, and the copy css path, it is making me angry and i am considering going back to firebug.

It hurts me to say this as i loved the dev tools in chrome prior, but now its nearly as bad as IE developer tools.

**Comment by pbakaus** [comment]
This isn't constructive feedback and not the right place to open a DevTools bug. If you'd like to provide actual constructive feedback, do so at https://crbug.com/new.
