### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/evaluate-performance/performance-reference?hl=en

### ISSUE THREAD

**Issue by Aweary** [google/WebFundamentals#2349]
It seems that the following guides:

* [Analyze Runtime Performance](https://developers.google.com/web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime)

* [How to Use the Timeline Tool](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en) 

Are completely out of date, as far as I can tell. The Timeline view that I have in Version 47.0.2526.80 (64-bit) looks like:
<img width="1848" alt="screen shot 2015-12-11 at 8 51 39 am" src="https://cloud.githubusercontent.com/assets/6886061/11746674/c1700e18-9fe4-11e5-8c9d-17671c676f35.png">

Which doesn't seem to correspond at all to the view those articles use:

![image](https://cloud.githubusercontent.com/assets/6886061/11746686/d357bb58-9fe4-11e5-9f10-72906de92908.png)

It wouldn't be a big deal if it was just a small UI update, but it seems that the feature set described in those articles have been replaced, or at least obscured. Things like Events/Frames mode seem to be gone, and I can't find any newer posts with updated information on the Timeline view.

At the very least, if there is a post I'm missing, this article should note that the view is out of date.

**Comment by Aweary** [comment]
Can anyone acknowledge whether this is an issue of outdated information, or just the wrong place to look for information on Chrome's new Timeline view?

**Comment by pbakaus** [comment]
You are at the correct place, but they are indeed completely out of date. We'll redo them early next year. Sorry about that!

**Comment by Aweary** [comment]
Thanks @pbakaus, I'll keep an eye out!

**Comment by mediafreakch** [comment]
@pbakaus Could you give a quick statement about where to find the Frames mode?

**Comment by Garbee** [comment]
There is no more frames mode @mediafreakch. The FPS view is built into the top overview. The first graph.

**Comment by riskers** [comment]
I'm really wait for it!

**Comment by kaycebasques** [comment]
Hallo, I'm starting work on this today.

**Comment by riskers** [comment]
@kaycebasques How long can finish? i am hunger

**Comment by kaycebasques** [comment]
Hi @riskers probably two weeks maximum. I have a lot of updates to make to all of the Timeline docs

**Comment by kaycebasques** [comment]
hey @Aweary @riskers @mediafreakch 

Hey @riskers, the [timeline doc](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en) has been updated! Sorry for delay and thanks for your feedback

**Comment by riskers** [comment]
@kaycebasques cool!!

**Comment by kaycebasques** [comment]
both docs have been updated

timeline-tool: 

https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en

analyze-runtime (changes haven't hit production site yet but you can view them on staging): 

https://pr-2712-dot-weasel-dot-web-central.appspot.com/web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime?hl=en

**Comment by Aweary** [comment]
Looks great, thanks again @kaycebasques :+1:
