### ISSUE TITLE
"discover the panels" is cut off on mobile version of /web/tools/chrome-devtools/

### ISSUE THREAD

**Issue by Aweary** [google/WebFundamentals#2350]
The "Discover the Panels" section gets cut off on mobile devices.
<img width="1268" alt="screen shot 2015-12-11 at 9 00 48 am" src="https://cloud.githubusercontent.com/assets/6886061/11746887/be7de4b8-9fe5-11e5-9d85-e211947cc0fc.png">

**Comment by PaulKinlan** [comment]
cc @pbakaus

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
