### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/03/push-notifications-on-the-open-web?hl=en

### ISSUE THREAD

**Issue by Whiteseeker** [google/WebFundamentals#2353]
The doc contain some outdated information:
 * In the unsubscribefunction there is: "pushSubscription.subscriptionId;" it should be "pushSubscription**.endpoint**;"
 * UI and screenshot should be updated for Make a Project on the Google Developer Console
 * serviceWorkerRegistration.pushManager.subscribe() must now have : ".subscribe(**{userVisibleOnly: true}**)"

**Comment by PaulKinlan** [comment]
cc @gauntface

**Comment by jpmedley** [comment]
WONT FIX

This is the standard procedure for /Updates content that has been superseded by /Fundamentals content. The newer content is here: https://developers.google.com/web/fundamentals/getting-started/push-notifications/?hl=en

**Comment by jpmedley** [comment]
See previous comment.
