### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/design-and-ui/input/forms/?hl=en

### ISSUE THREAD

**Issue by greenido** [google/WebFundamentals#2354]
It might be time to replace the link to rAq (which is deprecated) with the article I've wrote on Autofill.

Thoughts?

**Comment by PaulKinlan** [comment]
Sure, assigned to you as you are looking after monetization etc.  Please ensure that these remain up to date.

**Comment by PaulKinlan** [comment]
What is the status of this?

**Comment by greenido** [comment]
@petele how to do wish to do it?
I suggest we just remove this article on rAq and put a link to: https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill
Thoughts?

**Comment by petele** [comment]
Given the flow content from updates should migrate into fundamentals when ready. So, I'd like to see the content from the updates post properly migrated into the fundamentals content. 

Is it officially deprecated or just scheduled to be? If it's already deprecated, we should add a header to the rAc content now that says this is and recommend something else, we can then remove the content later and redirect.

PEte

**Comment by greenido** [comment]
Closing this one as we have this: https://github.com/google/WebFundamentals/issues/2584
