### ISSUE TITLE
[EN] Sometimes control scroll causes the website to be unresponsive

### ISSUE THREAD

**Issue by alanyee** [google/WebFundamentals#2358]
For whether reason, sometimes when I use control scroll to jump from one section to another on a large page, the page becomes unresponsive. All links and hyperlinks do not open, and I cannot use `ctrl+r` or any other keyboard shortcuts. Refreshing does not fix the problem. The only solution seems to just be to close the tab or window and then proceed to open the page on a completely new tab or window.

I am using Chrome 47.0.2526.80 m on Windows Pro 10.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
