### ISSUE TITLE
[EN] Feedback for: /web/showcase/spotlight/?hl=en

### ISSUE THREAD

**Issue by FatGhosta** [google/WebFundamentals#2370]
I wait the "INITIATING LIGHTSABER" page for too long.  And then, I find this error in my chrome sonsole, "Uncaught Error: THREE.Quaternion: .setFromEuler() now expects a Euler rotation rather than a Vector3 and order."

**Comment by FatGhosta** [comment]
I use mac and Moto x+1, and my chrome version is 47. It seems that everything is ok.

**Comment by PaulKinlan** [comment]
This place isn't the best place for bugs with the game.
