### ISSUE TITLE
 Auto-reload generated CSS

### ISSUE THREAD

**Issue by Jovilon** [google/WebFundamentals#2372]
Hi,

When Auto-reload generated CSS is activated in chrome dev tools, ruby no compile file css.

>sass --watch --scss sass/style.scss:css/style.css
>> Sass is watching for changes. Press Ctrl-C to stop.
>>> Change detected to: sass/style.scss
>>> Change detected to: sass/style.scss
>>> Change detected to: sass/style.scss
>>> Change detected to: sass/style.scss
>>> Change detected to: sass/style.scss
>>> Change detected to: sass/style.scss

When Auto-reload generated CSS is not activated, ruby compile file css, but reload css don't work.

>>> Sass is watching for changes. Press Ctrl-C to stop.
>>> Change detected to: sass/style.scss
      write css/style.css
      write css/style.css.map
>>> Change detected to: sass/style.scss
      write css/style.css
      write css/style.css.map
>>> Change detected to: sass/style.scss
      write css/style.css
      write css/style.css.map

I use Ruby installer for windows 2.2.3 and Sass 3.4.20. This versions, has been working perfectly until the day 10/12/15.

This issue broken my workflow completely...

Regards

**Comment by PaulKinlan** [comment]
cc @pbakaus

**Comment by pbakaus** [comment]
This seems to be in issue with DevTools itself, not the documentation. Please file your bug report at https://crbug.com/new instead. Thanks!
