### ISSUE TITLE
No explanation found for "Queueing" of Chrome devtools network timing

### ISSUE THREAD

**Issue by zengfenfei** [google/WebFundamentals#2378]
While inspecting network performance, chrome(49.0.2593.0 canary (64-bit)) shows the following results, I fail to find the explanation for "**Queueing**" in the document(https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading).

![image](https://cloud.githubusercontent.com/assets/773310/11888742/186c908c-a57c-11e5-8e1f-4da133e3edee.png)

**Comment by kaycebasques** [comment]
hey @zengfenfei 

@Garbee documented queuing in the new [Understanding Resource Timing](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/understanding-resource-timing?hl=en#viewing-in-devtools) doc. Check out the section titled "Viewing in DevTools. 

Thanks for your contribution.
