### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/console/console-ui?hl=en

### ISSUE THREAD

**Issue by 1der1** [google/WebFundamentals#2380]
I would be very happy if I could just get the content of the console.
Unfortunately, there is no "Select all".
When I save the console to a file, it will not save all the text in the console.
Example:
It will save:
Failed to load resource: the server responded with a status of 404 (Not Found)
but not the associated resource.

**Comment by CookieJon** [comment]
This may have been added since your request, but Right-Click (context menu) has "Select All" option.

**Comment by 1der1** [comment]
I have updated Chrome to the newest Version 47.0.2526.111 m (64-bit),
but there is still no "Select All" in the Right-Click (context menu) of the console.

**Comment by CookieJon** [comment]
I do apologise.. you are right.  I must have had another browser's dev tools open when I answered your comment (which look quite similar to Chrome's, and which do have the 'Select All' option)  

I'm sorry sorry for wasting your time, but I second your request.

**Comment by 1der1** [comment]
No worries, Jon. I appreciate your efforts to help me.

**Comment by Garbee** [comment]
Feature requests should be filed on the [chromium issue tracker](http://crbug.com). The team that works on the DevTools doesn't directly look here for things like this.

**Comment by kaycebasques** [comment]
As @Garbee said, this repository is only for DevTools docs. Please submit your feature request on the [Chromium issue tracker](http://crbug.com/).
