### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/push-notifications/step-07?hl=en

### ISSUE THREAD

**Issue by rimagahwa** [google/WebFundamentals#2381]
![untitled](https://cloud.githubusercontent.com/assets/13506835/11910088/b7111cb8-a62a-11e5-91ba-e41b65fe20d0.png)
my cURL command returns 'to' 
no errors but I still don't get any notifications .
I'm testing it on a localhost 
if I push using chrome://serviceworker-internals/ then I get the notification

**Comment by bijibox** [comment]
There must be https://gcm-http.googleapis.com/gcm/send instead of https://android.googleapis.com/gcm/send

**Comment by rimagahwa** [comment]
thanks for the reply.

I'll try it out in a few days and see if that solves the problem.

**Comment by rimagahwa** [comment]
No luck , tried it same response from cURL: "to"

**Comment by petele** [comment]
merging into #3445
