### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/performance/rendering/?hl=en

### ISSUE THREAD

**Issue by pkane** [google/WebFundamentals#2383]
Hi there! This is more of an edit for the callout text regarding a link-out to `csstriggers.com`.

Instead of:
```If you want to know which of the three versions above changing any given CSS property will trigger head to CSS Triggers. And if you want the fast track to high performance animations, read the section on changing compositor-only properties.```

Perhaps the phrasing could be written as:
```If you want to know if a given CSS property will trigger a change in one of the above cases, head to CSS Triggers. And if you want the fast track to high performance animations, read the section on changing compositor-only properties.```

**Comment by PaulKinlan** [comment]
cc @paullewis
