### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

### ISSUE THREAD

**Issue by Trebly** [google/WebFundamentals#2395]
Hi,

I deliver a lot of message during two weeks on developers forum **without getting back any signifiant answer**.

I remained two weeks unable to connect for chrome debug a LG G4 running Android Lollipop 5.1.
Everything was done as described into this doc and checked (look at my messages).

**Finally I solved the problem myself**, may be using  a too heavy solution, before getting the(a) solution I spent near fifty hours to check the problem and ask questions on forums (remaining without answers, even for the question : 'if somebody have a similar installation functioning answer simply "yes I have" ' : I got nothing !!!).

But **I could set the connection (device recognized) by installing fully  in Android studio the API (optional) for each running version of android of tested devices**.

*note :* At the end of installation of the API(s), as chrome://inspect/#devices was loaded (checks devices status regularly),  I could ear significant "bip" of connection established and then find the request of connection on the device and following all elements of the connection. Disconnection reconnexion is then perfect and remains.

*note* : It is verified systematically because I was not able to connect an old Samsung Galaxy S2, I failed a simple test, but it was on several devices... After the successful connection of the LG G4 I tried again and the test fails. But the installation of API for Jelly Bean 4.1.2 had established the connection...

It is true that, now, I find too the emulators that I have installed.

This is not necessary, because the first purpose was to use debugging mode in chrome for website development on several Android devices.

I don't know which component was missing but it is installed by the API and needed for each android version.

 
**So informations are missing into this page to get connection in all cases**. 

Best regards

Trebly

**Comment by kaycebasques** [comment]
@Trebly 

So, in summary, are you saying that you needed to install Android Studio in order to get remote debugging working?

**Comment by Trebly** [comment]
Yes,

As I could not get an automatic connect, if I not only installed Android Studio but add to development kit the corresponding API for the right level (version) I got an automatic perfect connection.

I could check this easily, while I could connect with Lollipop (a LG G4), I still could not see an old Galaxy s2 running 4.2.1. So on android Studio I checked installation of the API for 4.2.1 (for installation) and at the end of installing the API, I could hear the USB connection and found my G2 into the devices list and the current opened pages...
So, I don't know which component is needed, but since I uses this (a little heavy) way I have no more problem (After ten day of tries and lost time)

Best regards

Trebly

**Comment by Trebly** [comment]
Hi,
There is a solution, just found it using several forum.
There is a bug on lg G4 which need to debug to have a PTP connection and not a MTP. 
If MTP is defined (ad recommanded) this will not enable good drivers on PC. That's quite all.

Best regards
Trebly
