### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/03/push-notifications-on-the-open-web?hl=en

### ISSUE THREAD

**Issue by yacobm8** [google/WebFundamentals#2399]
Reading through the instructions to try and integrate notifications into my web app. It is painfully difficult just to wrap my head around it because of the way the document is written. I've spent far more time then I should have working my way through this because the author thinks were all some professional programmer with a fucking computer science degree. 

A simple flow diagram would be nice to start with at the top of the page showing what a service worker file is actually there for and how your server communicates with the google messaging server and then how the google server connects with the user who receives the notification.

**Comment by PaulKinlan** [comment]
There might be something in this issue about what we can improve on this article, but your language is disgusting.  

This site is built by people who spend a lot of time making this and we make our best efforts to make good solid guidance, and a lot of people have followed this successfully already.  I'll get around to dealing with this once the language and the tone becomes more civil.

**Comment by gauntface** [comment]
I've had a similar email to my personal account.

I'm going to go through and have a look at anything we can address. I think this doc has been unattended in the hope of new content for Web Fundamentals.

In the mean time there is probably a lot of old and irrelevant details that can be removed.
