### ISSUE TITLE
Add docs for network filters - DevTools

### ISSUE THREAD

**Issue by Garbee** [google/WebFundamentals#2401]
The [network filters](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/front_end/network/NetworkLogView.js&l=123) should be documented for people. They are undiscoverable in the UX and can be super-useful.

I think we should have some already... just having trouble locating and I don't recall it being a full list.

**Comment by kaycebasques** [comment]
@Garbee are you adding this to your updates to the network docs? I can do if not, just don't want duplicate efforts

**Comment by Garbee** [comment]
Yup, I'm going to cover this as I go through that page. Getting back to work on this stuff in about an hour, picking up on the Network Throttle page PR before moving onto the network page.

**Comment by Garbee** [comment]
Right now with this, I have created a new "Understanding Resource Timing" doc page that pulls some of the existing Network Panel content out and expands upon it. Once the PR for that is merged in and the panel's content is cleaned up a bit, I'm going to begin looking for anything else that can be pulled out into new pages for debugging in specific contexts. Whatever can't be, will then get updated inline along with adding any new functionality.

**Comment by kaycebasques** [comment]
done :heavy_check_mark: 

https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading?hl=en#filter-requests

ALL THE FILTERS
