### ISSUE TITLE
File paths truncated in sources panel

### ISSUE THREAD

**Issue by ryanVincent** [google/WebFundamentals#2407]
Within the file tree in the "Sources" panel file paths are truncated even when there is room to render them.
![chrome issue](https://cloud.githubusercontent.com/assets/1391731/12089338/ad88bf3a-b2db-11e5-913e-c9bdad3c5f48.png)

**Comment by gauntface** [comment]
This is a bug with Chrome DevTools, rather this the site this repo relates to. Could you please raise this issue here: https://code.google.com/p/chromium/issues/list
