### ISSUE TITLE
Feedback Regarding HTML5Rocks Intro to SW

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#2411]
A bug was opened on chrome regarding an intro to SW here: https://code.google.com/p/chromium/issues/detail?id=574264#makechanges

Its valid and we should probably move that doc over to web fundamentals but it needs a home.

@petele and @PaulKinlan thoughts? For quick fix we can just move it to a new updates post and fix issues in the process.

**Comment by PaulKinlan** [comment]
API Primers?
