### ISSUE TITLE
[EN] Language picker usability.

### ISSUE THREAD

**Issue by madroneropaulo** [google/WebFundamentals#2413]
The language picker tool is not obvious. It took me a while to figure out how to change the language without hand-coding the url (Actually, I found it by searching on the issues, I could not find it by myself within the site). And according to #2269 and #2143 it is not an uncommon issue. The current icon can be replaced with either a more obvious icon like the earth or with the language name. Some translations are incomplete and a lot of people prefer to read tech stuff in English even if it is not their mother language.

**Comment by PaulKinlan** [comment]
Yep, we will be working on it asap.  I think we are going with the language name.

Thanks,

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
