### ISSUE TITLE
can workspace map online file?

### ISSUE THREAD

**Issue by riskers** [google/WebFundamentals#2417]
in [Set Up Persistence with DevTools Workspaces
](https://developers.google.com/web/tools/setup/setup-workflow#stage-persisted-changes),the picture shows **html5rocks.com** ,it seems map online file . 

But I try map online file , it fail !

I have no idea that workspace can map online file ?

**Comment by Garbee** [comment]
This is not supported by DevTools. You need a proxy to intercept remote files and replace them with local files when testing. Workspaces maps remote files to a local filesystem for editing, but it does not allow you to then inject those files when the remote ones are called.
