### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/11/presentation-api?hl=en

### ISSUE THREAD

**Issue by paullewis** [google/WebFundamentals#2418]
The images on this article are pretty huge. We should probably update them to be [in a phone surround](http://developer.android.com/distribute/tools/promote/device-art.html).

/cc @samdutton

**Comment by samdutton** [comment]
Good idea — will do.

**Comment by samdutton** [comment]
https://github.com/google/WebFundamentals/pull/2419

**Comment by PaulKinlan** [comment]
@petele so we can get it in the next push.
