### ISSUE TITLE
[EN] Feedback for: /web/showcase/case-study/lightsaber?hl=en

### ISSUE THREAD

**Issue by minimice** [google/WebFundamentals#2420]
On the case study page
https://developers.google.com/web/showcase/case-study/lightsaber

"API’s, Frameworks, Libraries, Game Engines etc. "

It should be <b>APIs</b> not <b>API's</b>, proper use of grammar please!!

**Comment by PaulKinlan** [comment]
> It should be APIs not API's, proper use of grammar please!!

You mean really mean: It should be APIs not API's, proper use of grammar please!

/me ducks and runs.  Fixing now.
