### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by ManishLachwani** [google/WebFundamentals#2421]
Integration with HeadSpin (http://www.headspin.io)

HeadSpin has created an infrastructure of GEO distributed cell pops (points of presence) that lets developers/QA test and debug their apps/website on real networks. This lets the developers see what their user experience, test/debug real networks/GEOs and localization.

A number of our customers suggested integrating with Chrome dev tools, i.e. developers  can select a real GEO/Network  so traffic is routed via that cell pop and do their test session.

Please let me know if this is of interest. See http://www.webpagetest.org that lets you developers run  tests on real GEOs/networks using HeadSpin.

**Comment by PaulKinlan** [comment]
Not right now.  Thanks.
