### ISSUE TITLE
[EN] Typo on  /web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime?hl=en

### ISSUE THREAD

**Issue by fetis** [google/WebFundamentals#2431]
There's typo here
>The Chrome DevTools Timeline identifies when your application causes a **forced asynchronous layout** and marks such records with yellow warning icon: Forced synchronous layout warning.

it should be `forced synchronous layout`

**Comment by PaulKinlan** [comment]
Adding in @kaycebasques

**Comment by kaycebasques** [comment]
thanks @fetis I saw that too. I'm rewriting all of the profile docs, the type you caught will be fixed with those changes

**Comment by kaycebasques** [comment]
fixed in #2712 (changes will hit production site soon)
