### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by CookieJon** [google/WebFundamentals#2435]
It's all fabulous what you've done (so these requests may sound petty) but...

1. __Docking__
 Would like to dock Dev Tools to the LEFT of the window (why bottom and right only??)

2. __Variables View__ 
Fantastic how object properties remain expanded when clicking between different objects of the same type, but some suggested improvements that would really speed up development...

* Could properties remain expanded when switching back to the same object type after having clicked on a different object type in between.

* Could they remain expanded when the page is refreshed.

* Would REALLY REALLY like to be able to select multiple properties (ctrl/shift+click? click+drag?) and expand them all in one go.  

It's really tedious having to click on lots of properties individually to expand them one at a time, especially when the size of the list changes as each one is expanded (yes I know, select them from the bottom of the list and work up, but still...!) and then having to do it all over again when the page refreshes.

Thank you.

**Comment by petele** [comment]
@pbakaus

**Comment by Garbee** [comment]
This looks like DevTools technical feedback which is best reported in the [chromium issue tracker](http://crbug.com).
