### ISSUE TITLE
[EN] Request for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by drhersh** [google/WebFundamentals#2437]
Hi Developers,

Currently downloading, converting and organizing files on a chromebook using the file manager and google docs is inefficient and time-consuming. First I download the file, be it a power point or word doc, or whatever, from the web and then 2. I choose where I want to save it,  3. I then open it 4. then I need to convert it to google docs format, 5, then I have to "organize" it, which used to be "move to folder" to the same place I already saved it to in the first place. So step 5 is redundant, but if I skip step 5 the file is not where I want it to be. I would like to have all 5 steps combined into one, by having the file auto converted to google format as I download it and tell it where I want it downloaded. Is that possible? If not is cutting one or some of these steps out possible?

Thank you,

Joshua Hersh

**Comment by petele** [comment]
Hi, 

Thanks for the feedback, unfortunately this forum is meant for issues only with our web documentation. I'd recommend checking out the Google Docs product forums.
