### ISSUE TITLE
[EN] Chrome v47 Devtools variable value annotation issue

### ISSUE THREAD

**Issue by mooglemoogle** [google/WebFundamentals#2439]
Running Chrome Version 47.0.2526.111 m on Windows 7 64-bit

When using the dev tools this morning, I switched to a layer in the call stack and was initially confused by one of the annotations showing the current value of a particular variable on the side of the code. As you can see in the attached screenshot, there is a variable in the function called `length` which is reported to be 5 at the top. That is the correct value for `length`. A little ways down, there is an if statement looking for the value of `queueableFn.fn.length` to be greater than 0. The annotation for that line shows the value of `length` to be 5. My first thought seeing that was that the `length` reported there referred to the `queueableFn.fn.length` but it doesn't. It seems like the algorithm that produces the annotations was just a little more zealous (or possibly less distinguishing) than it should be in this case.

Small issue, but could cause a headache for a user that has grown to rely on those annotations.

![chrome debugger overzealous variable value](https://cloud.githubusercontent.com/assets/232911/12393944/d31b4948-bdc6-11e5-9e5c-1d02787df721.png)

**Comment by petele** [comment]
@pbakaus

**Comment by Garbee** [comment]
This looks like a technical issue. They should be filed in the [Chromium Issue Tracker](https://crbug.com) so the programming team can triage the problem and implement a fix if a problem is found.
