### ISSUE TITLE
Firefox fullscreen API typo

### ISSUE THREAD

**Issue by mininao** [google/WebFundamentals#2441]
Hi,
In the page https://developers.google.com/web/updates/2011/10/Let-Your-Content-Do-the-Talking-Fullscreen-API, the `document.mozCancelFullscreen()` method is mentioned.

 However, according to [the mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#Getting_out_of_full_screen_mode), `document.mozCancelFullscreen()` takes a capital S

**Comment by petele** [comment]
I've merged and will get this pushed this week.
