### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by kbitlive** [google/WebFundamentals#2451]
chrome-devtools   
chrome developer tools can be translated into Chinese it?    by：http://translate.google.cn/

**Comment by petele** [comment]
@samdutton - was Chinese included in the recent translation request?

**Comment by samdutton** [comment]
Yes: zh-cn and zh-tw.

@samdutton <https://github.com/samdutton> - was Chinese included in the
recent translation request?

—
Reply to this email directly or view it on GitHub
<https://github.com/google/WebFundamentals/issues/2451#issuecomment-175866232>
.

**Comment by petele** [comment]
Great - thanks @samdutton.

@kbitlive - this should be included in the next translation update that we're doing now using a professional translation service.

**Comment by kbitlive** [comment]
ok  thanks
