### ISSUE TITLE
/tools/chrome-devtools/iterate/device-mode/emulate-mobile-viewports needs updating

### ISSUE THREAD

**Issue by q42jaap** [google/WebFundamentals#2457]
This page does not say when this information is posted, right now, the `Save as` button does not appear in the devtools, a date would be helpful.

**Comment by petele** [comment]
@pbakaus @kaycebasques - can you two figure out who should update this and get it updated please? The workflow here has changed since we last documented.

**Comment by kaycebasques** [comment]
Thanks for the feedback, @q42jaap. I've updated the entire document and the changes are in review now.
