### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by QuentinLaco** [google/WebFundamentals#2458]
Hi 

I would like to report that just after installing Chrome version 48.0.2564.82 m (in French), I have an issue with the device simulator for iPhone 5 for example. The website is not displayed as it was before (in the previous Chrome version or on a real Iphone 5). Please let me know if you need more details (screenshots, example...)

**Comment by Garbee** [comment]
If you are having an issue with the way the tools are functioning, please file a bug report in the [chromium bug tracker](http://crbug.com).

**Comment by petele** [comment]
Thanks @Garbee!
