### ISSUE TITLE
Web Audio posts for /web/updates for Chrome 49 beta blog post

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2465]
WebAudio: Add IIRFilterNode
WebAudio: decodeAudioData returns a Promise
WebAudio: OfflineAudioContext.suspend() and resume()

**Comment by PaulKinlan** [comment]
WebAudio: Biquad filters run at a-rate
WebAudio: Support chaining on AudioNode.connect() and AudioParam automation methods

**Comment by PaulKinlan** [comment]
Uploading a PR for this now from Chris's doc.

**Comment by petele** [comment]
Closing, please reopen if it's not completed.
