### ISSUE TITLE
Update Network Conditions

### ISSUE THREAD

**Issue by Garbee** [google/WebFundamentals#2471]
Taking a peek at [network conditions](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/network-conditions?hl=en) there is quite a bit of room to improve here. I propose:

1. Drop the external tooling. DevTools now throttles uploads as well as downloads. The only stuff not throttled is WebRTC, Service Workers, and other non-primary (probably not the right term) work. Which a note can be made about the options to throttle even those with external tools.
2. Update the page to focus on the Network Throttle that is now built into the Network Panel.
    1. Update to show the new UX.
    2. Show how to create custom conditions via settings

Anything else to do when updating? Or any reason to keep the full instructions on using other tools?

cc @paulirish @kaycebasques @Meggin @pbakaus

**Comment by kaycebasques** [comment]
SGTM, this is independent of my updates to profiling docs.

**Comment by petele** [comment]
Since this is supposed to be the Chrome DevTools documentation, I don't have an issue with removing the instructions for other tools. It might be nice to include links to the official docs for those other tools with a note about doing it outside, but that's a nice to have.

**Comment by Garbee** [comment]
Yup. My plan is to link to them as things to use for testing what devtools
currently doesn't cover. Since we support the existing primary uses, the
existing info is confusing pushing other tools so heavily.

**Comment by pbakaus** [comment]
Yeah, SGTM. Go for it!

**Comment by kaycebasques** [comment]
@Garbee says that he's going to handle #2401 too while working on these updates

**Comment by Garbee** [comment]
I'm doing this page update on its own PR. Then moving onto #2401 as well as covering other things we need to update in a pass of the Resource Loading page.

**Comment by Garbee** [comment]
P.S. Should have a PR for this either this afternoon or tomorrow afternoon. Working on it now, we'll see how far along I get today.
