### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en

### ISSUE THREAD

**Issue by riskers** [google/WebFundamentals#2475]
please update **Timeline** part，It's so old

**Comment by petele** [comment]
@kaycebasques @pbakaus - please review and assign as appropriate

**Comment by kaycebasques** [comment]
Hey @riskers I'm in the process of updating all of the Profile docs

**Comment by kaycebasques** [comment]
Hey @riskers, the [doc](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en) has been updated!

Thanks for your feedback
