### ISSUE TITLE
Web Filter Showcase app is broken

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#2480]
The app highlighted in https://developers.google.com/web/showcase/spotlight/web_filter?hl=en is broken and doesn't work on Chrome for Android any more.

I recommend we remove it. Any objections? @pbakaus @PaulKinlan

**Comment by PaulKinlan** [comment]
Let's just speak to the eng on it.  THey need to move to https.

**Comment by petele** [comment]
OK - do you have a contact for them, or know who does?

**Comment by petele** [comment]
@PaulKinlan @pbakaus - ping. If you're not sure, I'm going to yank it next week.

**Comment by pbakaus** [comment]
On it, just reached out to the dev.

**Comment by drojdjou** [comment]
Hi! Can I move it to a different URL/domain that uses HTTPS?

**Comment by petele** [comment]
@drojdjou - yah, absolutely. Just let us know what the new URL is and we'll update the case study. Or submit a PR with the updated URL in case study :)
