### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by simonpapworth6742** [google/WebFundamentals#2485]
Version 49.0.2623.28 beta-m

Using the developer options to debug css print media is now significantly slower than in the previous version. This has me about to see if I can downgrade.

Sorry guys, I even had to close chrome down to get rendering of print media css to stop.

**Comment by kaycebasques** [comment]
@simonpapworth6742 please clarify, is this a problem with how the site performs or with some content that you're seeing on the page /web/tools/chrome-devtools?

**Comment by Garbee** [comment]
Please file technical problems in the [chromium issue tracker](https://crbug.com) so the developers of the software can triage.
