### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/engage-and-retain/simplified-app-installs/?hl=en

### ISSUE THREAD

**Issue by jonathanfauteux** [google/WebFundamentals#2503]
This kind of functionality lacks key elements, 

The ability for applications to share content to your home screen web app. 

Google also mentioned that users are concerned by background refresh data usage, as well as disk space used. Specifying this kind of information as part of the web app install process would provide a more transparent experience for our users.

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
