### ISSUE TITLE
Code block doesn't scroll horizontally

### ISSUE THREAD

**Issue by sgomes** [google/WebFundamentals#2506]
There's a long code block in [this page](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-07?hl=en) which doesn't seem to scroll horizontally, even though the scrolling UI is there:

![image](https://cloud.githubusercontent.com/assets/409615/12785077/7f089b1c-ca82-11e5-9beb-e8b2f41e68a9.png)

**Comment by legovaer** [comment]
I've tested this in Chrome Version 48.0.2564.103 (64-bit) on OSX 10.11.12 and it works fine. However, if I use Safari Version 9.0.2 (11601.3.9), I'm able to reproduce the issue. Scrolling using the trackpad is possible, but scrolling using the scrollbar isn't working.

**Comment by sgomes** [comment]
Thanks for the follow-up, @legovaer, shouldn't have assumed it happens in all browsers :)

I saw this in Chrome version 49.0.2623.39 beta (64-bit) on OS X 10.11.3, however. I can confirm the fix @legovaer suggested works there too.

**Comment by dandv** [comment]
If you change the zoom level, the scrollbar thumb can be dragged again.

This is a Chrome bug that I discovered as well, and reported at https://bugs.chromium.org/p/chromium/issues/detail?id=593202

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
