### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/01/urlsearchparams?hl=en

### ISSUE THREAD

**Issue by 31H0B1eV** [google/WebFundamentals#2514]
wtf? or i don't know something?
* Array.from(params.length) === 3

params.length == int
Array.from() - expect array like object.

**Comment by Garbee** [comment]
That would be a bug. `params` should be the parameter.

**Comment by 31H0B1eV** [comment]
yep, looks like it must be `Array.from(params).length === 3;`

**Comment by Garbee** [comment]
Yea, PR already open for it.
