### ISSUE TITLE
PWA Zip file contains extra Mac files like .DS_Store

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#2518]
Publish a new version without them

**Comment by dandv** [comment]
Where can the of the ZIP be found?

**Comment by petele** [comment]
It's linked from https://developers.google.com/web/fundamentals/getting-started/your-first-progressive-web-app/step-02 and is in the Git repo as well.

**Comment by dandv** [comment]
Had seen the link (that's how I found the Mac files), but where in the repo is, for instance, app.js?

![image](https://cloud.githubusercontent.com/assets/33569/12837607/2f5f77f0-cb79-11e5-90f0-f10f3abc8c28.png)

Couldn't find it at https://github.com/google/WebFundamentals/tree/master/src/content/en/fundamentals/getting-started/your-first-offline-web-app

**Comment by petele** [comment]
Ah - yep, it's in the Your First Progressive Web App folder, https://github.com/google/WebFundamentals/tree/master/src/content/en/fundamentals/getting-started/your-first-progressive-web-app, not the offline app.

**Comment by petele** [comment]
Will fix in the DevSite update coming in the next two weeks. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/
