### ISSUE TITLE
DevTools - Document Layer debug colors

### ISSUE THREAD

**Issue by Garbee** [google/WebFundamentals#2545]
[Interesting question](https://stackoverflow.com/questions/35301036/chrome-devtool-layer-border-color-meaning) came around asking what the colors mean for layers when developers enable "Show layer borders" in the Rendering settings. While I was trying to dig through the source, they had already found the answer.

Let's get this documented under DevTools so it is hopefully easier to find in the future. 

One kink to this is in the design doc that the asker found, it is stated that "These colors can sometimes change and the list that used to be here quickly gets outdated". If it "quickly gets outdated" then upkeeping a list of them is clearly a problem when we don't get alerted to changes. Anything we can do to help ensure things don't change but instead the list is added-to as new things happen?

**Comment by Garbee** [comment]
So, from a discussion in a meeting on DevTools stuff today it turns out the wiki was outdated. The colors don't change and we are safe to move forwarding documenting these.

**Comment by paulirish** [comment]
I've done the first pass at https://stackoverflow.com/questions/35301036/chrome-devtool-layer-border-color-meaning/35563108#35563108

**Comment by nayphyoaung** [comment]
{% re %}
