### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by stevehomer** [google/WebFundamentals#2554]
All I wanted to do was see the value of variables in JS. Lots of fancy stuff beyond my pay grade. I have breakpoints - fine. But, having followed your new "improved" help damned if I can see how to get the value of a variable apart from writing it to console.

Any chance of some BEGINNER'S help to get us starting or is this all just the boys talking to them selves and yes, some of the clever ideas are great. But today I just wanted to use a JS debugging tool. 

I am sure the info is there somewhere. but when you come to the help page you go straight into writing snippets not a basic primer. Ah well back to console writing which is a stunningly poor way of doing things.

**Comment by Garbee** [comment]
Under the `Sources` panel on the right-hand side there is a "Watch" collapse area. If you click the `+` button here, you can add the name of a variable to watch. The trick here is, they don't live-refresh. They are checked for when added, then if you need the value updated you need to press the refresh button beside the add button. This is how you can analyze variables without using the console.

I'll take a look and see if we can't improve documentation for this. Thanks for the feedback!

![sources-watch](https://cloud.githubusercontent.com/assets/868301/12976844/dab3f4bc-d094-11e5-9587-b525e5897d67.png)
