### ISSUE TITLE
Build error when contributor photo is a png

### ISSUE THREAD

**Issue by Garbee** [google/WebFundamentals#2559]
It would be nice if the build detected a non-jpg photo being used for contributors and fails if that is the case. Since everything is hard-coded to do jpg this would be a good early check so things that are known-to-work get merged.

Seems easy enough to add to the build process right? I'm thinking a quick gulp task that just counts the items in the folder. Then ask for all the `*.jpg` from it and compare the length. If lengths are equal then all is fine, if not throw an error that some file exists in there that isn't of the right type.

I accidentally comitted a png and no one caught that. Would be nice if we tried to catch it automatically in the future and get things solved early so the history of binary files is kept minimal. In a repo this large it adds up.

cc @crhym3

**Comment by crhym3** [comment]
Maybe this could be generalized to look for any broken link, not just photos.

**Comment by Garbee** [comment]
Yup, any 400 or 500 error on a link would be nice. We should be able to tell if it is a bad contributor photo fairly easily from that. So long as the exact link in question is provided as output in Drone. That way we can also catch stale external links if they exist or stale internal links.

**Comment by PaulKinlan** [comment]
@gauntface was writing tests for the build process, seems reasonable to include.

**Comment by gauntface** [comment]
I was looking at testing perf issues way back when I started, not build process tests (which is now done in Jekyll 3 but neither particularly help figure out perf issues).

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this. Check out the next-version branch.
