### ISSUE TITLE
https://github.com/google/WebFundamentals/blob/master/src/content/en/progressive-web-apps.markdown

### ISSUE THREAD

**Issue by jrears** [google/WebFundamentals#2561]
Lots of broken 404 links on this page. I would like to review the info, but it is not available. Thanks.

Johnothan

**Comment by Garbee** [comment]
The source when viewed through github will have "broken links" as it is. To properly view the content check out [developers.google.com/web](https://developers.google.com/web/progressive-web-apps) where the repository is compiled and hosted. The links on this site should all work. Please let us know if you find any dead links on the hosted version of the repository.
