### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by nasserghiasi** [google/WebFundamentals#2569]
Many websites minimize their css file's size for reducing file sizes and optimize website speed. And when they minimize their css file this mean that their css is just in one line and does not look nice for a web developer if needs to change it.

You know that some IDEs has a tool called tidy (reformat), and when you use that tool or click on tidy button it will tidy your code and make it so easier to read and work on it!

I have two suggestions:
1-In Chrome developer tools, maybe we can have a tidy button to see a source code in tidy mode. For example I have a css file here (view-source:http://payla.net/cache/main all.css?_=1455603323) that is minimized and I want to see its code but it is not clear what it is and I need to tidy those codes up.

2-When we inspect an element, we can see the link of the file what that element got style from it under the style tab on the right side of Chrome console, and we can click on that link then browse the css styles. But when the code is not tidy like this css file (view-source:http://payla.net/cache/main/all.css?_=1455603323) we can't easily work with that element's style and even it's hard to find its style. 

Then, maybe Chrome can have an option to tidy codes automatically if a developer needs it!

**Comment by Garbee** [comment]
You can use the same [JavaScript pretty print](https://developers.google.com/web/tools/chrome-devtools/debug/readability/pretty-print?hl=en) function to do CSS. We should make this more clear in the docs. I'll take a look into updating this.

In the future feature requests for the DevTools should be provided in the [Chromium issue tracker](https://crbug.com). This tracker is specifically for the documentation. The team in charge of building the DevTools doesn't look here.

Thank you.

**Comment by kaycebasques** [comment]
@Garbee any work here?

**Comment by Garbee** [comment]
Not yet. I want to try and think through a more general Sources Panel story that is abstracted from strictly  CSS or JS usage.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out [https://developer.chrome.com/devtools/docs/contributing](https://developer.chrome.com/devtools/docs/contributing) for how to ask questions or file issues on DevTools.
