### ISSUE TITLE
JavaScript Highlighting Not Working on Some Pages

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#2574]
Compare the following:

works: https://developers.google.com/web/fundamentals/primers/push-notifications/push-messages?hl=en

doesn't work: https://developers.google.com/web/fundamentals/getting-started/your-first-progressive-web-app/step-03?hl=en

NOTE: There are three code examples on that page. The first seems to work. The last two don't.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
