### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/inspect-styles/edit-styles?hl=en

### ISSUE THREAD

**Issue by smackesey** [google/WebFundamentals#2575]
" basics of inspecting and tweaking your pages." link at the top of the page is broken.

**Comment by Garbee** [comment]
PR #2587 is open to address this. Looks like just an old link from importing from our old documentation area.

Thanks for the report!

**Comment by kaycebasques** [comment]
Actually I broke it when I merged the content from "basics of inspecting..." into "inspect-styles". I need to do a redirect or something...
