### ISSUE TITLE
Outdated information about creating a project in the Google Developer Console

### ISSUE THREAD

**Issue by marco-c** [google/WebFundamentals#2578]
This Web Push page (https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-04) contains outdated information.
Is there an up-to-date alternative? Or do you plan to keep it up-to-date?

**Comment by marco-c** [comment]
@samdutton?

**Comment by samdutton** [comment]
Merged in #2609 but not yet published.

**Comment by marco-c** [comment]
That's great, thank you!
