### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/design-and-ui/input/forms/use-request-auto-complete?hl=en

### ISSUE THREAD

**Issue by greenido** [google/WebFundamentals#2584]
Can we put on the top of this article something like: 

We recommend not using the requestAutocomplete API - Instead please use the autocomplete attributes for perfect autofill. Read more: https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

**Comment by zkoch** [comment]
I would recommend stronger language, such as:

"requestAutocomplete is being deprecated and should not be implemented. We recommend instead annotating your checkout form fields with autocomplete attributes to leverage autofill."

**Comment by greenido** [comment]
Sounds good.
@petele - thoughts?

**Comment by petele** [comment]
Fine by me.

**Comment by greenido** [comment]
Here is the suggested fix: https://github.com/greenido/WebFundamentals/blob/new-header-2-rAc/src/content/en/fundamentals/design-and-ui/input/forms/use-request-auto-complete.markdown

**Comment by petele** [comment]
We've yanked the rAC
