### ISSUE TITLE
Image guidelines

### ISSUE THREAD

**Issue by Garbee** [google/WebFundamentals#2586]
With the original DevTools Docs repo we had a set of [image guidelines](https://github.com/GoogleChrome/devtools-docs/blob/master/contributing-images.md) for how images should point out information. I'd like us to have the same kind of thing here to try and keep images consistent. This will help people know what things to look out for to find what is trying to be shown.

**Comment by petele** [comment]
@Garbee - want to take a stab at this based on the new DevSite UI/UX?

**Comment by petele** [comment]
This is now in https://developers.google.com/style/images
