### ISSUE TITLE
question: devtools contributors guide

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#2588]
I want to create a guide of various tips and tricks for authors of DevTools docs. I could keep it general and just create one doc for all of web/fundamentals (with a section for DevTools). Are you guys cool with that? What should the file be? The README? Or a separate markdown doc? In the base directory? 

@petele @PaulKinlan @gauntface... don't know who to ask...

**Comment by petele** [comment]
We have a bunch of guidance in `src/content/en/resources/styleguide` but it's a bit buried. Maybe we can add a link from the README to there then update that?

Open to other suggestions though.

**Comment by Garbee** [comment]
This can kinda tie into issue #2586 as well. The resources area is linked to in the `README.md` for the repository. We could improve that with more specific contribution guidelines. Also linking to the resources area from within the `CONTRIBUTING.md` file would be a big plus.

**Comment by petele** [comment]
Is this covered by the new resources in /resources?

**Comment by kaycebasques** [comment]
I haven't thought about this for a long time so it must not be very important
