### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by acarrau** [google/WebFundamentals#2599]
I'd like to suggest the Watch window in the Sources tab having two columns, one for the expression and another for the value.

It happens that when the expression is long enough the value is not shown unless you resize the whole right container. 

For example the CSS Computed Tab is laid out in a similar way to what I'm suggesting.

**Comment by kaycebasques** [comment]
Hi @acarrau this repository is for DevTools docs. For feature requests in DevTools itself, please file them at [crbug.com](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component%3APlatform%3EDevTools+&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids). Thanks.
