### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/breakpoints/?hl=en

### ISSUE THREAD

**Issue by simiov** [google/WebFundamentals#2607]
HI. i using from several years 'inspect element' tool from chrome to debug javascript apps. Now my eyes said: "we have enough light, no more. We need dark" .
i see many developers tools (brackets for example) who have tons of dark theme. 
Why there in chrome tools we don't have themes so i can choose black to not hurt my eyes anymore.
i am doing something wrong?

thx for any help provided 
Ovidiu

**Comment by Garbee** [comment]
A dark theme settings is in Chrome v49 which should be stable in about 8 or 9 days.

**Comment by kaycebasques** [comment]
Hi @simiov read about it here: 

https://developers.google.com/web/updates/2016/02/devtools-digest-devtools-go-dark

Looks like this is in Stable now. Go to DevTools Settings > General > Appearance > Theme > Dark

<img width="445" alt="screen shot 2016-03-25 at 10 39 47 am" src="https://cloud.githubusercontent.com/assets/4713486/14049990/fd53b66c-f275-11e5-823a-af173ea1acda.png">
