### ISSUE TITLE
Deprecate the HTML5Rocks Service Worker doc

### ISSUE THREAD

**Issue by dandv** [google/WebFundamentals#2616]
http://www.html5rocks.com/en/tutorials/service-worker/introduction/ seems superseded by https://developers.google.com/web/fundamentals/primers/service-worker/

CC @jpmedley

**Comment by dandv** [comment]
Ping? https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-03?hl=en also links to the HTMLRocks page.

CC @gauntface, @PaulKinlan

**Comment by petele** [comment]
Fixed in https://github.com/html5rocks/www.html5rocks.com/pull/1445 - now we just need to get it deployed.
