### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/device-mode/media-queries?hl=en

### ISSUE THREAD

**Issue by cpcarey** [google/WebFundamentals#2621]
Looks like "Emulate print media" is now under "Rendering" instead of "Emulation" (Chrome 48)

**Comment by kaycebasques** [comment]
Note to self: doc was deleted in last big update to Device Mode docs. Need to add this content somewhere else. 

https://github.com/google/WebFundamentals/blob/71312046421de190aaf7602b6936c9b9d0c57e65/src/content/en/tools/chrome-devtools/iterate/device-mode/media-queries.markdown

**Comment by kaycebasques** [comment]
This is now documented at https://developers.google.com/web/tools/chrome-devtools/css/reference#print-mode
