### ISSUE TITLE
[EN] Feedback for: /web/tools/setup/setup-workflow?hl=en

### ISSUE THREAD

**Issue by mediadsign** [google/WebFundamentals#2631]
Hello,

I'm working with Chrome 49 on Linux Ubuntu 15.10. Until Version 49 it was no problem to map CSS files and edit my css live. Since Version 49 there is something strange going on:
- When I open DevTools without mapping, I see the css file and the line of the class.
- Then I set up mappings to the local css.
- The same class has no css file and line anymore and also is not changed, when I work on the class.
- In Settings -> General, "Enable CSS source maps" and "Auto-Reload generated CSS" is enabled.
- I also tried 49 Beta, there is the same issue.

Do I need to set up mappings different now? Or is this actually a bug?

Screenshot before the mapping:
![auswahl_005](https://cloud.githubusercontent.com/assets/17406126/13565811/be572bb4-e452-11e5-878b-7c053b84727c.png)
Screenshot after mapping:
![auswahl_004](https://cloud.githubusercontent.com/assets/17406126/13565812/be5795a4-e452-11e5-83a6-66fb541322b5.png)

**Comment by kaycebasques** [comment]
Hey @mediadsign it was a bug. You can track it here: 

https://bugs.chromium.org/p/chromium/issues/detail?id=595347&q=devtools%20map%20css&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by kaycebasques** [comment]
I added a comment in the bug linking to this issue. Thanks for your detailed report.
