### ISSUE TITLE
NBU: Design to handle very small viewports

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2632]
Add section to [Responsive web design patterns](https://developers.google.com/web/fundamentals/design-and-ui/responsive/patterns/?hl=en).

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
