### ISSUE TITLE
NBU: Design for limited CPU, memory and storage

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2633]
Add section to [Images, video and audio](https://developers.google.com/web/fundamentals/design-and-ui/media/?hl=en).  

Possibly add new material to [Optimizing content efficiency](https://developers.google.com/web/fundamentals/performance/?hl=en).    

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
