### ISSUE TITLE
NBU: Understand the intermittent/2G connectivity experience

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2634]
Add new section to [Tools](https://developers.google.com/web/tools/?hl=en). 

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
