### ISSUE TITLE
NBU: Design for ultra-low bandwidth and flakey connectivity

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2635]
Reduce the high proportion of page load failures caused by poor connectivity.

Update [Your first offline web app](https://developers.google.com/web/fundamentals/getting-started/your-first-offline-web-app/?hl=en) (and other resources?)

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
