### ISSUE TITLE
NBU: Handle low bandwidth by optimising resource selection and delivery

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2636]
Add new section to ?[Optimizing content efficiency](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/?hl=en) using existing content:
* [Automating resource selection with Client Hints
](https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints?hl=en)
* [Delivering Fast and Light Applications with Save-Data
](https://developers.google.com/web/updates/2016/02/save-data)  

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
