### ISSUE TITLE
NBU: Understand data cost

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2637]
Add new section to [Optimizing content efficiency](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/?hl=en) explaining the price/cost of data for users with prepaid data plans, etc.

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
