### ISSUE TITLE
NBU: Design to reduce data upload requirements

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2639]
For many users, uploading is slow, painful and pricey.

Add new content to [Optimizing content efficiency](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/?hl=en).

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
