### ISSUE TITLE
NBU: Reduce battery consumption

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2640]
Design to reduce battery used —avoid repaints and reflows, eliminate unnecessary network requests, reduce steps to accessing content, use hardware acceleration, e.g. for animations:

Add to:
* [Optimizing content efficiency](https://developers.google.com/web/fundamentals/performance)
* [Rendering performance](https://developers.google.com/web/fundamentals/performance/rendering)

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
