### ISSUE TITLE
NBU: Design to enable localisation and internationalisation

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#2641]
Create new section in [Design and UI](https://developers.google.com/web/fundamentals/design-and-ui).

(One of several issues raised to cover NBU requirements, as discussed via email — more detail [here](https://docs.google.com/document/d/1VjYBcsBbmasXLxsAjMaIeGxZduCLqSjd5_uJfV18YYo/edit#).)

**Comment by petele** [comment]
I believe you did this, if not, please re-open and assign to yourself.
