### ISSUE TITLE
[EN] Feedback for: /web/updates/?hl=en

### ISSUE THREAD

**Issue by simaodeveloper** [google/WebFundamentals#2642]
When I choose a css file in Source tab the browser blocks 

![image](https://cloud.githubusercontent.com/assets/4645658/13583623/2df0e896-e491-11e5-9ab8-62d609487895.png)

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
