### ISSUE TITLE
[EN] Feedback for: /web/shows/http203/podcast/http-203-promises-mistakes-and-door-handles?hl=en

### ISSUE THREAD

**Issue by davidmaxwaterman** [google/WebFundamentals#2645]
The #sgv2 image displays a 'hand' cursor, but the click handler is only on the anchor link next to it. I clicked on the icon for quite a while, eventually going somewhere else to get a link. When I came back to investigate more, I realised what was going wrong.

Please consider making the click work on the parent element to both the #svg2 image *and* the anchor - it makes more sense to click the rss icon than it does to click on the test (imo).

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
