### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en

### ISSUE THREAD

**Issue by KarandikarMihir** [google/WebFundamentals#2651]
Line 2 : `.then(device => device.connectGATT())`

Chrome throws an error saying "BluetoothDevice.connectGATT() is depricated, please use BluetoothDevice.gatt.connect() instead."

Please update the docs accordingly :)

**Comment by beaufortfrancois** [comment]
Done!
Thank you ;)
