### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/?hl=en

### ISSUE THREAD

**Issue by schindlerlee** [google/WebFundamentals#2654]
The try it button on the bottom of:
https://developers.google.com/web/fundamentals/getting-started/your-first-progressive-web-app/step-02?hl=en

is broken.

**Comment by petele** [comment]
Will fix in the DevSite update coming in the next two weeks. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/
