### ISSUE TITLE
document JS Profile and Paint better in timeline-tool

### ISSUE THREAD

**Issue by riskers** [google/WebFundamentals#2663]
hi, i see the timeline doc. i hava some question:

1. how to use the two parts, it seems to not selected have difference between selected

 <img width="398" alt="how_to_use_the_timeline_tool___web_tools_-_google_developers 2" src="https://cloud.githubusercontent.com/assets/5653652/13692513/fc0996ea-e77c-11e5-9c34-db742207c8d3.png">

2. there are many lines , i don't konw what it means

 <img width="713" alt="how_to_use_the_timeline_tool___web_tools_-_google_developers" src="https://cloud.githubusercontent.com/assets/5653652/13692587/cabcb058-e77d-11e5-88d3-dbd86a091437.png">

sorry, I'm a lot of problems recently. But I really can't find the answers to these questions, I really want to clear

**Comment by riskers** [comment]
i find [Analyze Runtime Performance
](https://developers.google.com/web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime?hl=en) introduces **js stack**, it need update,too.

but i don't find what paint means yet.

**Comment by riskers** [comment]
@kaycebasques

**Comment by kaycebasques** [comment]
@riskers enabling the **JS Profile** checkbox gives you more details about exactly which functions were called in your flame chart. I'll get back to you about **Paint**. Thanks again for the feedback. I'll use this issue to get these documented better.

**Comment by riskers** [comment]
Thanks for the trouble
