### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/09/tab-discarding?hl=en

### ISSUE THREAD

**Issue by cristian43** [google/WebFundamentals#2668]
I don't know if this is the correct place to ask it but... could Try to make it to detect when a tab is being used even in background? (like downloads from mega for example)

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
