### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime?hl=en

### ISSUE THREAD

**Issue by riskers** [google/WebFundamentals#2683]
it need to update

**Comment by kaycebasques** [comment]
Hey @riskers it's updated! The changes haven't hit the production site quite yet (they will soon), but you can see them on the staging site: 

https://web-central.appspot.com/web/tools/chrome-devtools/profile/rendering-tools/analyze-runtime?hl=en

Thanks again for your patience and feedback. I've been making good progress in updating the DevTools docs this quarter. :+1:
