### ISSUE TITLE
[EN] Feedback for Resource Tab in Dark theme of Dev Tools

### ISSUE THREAD

**Issue by abnersajr** [google/WebFundamentals#2692]
I suggest to make the hover and active of buttons (All, XHR, JS, IMG...) in Resource TAB with other colors.
Suggestion:
BG: Orange and Color: White
BG: Gray and Color: White
BG: Orange and Color: Black

For me this colors should be better to read and see what is active :+1:

**Comment by Garbee** [comment]
Please file technical issues on the [Chromium Issue Tracker](https://crbug.com). This will allow the team to take a look and address the issues directly.

This tracker is only for documentation issues.

Thank you.
