### ISSUE TITLE
Clicking on videos doesn't start them

### ISSUE THREAD

**Issue by mattzeunert** [google/WebFundamentals#2695]
The poster image for videos shows a big play button, but clicking on it doesn't start the video. You have to click on the Play button in the video controls instead.

Example: https://developers.google.com/web/tools/chrome-devtools/debug/breakpoints/step-code?hl=en

<img width="1403" alt="screen shot 2016-03-15 at 07 12 26" src="https://cloud.githubusercontent.com/assets/1303660/13770200/56cc524a-ea7d-11e5-9a4c-ff0a5df2d718.png">

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
