### ISSUE TITLE
[EN] Feedback for: /web/updates/?hl=en

### ISSUE THREAD

**Issue by jerrylee** [google/WebFundamentals#2696]
PLEASE put the width back in the upper right when resizing the browser, this is a huge tool.

**Comment by Garbee** [comment]
This bug has been addressed. It is fixed in the next version of Chrome.

In the future, please use the [Chromium issue tracker](https://crbug.com) for bug reports and technical feedback. This feedback system and issue tracker are only for documentation issues.

Thank you.
