### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by TehBucket** [google/WebFundamentals#2702]
Previewing in device mode no longer has the option to scale the entire viewer automatically when resizing the outer window. (This was very useful for simulating screens larger than my own)

With device mode turned off, scaling the devtools sidebar no longer displays the inner window resolution (This was a simple, handy tool when working on responsive sites)

**Comment by NathanDaugherty** [comment]
Adding my +1 to the second part of this comment. Absolutely no reason it should have been removed.

**Comment by kaycebasques** [comment]
Hey @TehBucket, this repo is for DevTools docs. [crbug.com](crbug.com) or the [mailing list](https://groups.google.com/forum/#!topic/google-chrome-developer-tools) are better places to discuss devtools features / bugs.

See #2709 regarding the second item.
