### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/09/tab-discarding?hl=en

### ISSUE THREAD

**Issue by processo** [google/WebFundamentals#2707]
I use Chrome (with 2-4 tabs) and memory intensive research software side by side, switching back and forth frequently only to see tabs being discarded and having to wait for reaload.

I understand memory goes low and Chrome thinks it should free up some, but I use all open tabs often enough for the reload time to matter, so none should be discarded.

I don't see what the problem is with Windows' memory management (reloading a page takes more time than pulling it back from HDD), but at least there should be a minimum time (like 30 mins) and tabs (maybe 10+) before Chrome starts discarding.

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
