### ISSUE TITLE
File System Resource Mapping between local files and localhost not working

### ISSUE THREAD

**Issue by Contract47** [google/WebFundamentals#2708]
When mapping local to remote files (in this case from a Tomcat localhost), no mappings are created, also the remote folder completely disappears from Sources in the localhost case, additionally these sources cannot be found when trying to establish the mapping via the information popup ("Establish the mapping now") or searching them directly (Ctrl+O).

Edit:
I adjusted the workspace settings so that full folders are mapped instead of files. I also noticed that a trailing slash appears to always be added to source paths automatically, even if they're referencing files. Might this be a part the problem?

**Comment by kaycebasques** [comment]
Hi @Contract47 I've been seeing a lot of bugs about workspaces in Chrome 49. Sounds like the team is aware of them. I don't think there's anything they can do to fix 49 but when 50 or 51 hits stable, the problems will be fixed. 

Let me know if any of these bugs are relevant to what you're seeing: https://bugs.chromium.org/p/chromium/issues/list?can=2&q=workspace&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids

This repo is for the DevTools docs. You'll get better help on the DevTools [mailing list](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/google-chrome-developer-tools/topics) or by filing a bug at crbug.com.
