### ISSUE TITLE
No more window size on resize with dev tools. thanks!!!

### ISSUE THREAD

**Issue by NathanDaugherty** [google/WebFundamentals#2709]
What happened to the window size overlay when resizing the dev tools dock window?

![image](https://cloud.githubusercontent.com/assets/3944585/13814774/a0938208-eb55-11e5-80bb-7b00bf4d24bf.png)

**Comment by kaycebasques** [comment]
Hey @NathanDaugherty, that was a known bug that apparently has been fixed already: https://groups.google.com/forum/#!topic/google-chrome-developer-tools/fbueXIfX09k

This repo is for DevTools docs. crbug.com or the [mailing list](https://groups.google.com/forum/#!topic/google-chrome-developer-tools) are better places to discuss devtools features / bugs.
