### ISSUE TITLE
[EN] Feedback for: /web/tools/service-worker-libraries/?hl=en

### ISSUE THREAD

**Issue by katopz** [google/WebFundamentals#2713]
Full screen for video is broken. It's look like this when click full screen at video player.

![vid-fullscreen-issue](https://cloud.githubusercontent.com/assets/97060/13838388/34c126d8-ec46-11e5-871e-17ad09910859.png)

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
