### ISSUE TITLE
create a settings directory for devtools docs

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#2716]
Problems:
* The **settings** link on /web/tools/chrome-devtools links out to DCC.
* The keyboard shortcuts doc is awkwardly organized under the iterate docs.
* There's no natural place to document general appearance features, like being able to reorder the panel tabs.
Solution:
* Create a directory /web/tools/chrome-devtools/settings and house the stuff there. We could name it "configure" so that it's consistent with the rest of action-oriented stuff, but I think "settings" is more straightforward. Or we can just store the docs directly under chrome-devtools. E.g. chrome-devtools/shortcuts, chrome-devtools/settings.

Thoughts @pbakaus?

cc @paulirish

**Comment by pbakaus** [comment]
We've left these things on the old page for some reason, but I think it makes sense to migrate them all over. That would only leave the "Let's work on DevTools themselves" docs on the old site, which is fine for now. Thoughts, @paulirish and @Meggin?

**Comment by paulirish** [comment]
URL wise i don't care very much... but "just store the docs directly under chrome-devtools. E.g. chrome-devtools/shortcuts, chrome-devtools/settings."  is my favorite.

Left-nav wise I'd be fine if they never showed up, but if they only showed at top-level when open, that'd be cool too.

But regardless they should be linked from the homepage.

**Comment by kaycebasques** [comment]
That was my preferred approach too. I'm going with that
