### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/network-performance/resource-loading?hl=en

### ISSUE THREAD

**Issue by joero24** [google/WebFundamentals#2719]
What happened to the window measurements that would appear on the top right of the screen when you resized your window? I used this feature almost everyday. It'll be a big disadvantage to remove it. Thanks! -Joe R
![yss6o](https://cloud.githubusercontent.com/assets/17912703/13858445/12abf582-ec55-11e5-9f8f-1b58e821785f.png)

**Comment by kaycebasques** [comment]
Hi @joero24,

This is a known bug that apparently has been fixed already: https://groups.google.com/forum/#!topic/google-chrome-developer-tools/fbueXIfX09k

This repo is for DevTools docs. [crbug.com](crbug.com) or the [mailing list](https://groups.google.com/forum/#!topic/google-chrome-developer-tools) are better places to discuss devtools features / bugs.
