### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=en

### ISSUE THREAD

**Issue by eidam655** [google/WebFundamentals#2723]
Changing a language setting on the Web Developers subweb is... bad.

I was googling something about webfont optimizations, when the developers.google.com site came up in the results. 'Awesome,' I thought, 'this is just what I need.' 

I was very surprised, when the site loaded - in german. No biggie - I'll just scroll to the end of the page and change the language. Oh, I won't, no such option there. Maybe in the sidebar? No, nothing like that. No hint whatsoever as to where I could change this setting. This is a Google website, maybe if I log in on the homepage? Oh, I'm already logged in. Why were the results in german then? 

I had to dig deep into the settings to change the language settings globally for the whole site, then go back and reload the page. Why? Why isn't there a single Language dropdown in the footer as on every other normal multilingual site? What if I hadn't had any google account? Would I have to create that first, just to change the language?

As I said. Bad.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
