### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en - DOMContentLoaded line no longer draws

### ISSUE THREAD

**Issue by rkalasky** [google/WebFundamentals#2731]
In the Network tab, a blue line used to draw in the timeline to show where the DOMContentLoaded event was fired. This line still appears in the mini timeline at the top:

![image](https://cloud.githubusercontent.com/assets/2799834/13952612/72b2d8ca-f005-11e5-8268-c8a6b63cd35b.png)

However, it no longer shows in the detailed view:

![image](https://cloud.githubusercontent.com/assets/2799834/13952627/827639b4-f005-11e5-9cdc-24699b21d6e7.png)

I'm assuming this is a bug since the red Load line still draws.

Version 49.0.2623.87 m

**Comment by Garbee** [comment]
Technical bugs belong in the [Chromium issue tracker](https://crbug.com) so the team can triage and address the issue. This repository is for documentation errors.

Thank  you.

**Comment by rkalasky** [comment]
Sorry about that. I will post over there.

**Comment by Garbee** [comment]
The blue line is showing here. So it could be a bug in the stable version already fixed. Which most likely won't be patched in a stable patch. Best thing would be wait for the next major and see if that fixes it.
