### ISSUE TITLE
Fix links in /web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en

### ISSUE THREAD

**Issue by jyasskin** [google/WebFundamentals#2732]
https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android#native links to the top of the article, instead of the "Native app install banner" heading.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
