### ISSUE TITLE
/web/updates articles are not scrollable in Safari 9.1

### ISSUE THREAD

**Issue by ivanoats** [google/WebFundamentals#2733]
The page does not scroll, and is therefore unreadable beyond the first few paragraphs, in Safari 9.1
https://developers.google.com/web/updates/2015/01/ES6-Template-Strings

**Comment by mcmillion** [comment]
+1

Noticed this on some other pages.

**Comment by TraderStf** [comment]
1 month already, not corrected...

**Comment by PaulKinlan** [comment]
@sgomes @petele please sort asap, this is getting beyond a joke now.  I know we are planning to migrate back into devsite soon but right now we need to get this fixed, people can't use our site.

**Comment by sgomes** [comment]
This is not an MDL issue, as it only affects Web Fundamentals. WF seems to be modifying page and MDL layout styles, and is triggering a Safari bug. Workaround on #3118.

**Comment by petele** [comment]
Fixed earlier today.
