### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by egucciar** [google/WebFundamentals#2734]
Hi,

I noticed recently my chrome debugger updated. Thats fine but now functionality that I used to rely on heavily for Debugging no longer works!

As we all know, in the debugger, you cannot reference outside scope unless its been used within the scope. For example

    function () {
        var bool = true;

         function () {
            console.log('hello world');
        }     
    }

In the past if I put a breakpoint at the console.log statement, and type into console:
bool

I will get undefined. Because bool is declared in the outside scope.

**BEFORE CHROME UPDATE**
Before the chome update, I often would use _conditional _breakpoints_ which referenced outside scope to break inside the function. So Before update, if i added a conditional breakpoint at the console.log line with the following

    bool === true

it would have broke, and bool would now be defined within the scope, and everything went smoothly.

Seems like declaring a conditional breakpoint "brought in" the vars from outer scope.

This is EXTREMELY useful for my development, where i often want to break only when certain conditions are met, without having to write if statements in my code.

**AFTER CHROME UPDATE**

Now my breakpoint isnt getting hit. Why? I know the condition is evaluating to true. Furthermore, no errors in the console are generated from my conditional breakpoint. Now if i update my function:

    function () {
        var bool = true;

         function () {
            bool;
            console.log('hello world');
        }     
    }

My conditional breakpoint gets met.

This defeats the purpose of my conditional breakpoint in the first place - I do not want to have to change my code just to break on a condition. 

Please revert the change in the chrome debugger which broke this useful functionality.

Thanks

**Comment by pbakaus** [comment]
This issue tracker only covers DevTools documentation, not product bugs. Please re-file your issue at https://crbug.com/new. Thanks!
