### ISSUE TITLE
Automatic Tab Discarding Behavior

### ISSUE THREAD

**Issue by Crayder** [google/WebFundamentals#2740]
I love the idea of this feature, but it should have some major improvements.

### Problem

- The automatic tab discarding is inappropriately discarding tabs I need to stay open.

### Examples

- I have Facebook open and am waiting for an important message.
- Chatting on Skype Web.
- Watching YouTube videos.
- Keeping a Kiwi IRC tab.
- Typing a post somewhere (whether this is a forum, Facebook, or even GitHub).
- LOT'S more.

### Suggestions

- A tab "wake lock". This will keep specifically locked tabs from being discarded. Just right click on the important tabs and enable wake lock.
- Whitelist. A list of URL's that will prevent any tab on these URL's from being discarded. This would be in the settings someone of course.

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com

**Comment by Crayder** [comment]
@petele I was told by someone else to post an issue here
