### ISSUE TITLE
[EN] Feedback for: /web/updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API?hl=en

### ISSUE THREAD

**Issue by Tomq2356** [google/WebFundamentals#2741]
It does a very poor job especially when you have two person conversations or two different versions of English speaking, if one of them happen to be not as fluently speaking in the video. When I use "virtual audio cable" instead of "speaker, headphones and microphone" as my computer "sound" set up in order to transcribe a video, it does not work smoothly at all, I almost have to click on the "microphone" within the "Web Speech API Demonstration" webpage to restart it once every 10-15 seconds (just imagine a two-hour long video), otherwise, it will not continue transcribing. Also, what's making it more complicated is that each time I click the "microphone," the webpage will prompt me to confirm "http://www.google.com wants to: use your microphone," at this point I will either click "Allow" or "Block." So I have tried to change the setting by going to "microphone exception" in Chrome's "Advanced settings," for some reason, it does not allow me to type in anything to make changes. I see a blank box when I click "microphone exception," but it will not let me to put the cursor into the box. Please fix that.  

Also, I hope there will be some new keyboard shortcuts to what were mentioned above. For example, press Control-M instead of clicking on "microphone"; press Control-A to "Allow," and press Control-B to "Block."

Thank you!

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
