### ISSUE TITLE
Canary web dev tools issue

### ISSUE THREAD

**Issue by carinlynchin** [google/WebFundamentals#2742]
After doing "pretty print" on a minified file, and setting my breakpoint, I refresh the page and its like the breakpoint is on the minified file..not the pretty one...In chrome it never did this  and I am unable to step through the code , so i am pretty sure its a bug. 

ALSO:   its intermittent

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
