### ISSUE TITLE
feedback for /web/fundamentals/getting-started/push-notifications

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#2743]
cc @samdutton I think I can tighten up this codelab... if you're cool with it I'll put in a PR and you can review it

`step-01`:

I recommend removing the ToC include module from this page. 

<img width="980" alt="screen shot 2016-03-25 at 4 23 17 pm" src="https://cloud.githubusercontent.com/assets/4713486/14056178/edd24958-f2a5-11e5-8600-a90c70f3d138.png">

`step-02`:

Ditto re: ToC

Is `sudo` necessary when running `SimpleHTTPServer`?

`step-03`:

The pages tend to look better if you put a introductory sentence before the ToC.

**Comment by samdutton** [comment]
Thanks @kaycebasques!  (I've been traveling and at events — hence delay in responding.)

> Is sudo necessary when running SimpleHTTPServer?

It is when I run it.

Other changes done in #2790.

**Comment by PaulKinlan** [comment]
No, sudo is not required for anything less than port 1024

**Comment by samdutton** [comment]
> No, sudo is not required for anything less than port 1024

Ah — I didn't know that, though sudo seems to be required *below* port 1024, rather than the other way around. 

Updated.

**Comment by petele** [comment]
Merging into #3445
