### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by donnygunawan93** [google/WebFundamentals#2745]
![untitadwled](https://cloud.githubusercontent.com/assets/10414213/14065261/1aa70d9e-f44d-11e5-83f1-3ab9bbb58be7.png)

On newest version when open chrome dev tool, always auto open console, and screen size dev tool be half, and we have console on top, why must have console on below also? and why auto open my screen be half -_-

**Comment by Garbee** [comment]
Please file technical issues at the [Chromium bug tracker](https://crbug.com). By doing this the internal team can triage and address the problem. This tracker and feedback system are for the documentation only.

Thank you.
