### ISSUE TITLE
[EN] Feedback for: /web/updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API?hl=en

### ISSUE THREAD

**Issue by IgorGelfenbeyn** [google/WebFundamentals#2747]
Hi there,

My name is Igor, and I'm wondering whom should I contact in regards of the issue with the Google voice recognition that we use in our mobile app. The thing is - with the last update of the Google Voice Rec, the listening time has shorten drastically. Could you please tell me who do I contact here, or where do I create a ticket in regards of this issue?

Thank you.
--
Best regards,
Igor

**Comment by PaulKinlan** [comment]
crbug.com/new is the best place to file these issues.
