### ISSUE TITLE
When viewing websocket frames, the selected network request automatically changes

### ISSUE THREAD

**Issue by stephenweaver** [google/WebFundamentals#2748]
On the network tab if you select a web socket connection, it won't stay selected. This makes it very difficult to debug the frame data. 

http://screencast.com/t/3muSFLKD8WB

**Comment by PaulKinlan** [comment]
@stephenweaver it is best to file this bug on crbug.com/new as this is just the documentation section.

cc @pbakaus

**Comment by Garbee** [comment]
Looks related to this existing bug. Please **star** to show it is also affecting you. https://bugs.chromium.org/p/chromium/issues/detail?id=586831
