### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by brandonr1** [google/WebFundamentals#2773]
Could you put an option in so the developer can choose whether to escape carriage returns and newlines sent to the console?  Right now they are escaped by default with no other option.  Thanks.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
