### ISSUE TITLE
TLS version fallback deprecation post should include instructions for administrators

### ISSUE THREAD

**Issue by davidben** [google/WebFundamentals#2775]
In https://developers.google.com/web/updates/2016/03/chrome-50-deprecations#remove-insecure-tls-version-fallback, the TLS version fallback section ideally would include a sentence or two for administrators. Something generic like: "Administrators should ensure their server software is up-to-date." should do. In the Intent email I also added "If this is still unresolved, reach out to the software vendor". I don't know how useful that is.

(This is caused by bugs in, usually, old server software. I'm not aware of any concrete bugs remaining, apart from one Windows issue fixed years ago. But there might be some I'm not aware of.)

**Comment by gauntface** [comment]
Can you give me a revised paragraph of what you'd like the "Remove Insecure TLS Version Fallback" to be and I'll make the changes, I don't know enough about this to comment on any of the topics you are raising.

Are there any steps to diagnose is this is the issue? I.e. error messages in the DevTools security panel or something that might get caught in a google search?

**Comment by davidben** [comment]
> Can you give me a revised paragraph

The only thing you need to add is that affected sites should get this bug fixed. There really anything more specific. This is fundamentally a server bug. Whatever software or appliance they're using for TLS is defective and never implemented the spec correctly. Something simple like this at the end should do:

Affects sites will fail to connect with `ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION`. Administrators should ensure their server software is up-to-date. If still unresolved, contact the server software vendor to see if a fix is available.

> Are there any steps to diagnose is this is the issue?

If the connection fails with ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION

**Comment by davidben** [comment]
Ping

**Comment by PaulKinlan** [comment]
@gauntface I will add this in now.
