### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/03/domtokenlist-validation-added-in-chrome-50?hl=en

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [google/WebFundamentals#2776]
Per DOM `supports()` method should be ASCII case insensitive:
https://dom.spec.whatwg.org/#concept-domtokenlist-validation
but your implementation is ASCII case sensitive.

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
