### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/design-and-ui/animations/css-vs-javascript?hl=en

### ISSUE THREAD

**Issue by gea4** [google/WebFundamentals#2791]
"Many tools will aid you in creating the prefixed versions of the CSS you need, allowing you to write the unprefixed version in your source files."

You should add a couple resources for handling the prefixes!

**Comment by petele** [comment]
Depending on your situation, there are many ways to handle this. Rather than give only a few, it's better to allow developers to choose their own.
