### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/device-mode/?hl=en

### ISSUE THREAD

**Issue by Gavarni** [google/WebFundamentals#2793]
I just wanna say that i loved the old device mode with its dark background as it its good for your eyes as a designer to see contrast when develolping and that im freaking annoyed right now that there is a new device mode which is ugly. where you guys didnt even ask me if i wanted to change it or not. 

so thmbs down on that

**Comment by kaycebasques** [comment]
@Gavarni check out dark mode!

<img width="1437" alt="screen shot 2016-07-20 at 1 24 01 pm" src="https://cloud.githubusercontent.com/assets/4713486/17001776/43682972-4e7d-11e6-9e7f-8299131ddf9a.png">

To learn how to enable, check out https://developers.google.com/web/tools/chrome-devtools/settings#dark-theme
