### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by valtido** [google/WebFundamentals#2794]
Not sure if this is the right place to do this (please advise if I should do it somewhere else).

I wish to submit a feature request for dev tools.

The feature should be called "Variables":
- Where we can inspect the variables (DOM objects like window, jQuery etc..).
- It should be split in the following groups:
  - GLOBAL SCOPE User defined variables (anything that isn't defined by the browser itself, like jQuery, _, underscore,)
  - USER AGENT defined variables (window, HTMLElement, JSON,...)
  - USER AGENT reserved keywords (optional) (e.g: var, global, window, for etc...)

The reason: 
It should help to keep global scope clean from pollution and at a minimum and give an incentive to developer to not pollute the global scope.

This is simply an idea, not sure if this is the best approach or something worth while but I would be more inclined to keep the global scope at a minimum if I see too many variables on one place, where as if it's all mixed with user agents variables because there are so many there and I don't get a sense of how much pollution I have caused I would be less sensitive to creating more.

Over time it should help libraries and developer to keep the global scope at a minimum.

**Comment by kaycebasques** [comment]
Hey @valtido that could be a good idea! This repo is for DevTools docs issues and feedback. Please send DevTools feature requests to crbug.com.
