### ISSUE TITLE
[KO] Feedback for: /web/fundamentals/performance/critical-rendering-path/render-tree-construction?hl=ko

### ISSUE THREAD

**Issue by oshx** [google/WebFundamentals#2798]
크롬 49 버전을 사용 중 입니다. 현재 타임라인의 모습이 현재 설명 중간에 그림과 다른데요. 내용이 최신 상태를 반영하지 못하고 있습니다. 그리고 설명 중간에 영문을 그대로 적은 것들이 많이 보이는데, 이 번역이나 설명문에 기여할 수 있는 방법이 있나요?

**Comment by cwdoh** [comment]
@oshx 현재 문서를 fork하셔서 작업 후에 PR을 주시면 됩니다. 도움이 필요하시다면 [비공식 한국어 번역 트렐로](https://trello.com/b/kHklsuV1/webfundamental-ko)에 [관련 문서](https://trello.com/c/zlYy2Tac/7-8-translation-fundamentals-performance-critical-rendering-path)을 이용하셔도 됩니다.
