### ISSUE TITLE
Add AMP support to /web/updates

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#2801]

**Comment by petele** [comment]
@pbakaus - Can we do this now that we've moved to DevSite?

**Comment by pbakaus** [comment]
I'll investigate today!

**Comment by pbakaus** [comment]
From further investigation: Unfortunately, doing this requires the following:

- DevSite to provide a root template that is AMP compatible, includes AMP lib, and removes all other JavaScript
- Custom markdown parser than converts images to <amp-img>, or automatically replace all instances of video and images in our updates with their AMP equivalents

If we want to make this happen, we'll need to spin up a joint-project with DevSite – but if they're interested, I'm definitely willing to provide support.

**Comment by petele** [comment]
Closing as this isn't something that's feasible on DevSite, if we want it, we'll need to start the discussion with the DevSite team.
