### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by andyseaton83** [google/WebFundamentals#2810]
Hi there - I use responsive mode on devtools a lot for my work and I noticed that since the latest update, the little white tap target thing that replaces the cursor when you mouse over the view of the responsive website has disappeared. So you don't know where you are trying to click on the site. I'm on chrome 49.0.2623.112 m - I can make a quick screencast showing the issue if you like. Just let me know via email. Thanks.

**Comment by kaycebasques** [comment]
@andyseaton83 please make a screencast

**Comment by Garbee** [comment]
This is the touch indicator to show that touch is being emulated. To turn if off you need to go into the overflow menu, turn on "Show Device Type" then select a no-touch type to get the cursor in device mode.
