### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by Hamlj** [google/WebFundamentals#2812]
Network throttling dropdown on dark theme is white, can not see text unless you hover on items.

Ubuntu: 14.04
Chrome version: Version 49.0.2623.112 (64-bit)

**Comment by kaycebasques** [comment]
@Hamlj can you add a screenshot?

**Comment by Garbee** [comment]
This issue tracker and feedback form are for the documentation and site hosting it specifically. Feature requests and bug reports are handled on crbug.com. There is already an [existing issue](https://bugs.chromium.org/p/chromium/issues/detail?id=572706) about the contrast problems, so *star* that to show it is affecting you as well.
