### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/push-notifications/step-10?hl=en

### ISSUE THREAD

**Issue by the-unsoul** [google/WebFundamentals#2815]
`var url = 'https://youtu.be/gYMkEMCHtJ4';`

This should be instead `'https://www.youtube.com/watch?v=gYMkEMCHtJ4'` . Because `youtu.be` will be redirected to `youtube.com` . Thus the clicks will always open a new window.

**Comment by petele** [comment]
Merging in to #3445
