### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by kristoforusrp** [google/WebFundamentals#2822]
I have an overlap issue (on the right side of the screenshot) with the web contents when viewing Google Dev Web in Firefox as you can see in the screenshot below. 
![overlap when viewing at ff 45 0](https://cloud.githubusercontent.com/assets/11352023/14589514/57c9615a-050e-11e6-8a44-852c48b17056.png)

Operating System: Linux Mint 17.3 (64 bit)
Browser: Firefox 45.0

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
