### ISSUE TITLE
performance-reference docs need updated visuals

### ISSUE THREAD

**Issue by bmohabir** [google/WebFundamentals#2828]
Having trouble trying to adapt to the updated timeline using this documentation. For example, in the old timeline, I had the ability to view the "Layout scope" property for layout events. Even though the new documentation claims this hasn't changed, there is no such property (all I get with any layout events are "Nodes That Need Layout", "Layout root" and "First layout invalidation"). There seem to be other changes in the new timeline that aren't addressed in the new documentation and I haven't found any useful information online other than others saying 'Oh yea, I guess they changed it'.

**Comment by kaycebasques** [comment]
Hey @bmohabir , I've been updating all of the DevTools docs this quarter. This is on my radar but I may not be able to get to it in the next couple of weeks.

**Comment by kaycebasques** [comment]
Performance panel screenshots should be up-to-date in the new [Perf Analysis Reference](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference). Please open new issues if you encounter any. Thank you for the feedback!
