### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-02?hl=en

### ISSUE THREAD

**Issue by YoGeilmann** [google/WebFundamentals#2829]
Dear Google Dev Team,

I really enjoy the Google developers guides and tools for a decent amount of time and first of all I want to thank you for sharing the great stuff. Keep up the good work!

I am still improving my skills and I often see details in guides I cant find on the internet maybe because I'm not a native english speaker. But for example the tools you were using to customize your workflow are even customized and I'd like too see the customization as an example too.

e.g. https://weather-pwa-sample.firebaseapp.com/styles/inline.css
notice the prettified css is grouped and has indent depending on the parent styles.

I'd like to see how this is done to set up my sublime text plugin doing the same.
Maybe I'm just a noob yet but I want to learn and I'd really like to know this is done.

Thanks in advantage & greetings from Germany

**Comment by petele** [comment]
Check out SASS, that's how I did that.
