### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by robmeijerink** [google/WebFundamentals#2833]
Dear Google,

I love the Chrome Dev Tools which help me develop on a daily basis. I have a feature request though, which I saw Firefox Developer Edition has already implemented.

When I open up the DevTools and go to the Elements Tab it would be great when I hover on a starting HTML tag that I can see where this starting tag ends. Just highlighting the end tag the same way as the start tag is highlighted would be a great improvement, just like how it works in Firefox DE.

Please add this minor feature to make working with the DevTools even better.

**Comment by kaycebasques** [comment]
Hi,

This repo is for the DevTools docs. Please report DevTools feature requests and issues to [crbug.com](crbug.com).

I created an issue for you on crbug.com. Follow its progress here: https://bugs.chromium.org/p/chromium/issues/detail?id=606874
