### ISSUE TITLE
Esc key not recognized while in Fullscreen

### ISSUE THREAD

**Issue by wumpeth** [google/WebFundamentals#2840]
I'm trying to trigger a function when the Escape key is pressed during fullscreen mode. Right now Esc will close fullscreen, as it is meant to, but it's not recognizing the keydown or keypress events to trigger another function as well.

Can anyone help?

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
