### ISSUE TITLE
/web/tools/chrome-devtools - menu item animation looks bad

### ISSUE THREAD

**Issue by kdzwinel** [google/WebFundamentals#2843]
Each animation is preceded with a short blink that looks like a glitch. Possibly a MDL issue?

![menu animation](http://i.imgur.com/JI4CBoy.gif)

**Comment by pbakaus** [comment]
Yep, MDL issue. Can't do anything against it, I believe.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
