### ISSUE TITLE
Information about creating a project in the Google Developer Console is outdated again

### ISSUE THREAD

**Issue by marco-c** [google/WebFundamentals#2847]
Now there's `https://console.developers.google.com/` and `https://console.cloud.google.com/`.
I think the instructions now apply to the second.

**Comment by PaulKinlan** [comment]
Gotcha. will sort.

**Comment by petele** [comment]
Not sure where this is referring to. Would you please update?

**Comment by marco-c** [comment]
There's some history in https://github.com/mozilla/wp-web-push/issues/315.
