### ISSUE TITLE
Memory Profiling Resources example links

### ISSUE THREAD

**Issue by amio** [google/WebFundamentals#2851]
https://developers.google.com/web/tools/chrome-devtools/profile/memory-problems/memory-diagnosis?hl=en

> Example 1: Growing memory
Example 2: Garbage collection in action
Example 3: Scattered objects
Example 4: Detached nodes
Example 5: Memory and hidden classes
Example 6: Leaking DOM nodes
Example 7: Eval is evil (almost always)
Example 8: Recording heap allocations
Example 9: DOM leaks bigger than expected
Example 10: Retaining path

These examples still link to legacy dev-tool repo source code, such as [Example 1](https://github.com/GoogleChrome/devtools-docs/blob/master/docs/demos/memory/example1.html), is it meant to be like this? Or it should link to a webpage instead of source code?

**Comment by kaycebasques** [comment]
Hey @amio, I've been updating all of the DevTools docs this quarter. This is on my radar but I may not be able to get to it in the next couple of weeks.

**Comment by amio** [comment]
Thanks @kaycebasques

**Comment by kaycebasques** [comment]
hey @amio I dropped all of those links when I updated that doc last week (or was it the week before...?)

**Comment by amio** [comment]
Hi @kaycebasques , these examples could be really useful when learning debugging I think, why do you drop these links? Is it be moved to somewhere else?
