### ISSUE TITLE
[EN] Feedback for: http://www.html5rocks.com/en/tutorials/indexeddb/todo/

### ISSUE THREAD

**Issue by luxlux** [google/WebFundamentals#2858]
This page 
**http://www.html5rocks.com/en/tutorials/indexeddb/todo/**
does not work, but it is linked i.e. from here: 
**https://developer.chrome.com/apps/app_storage**

I have found it only in internet archive:
**https://web.archive.org/web/20150217065724/http://www.html5rocks.com/en/tutorials/indexeddb/todo/**

**Comment by oguzzkilic** [comment]
broken link => [](http://www.html5rocks.com/en/tutorials/indexeddb/todo/)
working link => [](http://www.html5rocks.com/en/tutorials/webdatabase/todo/
)

I'm reported a content bug. Thanks @luxlux

**Comment by petele** [comment]
Please file issues for HTML5Rocks at https://github.com/html5rocks/www.html5rocks.com
