### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/04/keyboardevent-keys-codes?hl=en

### ISSUE THREAD

**Issue by bunsen32** [google/WebFundamentals#2863]
Scrolling is woefully broken!

I can’t scroll down using mouse wheel, scroll bar, or arrow keys. (A little globe icon shoots up and down the screen, but the content does not move.)

I’m using Safari on OS X. (But really: scrolling! It’s pretty basic. It’s the last thing that you should break, presumably for cosmetic reasons.)

**Comment by Garbee** [comment]
Can you please provide your OS X version and Safari version?

These issues come up from time-to-time due to how the library we are currently using for layout handles things to align with MD spec.

**Comment by bunsen32** [comment]
OS X 10.11.4
Safari Version 9.1 (11601.5.17.1)

**Comment by bethge** [comment]
Confirming this issue. The site is not usable on Safari 9.1. And the same holds for Safari Technology Preview Version 9.1.1 (11601.6.17, 11602.1.31).

It appears to be for all sites under https://developers.google.com/web/tools/ .

**Comment by Garbee** [comment]
Probably an MDL bug with the way our layout system works there...

I'm unable to debug this specifically since I don't have Safari access. Working on getting someone who does to take a look.

**Comment by PaulKinlan** [comment]
@sgomes @petele please sort asap, this is getting beyond a joke now.  I know we are planning to migrate back into devsite soon but right now we need to get this fixed, people can't use our site.

**Comment by sgomes** [comment]
This is not an MDL issue, as it only affects Web Fundamentals. WF seems to be modifying page and MDL layout styles, and is triggering a Safari bug. Workaround on #3118.
