### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by keeferTS** [google/WebFundamentals#2864]
It was better when I was able to see the size of a webpage when sizing down a window.

You removed this with the last update.

Now I can only see the screen size when I am selecting the <body> tag and resizing the screen, HOWEVER, on many sites this technique does not work and it makes my life a lot harder. Just put that feature back please.

Thanks.

**Comment by kaycebasques** [comment]
Hi,

This repo is for the DevTools docs. Please report DevTools feature requests and issues to [crbug.com](crbug.com).

P.S. this was a bug and has been fixed. See [issue 582421](https://bugs.chromium.org/p/chromium/issues/detail?id=582421).
