### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by raulvictorrosa** [google/WebFundamentals#2865]
It is an basic error that is don't so important but is a detail.
If I set a margin left with a single quotes unintentionally, for example margin-left' = 0. The editor in this particular line stay with bug and I don't got to editor no more, unless that I delete the content from this particular line and retype.
Tanks for listening.

**Comment by kaycebasques** [comment]
Hi,

This repo is for the DevTools docs. Please report DevTools feature requests and issues to [crbug.com](crbug.com).
