### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

### ISSUE THREAD

**Issue by QuinnMatthew** [google/WebFundamentals#2868]
[https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging](url)
![image](https://cloud.githubusercontent.com/assets/1865081/14890102/519b7704-0d2f-11e6-9301-47d60e4f4446.png)

**Comment by petele** [comment]
This should be fixed now. Sorry about that!!
