### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by jacobuid** [google/WebFundamentals#2869]
Bring Back the Toggle Console on the Main top Bar

![image](https://cloud.githubusercontent.com/assets/1899414/14893751/3c319888-0d36-11e6-8256-173ac7c44eb4.png)

Because it has been moved to here:

![image](https://cloud.githubusercontent.com/assets/1899414/14893813/733612dc-0d36-11e6-87c9-fa092c0291ae.png)

We now have to make 2 clicks in order to toggle the "mini" console. this is inefficient and slows development. Please bring it back or atleast let us chose where it goes through a setting. Thank you

**Comment by Garbee** [comment]
This feedback form and issue tracker are only for the documentation provided on https://developers.google.com/web . Please file an issue on the [Chromium Issue Tracker](https://bugs.chromium.org) so the developers can see this request and triage it further.

Thank you.

**Comment by kaycebasques** [comment]
hey @jacobuid you can open the Console drawer at any time by pressing the `Esc` key... You can try logging an issue on this on crbug.com but to be honest I don't think the DevTools team will change this back...

**Comment by jacobuid** [comment]
Well, i had to try. Whatever designer/UI developer that came up with this
should go back to school, Its bad User Experience. I am aware of the "esc"
button shortcut. Ive been using dev tools for 10+ years and this is bar far
the stupidest decision they have made, hey i got an idea, instead of it
being 2 clicks to get it to show, lets make it 3 or for, I mean why not,
nest it down deep and lets cut add about one hour of development time for
every user that has to use this amazing Tool in the hands of what seems
incompetent designers

*Jacob King*
*email*: jacobuid@gmail.com
*cell:* 214-449-3039

**Comment by kaycebasques** [comment]
Actually if you feel very strongly about it go ahead and open a bug! If you
vocalize your opinion and a lot of people agree than they might add it
back! Never know until we try :)

**Comment by jacobuid** [comment]
Cool, yea, i do feel very strongly, when i use the tool, i feel like im
holding one hand behind my back, ill open up a bug and see how far it will
go. Thanks for the advice. :)

*Jacob King*
*email*: jacobuid@gmail.com
*cell:* 214-449-3039
