### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by ricksmt** [google/WebFundamentals#2870]
Could we have Ctrl + W close tabs in the main pane of the Sources tab? It's a bother having to manually close each one, especially since the different file name lengths put the close in different spots. Currently Ctrl + W closes the Developer Tools when viewed as a separate window.

**Comment by Garbee** [comment]
Reference this recent issue in the issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=607564

This feedback form and issue tracker are for the documentation alone. The developers do not look here. In the future you should file feature requests and bug reports directly on the [Chromium Issue Tracker](https://bugs.chromium.org).

**Comment by ricksmt** [comment]
Thanks Jonathan!
