### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/device-mode/?hl=en

### ISSUE THREAD

**Issue by agopaul** [google/WebFundamentals#2893]
The keyboard shortcut for Mac does not work. It actually triggers a view inside Chrome where you can switch Google user.
It's also documented here: https://support.google.com/chrome/answer/157179?hl=en

> ⌘+Shift+M	Switch between multiple users.

It seams that this hotkeys has multiple bindings

**Comment by Garbee** [comment]
Have you tried it with DevTools open? This one specifically only works when DevTools are already open.

**Comment by agopaul** [comment]
Oh I see, you're right, but the DevTools must be docked in the browser window and I was using it in 'floating mode' in the secondary monitor. In that case, the shortcut doesn't work

**Comment by Garbee** [comment]
Maybe that is Mac-specific then... On Linux here un-docked and the shortcut works perfect to toggle Device Mode on and off.

**Comment by kaycebasques** [comment]
Hey @agopaul  you need to be focused on the DevTools window. If you're focused on the viewport, then the shortcut you mentioned gets triggered.

**Comment by kaycebasques** [comment]
I updated the doc to clarify this 👍
