### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-03?hl=en

### ISSUE THREAD

**Issue by soraoka** [google/WebFundamentals#2894]
Initially, this website seemed so promising.  It details a very good architecture for designing a mobile application.  Then, it provides example code that doesn't work (found references to files pointing to wrong directories, calling DOM objects that don't exist, null pointer exceptions, etc).  And has instructions like "Add the following inside the immediately invoked function expression".  What is "immediately invoked function expression"?  Decided to give up reading this site.

**Comment by nelsonic** [comment]
@soraoka what did you search for when trying to understand this?
there's a good explanation here: http://stackoverflow.com/questions/8228281/what-is-the-function-construct-in-javascript

**Comment by petele** [comment]
Sorry you didn't find it helpful :(
