### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-02?hl=en Firebase Weather API Deprecated 

### ISSUE THREAD

**Issue by nelsonic** [google/WebFundamentals#2896]
While going through @petele's Weather Forecast app tutorial: https://developers.google.com/web/fundamentals/getting-started/your-first-progressive-web-app/step-02 [code](https://github.com/google/WebFundamentals/blob/master/src/content/en/fundamentals/getting-started/your-first-progressive-web-app/step-02.markdown) we noted that it's *meant* to use [***Firebase Public Weather API***](https://github.com/google/WebFundamentals/blob/master/src/content/en/fundamentals/getting-started/your-first-progressive-web-app/step-02.markdown#add-the-key-javascript-bootstrap-code):
![pwa-weather-app-requires-firebase-weather-api-deprecated](https://cloud.githubusercontent.com/assets/194400/15094094/0ea0e30c-1492-11e6-81c5-6b75d6ff7607.png)
Sadly, the "_Firebase Open Data Sets are [**deprecated**](https://www.firebase.com/docs/open-data/weather.html) and will be **shut down** on **March 30th, 2016**._"
![firebase-open-datasets-depracated](https://cloud.githubusercontent.com/assets/194400/15094113/66a44242-1492-11e6-96a7-8f8dfc66d256.png)

Also, the [link](https://github.com/google/WebFundamentals/issues/2550) to "**Try it**" at the end of Step 2:
![pwa-weather-app-try-it-404](https://cloud.githubusercontent.com/assets/194400/15094134/de35691c-1492-11e6-9639-296e98d39cc9.png)

![weather-pwa-sample-404](https://cloud.githubusercontent.com/assets/194400/15094139/1a9ffaac-1493-11e6-82ab-9ef56698572f.png)

Why?!

**Comment by nelsonic** [comment]
Firebase API still works ... but data is a Snapshot from 31st March 2016 (*the day they discontinued the API*)
![pwa-weather-demo-step-04](https://cloud.githubusercontent.com/assets/194400/15094655/06567e26-14a3-11e6-865a-1ae55a325f75.png)

**Comment by petele** [comment]
Will fix in the DevSite update coming in the next two weeks. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/
