### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en

### ISSUE THREAD

**Issue by leggsimon** [google/WebFundamentals#2898]
Minor one and not sure if intended, but the table lines only appear once you've hovered over the table.

Version 50.0.2661.94 (64-bit)

**Comment by kaycebasques** [comment]
Thanks @leggsimon I've seen that too. It bugs me so much but unfortunately it's a bug in the site ( issue #2134 ) that can't be easily fixed :(
