### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by pwacher** [google/WebFundamentals#2905]
I'm currently using Chrome Version 50.0.2661.94 (64-bit) - Mac and noticed when using the Network tab in dev tools, there is noticeable lag clicking between entries in the list. I have not had this issue previous to this version.

I have added a screen capture to illustrate the issue.

[devtools_slow.zip](https://github.com/google/WebFundamentals/files/258417/devtools_slow.zip)

**Comment by Garbee** [comment]
Please submit a bug report in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.

Thank You.
