### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/03/notifications?hl=en

### ISSUE THREAD

**Issue by roylkng** [google/WebFundamentals#2907]
https://developers.google.com/web/updates link is not working.
No detailed documentation for payload is present. There are so many grey areas left uncovered in the current documentation. Event the module for nodejs  https://github.com/GoogleChrome/web-push-encryption is not having the proper documentation about payload or the types of notification.

**Comment by petele** [comment]
We've updated the developer docs for push at https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/
