### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by xml** [google/WebFundamentals#2919]
Hi! DevTools are awesome. Thank you!

With many in the community (particularly with React) investing more and more effort in inline styling, there's a point of friction that appears: **the elements view looks _terrible_ with all the inline styles appended to the elements**. It would be super-handy if there were a setting that allowed you to suppress the styles information, and to see it only in the Styles pane.

Is it possible to do this with a theme? Could they be suppressed there? It doesn't look like it, based on my initial research...

**Comment by Garbee** [comment]
Please submit feature requests in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.

Thank you.
