### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-02?hl=en

### ISSUE THREAD

**Issue by ChrisDM1** [google/WebFundamentals#2926]
Hi, Mine just gets the header and the spinning circle. this occurs when I test the final version of the code, when I use the first few steps and when I press the try it button at the bottom of the implement the shell page. I am running version 50 of chrome. Anyone else getting this problem??

Thanks,
Chris

**Comment by petele** [comment]
Will fix in the DevSite update coming in the next two weeks. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/
