### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-02?hl=en

### ISSUE THREAD

**Issue by HugoPHAM** [google/WebFundamentals#2930]
Seems the link : https://weather-pwa-sample.firebaseapp.com/step-04/ does not work.

**Comment by Garbee** [comment]
@petele Quite a few reports in the tracker about this one. Last time I looked into it:

```js
  // Uncomment the line below to test with the provided fake data
  // app.updateForecastCard(fakeForecast);
```

At the bottom of the `app.js` file needs updating. Uncomment the `app.updateFOrcastCard` for it to load properly. Looks like the demo on firebase needs updating, not sure how that is handled. Can you see about getting it done please?

**Comment by petele** [comment]
I think this was fixed. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/
