### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by creage** [google/WebFundamentals#2935]
Having some long parameter in the POST requests makes viewing of the request headers (Network tab) VERY, I MEAN VERY slow.

Here is an example HAR file.

[db01.lmdom.local.har.zip](https://github.com/google/WebFundamentals/files/281362/db01.lmdom.local.har.zip)

I assume Chrome tries to "parse" it somehow while making a pretty view of the parameter, which takes long time.

**Comment by Garbee** [comment]
Please submit bug reports in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.

Thank you.
