### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by richimuchacho** [google/WebFundamentals#2936]
I love Chrome DevTools, but sometimes the display becomes a bit messy with so many panels and sections inside of them.

Wouldn't it be great if it'd allow to place and view the DevTools Panels as Tabs in the main Chrome Window?

Just a suggestion ;)

**Comment by Garbee** [comment]
You can undock the DevTools by pressing the overflow menu and selecting the "undock" option (one of the three layout icons at the top.)

That is about as close as you're going to get.
