### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-02?hl=en

### ISSUE THREAD

**Issue by ncouture** [google/WebFundamentals#2942]
I guess we can unzip -l before unzipping but it would be nice if the pwa-weather.zip archive would extract its content in a self-contained folder.

https://web-central.appspot.com/web/fundamentals/getting-started/your-first-progressive-web-app/pwa-weather.zip

**Comment by petele** [comment]
Will fix in the DevSite update coming in the next two weeks. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/
