### ISSUE TITLE
TTT Progressive Web App videos on /web

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#2943]
The [first set of videos](https://www.youtube.com/playlist?list=PLNYkxOF6rcIB3ci6nwNyLYNU6RDOU3YyL) for this season of TTT cover PWAs (manifest, offline, appshell, push and so on). I was wondering if this was content you felt would be valuable to include somewhere over on https://developers.google.com/web/progressive-web-apps/ in our official guidance.

I would understand if not, but one suggestion is we could expand the items in this section below to include an `Article | Video` type split so folks have an option on whether they want to see a quick overview video:

![](http://i.imgur.com/HFok5Ms.png)

If you decide to include these somewhere, the links to the videos are:

* [Web App Manifest](https://www.youtube.com/watch?v=yQhFmPExcbs&index=1&list=PLNYkxOF6rcIB3ci6nwNyLYNU6RDOU3YyL)
* [Offline support](https://www.youtube.com/watch?v=OBfLvqA_E4A&index=4&list=PLNYkxOF6rcIB3ci6nwNyLYNU6RDOU3YyL)
* [Push Notifications](https://www.youtube.com/watch?v=Sftbg45nQcQ&index=2&list=PLNYkxOF6rcIB3ci6nwNyLYNU6RDOU3YyL)
* [Instant loading with Application Shell](https://www.youtube.com/watch?v=QhUzmR8eZAo&index=3&list=PLNYkxOF6rcIB3ci6nwNyLYNU6RDOU3YyL)

we'll have a high-level PWA overview video coming out sometime soon too.

cc @petele @PaulKinlan, @gauntface as an fyi.

**Comment by petele** [comment]
Totally refactoring this page.
