### ISSUE TITLE
Scrolling broken in safari - developers.google.com/web/tools/*

### ISSUE THREAD

**Issue by ricardobeat** [google/WebFundamentals#2949]
Safari Version 9.1.1 (11601.6.17), OSX 10.11.5

![scroll-broken](https://cloud.githubusercontent.com/assets/97396/15748564/afcc160a-28df-11e6-9d0f-89393b2e60b3.gif)

![scroll-broken2](https://cloud.githubusercontent.com/assets/97396/15748716/302bbec2-28e0-11e6-965c-5cb573623153.gif)

**Comment by ricardobeat** [comment]
Hello, anyone there? This is still happening across all developer pages.

**Comment by PaulKinlan** [comment]
@sgomes @petele please sort asap, this is getting beyond a joke now.  I know we are planning to migrate back into devsite soon but right now we need to get this fixed, people can't use our site.

**Comment by sgomes** [comment]
@PaulKinlan Safari bug. I'll keep looking into this, but I'm not sure there's much that can be done. 

Safari is incorrectly deciding what to repaint. The content is scrolling (which you can check by looking at the position of things with dev tools), but the screen isn't getting updated. Promoting layers seems to have no effect on this, and I'm struggling to find any workarounds.

**Comment by sgomes** [comment]
Alright, investigation done. This is not an MDL issue, as it only seems to affect Web Fundamentals.

WF seems to be modifying page and MDL layout styles, and is triggering a Safari bug. Workaround on #3118.

**Comment by petele** [comment]
This should be fixed now. Sorry about that!!
