### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by oozj** [google/WebFundamentals#2950]
Can you develop a Chinese version? Open or import a language pack features, I can make the personal import language packs to the developer tools. This is not perfect it? The debugging tool is very powerful. But you have not thought of, in China or other countries, there are many beginners? They need to use their own language to adapt slowly.
The author hopes to develop this tool can be considered under!
We are expecting a reply!
If you have an existing implementation, please tell me, thank you!

**Comment by oozj** [comment]
I can help you convert Chinese Language

**Comment by Garbee** [comment]
Please submit feature requests in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.
