### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by Joelsz** [google/WebFundamentals#2951]
ctrl+z does not work when modifying anything in the 'Elements' panel in chrome dev tools. Chrome Version 50.0.2661.102 m (64-bit)

**Comment by Garbee** [comment]
Please submit bug reports in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.

**Comment by Joelsz** [comment]
Thanks for clarifying.
