### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/performance/?hl=en

### ISSUE THREAD

**Issue by santoshkumarjena** [google/WebFundamentals#2953]
There should be a close button on the below screen

![pagespeed](https://cloud.githubusercontent.com/assets/13331071/15769836/580f8e68-297c-11e6-97ac-96eeb1e65e81.png)

**Comment by Garbee** [comment]
@PaulKinlan Looks like someone should reach out to the internal developers of this site and have them address the dialog UX on small viewports. Know anyone to do that?

**Comment by PaulKinlan** [comment]
It is just using Page Speed Insights under the hood.  I will check.
