### ISSUE TITLE
[EN] Feedback for: /web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en

### ISSUE THREAD

**Issue by jyasskin** [google/WebFundamentals#2954]
Linking directly to https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en#user-gesture-required doesn't scroll to the right place on the page.

**Comment by Garbee** [comment]
Duplicate of #2253

**Comment by PaulKinlan** [comment]
@sgomes @petele please sort asap, this is getting beyond a joke now.  I know we are planning to migrate back into devsite soon but right now we need to get this fixed, people can't use our site.

**Comment by sgomes** [comment]
This is not an MDL issue, as it only affects Web Fundamentals. WF seems to be modifying page and MDL layout styles, and is triggering a Safari bug. Workaround on #3118.

**Comment by jyasskin** [comment]
I'm using Chrome.

**Comment by sgomes** [comment]
Bad dupe, sorry. The follow up to this is on #2291.
