### ISSUE TITLE
Doc request: Record Allocation Profile

### ISSUE THREAD

**Issue by mnater** [google/WebFundamentals#2957]
Please add some documentation about "Record Allocation Profile" (the new forth profiling type).

**Comment by kaycebasques** [comment]
Hey @mnater what are you trying to profile? Just curious, as this information would help me understand what I need to document.

**Comment by petele** [comment]
[EN] Feedback for: /web/tools/chrome-devtools/profile/memory-problems/?hl=en

**Comment by moos** [comment]
This page is out of date: https://developers.google.com/web/tools/chrome-devtools/profile/memory-problems/allocation-profiler?hl=en

Missing info on the last item:
<img width="682" alt="screen shot 2016-09-24 at 1 15 32 am" src="https://cloud.githubusercontent.com/assets/233047/18807130/8124c59a-81f4-11e6-8963-96acde74d1b2.png">

Chrome 53.
