### ISSUE TITLE
[EN] Feedback for: https://testmysite.thinkwithgoogle.com/

### ISSUE THREAD

**Issue by samanthabollmann** [google/WebFundamentals#2958]
I was testing different websites on Google's Test My Site Tool after I noticed that most companies were receiving about the same score for mobile friendliness despite clear differences in the quality of said sites' mobile usability.  One of the sites I looked at was Shoprite.com.  When I selected "View the Details", I saw that one of the features that sites are graded on is "Avoid app install interstitials that hide content"; however, the very first page of shoprite.com is an app install interstitial that hides content.  Please see the pictures below. The red circles were my additions. 

![shoprite1](https://cloud.githubusercontent.com/assets/19779644/15825251/0910c348-2bd1-11e6-8457-fb5416b5b1c6.png)

![shoprite2](https://cloud.githubusercontent.com/assets/19779644/15825261/0dd37132-2bd1-11e6-89b1-7d33e4bd15e8.png)

**Comment by Garbee** [comment]
The heuristics here is still a bit tricky. However, the "thinkwithgoogle" site is not a part of this project or team, so there isn't anything we can do about it internally.
