### ISSUE TITLE
[EN] Feedback for: /web/tools/starter-kit/?hl=en

### ISSUE THREAD

**Issue by saishyamvinjamuri** [google/WebFundamentals#2970]
I have a suggestion to add one more feature to chrome browser, not sure if you guys are already implementing it. Am finding a way to reach chrome browser dev team. Can someone who see this message cascade this to development team.

**Comment by Garbee** [comment]
Please submit feature requests in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.

**Comment by Garbee** [comment]
Just do the best you can to explain the request within the confines of what the issue tracker provides.

**Comment by saishyamvinjamuri** [comment]
Greetings Jonathan -

I have tried my best in depicting my idea. Please let me know if am not
clear at any point.

Have a great weekend ahead. Am attaching a word file, which gives a
pictorial description of the feature.
Thank you.

- Shyam Vinjamuri


[image: https://www.linkedin.com/pub/sai-shyam-vinjamuri/106/86/87a]
<https://www.linkedin.com/pub/sai-shyam-vinjamuri/106/86/87a>

**Comment by Garbee** [comment]
Do it *in the issue tracker* please. This isn't the proper place for that kind of discussion.

**Comment by saishyamvinjamuri** [comment]
Greetings Jonathan -

I believe you must be having a great time.

I would like to know if you had got a chance to review my idea of new
feature. I was just anxious to know the feedback about my idea.
If at all, if there are any comments or suggestions from your side - it
would help to more enhance the root idea of "Categorizer".

Will be waiting to hear from you. Thank you.
Have a great weekend ahead.

- Shyam Vinjamuri


[image: https://www.linkedin.com/pub/sai-shyam-vinjamuri/106/86/87a]
<https://www.linkedin.com/pub/sai-shyam-vinjamuri/106/86/87a>

**Comment by Garbee** [comment]
Can you please link to the Chromium Issue where you filed the request?

**Comment by saishyamvinjamuri** [comment]
Is this closed since its implementation is underway or otherwise ?
Just curious .. !!

**Comment by Garbee** [comment]
It is closed since this isn't the proper forum for this request. The team working on the code does not look here for work. Please provide a report in the [Chromium Issue Tracker](https://crbug.com/new) for them to assess the request and get back to you.

Thank you.
