### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/06/devtools-digest?hl=en

### ISSUE THREAD

**Issue by undoware** [google/WebFundamentals#2980]
![image](https://cloud.githubusercontent.com/assets/315987/15980653/2003dd8e-2f22-11e6-88f2-8ab731fd3852.png)

**Comment by jpmedley** [comment]
What, exactly, are you trying to tell us?

**Comment by undoware** [comment]
That 'Progressive Web Aps' is missing a 'p': You really want 'Progressive
Web Apps":

Is this really something that needs elucidation? You spell it right
literally in the next sentence.


[image: Inline images 1]
