### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/06/devtools-digest?hl=en

### ISSUE THREAD

**Issue by jchorl** [google/WebFundamentals#2981]
4K is not actually 2560px. 4K is 3840x2160.

Actual result:
The desktop story has improved, too. Thanks to Device Mode’s zoom feature, you can emulate desktop screens larger than the screen that you’re actually working on, such as a 4K (2560px) screen.

Expected result:
The desktop story has improved, too. Thanks to Device Mode’s zoom feature, you can emulate desktop screens larger than the screen that you’re actually working on, such as a 4K (3840px x 2160px) screen.

**Comment by kaycebasques** [comment]
Thanks @jchorl. I've fixed it in one of my branches.
