### ISSUE TITLE
[EN] Bug in Chrome Developer Tools

### ISSUE THREAD

**Issue by kshitijb** [google/WebFundamentals#2984]
I've been observing _device scale issues_ with Nexus devices in Device Emulator specifically with Nexus 6P and Nexus 5X. On switching devices, the viewport shows zoomed in view of the layout even when `initial-scale=1` is set in `<meta>`.
The problem persists even after refreshing (soft and hard) the page. The only way I could go around this is by manually changing `initial-scale` values from the `Elements Inspector` in the **Chrome Dev Tools**.

Check the screen shot below.
![image](https://cloud.githubusercontent.com/assets/4145434/15985794/6b97e73c-3016-11e6-9dcc-686b96748b30.png)

You can clearly see that the `initial-scale=1`, yet Nexus 6P viewport is zoomed in.

**Edit** - Turns out, the bug is occurring for other devices too.

**Comment by datboigetmoe** [comment]
what does this mean?????

**Comment by Garbee** [comment]
Please bug reports in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.

Thank you.

**Comment by kshitijb** [comment]
Cool. I'll do that.
