### ISSUE TITLE
[EN]  Page fails to scroll on Safari 9.11.1 (Mac OS 10.11.5)

### ISSUE THREAD

**Issue by alunny** [google/WebFundamentals#2985]
Feedback for: /web/fundamentals/performance/?hl=en

Works in Chrome and Firefox. On Safari, only the rightmost column scrolls, not the content.

**Comment by PaulKinlan** [comment]
@sgomes @petele please sort asap, this is getting beyond a joke now.  I know we are planning to migrate back into devsite soon but right now we need to get this fixed, people can't use our site.

**Comment by sgomes** [comment]
This is not an MDL issue, as it only affects Web Fundamentals. WF seems to be modifying page and MDL layout styles, and is triggering a Safari bug. Workaround on #3118.

**Comment by petele** [comment]
This should be fixed now. Sorry about that!!
