### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/push-notifications/step-06?hl=en

### ISSUE THREAD

**Issue by whiteswift** [google/WebFundamentals#2988]
Hey!

Where you tell the user to copy the subscription IDs - be careful! 

Chrome converts periods to be ellipses in console output, which means the subscription ID becomes corrupted.

Copying and pasting this will be a problem later on in the guide because of this.

Darryl

**Comment by petele** [comment]
Merging into #3445
