### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en

### ISSUE THREAD

**Issue by djzoning** [google/WebFundamentals#2989]
Hello!

On [_this page_](https://developers.google.com/web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en) In the Global keyboard shortcuts table, if you search for "Show General Settings dialog" you will find that it appears two times. It is duplicated and it is the same!

Best Regards,
Mihail Ivanov

**Comment by kaycebasques** [comment]
Thanks @djzoning I've got a fix in one of my branches
