### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/push-notifications/step-09?hl=en

### ISSUE THREAD

**Issue by bjm-jwiegand** [google/WebFundamentals#2994]
Notifications will not show.

The showNotification promise fails with the following error:

Uncaught (in promise) undefined

![image](https://cloud.githubusercontent.com/assets/19916228/16025856/b2e9c31a-318f-11e6-87b6-3eef3338e424.png)

**Comment by petele** [comment]
Merging into #3445
