### ISSUE TITLE
[EN] Feedback for: /web/tools/setup/setup-workflow?hl=en

### ISSUE THREAD

**Issue by lucasmaj** [google/WebFundamentals#2997]
Hello
It seems that unless File System Resource and Network Resource have absolute the same name, the mapping "will not hold". For example query string params in network resource wont allow it to be mapped to file resource. Trying to map site.css?v=1.1 to any network resource and I can't get it mapped whatever I try.

Any ideas?

Thanks,
Lucas

**Comment by Garbee** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=277885

Upstream bug for this exists, known issue. Please *star* that issue to show it is affecting you as well so the team knows what tasks to focus on. By doing that you'll also receive email updates as work happens.

![star_location](https://cloud.githubusercontent.com/assets/868301/16059842/d806be96-3252-11e6-8a4b-15522125a509.png)

**Comment by lucasmaj** [comment]
Did as instructed. Thanks
