### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by deestudio** [google/WebFundamentals#3001]
谷歌浏览器开发者模式下面，模拟手机浏览后，我的居然看不到鼠标那个黑色的小圈圈，其他电脑都正常。请问这个是怎么回事呢？
Under the Google browser developer mode, simulation mobile browsing, I can't even see the mouse black ringlets, other computers are normal. May I ask how this is going on?

**Comment by Garbee** [comment]
Please submit bug reports in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here. Once it is filed upstream with the appropriate information we can triage the issue further.

Thank you.
