### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/breakpoints/add-breakpoints?hl=en

### ISSUE THREAD

**Issue by suryateja619** [google/WebFundamentals#3017]
Here is my html file:
`<select id="drop-down">
  <option value="1" title="East">East</option>
  <option value="1" title="West">West</option>
  <option value="0" title="North">North</option>
  <option value="1" title="South">South</option>
 </select>`

In my JavaScript code:
`$("#drop-down option:selected").text();
console.log("It doesn't stop in here");`

If you have a breakpoint in chrome on this line `$("#drop-down option:selected").text();` and step over using F10, it rushes through the rest of the lines instead of stopping the execution on the next line.

Here is the working sample of this [fiddle](https://jsfiddle.net/37ayo94y/).

**Comment by kaycebasques** [comment]
Hey @suryateja619 

For some reason, when I open up that fiddle, the code is wrapped in an `onload` listener. Which would explain why that breakpoint isn't getting triggered. Are you seeing the same thing?

<img width="479" alt="screen shot 2016-06-27 at 9 08 07 am" src="https://cloud.githubusercontent.com/assets/4713486/16386823/fd56600e-3c46-11e6-8458-36aa606ec752.png">

**Comment by suryateja619** [comment]
Hey @kaycebasques 

It's not about the breakpoint being triggered at that point. If you have a breakpoint on line no 50 in the image you posted and step over(F10) then it would need to stop on line 51 but instead it rushes through rest of the code.

**Comment by kaycebasques** [comment]
Hey @suryateja619 I'll check again but I'm pretty sure that DevTools properly stopped on line 51 when I tried it thirty minutes ago, but I'll check again.

**Comment by suryateja619** [comment]
@kaycebasques It stops on IE but not in chrome.

**Comment by Garbee** [comment]
Please submit bug reports in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here. Once it is filed in the issue tracker with the appropriate information we can help triage further.

Thank you.

**Comment by suryateja619** [comment]
@Garbee Thanks, Garbee. Logged the issue in [Chromium issue tracker](https://bugs.chromium.org/p/angleproject/issues/detail?id=1440).

**Comment by Garbee** [comment]
@suryateja619 Check the issue, wrong tracker component. Sorry about that, updating my link now to be more direct.

**Comment by suryateja619** [comment]
@Garbee My bad. Updated the link with the correct component.
