### ISSUE TITLE
[EN] Feedback for: chrome://flags

### ISSUE THREAD

**Issue by Oxmaster** [google/WebFundamentals#3027]
I'd really like to see updated flags page where you can sort by multiple values, like: date added, last update, platform, touch etc. Current list is very chaotic. If that would take a lot of work or any other reason why not to do this, just add date of last update and date of release next to available platforms label.

**Comment by PaulKinlan** [comment]
That's not a bad idea.

**Comment by kaycebasques** [comment]
Good idea @Oxmaster! I forwarded your request: https://bugs.chromium.org/p/chromium/issues/detail?id=629936
