### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/performance/?hl=en

### ISSUE THREAD

**Issue by shannoncox** [google/WebFundamentals#3034]
I really wish you would do the designers and developers around the world a favor and not push the sites you have at the following location:\
https://testmysite.thinkwithgoogle.com/solutions

Killing the freelance design business and creativity!

**Comment by PaulKinlan** [comment]
Lots of people just want to get a site up and running as quickly as possible that works in as many places as possible.  If they start to succeed after using one of these tools then they are more likely to extend into a custom solution that employs people and agencies etc.
