### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by Quikchek** [google/WebFundamentals#3040]
Your Devtools window pops up when one of our users scans a barcode through their scanner. The scanner sends in a tilde barcode tilde when a user scans. Example ~1234~. Our users are health clubs, hospitals, and wellness centers. How can we prevent the Devtools popup from appearing every time a member scans at the facility. The front desk employees panic as if something went wrong. There should just be an option in the Chrome Settings panel to turn that feature off. Can you provide any help with this ongoing issue?
John Becker
Director of Development 
Coral Springs Software

**Comment by PaulKinlan** [comment]
I would raise an issue on https://crbug.com/new, it sounds like an issue with Chrome.
