### ISSUE TITLE
The pain of maintaining a polymer app

### ISSUE THREAD

**Issue by sebs** [google/WebFundamentals#3044]
Some things I found while building on starter kit

* bower with its "questions" really raises the question if components still work. 
* the community is not so fast. Maybe a little more tooling would help. 
* starter kit takes all the elements, maybe introduce users to a little more choices. Selecting and installing just a part of the components is not so common. The general polymer world has some x megabyte repos in terms of dependencies for one element. Is that necessary, or just a result of development docs saying so?  
* starter kit installs the test toolchain multiple times. that takes time 
* To upgrade a old application the best way seems to reinstall all modules via bower. Using the offcial bower repo was my choice! Not using the direct git urls anymore. 

I came from pre 1.0 and now is 1.6.0. Updating takes a lot of effort. I know a lot of these issues are with 3rd party modules. But maybe have a closer look at some elements that are reularly used and re-used and maybe support these a little more. Maybe a kind of validator and wizard can help generate the right pull requests for these. Online and connected to github. 

In a nutshell. 

Please, 

* make starter kit a little leaner and teach users to build small
* help upgrades with even more tooling. Non Module authors must be able to shortcircuit a dead component a little better. 
* try reduce the pain form quirky bower installs please

**Comment by robdodson** [comment]
Moved to https://github.com/PolymerElements/polymer-starter-kit/issues/858
