### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/rendering-tools/forced-synchronous-layouts?hl=en

### ISSUE THREAD

**Issue by proles** [google/WebFundamentals#3045]
Typo present in the callout to the PWA Dev Summit Sessions.

Currently read: availble
Should read: available

Issue is present throughout site wherever the callout is included.

Example:
https://developers.google.com/web/tools/chrome-devtools/

![pwa-dev-summit-callout-typo](https://cloud.githubusercontent.com/assets/787171/16529422/ac4de9c8-3f77-11e6-9531-ea9cfde6b00e.png)

**Comment by kaycebasques** [comment]
good eye @proles thank you for the bug submission
