### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/06/persistent-storage?hl=en

### ISSUE THREAD

**Issue by sirjamesgray** [google/WebFundamentals#3046]
please make the links open in new tabs. 

See: ![screen shot 2016-07-01 at 6 09 06 pm](https://cloud.githubusercontent.com/assets/16139439/16536432/fae21944-3fb6-11e6-8d7d-6b38dbd28ea7.jpg)

**Comment by PaulKinlan** [comment]
We have traditionally left this to the discretion of the user.  Once we force new tabs then it does it for everyone which annoys more people than letting the user middle click etc.
