### ISSUE TITLE
[EN] Feedback for: /web/updates/devtools/?hl=en - Copy and paste class names

### ISSUE THREAD

**Issue by ico3iain** [google/WebFundamentals#3052]
Hello, when copying a class name from the inspector (styles) tab it now breaks the copy and paste to two lines not one as it used too - one line is very very handy, two a bit of a pain!

Thanks
Iain

![issue](https://cloud.githubusercontent.com/assets/4487392/16578564/1a721d8e-4293-11e6-9e44-261150786b52.jpg)

**Comment by Garbee** [comment]
Please submit feature requests and/or bug reports in the [Chromium issue tracker](https://bugs.chromium.org). This tracker is for the documentation only and the team that works on the software itself does not look here.

Thank you.

**Comment by kaycebasques** [comment]
FYI @ico3iain I can't repro that behavior... if you're still seeing it please post a bug on crbug.com...

**Comment by ico3iain** [comment]
Hello yes it looks like it is fixed now! :)
