### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en

### ISSUE THREAD

**Issue by SPConrad** [google/WebFundamentals#3059]
It would be very helpful if I could zoom in on the FPS graph, it's not even an inch tall on my screen which makes it rather difficult to read. And to clarify by zoom I do not mean change the amount of time I am inspecting, I mean make the FPS bar larger. 

Apologies if this is the wrong place.

**Comment by kaycebasques** [comment]
Hey @SPConrad this repo just tracks feedback and bugs for the docs... but I forwarded your request! 

https://bugs.chromium.org/p/chromium/issues/detail?id=629930#
