### ISSUE TITLE
Line numbers in the code make this hard to copy and paste : /web/fundamentals/engage-and-retain/push-notifications/permissions-subscriptions?hl=en

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3060]
It is really hard to copy and past the code from this page.

**Comment by jpmedley** [comment]
It can't be helped because there's no way to highlight lines in code samples (none that I know of). We can revisit this after the devsite conversion.

**Comment by petele** [comment]
This'll go away with DevSite.
