### ISSUE TITLE
It's impossible to navigate other articles in this section. [EN] Feedback for: /web/fundamentals/engage-and-retain/push-notifications/?hl=en

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3069]
Once I am in an information page it is nearly impossible to tell where I should go next or go to another section.

Would love to see the TOC more visible so I can navigate.

**Comment by jpmedley** [comment]
If I'm understanding this, it's not particular to push-notifications.

**Comment by petele** [comment]
Fixed with DevSite
