### ISSUE TITLE
The relationship between the servers need to be visualised. [EN] Feedback for: /web/fundamentals/engage-and-retain/push-notifications/sending-messages?hl=en

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3070]
> It's easy to assume that sending messages must involve building a complex messaging system on the server. That's not quite right. There are actually two servers involved in sending a message: your ? server and a third party messaging server. You keep track of two things: recipients and recipient- specific endpoints on the messaging server. The messaging server handles the routing.

This gets to my previous issue, the flow is not visualised anywhere and it is critical that we have that shown because there are a lot of actors in this dance.

**Comment by petele** [comment]
Fixed with DevSite, if not, please reopen and provide suggestions for fixing.
