### ISSUE TITLE
Combine similar notifications mentions three parts of the API without explaining them [EN] Feedback for: /web/fundamentals/engage-and-retain/push-notifications/handling-messages?hl=en

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3071]
The interplay between all three API's is pretty convoluted and I had to work out why it was done this way. I think this needs to be exaplined up front, but also that the APIs `tag`, `getNotifications` etc need to be explained about what they do first and then why they are being used this way.

**Comment by petele** [comment]
I believe Joe has addressed.
