### ISSUE TITLE
Update links in /web/tools/setup/setup-preprocessors

### ISSUE THREAD

**Issue by cvrebert** [google/WebFundamentals#3077]
The Autoprefixer link (https://github.com/ai/autoprefixer#source-map ) is broken.
There's no longer a #source-map on that page.
(Also, the repo has been moved to https://github.com/postcss/autoprefixer )

**Comment by vitorinoaraujo** [comment]
Hey @cvrebert , it seems someone fixed this! At least it works for me... the https://github.com/ai/autoprefixer URL now returns a 301 Status Code (Moved Permanently) and in the response header the location sent is https://github.com/postcss/autoprefixer so it seems that everything is as it was supposed to be right ?

**Comment by cvrebert** [comment]
The fragment ID is still broken. Also, might as well update the URL to bypass the redirect.
