### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-02?hl=en

### ISSUE THREAD

**Issue by Valmach** [google/WebFundamentals#3083]
Just wondering.. Is PWA an additional framework designed to alter an existing native mobile app, or an additional framework to turn an existing website into a PWA, or is it a stand-alone framework to build /create from scratch web-app for Android phones.. Which one Is it...  and where to find the step-by-step video tutorials..

**Comment by petele** [comment]
Check out https://udacity.com/ud811
