### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/breakpoints/add-breakpoints?hl=en

### ISSUE THREAD

**Issue by metafive** [google/WebFundamentals#3084]
Why do you show images with line numbers for the code when the Elements panel in DevTools for Chrome no longer shows them?  That is a pretty blatant mismatch between the official documentation and the respective tool.

**Comment by kaycebasques** [comment]
@metafive my job keeping all of the devtools docs up-to-date roughly looks like this:

![herding cats gif](https://cloud.githubusercontent.com/assets/4713486/16999850/e6985ad0-4e74-11e6-8639-9ebaaf417a9f.gif)

;)

Doc has been updated as of PR #3123
