### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-07?hl=en

### ISSUE THREAD

**Issue by zuDevonRW** [google/WebFundamentals#3095]
Src for two images under **Declare an app manifest with a manifest.json file** have incorrect paths

the 192x192 and 256x256 icons have a src as "images/touch" whereas they are located under "images/icons"

**Comment by petele** [comment]
Will fix in the DevSite update coming in the next two weeks. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/

**Comment by zuDevonRW** [comment]
👍
