### ISSUE TITLE
[EN] chrome.devtools.panels.sources.* APIS (Loosly https://developers.google.com/web/tools/chrome-devtools/?hl=en)

### ISSUE THREAD

**Issue by thenoseman** [google/WebFundamentals#3100]
Hi,

I'm trying to write a chrome extension that meddles with the "Sources" Panel in devtools.

The (not working) extension is here : https://github.com/thenoseman/chrome-devtools-autorun-snippets (installable as extracted extension)

Question:

How do the `chrome.devtools.panels.sources.*`APIs work?
The docs (https://developer.chrome.com/extensions/devtools_panels) are - at least for me - too confusing and not working (See extension above).

The goal would be a better documentation for these APIs. 

*Things I checked:*
- DevTools docs at https://developer.chrome.com/extensions/devtools_panels
- Legacy Docs issue : https://github.com/GoogleChrome/devtools-docs/issues/121 (from 2014)
- Feature commit: https://bugs.chromium.org/p/chromium/issues/detail?id=295888

If someone can give me a working example I would be very thankful.

Cheers,
Frank

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.

**Comment by Wizzy-wooz** [comment]
Hi guys,

can someone advise how can I call from my extension "Toggle Device Toolbar" panel like here:

chrome.devtools.panels.sources
chrome.devtools.panels.elements

should it be chrome.devtools.panels.toggleDeviceToolbar? Or what?

Any help matters :)

Best regards,
