### ISSUE TITLE
Support shortname for nav items

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#3101]
https://github.com/google/WebFundamentals/pull/3080#issuecomment-232745728 attempted to ellipsis the title names in the nav, but that is undesirable for shorter titles b/c it makes them less descriptive. 

Longer titles make sense for some content (like https://developers.google.com/web/fundamentals/primers/customelements/) are good for SEO and users discovering content.

We should support a `shortname` item in the article's metadata would would be the nav item name. The full article title would be kept as `title`.

**Comment by petele** [comment]
This'll go away with the DevSite redesign.
