### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/push-notifications/step-02?hl=en

### ISSUE THREAD

**Issue by xrd** [google/WebFundamentals#3107]
When you run the command noted:

```
python -m SimpleHTTPServer
```

The immediately following statement says "This will start a web server on the default HTTP port.". This command actually starts the webserver on port 8000. 

It might be better to use this command:

```
python -m SimpleHTTPServer 8080
```

This will start on port 8080, explicitly showing people the port; also, this is a port which is unprivileged and does not require teaching people about sudo. :)

Great guide, I'm enjoying it a lot.

**Comment by petele** [comment]
Merging into #3445
