### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/push-notifications/step-01?hl=en

### ISSUE THREAD

**Issue by yelsane** [google/WebFundamentals#3114]
Not sure if I need to do something else, but 

> git clone git@github.com:GoogleChrome/push-notifications.git

 doesn't seem to work. Got an error:

> fatal: Could not read from remote repository

> Please make sure the correct access rights and the repository exists.

Just thought of letting you know.

**Comment by petele** [comment]
Merging into #3445
