### ISSUE TITLE
[EN] Question/Feedback for: /web/fundamentals/getting-started/push-notifications/step-11?hl=en

### ISSUE THREAD

**Issue by xrd** [google/WebFundamentals#3116]
I'm able to send notifications with cURL to my sample application using the provided instructions.

If I understand it, and endpoint is basically a way to extract the subscription ID for that subscriber. 

I'm unclear on these two questions:

* Does each client generate its own endpoint? Is that how we notify each client independently?
* If so, is it proper that a client (like a web browser) would register, and then send the endpoint back to the server (making an XHR call). The server will need to store the endpoint against the user that created it. Or, is there another way to get an endpoint, say from the cloud console (and is that the preferred way to do it) by making an API call to the Google Services?

**Comment by petele** [comment]
Merging into #3445
