### ISSUE TITLE
A wrong rendering of the margin property 

### ISSUE THREAD

**Issue by dagolinuxoid** [google/WebFundamentals#3126]
It looks like a bug, isn't it? A confusing visual representation of `margin-right` property of the `p` which have `margin-right` equal to 0 (zero) . Compare with Firefox:
[Chrome](http://imgur.com/a/Of5In)
[Firefox](http://imgur.com/a/LFoLC)
Chromium version 51.0.2704.79 Built on Ubuntu 14.04, running on elementary OS 0.3.2 (64-bit)

**Comment by cvrebert** [comment]
This issue tracker is for bugs in the Web Fundamentals website.
Chrome bugs should be filed at https://crbug.com/new
