### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by matthew-a-thomas** [google/WebFundamentals#3132]
The frame context dropdown appears to start with a random context chosen. It would be great if it either remembered the last context I chose for the domain, or if it always defaulted to "top". Is this behavior controlled by a setting?

**Comment by Garbee** [comment]
The context is `top` unless you last inspected something within an `iframe` on the page, otherwise it will be within that sub-frame context.

We should document this behavior better, but there is no setting to control how it operates.

**Comment by matthew-a-thomas** [comment]
@Garbee Thanks for the explanation. I'm closing this issue

**Comment by Garbee** [comment]
We should leave the issue open please as there is some actionable documentation work to be done here.

**Comment by matthew-a-thomas** [comment]
Oh ok, my bad. Open sesame!

**Comment by kaycebasques** [comment]
FYI there's been a spat of bugs recently that were setting the context randomly. It's supposed to default to `top`
