### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/device-mode/emulate-mobile-viewports?hl=en

### ISSUE THREAD

**Issue by fujq** [google/WebFundamentals#3141]
Is the device mode able to get windows width?
I've tried $(window).width() in $(document).ready(function() on device mode and always get 980px.

**Comment by kaycebasques** [comment]
Hey @fujq interesting question...

I think it depends what site you're on and whether they've optimized for mobile properly.

For example, `window.innerWidth` appears to be working correctly on developers.google.com...

![dgc](https://cloud.githubusercontent.com/assets/4713486/17419883/6ebf18c8-5a54-11e6-9727-992d7cd33511.gif)

But when I load the desktop version of GitHub and then trigger Device Mode, it doesn't work (notice how the site isn't transitioning into its mobile version). But when I reload the site while already in Device Mode, it properly detects that I'm in mobile mode.

![gh](https://cloud.githubusercontent.com/assets/4713486/17419930/a112f6a0-5a54-11e6-8961-5d4cafde9074.gif)

So I think these are bugs with the sites and not bugs in DevTools

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
