### ISSUE TITLE
[EN] Feedback for: /web/tools/setup/setup-preprocessors?hl=en

### ISSUE THREAD

**Issue by TheLarkInn** [google/WebFundamentals#3145]
I'd love to see some further updates to this document to include configuration via webpack. 

We at @webpack are more than happy to assist you with this if you need further information or support.

Here is a bit of documentation to reference. https://webpack.github.io/docs/configuration.html#devtool

**Comment by kaycebasques** [comment]
@TheLarkInn for sure, happy to include webpack info where relevant. I haven't used it. What changes are you looking to make?

**Comment by TheLarkInn** [comment]
Haha well I think the page I was in was pre processors, or maybe just utilizing tools. Etc. When I have some time I'll post some basic usage docs next week I'd that's okay and we can draft something.

**Comment by TheLarkInn** [comment]
@kaycebasques so I think this is a great collab point for us with this page and our new documentation rewrite we are doing. For Web Fundementals, because a bundler is a paradigm shift in the way resources are used and requested in JavaScript, would it be useful to talk about `modules`, `dependency graphs`, etc. [Like seen here](https://github.com/webpack/webpack.io/blob/develop/content/concepts/index.md)

Otherwise, I'm going to be working on https://github.com/webpack/webpack.io/issues/48 and https://github.com/webpack/webpack.io/issues/8 and https://github.com/webpack/webpack.io/issues/10 this week sometime, so I can provide as much content as interests you.

**Comment by kaycebasques** [comment]
Revisiting old issues. These pages aren't being maintained. Working on a PR that deprecates them.
