### ISSUE TITLE
[EN] Feedback for: /web/updates/?hl=en

### ISSUE THREAD

**Issue by santolaria** [google/WebFundamentals#3155]
bonjour , je me permet de vous interpeller , mais je ne sais pas du tout si vous pourrez faire quelque chose pour moi , ! voilà je suis revenu sur mon site wix , et je n'ai plus rien qui fonctionne tous les liens que j'avais connecté sont rompu , ai-je fais des erreurs ? merci si vous pouvez m'aider , cordialement Mr santolaria gilles . 

Hello, I can question you, but I do not at all know if you do something for me! Here I am back to my wix site, and I have nothing that works all the links I had connected are broken, I make mistakes? Thanks if you can help me, cordially Mr santolaria gilles.

**Comment by manekinekko** [comment]
@santolaria ce repo github n'est pas dédié au support de Wix. Merci de vous orienter vers le support officiel de Wix à cette adresse: https://fr.wix.com/support/html5/

**Comment by santolaria** [comment]
Bonsoir  , merci pour votre réponse  , Santolaria gilles.

gilles santolaria
