### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/network-performance/resource-loading?hl=en

### ISSUE THREAD

**Issue by nailfar** [google/WebFundamentals#3160]
when I loading  a file from local serve  ,the file is only 1.kb which takes 1.1min to download the content .what's wrong whith it .

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
