### ISSUE TITLE
Unnecessary(?) underscore escaping ("\_") in code samples in Markdown files

### ISSUE THREAD

**Issue by tomayac** [google/WebFundamentals#3161]
For some reason, underscores in code samples in Markdown files are consequently escaped like so: ```\_```, e.g., line 142 in [step-04.markdown](https://raw.githubusercontent.com/google/WebFundamentals/master/src/content/en/fundamentals/getting-started/your-first-progressive-web-app/step-04.markdown) (raw link, as line-level deep links don't work for ```.markdown``` files).

These backslashes end up in code samples in the [production site](https://developers.google.com/web/fundamentals/getting-started/your-first-progressive-web-app/step-04?hl=en) (full text search for "\\_").

I tried removing all escape backslashes in one particular code sample and succeeded in building the site locally by going from (simplified for readability)…

```javascript
{% highlight javascript %}
var filesToCache = [  
  '/images/ic\_add\_white\_24px.svg'
];
{% endhighlight %}
```

…to…

```javascript
{% highlight javascript %}
var filesToCache = [  
  '/images/ic_add_white_24px.svg'
];
{% endhighlight %}
```

…and received the desired output, i.e., just the underscores without the escape backslashes after the ```gulp``` build:

<img width="760" alt="screen shot 2016-07-30 at 13 45 17" src="https://cloud.githubusercontent.com/assets/145676/17270134/04c7571a-565c-11e6-91ea-5fded617ee0f.png">

There are currently 69 more occurrences of the pattern ```\_``` in ```*.markdown``` files across the project; before creating a formal Pull Request, I wanted to double-check whether these escapes are there for any reason that I'm not aware of?

(CC: @PaulKinlan @petele)

**Comment by petele** [comment]
thanks for looking into this @tomayac!

Are the 69 other occurrences in ``{% highlight something %}` or throughout the whole project? I *think* the `\_` pattern is only needed in markdown,  but I'm not 100% sure. In markdown, we need the `\_` otherwise markdown thinks it's the start of an underline.

We probably need to check one by one. :/

**Comment by tomayac** [comment]
I did a quick search for the regular expression /\\_/ on all *.markdown files in the project, it occurs mostly in code blocks and the occasional URL (probably could come up with a smarter search to exclude those. Removing the backslashes in the one particular example had no negative consequences as far as I can tell.

**Comment by tomayac** [comment]
Duh, `/\\_/` I meant.

**Comment by petele** [comment]
Sounds good - let's do the PR and then be sure to test thoroughly.
