### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by Phalangers** [google/WebFundamentals#3162]
Ctrl + Shift + T : opens the last closed tab, even in the developer tools.
I guess this is not expected behaviour, but I might be wrong.

**Comment by kaycebasques** [comment]
@Phalangers what OS are you using and what shortcut are you trying to do?

**Comment by Phalangers** [comment]
Ubuntu 14.04.1
Version 51.0.2704.103 (64-bit)

Was developing an extension (background page inspection) and hit the shortcut by mistake.
Can't reproduce now. Sorry.

**Comment by kaycebasques** [comment]
@Phalangers no prob! Thanks for contributing
