### ISSUE TITLE
Link to Base Styleguide page under /web/resources is broken.

### ISSUE THREAD

**Issue by moinshaikh** [google/WebFundamentals#3163]
Hi,

The [Base Styleguide](https://developers.google.com/web/resources/styleguide/) page link under [web/resources](https://developers.google.com/web/resources/) is broken and is throwing 404.

Can someone pls fix it so that we contributors can refer to it as an when needed while making any contribution :)

Thanks,
**Moin**

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.

**Comment by moinshaikh** [comment]
No worries,

Thanks

On Sep 23, 2016 2:20 AM, "Pete LePage" <notifications@github.com> wrote:

Thanks for the feedback, we've got an update coming next week that should
fix this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/WebFundamentals/issues/3163#issuecomment-249023921>,
or mute the thread
