### ISSUE TITLE
[EN] Feedback for: /web/tools/polymer-starter-kit/?hl=en

### ISSUE THREAD

**Issue by gerardoemmanuel** [google/WebFundamentals#3171]
This link not working:

https://elements.polymer-project.org/

please , check

**Comment by manekinekko** [comment]
@gerardoemmanuel what do you mean by "it's not working" ? are you talking about this link https://elements.polymer-project.org/web/tools/polymer-starter-kit/?hl=en ?

**Comment by petele** [comment]
Seems to be working now.
