### ISSUE TITLE
[EN] Feedback for: /web/updates/?hl=en

### ISSUE THREAD

**Issue by AdeyG** [google/WebFundamentals#3176]
On the Network tab, I'm sure I used to be able to do a negative search to exclude results from the network traffic.

It's a real pain for me as browserLink pollutes the list with all it's polling while I'm in a dev environment.

**Comment by kaycebasques** [comment]
Hey @AdeyG can you give me an example of a search you're trying to perform?

I just tested out negative filters using the filter keywords and it looks like those are working in Canary:

![image](https://cloud.githubusercontent.com/assets/4713486/17418671/85a30ce4-5a4e-11e6-992c-dbfb12c80c42.png)

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
