### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/device-mode/emulate-mobile-viewports?hl=en

### ISSUE THREAD

**Issue by EionRobb** [google/WebFundamentals#3182]
Resize and OrientationChange events are not fired when clicking the 'rotate' button

**Comment by kaycebasques** [comment]
Hey @EionRobb they're both working in Canary! 

![test](https://cloud.githubusercontent.com/assets/4713486/17418352/ff5786ac-5a4c-11e6-9337-d4bf78bb06c7.gif)

**Comment by EionRobb** [comment]
Not with the `window.onorientationchange` syntax though

**Comment by kaycebasques** [comment]
Hey @EionRobb that syntax looks experimental: https://developer.mozilla.org/en-US/docs/Web/API/Screen/onorientationchange

It's also being listed as `screen.orientationchange`.

**Comment by EionRobb** [comment]
No, I'm talking specifically about `window.onorientationchange`, i.e. using the 'old' style of event http://w3c.github.io/html/webappapis.html#events-event-handlers.  Works everywhere except for in the emulator, so should probably be documented.

**Comment by kaycebasques** [comment]
I hear ya, I'm familiar with the syntax. But when I went to test out the syntax (I.e. Just log to console when the event is fired) it wasn't working. Maybe I messed something up! I'll check again tomorrow or Tuesday

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
