### ISSUE TITLE
clarify app install banner section in "debug pwas" doc

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#3200]
do this in the same PR as #3190 

use this photo:

<img width="364" alt="native-install-banner" src="https://cloud.githubusercontent.com/assets/4713486/17458450/6fe0bfe6-5bc5-11e6-908d-2168734a1114.png">

**Comment by ebidel** [comment]
Can we use the 2016 site instead of 2015? events.google.com/io2016/

**Comment by kaycebasques** [comment]
@ebidel for sure
