### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/04/chrome-51-deprecations?hl=en

### ISSUE THREAD

**Issue by kkwiatkowska** [google/WebFundamentals#3204]
Hi there,

With the new version you said that "custom string will no longer be shown to the user. Chrome will still show a dialog to prevent users from losing data, but it's contents will be set by the browser instead of the web page.". 

However it's like that for refreshing/closing the browser, but not for clicking back button:

![screen shot 2016-08-09 at 14 57 22](https://cloud.githubusercontent.com/assets/16577411/17518992/06a2d904-5e42-11e6-80a3-6cedfac8aa64.png)

I still see custom message. 

Is it expected behaviour?

Karolina

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at https://new.crbug.com
