### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/primers/customelements/?hl=en

### ISSUE THREAD

**Issue by DmitryMakhnev** [google/WebFundamentals#3219]
Hello.

Article has problems with markup
<img width="796" alt="screen shot 2016-08-13 at 18 57 37" src="https://cloud.githubusercontent.com/assets/895560/17644166/2e6f7c8c-6188-11e6-8905-99313ffd124d.png">

**Comment by ebidel** [comment]
Thanks. This was fixed in https://github.com/google/WebFundamentals/pull/3213, but the site still needs a deploy. 

cc @petele
