### ISSUE TITLE
[EN] Shortcuts Problem Page Up and Page Down /web/tools/chrome-devtools/iterate/inspect-styles/shortcuts?hl=en

### ISSUE THREAD

**Issue by sylido** [google/WebFundamentals#3228]
In the most recent version of chrome it seems like the behavior of the PgDown and PgUp keys has been changed to increment/decrement the CSS value by "1" instead of by "10". Holding down Shift + PgUp/PgDown results in the correct behavior of using the "10". Yet I think this is in error since the arrow keys already provide this behavior.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
