### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/primers/payment-request/?hl=en

### ISSUE THREAD

**Issue by avishyes** [google/WebFundamentals#3229]
Hi,

I would like to start playing with the payment-request API for Desktop.
Is there any Chrome Extension I can download which has this API? or any Beta version? if not, when do you think it will be ready? what is the road-map for implementing this API in Chrome?

BR,
Avish Yeshurun
avish.yeshurun@bluesnap.com

**Comment by petele** [comment]
@agektmr - can you answer this?

**Comment by agektmr** [comment]
Desktop version is under development. It should be available hopefully in Chrome 55.
