### ISSUE TITLE
[EN] Feedback for: /web/updates/2016/03/web-push-encryption?hl=en

### ISSUE THREAD

**Issue by BanuRajadurai** [google/WebFundamentals#3272]
Hello everyone , 
  we are getting the charactre '/' in the p256dh key  and while sending push , it is throwing error as below 

Exception in thread "main" java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: /

can any one please help me to sort this out . 

Thanks in advance

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. I'd suggest using StackOverflow to see if anyone has an answer to your question there.
