### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/primers/promises/?hl=en Error Handling

### ISSUE THREAD

**Issue by abraham** [google/WebFundamentals#3296]
The flowchart is not readable.

<img width="824" alt="screen shot 2016-08-31 at 15 02 06" src="https://cloud.githubusercontent.com/assets/3341/18144481/7c75dbf8-6f8c-11e6-9fc7-9ef2fce50caa.png">

**Comment by petele** [comment]
This'll be fixed in the DevSite relaunch coming Oct 5th.
