### ISSUE TITLE
[PT-BR] Feedback for: /web/tools/chrome-devtools/?hl=pt-br

### ISSUE THREAD

**Issue by alineDiesel** [google/WebFundamentals#3300]
Olá.  (=

Gostaria de fazer uma sugestão.
Não sei se existe uma ferramenta assim já, enfim... eu não uso.

Quando você edita sua página através do developer tools e altera o CSS, penso que seria muito interesse eu ter tipo uma ferramenta que pudesse criar pontos de estilos salvos. Saca?
Supomos que eu esteja fazendo testes de alteração de uma página, que, para chegar nela, eu tenha uma série de outras páginas antecessoras. Quando eu chego nessa página, altero o estilo de 10, 15 elementos e gostaria de salvar o estado dessa página a partir dali. Porque o que virá a seguir, talvez nem Deus saiba. hahaha

Então, caso eu estrague totalmente o estilo da página depois de 50 alterações de elementos, eu não quero controlar o ctrl + z, pra chegar até o estado que eu tinha alterado, porque pode ser que eu passe aquele nível ou demore a chegar. Se houvesse uma opção: ir ao estado de estilo X, seria muito mais interessante.

Obrigada. (=

Aline.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
