### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/remote-debugging/remote-debugging?hl=en

### ISSUE THREAD

**Issue by mmartinez** [google/WebFundamentals#3301]
For some reason, even after following the step by step, I can't see the screencast option. I can see the markup and inspect everything on the phone. However, I can't see the phone rendering on my Chrome.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
