### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-progressive-web-app/step-08?hl=en

### ISSUE THREAD

**Issue by kimblenz** [google/WebFundamentals#3306]
There is a typo in this sentence:
" ... recommends serving the above the fold content"

I'm not sure what the intent was, but there's something wrong with those two instances of "the" and above.

Perhaps this was meant? "... recommends serving this above the fold content"

**Comment by jpolly168** [comment]
I am pretty sure it is just talking about serving the "above the fold" content.  Using this as a singular instance on page load.

**Comment by petele** [comment]
Will fix in the DevSite update coming in the next two weeks. In the mean time, try https://codelabs.developers.google.com/codelabs/your-first-pwapp/
