### ISSUE TITLE
Issue in: /getting-started/your-first-multi-screen-site/content.html

### ISSUE THREAD

**Issue by katrinalprescott** [google/WebFundamentals#335]
In the "Create the Video and Information section" the first code snippet includes different code than the second (and than the code in the linked example).  In the first code snippet the sources for the video are:

```
<source src="udacity.mp4" type="video/mp4"></source>
<source src="udacity.webm" type="video/webm"></source>
```
In the second (and the "show source" of the example) they are: 

```
<source src="udacity.webm" type="video/webm"></source>
<source src="udacity.mov" type="video/mov"></source>
```

**Comment by petele** [comment]
this appears to be fixed
