### ISSUE TITLE
window view collapse

### ISSUE THREAD

**Issue by ellenlee** [google/WebFundamentals#3355]
![2016-09-08 16 47 35](https://cloud.githubusercontent.com/assets/13810570/18343196/e7b854c8-75e4-11e6-9a98-8aa2a5dadd9a.png)

My console window show as attach img....
can't find how to fix up......
please let me know how to get it back 
thank you very much!!!

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
