### ISSUE TITLE
Make showcase header images clickable

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3378]
Request from Alex: can someone make it so you can click on the header images to go to the articles here? https://developers.google.com/web/showcase/

I can PR this in, just need to know whether it has to be against the next updates branch, master or directly in devsite.

cc @petele @jpmedley

**Comment by petele** [comment]
That page uses an index.yaml file, so we can't simply wrap the image in an anchor tag. We'd need to file a bug with the DevSite team to get this behaviour changed. Ping me offline and I can point you in the right direction.
