### ISSUE TITLE
Getting started section missing from homepage

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#3390]
There's no way to get to the "Getting started" section from the homepage:

<img width="333" alt="screen shot 2016-09-14 at 9 31 42 am" src="https://cloud.githubusercontent.com/assets/238208/18520792/3255734e-7a5e-11e6-926e-73b89604d0db.png">

home:

<img width="997" alt="screen shot 2016-09-14 at 9 31 48 am" src="https://cloud.githubusercontent.com/assets/238208/18520802/3cdd3a86-7a5e-11e6-82a8-61a25f267157.png">

**Comment by ebidel** [comment]
I think this is especially important to surface if we're putting Primers under Getting Started.

**Comment by petele** [comment]
Good point - will sort.

**Comment by petele** [comment]
Added.
