### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/getting-started/your-first-multi-screen-site/content?hl=en

### ISSUE THREAD

**Issue by abdshomad** [google/WebFundamentals#3404]
When i click the [Try Full Sample] button of Add the Tabulated Data Section, it directs me to https://googlesamples.github.io/web-fundamentals/samples/fundamentals/getting-started/your-first-multi-screen-site/addtable.html, but github reported that the file not found. 

Here's the screenshot: 
![add-table-not-found](https://cloud.githubusercontent.com/assets/15354/18569922/4c2dd57c-7bd0-11e6-896f-a7e5300b2017.png)

**Comment by petele** [comment]
This will be fixed in the new DevSite update coming shortly.
