### ISSUE TITLE
Push GCM instructions should use unrestricted API key

### ISSUE THREAD

**Issue by johnmellor** [google/WebFundamentals#3407]
[getting-started/push-notifications/step-04](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-04) ([source](https://github.com/google/WebFundamentals/blob/faa8ff9320ee8028f2d0059e230a53a885f0a624/src/content/en/fundamentals/getting-started/push-notifications/step-04.markdown)) recommends to create a "Browser key" (with blank HTTP referrers field) for Google Cloud Messaging.

But the [API Manager UI](https://console.developers.google.com/apis/credentials) has changed since then, and there is no longer a concept of a "Browser key" (and in fact, we should have been recommending "Server key"s anyway since messages are usually sent from web servers rather than from web pages). We should update the docs (and screenshots) to simply recommend leaving the key unrestricted.

(Or we could recommend using the Web Push protocol with [VAPID](https://developers.google.com/web/updates/2016/07/web-push-interop-wins#introducing-vapid-for-server-identification) instead, but we'll probably still want GCM documentation somewhere for developers that are already heavily invested in GCM.)

cc @samdutton @beverloo

**Comment by samdutton** [comment]
Yes...

This article needs an overhaul — on my TODO list, unless someone else wants
to take it on :).

**Comment by petele** [comment]
Merging into #3445

**Comment by johnmellor** [comment]
It turns out the supported flow for creating API keys is now to use the Firebase console (see [Diego's post](http://stackoverflow.com/a/39695306/691281)):

1. Go to https://console.firebase.google.com
2. If you don't already have a Firebase project, import an existing Google Cloud project or create a new Firebase project.
3. The API key is under (gear-next-to-project-name) > Project Settings > [Cloud Messaging](https://console.firebase.google.com/project/_/settings/cloudmessaging)

We should prioritize updating this part of the docs, since the current instructions don't work at all (there's no longer a button called Browser key, and the obvious step of creating an unrestricted key doesn't work either).
