### ISSUE TITLE
Feedback for WebFundamentals/src/content/en/updates/posts/2016/04/intersectionobserver.md

### ISSUE THREAD

**Issue by minaseem** [google/WebFundamentals#3419]
When IntersectionObserver is asked to observe on shadow DOM. It gives following warning

IntersectionObserver.observe(target): target element is not a descendant of root.

Though this is correct technically, but it will be great if IntersectionObserver is made configurable to watch on shadow DOM too.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://github.com/WICG/IntersectionObserver/issues/ for how to file an issue with the spec.
