### ISSUE TITLE
Can't find FPS meter in devtools after being linked from developers.chrome.com

### ISSUE THREAD

**Issue by wffurr** [google/WebFundamentals#3420]
I was linked to this page by a banner on an older page about Chrome rendering settings and the FPS meter, but there is no mention or documentation for the rendering settings and FPS meter on the new page.

Please add a linkable destination for showing how to enable the FPS Meter before removing the old site:  https://developer.chrome.com/devtools/docs/rendering-settings

**Comment by kaycebasques** [comment]
Just put in some fixes to the page. I'll check back tomorrow to see if they worked as expected. https://developer.chrome.com/devtools/docs/rendering-settings

**Comment by kaycebasques** [comment]
Page has successfully updated.
