### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/profile/network-performance/resource-loading?hl=en

### ISSUE THREAD

**Issue by trobro** [google/WebFundamentals#3426]
"Enable the Preserve log checkbox to save the network log across these scenarios. New records are appended to the bottom of the Requests Table."

Unfortunately it seems that just the headers are preserved, not the response data (OSX, Chrome 53.0.2785.116 (64-bit)). That really makes the feature less useful. I still have to prevent page navigation if I want to investigate api responses (or be really quick when clicking on a network request in the log, so that the response data is loaded in the developer tools before the page navigation).

Firefox preserves the response data too, much more useful.

**Comment by jpmedley** [comment]
@kaycebasques FYI.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.
