### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/device-mode/emulate-mobile-viewports?hl=en

### ISSUE THREAD

**Issue by mrclMD** [google/WebFundamentals#3427]
Hi,

I have a question concerning the device pixel ratio. Existing devices seem to deal correctly with the setting. An iPhone 4 which has a physical resolution of 960x640pixel. Because of the device pixel ratio of 2, the dimensions in dev tools are shown as 480x320pixel. Correct?

If I add a custom device with 2560x1440 and DPR 2 the dimensions are not shown as 1280x720 as expected, but with 2560x1440. Why? I am using the latest Version 53.0.2785.116 m of Chrome.

Regards, 
Marcel

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out https://developer.chrome.com/devtools/docs/contributing for how to ask questions or file issues on DevTools.

**Comment by mrclMD** [comment]
Sorry. I was also a little surprising that I was led to go here. Thanks for the link.
