### ISSUE TITLE
Houdini: further updates?

### ISSUE THREAD

**Issue by myakura** [google/WebFundamentals#3433]
https://github.com/google/WebFundamentals/commit/482dbae1c61902b059a5cae97e1b13c1e6b7adaa added some status updates.
time flies. things getting change:

* Compositor Worklet becomes [Animation Worklet](https://github.com/majido/animation-worklet-proposal) [(bug)](https://bugs.chromium.org/p/chromium/issues/detail?id=467782#c3)
* Initial patch to support Props and Values API landed on Blink (yay!) [(commit)](https://chromium.googlesource.com/chromium/src/+/01ce431409e3a019858677626a983c55168da6dc)
* possibly some spec work happening during TPAC?

**Comment by myakura** [comment]
ping @surma

**Comment by surma** [comment]
Hey @myakura,

yeah, things are changing. I am at TPAC, so I will do an overhaul after so I get all the news.

Also, https://ishoudinireadyyet.com is a thing, so gotta cover that ;)
