### ISSUE TITLE
Auditing an existing site with Lighthouse

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3446]
Port over from the ILT course article: https://docs.google.com/document/d/1Orh7oGb1UdDrT8zjEynNllf9Z_2anmeazePmNXp84Iw/edit

**Comment by addyosmani** [comment]
@kaycebasques We should coordinate with you on how this might fit in with your plans for LH content on /web. Or just assign this to you directly :P

**Comment by addyosmani** [comment]
@paullewis We had a chat a while back about you maybe doing an intro to Lighthouse article. If you were up for it, you could work on this and trade Kayce for another item. Any preferences?

**Comment by kaycebasques** [comment]
This is pretty easy. I'll write it.

**Comment by addyosmani** [comment]
Thanks @kaycebasques!

**Comment by petele** [comment]
this was merged.

**Comment by addyosmani** [comment]
🎉
