### ISSUE TITLE
Tooling and Automation (Gulp)

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3452]
ILT content: https://docs.google.com/document/d/1CWUIbxfWLXBsfYvEliUeg7HTjylJPt1GpAulVQSeCbk/edit#heading=h.bz6dgupebetm

Note that there is also a code lab available: https://docs.google.com/document/d/1txpEXLOttqKmYbDCiRZSSmH4vJEFBiGrZBt2lic5AYA/edit#heading=h.41rml77yub8c

**Comment by pbakaus** [comment]
Looking at the tools section (and the other sections), I'm not sure this content has a fitting home at Web Fundamentals.

**Comment by addyosmani** [comment]
We currently have https://developers.google.com/web/tools/setup/setup-buildtools which I think was written a while back and may have been a little too focused on Web Starter Kit. 

@petele do you have opinions on whether it's worth bringing in the ILT content to replace/evolve this doc?

**Comment by petele** [comment]
There are plenty of other great places where this intro level content exists on the web already, we're not adding anything new or insightful to it. I think it makes sense in the ILT context, but I don't think it makes sense on /web, I'd rather Devs get content from the source (ie Gulp, or Grunt, etc)

**Comment by addyosmani** [comment]
Okay. Let's refocus our efforts elsewhere.
