### ISSUE TITLE
Offline caching with Service Worker libraries (sw-precache, sw-toolbox)

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3453]
ILT course content: https://docs.google.com/document/d/1PDLd3nHw2zVKODMFDeYpeeUkMxdwwYvOqby6A9hp7fI/edit#heading=h.3awfbbcw4ydp

**Comment by jeffposnick** [comment]
I've been working on a draft in an `@google.com` siloed doc: https://docs.google.com/a/google.com/document/d/16FLJA7HLUcdiLcj_gGvwHmwyd_ZPpBsrRMB56vpjPUI/edit?usp=sharing

**Comment by jeffposnick** [comment]
@jpmedley @Meggin & co., that internal draft should be ready for review. I'd rather collect and resolve any feedback there before converted it into Markdown and filing a PR.

**Comment by addyosmani** [comment]
Captured by Workbox docs
