### ISSUE TITLE
Introduction to Push Notifications

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3454]
ILT content: https://docs.google.com/document/d/1nc0ADQUNZhEz0xmAyDtvKhTRoplEWKuhWM_cc4Di5Fk/edit#heading=h.gxkloi8vwsa2

What we have today: https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/?hl=en and https://developers.google.com/web/fundamentals/getting-started/push-notifications/?hl=en

We may not need to migrate this content over if the current section is enough. Assigning to Joe initially to take a pass through ILT.

**Comment by jpmedley** [comment]
I've started work on this. Updated content is in the push-hackathon branch.

https://github.com/google/WebFundamentals/tree/push-hackathon

**Comment by jpmedley** [comment]
#3556 Merged earlier today.
