### ISSUE TITLE
The PRPL Pattern

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3459]
During the /web hack week, we have an opportunity to land a dedicated page for the [PRPL](https://www.polymer-project.org/1.0/toolbox/server) pattern outside of the Polymer docs. 

This would be a description of the pattern that isn't tied to the App Toolbox, but links out to it and Shop as canonical examples of how the pattern could be implemented in practice. Anything we can do to further improve it and link out to relevant other docs would be a nice to have.

Given the Polymer team created/discovered PRPL, looping in @graynorton @tjsavage for their thoughts here. 

We might be able to fit this under https://developers.google.com/web/fundamentals/performance/?hl=en

**Comment by tjsavage** [comment]
+1

**Comment by PaulKinlan** [comment]
Will this be established best practice? I am asking because if it is going to live in /web/fundamentals, then  we expect every developer to follow this guidance.  I've heard reports from a few teams that H2 Push can degrade the performance of your site especially if the content is already in the browser cache.  So this pattern seems experimental at best.  Do we have real-world data and guidance from production sites?

**Comment by addyosmani** [comment]
This is a good point. I would say it is experimental. We know that Housing.com, Flipkart and the NFL are experimenting with PRPL but you're correct in saying the pattern is more of "here's a pattern we think makes sense" with companies investigating the impact of implementing route-chunking and seeing how far Server Push, H/2, preload etc can take them. 

If it wouldn't live under fundamentals, what would be another place /web that this could live? It's not an update (we want something more formal than that) but it would also be better served outside of the Polymer docs.

My suggestion would be an entry under Performance with the experimental label if there isn't a better place for it today. @petele might have suggestions too.

**Comment by addyosmani** [comment]
After talking to Arthur, I'm going to take this one as he is heads down on docs for Polymer Summit. I don't think it'll take too long to land.
