### ISSUE TITLE
Debugging Service Workers

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3463]
**What:**
How to use DevTools > Application > Service Workers sub-panel to debug Service Workers

**Current content:**
- https://www.chromium.org/blink/serviceworker/service-worker-faq
- https://developers.google.com/web/updates/2015/10/devtools-digest-efficient-element-edits?hl=en
- https://codelabs.developers.google.com/codelabs/debugging-service-workers/index.html?index=..%2F..%2Findex#0

we also have docs on https://developers.google.com/web/tools/chrome-devtools/iterate/manage-data/?hl=en but this (I think) doesn't cover the Service Workers sub-panel

**Comment by addyosmani** [comment]
cc @kaycebasques @paulirish

**Comment by paulirish** [comment]
Yah good call. 
Also, Your-first-pwa codelab has some exciting docs on this too.

**Comment by jakearchibald** [comment]
"Update on reload" is probably the most important tool we have here.

I have an almost-ready article on the service worker lifecycle that I can privately share if that'd be useful.

**Comment by addyosmani** [comment]
@jakearchibald That was a really ace article. Would you mind sharing it with Rob? (I think he may have seen it, but juuuuust in case)

**Comment by jakearchibald** [comment]
Shall do! I think we're going to publish it on fundamentals rather than my blog.

**Comment by kaycebasques** [comment]
https://developers.google.com/web/tools/chrome-devtools/debug/progressive-web-apps/#service-workers (old site) contains a quick reference of the panel

**Comment by kaycebasques** [comment]
We could cross-link to Rob's codelab in the relevant places, but I don't think new content is needed here

**Comment by addyosmani** [comment]
One of my worries is the discoverability of our SW debugging docs given where they are at the moment. It was nigh impossible to find https://developers.google.com/web/tools/chrome-devtools/debug/progressive-web-apps/#service-workers in search for example and navigating Rob's codelab just to link folks out to specific things is non-ideal (espec if you just want a doc you can scroll through).

**Comment by Meggin** [comment]
Testing service workers should be an important part of service worker docs,
wherever they live.

**Comment by robdodson** [comment]
I'm working on moving in the a11y docs and probably won't be able to get to this during the sprint but I'm happy to work on the ticket after the sprint :D cc @petele

**Comment by Meggin** [comment]
Great, thanks, Rob. I'm working on Identity docs, and will then try and do
a bit of HTTPS, so I'm unlikely to get to this during Sprint as well. We
will get there-- just might not be this week.

**Comment by addyosmani** [comment]
Captured by more recent DevTools guidance + codelabs
