### ISSUE TITLE
Introduction to HTTP/2 guide

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3464]
Existing content: 
https://surma.link/things/h2setup/
http://blog.chromium.org/2015/02/hello-http2-goodbye-spdy.html
http://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html
https://docs.google.com/presentation/d/1r7QXGYOLCh4fcUq0jDdDwKJWNqWK1o4xMtYpKZCJYjM/edit#slide=id.p19
hpbn.co/http2
https://docs.google.com/document/d/1K0NykTXBbbbTlv60t5MyJvXjqKGsCVNYHyLEXIxYMv0/edit (H/2 Push specific)

Partially related to #3459 but also just to have a good one-pager on it for /web.

**Comment by PaulKinlan** [comment]
we should also make sure we link to surma's course.  and if possible steal resources from it too.

**Comment by Meggin** [comment]
I can help with HTTP/2 docs.

**Comment by PaulKinlan** [comment]
Can we work out how this will be integrated in to /web/fundamentals/performance, the resources there are more action oriented vs explainer and it might not make sense to have a "one pager" but instead an holistic look at Optimizing content and critical render path... (note: It could be that we have a dedicated h2 section, I just want us to be mindful)

**Comment by surma** [comment]
The Udacity course is only partly about HTTP/2 though. But definitely a resource to put in a “Further Reading” section.

I think the article in WF should be an introduction, while we use different features of h2 for the `/performance` section. I’m also not sure if I should migrate [my blog post](https://surma.link/things/h2setup/) or just link to it (it’s rather dry).

**Comment by surma** [comment]
So I suggest we take Ilya’s [hpbn](https://hpbn.co/http2/) article, trim it down a bit and put that here, potentially linking to the other resources where appropriate. Does that sound reasonable?

**Comment by addyosmani** [comment]
cc @igrigorik for his thoughts on us doing that

**Comment by igrigorik** [comment]
Not entirely clear to me where this will live... under perf section?

Is the goal to "explain" h2, or to contrast the differences (i.e. be more action oriented)? If it's the latter, then my attempt at covering that in HPBN is: 
- https://hpbn.co/optimizing-application-delivery/#optimizing-for-http1x
- https://hpbn.co/optimizing-application-delivery/#optimizing-for-http2

**Comment by surma** [comment]
AFACIT, the `/perf` article @PaulKinlan mentioned is another thing that needs to get written eventually. I don’t know where this will live under `/web`, but it’s supposed to be an introduction to h2. I don’t think it’s feasible to create new content which is why I thought your HPBN would be a great basis to work off of.

@PaulKinlan @Meggin WDYT?
