### ISSUE TITLE
Ten Things You Shouldn't Still be Doing in 2016

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3467]
@jpmedley had this idea to maybe capture web dev practices that were once best practices but should be avoided in 2016. @ebidel has been thinking about some Lighthouse audits in this space and has a great doc of newer best practices that could fit into a guide here.

**Comment by ebidel** [comment]
Where would this live? I'm not I'll have time to author new content for the sprint, but I think we can think about how this connects with DoBetterWeb ad supplements content in written form.

**Comment by ebidel** [comment]
Untagging this for the the hackathon.
