### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/security/encrypt-in-transit/make-intra-site-urls-relative?hl=en

### ISSUE THREAD

**Issue by kimblenz** [google/WebFundamentals#3470]
So is it just me or is there a rich irony here? The very page advocating intra-site URLs being relative has intra-site URLs that are not relative? Or is it just Chrome transparently converting the URLs in the source? Or perhaps making URLs relative is thought of something that should be done with a script over the entire content of https://developers.google.com/web/fundamentals ?

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
