### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/iterate/inspect-styles/?hl=en

### ISSUE THREAD

**Issue by lunakwai** [google/WebFundamentals#3479]
Username/Password Generator.

I need an application to be developed that I will be putting in my commercial website. The purpose of this application is to produce a username and password for the visitor that has just paid the payment processor the necessary fee. This username and password will allow the member to enter the Members Gallery to see the 3,000 pictures featured there. If the Member does not cancel his membership before the 30 days has expired, they will be rebilled the same amount the paid when they first became a member. If the member cancels their membership, they will not be re-billed.

**Comment by lunakwai** [comment]
Can I pay someone to do this for me?

**Comment by petele** [comment]
Hi, Sorry, this repo isn't for looking for developers to help with your project.
