### ISSUE TITLE
Metrics for Progressive Web Apps

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3480]
**Goal**
A guide outlining a minimal set of summaries for the following PWA metrics we ask developers to optimize for (both in talks and via Lighthouse):
- First Meaningful Paint
- Time to interactive (focus on high-level, caveat with technical definition evolving)
- First paint (or First Contentful Paint)

Maybe with visuals to help folks grok em and how they might read them from say..devtools.

**Why do we want this?**
In the absence of a doc defining a clear definition for the above, we end up needing to re-explain them to folks pretty often (atm every few days). Having this documented would be hella nice.

**Nice to have**
Filmstrips for each pointing to the key moment when they occur during the loading lifecycle of a page. Could be from DevTools, WebPageTest or manually mocked up.

**Existing content:**
https://www.youtube.com/watch?v=IxXGMesq_8s
go/progressivewebmetrics (internal)
https://groups.google.com/a/chromium.org/forum/#!forum/progressive-web-metrics

cc @paulirish @paullewis for an "is this worthwhile documenting during the hackathon?" and fyi

**Comment by PaulKinlan** [comment]
Can you work out where this will live in /web/fundamentals/performance.  It feels like this could be on the overview page as a Here are the things metrics you need to be concerned about and here are the [existing] guides to help you reach those targets.

**Comment by addyosmani** [comment]
We could do something short on the overview page or a dedicated metrics page that also provides links to talks (like Paul's from BlinkOn).

**Comment by addyosmani** [comment]
The always awesome @paulirish is gonna take a stab at getting some basics written on this one today \o/

**Comment by addyosmani** [comment]
Captured by https://developers.google.com/web/updates/2017/06/user-centric-performance-metrics
