### ISSUE TITLE
Couldn't find disable all styles in /web/tools/chrome-devtools/iterate/inspect-styles/edit-styles

### ISSUE THREAD

**Issue by lingtalfi** [google/WebFundamentals#3482]
Hi, I didn't find a "disable all styles" button in chrome dev tools.
I believe it should be right at the web developer's fingertips.
So that would be great if chrome dev tool had it.

**Comment by kaycebasques** [comment]
Hey @lingtalfi can you create a feature request on crbug.com? That's the issue tracker for DevTools (the product). This is the repo for DevTools docs.

**Comment by lingtalfi** [comment]
Thanks. 
https://bugs.chromium.org/p/chromium/issues/detail?id=651687
