### ISSUE TITLE
Review and Update "Optimizing Content Efficiency"

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#3484]
Review "Optimizing Content Efficiency" for updates and improvements focusing on, but not excluded to PWA's.

https://github.com/google/WebFundamentals/tree/master/src/content/en/fundamentals/performance/optimizing-content-efficiency

**Comment by addyosmani** [comment]
Live doc: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/?hl=en

**Comment by addyosmani** [comment]
Initially assigning to @wibblymat and @samthor

**Comment by petele** [comment]
@paullewis reviewed and said it was OK
