### ISSUE TITLE
Review and Update "Critical Rendering Path"

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#3485]
Review "Critical Rendering Path" for updates and improvements focusing on, but not excluded to PWA's.

https://github.com/google/WebFundamentals/tree/master/src/content/en/fundamentals/performance/critical-rendering-path

Link to live doc: https://developers.google.com/web/fundamentals/performance/critical-rendering-path/?hl=en

**Comment by addyosmani** [comment]
@igrigorik We're having a Web DevRel hackathon for /web content next week. More than welcome to join if you'd like to take a look at updating CRP. If you're busy though, can assign to someone else :)

**Comment by igrigorik** [comment]
@addyosmani anything in particular? Took a pass over it and I don't see anything that requires change; all the advice is as relevant as before.

**Comment by jpmedley** [comment]
Are there no places where you can add stuff like, "This is particularly
important if you're doing [PWA | App Shell | *fillInTheBlank*]"?

Just playing devil's advocate.

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by PaulKinlan** [comment]
I really don't think it makes sense to change this too much wrt to PWA as a lot of this is core principles that haven't changed.  I do have one question, do we want to consider Prefetch and H2 Push in as options for people to consider?

**Comment by petele** [comment]
Closing based on Ilya's feedback.

**Comment by igrigorik** [comment]
> Are there no places where you can add stuff like, "This is particularly
> important if you're doing [PWA | App Shell | *fillInTheBlank*]"?

We could. In particular, explain how/why caching the critical assets on the device will help, not only with offline cases, but with the general case because we're no longer at the mercy of random network delays / properties of the user's connection. That said, this is just another plug for why caching is good, which we already talk about.

> I do have one question, do we want to consider Prefetch and H2 Push in as options for people to consider?

Yeah, an explainer on pre{connect, fetch, render} + h/2 push would be good. This has been long on my list.. I'll try to tackle it in Q4.

**Comment by addyosmani** [comment]
> Yeah, an explainer on pre{connect, fetch, render} + h/2 push would be good. This has been long on my list.. I'll try to tackle it in Q4.

That would be incredibly valuable. Thanks Ilya!
