### ISSUE TITLE
Implementing Offline Analytics

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#3496]

**Comment by addyosmani** [comment]
Existing content: https://developers.google.com/web/updates/2016/07/offline-google-analytics?hl=en

**Comment by addyosmani** [comment]
Note that offline analytics are also briefly covered in the ILT content for https://github.com/google/WebFundamentals/issues/3455 (so we might already be covered on this). Let's coordinate with @samdutton who is currently assigned to that one.

**Comment by PaulKinlan** [comment]
Where abouts will this live on the site?

**Comment by petele** [comment]
Closing and merging into #3455
