### ISSUE TITLE
Intro to HTTP/2 Server Push

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3497]
HTTP/2 server push allows a server to provide content to clients without waiting for a request. This can improve the time to retrieve a resource, particularly for connections with a large bandwidth-delay product where the network round trip time comprises most of the time spent on a resource.

It's useful to have a short primer on this as we reference the topic in #3459 (PRPL). This could build on the intro to HTTP/2 @surma is looking at in #3464.    

**Existing content**
https://www.igvita.com/2013/06/12/innovating-with-http-2.0-server-push/
https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/
https://www.chromium.org/spdy/link-headers-and-server-hint

**Comment by PaulKinlan** [comment]
Where abouts will this live on the site?

**Comment by Meggin** [comment]
I can help with HTTP2 docs this week!

**Comment by addyosmani** [comment]
cc @samccone as he's been researching this area lately and may have some pointers on additional gotchas it is worth us calling out.

**Comment by samccone** [comment]
> This can improve the time to retrieve a resource, particularly for connections with a large bandwidth-delay product where the network round trip time comprises most of the time spent on a resource.

This is a very very nuanced thing  as far as where you can get objective wins. Misusing h2 push is actually very easy to do at the detriment to your users.

Perhaps an intro to h2 since the wins here are pretty easy to get.. with then a follow up to h2 push

**Comment by addyosmani** [comment]
> Perhaps an intro to h2 since the wins here are pretty easy to get.. with then a follow up to h2 push

That's the plan with #3464 :)

**Comment by x1ddos** [comment]
I think someone more experienced in writing should take this. I won't have enough time to deliver something I would be satisfied with.

**Comment by PaulKinlan** [comment]
Just to ask again, where do we see this document living?  In Performance?

**Comment by addyosmani** [comment]
@PaulKinlan I see this living in Performance. Wdyt, @petele?

**Comment by petele** [comment]
Yep, it should go under performance, and HTTP2 should move to it's own node and include the intro and push.

- Performance
  - ...
  - HTTP/2
    - Overview
    - Push

**Comment by surma** [comment]
Summoning @igrigorik

**Comment by igrigorik** [comment]
We already explain push in https://developers.google.com/web/fundamentals/performance/http2/#server_push. In HPBN I also have more guidance in https://hpbn.co/optimizing-application-delivery/#eliminate-roundtrips-with-server-push.. but, to be honest, I'm not sure duplicating all of the HPBN is a good idea; we're just adding more things to get out of sync without adding much value. I'd rather just link to relevant sections in HPBN.
