### ISSUE TITLE
Next: youtubeAPIKey.txt missing from source

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#3507]
`gulp build` throws an error for a missing file:

<img width="985" alt="screen shot 2016-09-26 at 11 28 55 am" src="https://cloud.githubusercontent.com/assets/238208/18842946/728f7234-83dc-11e6-9c9c-1fb292996d99.png">

**Comment by petele** [comment]
Correct, that's a Google API key, most folks won't need to run that step - only when publishing to DevSite. Did it fail the build, or just fail that section?

**Comment by ebidel** [comment]
Failed the section. Feel free to close if this is WAI.

**Comment by petele** [comment]
OK - yep, WAI.
