### ISSUE TITLE
Base template has `<meta name="robots" content="noindex">`

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#3508]
Just want to make sure this is intended. `gae/home.tpl` contains a meta tag to not index the content:

<img width="409" alt="screen shot 2016-09-26 at 11 52 30 am" src="https://cloud.githubusercontent.com/assets/238208/18843686/b177e1ae-83df-11e6-8c9e-c4330d539f30.png">

**Comment by ebidel** [comment]
@petele

**Comment by petele** [comment]
Yes - since the template is only used in the staging environment, not when published by devsite, we don't want the staged content indexed.

**Comment by ebidel** [comment]
Ack
