### ISSUE TITLE
Create a storage overview page

### ISSUE THREAD

**Issue by marcacohen** [google/WebFundamentals#3511]
Under the Fundamentals sub-tree, we should have an overview page on offline storage (or possibly storage in general, with sections on online/local and offline/remote). For now, this should be an overview, modeled on Addy's excellent [medium article](https://medium.com/dev-channel/offline-storage-for-progressive-web-apps-70d52695513c#.1x1a7gna5). Then, over time, we should add deeper dive local content on selected topics, like IndexedDB, localstorage, Cache API, etc.

**Comment by marcacohen** [comment]
Cross linking with [related issue](https://github.com/google/WebFundamentals/issues/3450) to add an IndexedDB page.

**Comment by marcacohen** [comment]
CC @addyosmani , @drufball as fyi

**Comment by addyosmani** [comment]
Per thread, this sgtm.

**Comment by PaulKinlan** [comment]
How does this correlate with what @Meggin was suggesting in her Instant and Offline refactoring doc?

**Comment by petele** [comment]
After discussing with Addy this morning, this should live in **Instant and Offline**

**Comment by marcacohen** [comment]
That's fine. Should we keep this, mod edits, as a storage overview page under I&O or do you prefer a diff strategy? I guess I'm asking is there value in a storage overview page like this or should we just have topic focused pages (IDB, cache api, firebase storage, etc.) without an overview?

**Comment by petele** [comment]
I think we need the overview that introduces each of the mechanisms and helps you understand when you should pick one over the other.

**Comment by marcacohen** [comment]
ok, thx.
