### ISSUE TITLE
Add RAIL to /web/fundamentals/performance

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3519]
It is crazy that we don't mention RAIL in the performance section and it's buried away in the /web/tools (I understand the context).

It would be good to get the RAIL guidance front and center in /web/fundamentals/performance

**Comment by addyosmani** [comment]
Is the ask here to move the current guide to /web/fundamentals/performance or add a section and cross-reference?

**Comment by PaulKinlan** [comment]
Personally, I would say move. It feels out of place in tools, but should be referenced from the tooling pages...

**Comment by PaulKinlan** [comment]
/web/tools/chrome-devtools/evaluate-performance/rail specifically.

**Comment by addyosmani** [comment]
@paullewis think you'll have time to do a moveeroo of that doc this week? If not one of us can squeeze it in.

**Comment by kaycebasques** [comment]
@addyosmani @paullewis @PaulKinlan I can move the doc

**Comment by addyosmani** [comment]
\o/

**Comment by Meggin** [comment]
Kayce, go for it 👍 

I've unassigned myself.
