### ISSUE TITLE
Enable staging of PRs for next-version

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#3521]
This is specifically for PRs into next-version.

This is the second of two issues that came out of #3330. Also see #3520.

**Comment by addyosmani** [comment]
\o/ Would a staged version be closer preview to what content might look like on devsite than the current local preview mechanism?

**Comment by petele** [comment]
Nope, it'd be identical. The only way to get an identical DevSite would be to stage on DevSite, which I can document if you think it'd be useful.

**Comment by addyosmani** [comment]
Nah. TBH the local preview is incredibly useful in the current form. I was mostly curious because I'm unsure how much difference there might be, but I imagine it's minimal.
