### ISSUE TITLE
broken links in new tools docs

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#3522]
Getting links from: http://localhost:8080/web/tools/chrome-devtools/console/console-reference
├─BROKEN─ http://localhost:8080/web/tools/chrome-devtools/console/console-ui#preserve-log (HTTP_404)
├─BROKEN─ http://localhost:8080/web/tools/chrome-devtools/console/console-ui#clearing (HTTP_404)

@kaycebasques - can you take a look, i'm not sure where these should actually link to.

**Comment by kaycebasques** [comment]
@petele I'll check it out
