### ISSUE TITLE
$(), shortcut for document.querySelector()？

### ISSUE THREAD

**Issue by charliethinker** [google/WebFundamentals#3542]
> $()   Returns the first element that matches the specified CSS selector. Shortcut for document.querySelector().

I use $() to get the first img, but returns an array of img. use document.querySelector() can return the first img.

See the figure：
![image](https://cloud.githubusercontent.com/assets/5362201/20131143/96030ed8-a696-11e6-92a4-e34d3a13ac38.png)

**Comment by kaycebasques** [comment]
Hey @charliethinker I just tried `$()` on a couple sites and it's working as expected. You might have had another JS library loaded that was overwriting the functionality of `$()`... Try it out on a few sites out in the wild and feel free to re-open this if you're still `$()` act like `document.querySelectorAll()`.
