### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by keipher** [google/WebFundamentals#3554]
I like the chrome developer tools. But I do have an issue with the choice of the international "no" symbol for the purpose of clearing the screen buffer. That symbol is to turn something off or block something, not to clear or erase something. If you don't like the trash can symbol at least pick something that indicates "erase/clear". Misusing symbols interferes with communication and renders symbols meaningless. 

I'm not a symbol cop, but I looked all over for the trash symbol and saw that "no" symbol, but I though that would turn off developer tools. That's is what that symbols indicates.

**Comment by addyosmani** [comment]
This issue tracker is for issues related to the developers.google.com documentation for /web. For issues specific to the Chrome DevTools, could you kindly repost your question about symbol consistency to crbug.com? The DevTools team will triage it and provide some insight into whether there would be interest in changing it over there.
