### ISSUE TITLE
Issues with SVGs in service worker articles

### ISSUE THREAD

**Issue by jeffposnick** [google/WebFundamentals#3564]
CC: @petele 

There are two issues with the SVGs in @jakearchibald's service worker articles that have been migrated into this repo:

On /web/fundamentals/instant-and-offline/offline-cookbook/, they're not cut off, but not animated (contrast with https://jakearchibald.com/2014/offline-cookbook/ where the animations help make the point).

On /web/fundamentals/instant-and-offline/service-worker/lifecycle, they're animated, but cut off:
![image](https://cloud.githubusercontent.com/assets/1749548/18997211/60833260-8701-11e6-8d28-afd5bcaee2a8.png)

**Comment by jakearchibald** [comment]
Huh, that's bizarre, it seems to be reserving the right amount of space. It was working locally for me, but I guess the iframe is no longer height 100% for some reason

**Comment by petele** [comment]
@jakearchibald - can you please investigate and fix.

**Comment by jakearchibald** [comment]
Shall do. @jeffposnick any particular browser/version?

**Comment by jeffposnick** [comment]
Sorry for not including it initially—the screenshot with the cut off SVG was on Mac Chrome 53.0.2785.116. I just reproduced the cut off SVG against the [production site](https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/lifecycle) in Firefox 49.

In Safari 10.0 (11602.1.50.0.10), it's worse, in that the SVG is missing entirely:
![image](https://cloud.githubusercontent.com/assets/1749548/19006643/b592376a-872e-11e6-848e-353e027074e5.png)

**Comment by jakearchibald** [comment]
Ohh, didn't realise it was on production now. Yeah, it didn't do that in dev, will investigate. Cheers.

**Comment by jakearchibald** [comment]
@petele I *think* this is fixed now. Unfortunately framebox is behaving different on dev to staging, so I can't be sure. Assigning to you since it needs deploying and verifying.
