### ISSUE TITLE
Use the proper formats for @font-face examples

### ISSUE THREAD

**Issue by RoelN** [google/WebFundamentals#3566]
In https://github.com/google/WebFundamentals/blob/master/src/content/en/fundamentals/performance/optimizing-content-efficiency/webfont-optimization.markdown the `@font-face` examples have invalid [format strings](https://www.w3.org/TR/css-fonts-3/#src-desc), e.g.

```
url('/fonts/awesome.woff2') format('woff2'), 
url('/fonts/awesome.woff') format('woff'),
url('/fonts/awesome.ttf') format('ttf'),
url('/fonts/awesome.eot') format('eot')
```

This should be 

```
url('/fonts/awesome.woff2') format('woff2'), 
url('/fonts/awesome.woff') format('woff'),
url('/fonts/awesome.ttf') format('truetype'),
url('/fonts/awesome.eot') format('embedded-opentype')
```

**Comment by RoelN** [comment]
Hi folk, any update on this? If you copy/paste this code now it'll result in invalid code.

**Comment by igrigorik** [comment]
Oi, yes, good catch.. this needs to be fixed, thanks for reporting it.

Aside: it's unfortunate that they didn't simply stick with extension names, makes everything super confusing!

**Comment by RoelN** [comment]
Absolutely. Or even better: leave them out and parse the actual extension names!

**Comment by igrigorik** [comment]
FWIW, my preference would be to be explicit.. since not all files have to have an extension.
