### ISSUE TITLE
Cache API stats issue

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3572]
https://developers.google.com/web/fundamentals/instant-and-offline/web-storage/ has a slightly incorrect piece of data about Cache Storage. the 92 figure references the [AppCache](http://caniuse.com/#search=cache) and not window.caches

**Comment by marcacohen** [comment]
Good catch, I'll correct and add links to the corresponding caniuse page so there clear accountability for those figures.

**Comment by marcacohen** [comment]
Added links to both MDN ref articles for each API and the caniuse page substantiating support numbers. Check me on the revised figure for cache API.
