### ISSUE TITLE
Hit a 404 from Search for Push Code Lab

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#3576]
https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-06?hl=en

Looks like everything is now a single file and url has codelabs in the name:

https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/

**Comment by PaulKinlan** [comment]
Ah, yes.  Looks like we moved primers in /primers in getting-started and codelabs in /codelab

**Comment by petele** [comment]
Fixed yesterday, now works.
