### ISSUE TITLE
Framebox without height behaves differently in dev & live

### ISSUE THREAD

**Issue by jakearchibald** [google/WebFundamentals#3577]
Discovered in #3564.

```
{% framebox %}
```

…on the dev server this produces `<iframe style="width: 100%;" …>`. On live it produces `<iframe style="width: 100%; height: 100px;" …>`.

**Comment by PaulKinlan** [comment]
I believe Pete said that it requires a height

**Comment by jakearchibald** [comment]
Throwing a template error when no height is set is a decent resolution.

**Comment by jakearchibald** [comment]
(although my preference would be to make it behave like the live server, since that's the least surprising)

**Comment by PaulKinlan** [comment]
yeah.

1) we could add a test to gulp-tasks/test.js to check from framebox,
2) as jake said, parity. devsiteHelper.py line 212

**Comment by petele** [comment]
Jake fixed
