### ISSUE TITLE
Author photo's get squashed when the bio is long

### ISSUE THREAD

**Issue by mustafa-x** [google/WebFundamentals#3578]
Author photo's get squashed when the bio is long

**Example:**
![screen shot 2016-10-03 at 10 38 08 am](https://cloud.githubusercontent.com/assets/1212513/19033382/ff43bba8-8955-11e6-964d-027700e3af2e.png)

**Proposed fix:**

```
.wf-byline img {
    min-width:64px
}
```

**Comment by mustafa-x** [comment]
Ive added a pull request to make my bio shorter, it seems to be the issue for breaking the design. But ideally we should fix this.

**Comment by shaz13** [comment]
Can I work on this issue?

**Comment by mustafa-x** [comment]
sure you can, just do a PR when you are ready.

**Comment by shaz13** [comment]
@mustafa-x  I have my code ready and signed the CLA agreement as stated in the docs.
For submitting the PR, Where should the source branch come from? 
Do I have to source the branch at my local repo or creating a branch in here is fine?

**Comment by surma** [comment]
@shaz13 Thanks for taking care of this! Regarding the PR: Can you create a branch based on master in your fork and PR that into this repo?

**Comment by mustafa-x** [comment]
what @surma said 👍

**Comment by shaz13** [comment]
@mustafa-x  @surma  Sure :+1:

**Comment by shaz13** [comment]
Couldnt build. 
Help needed.

![screenshot from 2017-05-02 21-18-18](https://cloud.githubusercontent.com/assets/24438869/25626345/e401b9ee-2f7c-11e7-9e70-e5559d793690.png)

[NPM log
](https://gist.github.com/shaz13/72efaee79426dc56e13acda15e767b3b)

**Comment by surma** [comment]
@shaz13 Did you follow the README on how to set up your local environment? 

Also, the screenshot is missing the crucial part of the error log, while the npm log doesn’t seem to contain the same data, sadly.

**Comment by surma** [comment]
`dev_appserver.py: command not found`.

It seems your App Engine SDK is not properly set up. Make sure that `dev_appserver.py` is in your `$PATH`.

**Comment by shaz13** [comment]
@surma Thanks a bunch. The PATH was already set right. I was trying without starting the Google App Engine. A restart made it all set. 
@mustafa-x One last check before pushing the PR. There are many; as many as 92 matches of property - 
```
.wf-byline img {

}
```
![screenshot from 2017-05-02 23-41-39](https://cloud.githubusercontent.com/assets/24438869/25632343/eb8f69d6-2f90-11e7-8a78-e38fec413e6b.png)

Shall I edit all of them or **only** **specific** one ?

**Comment by surma** [comment]
I’m pretty sure the HTML files are all generated. I am not sure where you’d find the source style sheet, tho :-/ I can take a look tomorrow

**Comment by shaz13** [comment]
Thanks for the info. Found the soruce file. PR is on the way. @surma  Thanks alot!

**Comment by shaz13** [comment]
@mustafa-x Made a PR. Kindly review it

**Comment by mustafa-x** [comment]
Hey @shaz13 - 

@petele will have to take a look at this when he is around, it might take some time though.

**Comment by shaz13** [comment]
Sure @mustafa-x  I can wait and perhaps look into another issue and submit a PR for it. Happy Summer :+1:

**Comment by shaz13** [comment]
@mustafa-x  and @surma I guess my PR is merged and this issue can be closed safely. Thanks!
