### ISSUE TITLE
"Responsive Web Design Patterns" - "Try It" links need updating.

### ISSUE THREAD

**Issue by JohnLukeBentley** [google/WebFundamentals#3590]
At [Responsive Web Design Patterns](https://developers.google.com/web/fundamentals/design-and-ui/responsive/patterns) all the "Try It" links return 404 errors.

E.g. https://googlesamples.github.io/web-fundamentals/samples/fundamentals/design-and-ui/responsive/patterns/mostly-fluid.html

Requires updating.

**Comment by petele** [comment]
Fixes in #3657, deploying now.

**Comment by JohnLukeBentley** [comment]
@petele Thanks! I've confirmed all the "Try It" links work at my end.
