### ISSUE TITLE
Set up redirect for Android Pay integration guide

### ISSUE THREAD

**Issue by agektmr** [google/WebFundamentals#3597]
[This old URL](https://developers.google.com/web/fundamentals/primers/payment-request/android-pay) is supposed be redirected to [this new URL](https://developers.google.com/web/fundamentals/getting-started/primers/payment-request/android-pay).

@petele Can you fix?
cc: @asieke

**Comment by petele** [comment]
I'll be at the PWAR tomorrow. Any chance you can add the redirect to the
_redirects.yaml file in src/content/en/. If not I'll do it when I've got
some time.

PEte
