### ISSUE TITLE
Fix problem with headings that use HTML entities

### ISSUE THREAD

**Issue by samdutton** [google/WebFundamentals#3599]
This is to remind me to fix problems with headings that use HTML entities, like this:

https://github.com/google/WebFundamentals/edit/master/src/content/en/updates/posts/2016/07/autoplay.markdown

https://developers.google.com/web/updates/2016/07/autoplay?hl=en

**Comment by petele** [comment]
Could you be more explicit about the issue here? Is this a content issue or a problem with the infrastructure?

**Comment by samdutton** [comment]
HTML entities in headings is causing problems (it used to be OK).

For example, on the page linked to above, this is in the Markdown: 

`title: "Muted autoplay on mobile: say goodbye to &lt;canvas&gt; hacks and animated GIFs!"`

This is in the HTML:

`<h1 itemprop="name" class="devsite-page-title">Muted autoplay on mobile: say goodbye to <canvas> hacks and animated GIFs!</canvas></h1>`

![image](https://cloud.githubusercontent.com/assets/205226/19122670/73879b0a-8b23-11e6-842b-110ffd030414.png)

**Comment by petele** [comment]
That file points to master, which we're not using any more, we're working from the next-version branch currently.

You'll need to fix it at https://github.com/google/WebFundamentals/blob/next-version/src/content/en/updates/2016/07/autoplay.md

It should have been caught in one of the tests, but looks like it wasn't. Will add a test to make sure it doesn't happen again.

**Comment by samdutton** [comment]
Thanks for the correct source link!

I've done a PR ay #3602.
