### ISSUE TITLE
Change the site promo banner to promote Chrome Dev Summit

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#3612]

**Comment by petele** [comment]
What do you want it to say?

**Comment by PaulKinlan** [comment]
err. Lemme check in with Katie.  We are specifically wanting to promote the livestream at the moment.

**Comment by PaulKinlan** [comment]
> Don't miss out on the action at this years [Chrome Dev Summit](https://developer.chrome.com/devsummit), happening on Nov 10th & 11th. [Register for livestream updates](https://services.google.com/fb/forms/cds2016/).
