### ISSUE TITLE
Migrate User Timing doc?

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#3630]
Should we migrate the HTML5Rocks doc to WF?

https://www.html5rocks.com/en/tutorials/webperformance/usertiming/

One motivation is that it doesn't mention DevTools. As I understand it, User Timing stuff shows up in Timeline recordings.

I could potentially do this, but I'd want to slim down the article

Lemme know @petele @PaulKinlan

**Comment by kaycebasques** [comment]
This could fit nicely in /web/fundamentals/performance

**Comment by PaulKinlan** [comment]
Yes, I would love to see this migrated.  Feels a good fit to have under performance.  @petele ?

**Comment by PaulKinlan** [comment]
@kaycebasques there is also guidance that @marcacohen wrote for PerforamnceObserver in /web/updates that would now be good to fold into fundamentals https://developers.google.com/web/updates/2016/06/performance-observer

**Comment by kaycebasques** [comment]
Still would be good to migrate but it doesn't seem that I'll be getting around to this
