### ISSUE TITLE
Example links on the JS Promises primer are broken

### ISSUE THREAD

**Issue by philwolstenholme** [google/WebFundamentals#3646]
On https://developers.google.com/web/fundamentals/getting-started/primers/promises the example links are broken.

Example broken example links:

* https://developers.google.com/web/fundamentals/getting-started/primers/_code/async-best-example
* https://developers.google.com/web/fundamentals/getting-started/primers/_code/async-example

**Comment by petele** [comment]
Fixed this in #3657, deploying now.
