### ISSUE TITLE
videos should have a max-width: 100% attribute

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#3668]
This needs to be deployed on DevSite.

**Comment by petele** [comment]
Fix has been submitted, to DevSite, waiting for review and deployment.

/cc @surma

**Comment by petele** [comment]
CL has been submitted, but they're in a code freeze right now. You may want to fix in that specific page temporarily.

**Comment by surma** [comment]
Thanks @petele. Will issue a PR shortly

**Comment by petele** [comment]
This has been fixed on DevSite

**Comment by surma** [comment]
🎉 🎉 🎉
