### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#3689]
[cloning the repo](https://github.com/google/WebFundamentals#cloning-the-repo) references `next-version` branch

**Comment by kaycebasques** [comment]
Also, when I run `npm install` and the `pip` command for setting up the repo, git is detecting untracked files... do we need to update `.gitignore`?

**Comment by petele** [comment]
I've created a PR (#3691) that updates the readme to remove the `next-version` comments. Can you take a peek and if it looks good to you, do a PR review and approve it? 

I've also checked in the Python Markdown library, and removed the exclude that I had for it. If you do a pull now, I think it should be good.

**Comment by petele** [comment]
PS - if all is good and you 'approve' the PR, please close this.
