### ISSUE TITLE
Content updates for Service Worker libraries

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3698]
## New libraries 📚

**sw-offline-google-analytics**: https://github.com/GoogleChrome/sw-helpers/tree/master/projects/sw-offline-google-analytics . Covered in https://developers.google.com/web/updates/2016/07/offline-google-analytics if you want to link up to it 

**sw-appcache-behavior**: https://github.com/GoogleChrome/sw-helpers/tree/master/projects/sw-appcache-behavior. A service worker implementation of the behavior defined in a page's App Cache manifest - helps migrate users away from AppCache -> Service Worker. 
## Videos 📹
- [Totally Tooling Tips: Service Worker Libraries](https://www.youtube.com/watch?v=IIRj8DftkqE&list=PLNYkxOF6rcIB3ci6nwNyLYNU6RDOU3YyL&index=8)
- [Totally Tooling Tips: Offline caching with sw-toolbox](https://www.youtube.com/watch?v=gfHXekzD7p0)
- [Great libraries and tools for building PWAs](https://www.youtube.com/watch?v=Use459WBeWc)
## Codelabs 💥

[Adding a SW with sw-precache](https://codelabs.developers.google.com/codelabs/sw-precache/index.html#0)
## Articles (team/community) 🗞
- [Getting started with sw-toolbox](http://deanhume.com/home/blogpost/getting-started-with-the-service-worker-toolbox/10134) by Dean Hume
- [Adding offline support to create-react-app using sw-precache](https://medium.com/dev-channel/create-react-pwa-7b69425ffa86#.3absuhu0j)

**Comment by addyosmani** [comment]
cc @jeffposnick as an FYI. Is there anything else worth including in the updates?

cc @gauntface Worth linking up to the FCM Web Push library work here too? (we don't currently reference it anywhere). Guess we could link up to https://firebase.google.com/docs/cloud-messaging/js/client?

**Comment by jeffposnick** [comment]
I put together a draft of some related material as part of the WebFundamentals hack week, linked to from https://github.com/google/WebFundamentals/issues/3453

@jpmedley, I don't know if you've reviewed it yet. If you find it useful, maybe it can just be incorporated into the deliverable tracked by this issue.

**Comment by jpmedley** [comment]
That was my plan.

**Comment by addyosmani** [comment]
@jpmedley do we think we can get these landed in time for CDS?

**Comment by jpmedley** [comment]
Yes.

**Comment by jpmedley** [comment]
Here's the result: https://developers.google.com/web/tools/service-worker-libraries/
