### ISSUE TITLE
Recording Audio from the user

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#372]
This is lower priority and not for launch.

TL;DR

*  Prefer getUserMedia (with mic selection and constraints) allows in-page audio experience
*  Use input type=file accept audio/* capture when not supported.

**Comment by PaulKinlan** [comment]
@petele it is low priority, but I am going to take a quick stab at this given that we have MediaRecorder and some other things.  This will live in web/fundamentals/native-hardware/ for now.

**Comment by petele** [comment]
Merged - closing.
