### ISSUE TITLE
[Italian Translation] Critical Rendering Path: should _shared template be translated?

### ISSUE THREAD

**Issue by mendaomn** [google/WebFundamentals#3769]
I've seen that in the Italian version of the [Critical Rendering Path article](https://github.com/google/WebFundamentals/blob/master/src/content/it/fundamentals/performance/critical-rendering-path/index.md), there's a paragraph written in English.

I would like to help with the translation in Italian but, being such paragraph taken from [this shared file](https://github.com/google/WebFundamentals/blob/master/src/content/en/_shared/udacity/ud884.html), I don't know how I could go about it. 

Is it supposed to stay in English?

**Comment by petele** [comment]
My inclination is that it should be translated, but I haven't tested it with our new infrastructure yet. Let me give it a shot today and see what happens. Will update the bug once I have a good answer.

**Comment by petele** [comment]
SWEET - the answer is yes. Essentially you'll need to create a new _shared folder in language (ie src/content/it/) and drop the translated file in there. It should work on staging and DevSite!
