### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#3778]
On https://developers.google.com/web/tools/chrome-devtools/javascript/step-code there's a broken link pointing to https://developers.google.com/web/tools/chrome-devtools/javascript/What%20do%20the%20colors%20mean%20in%20Chrome%20Developer%20Tools%20Scope%20panel

**Comment by kaycebasques** [comment]
devtools tracker: /web/tools/chrome-devtools/javascript/step-code

**Comment by kaycebasques** [comment]
DevToolsTracker
