### ISSUE TITLE
Iterate on the PRPL pattern doc

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3785]
Feedback from Alex R:

> - Using HTML Imports to keep the main thread interactive and parse in small chunks needs to be called out explicitly. 
> - The use of lazy upgrades to help ensure there's a structure that can be styled before elements load should probably be called out as something that other frameworks need to work at
> - Small-module loading has a lot of complication; not sure how deeply you want to go into it?
> - Might be worth calling out the high-level goal of interactivity in 3s on a 3G connection on moderate (~$200) hardware

My understanding of why Imports are a performance primitive is because they take advantage of the off-main-thread preload scanner to parse imports and fetch them async unlike modules, because the preload scanner can't look inside script. We haven't really talked about this in great detail anywhere and may need to decide whether this belongs directly in this doc or elsewhere that we link to.

Alex also called out that Imports also function as a natural way of structuring your code and managing module dependencies; this means that your imported modules _tend_ to be small. If you load them in this unvulcanized form (as Shop does), what you gets is that very, _very_ nice highly-chunked eval pattern that you see at the end of a Shop trace. Imports lead you down the road of small evals without extra infrastructure, which is CRITICAL to staying interactive.

cc @graynorton as we're iterating on PRPL in one of his docs and he may have thoughts here

**Comment by ebidel** [comment]
There's also some prior art at https://www.html5rocks.com/en/tutorials/webcomponents/imports/#performance on performance and ergonomic benefits.

There was also https://bugs.chromium.org/p/chromium/issues/detail?id=323096, which would have prefetched stylehsheets and subimports, making HTML imports even faster than they are today. That was marked as WontFix due to the lack of interest in Imports :\

**Comment by addyosmani** [comment]
We've been working on a set of specific improvements to the PRPL docs and will aim to get them in PR form this quarter.
