### ISSUE TITLE
Contributors list misses translation contributor

### ISSUE THREAD

**Issue by ymschaap** [google/WebFundamentals#3791]
I noticed the contributors list:
> https://developers.google.com/web/resources/contributors

Doesn't list me anymore. Although I translated a section (Merge: #1536) to Dutch which is also used and live:

> https://developers.google.com/web/fundamentals/discovery-and-monetization/social-discovery/?hl=nl-nl (NL) 

I know lots has changed with the move to developers.google.com. Is there a reason or is this a small mistake? I can make a PR to the _contributors.yaml file to resolve.

**Comment by petele** [comment]
Sorry about that, not sure why it was dropped. Should be deployed tomorrow morning.
