### ISSUE TITLE
Markdown should be able to handle multi-paragraph numbered items

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#3796]
Add the following Markdown to a page.

```
1. Hello this is line 1

   Hey this is line 2

1. I go by the name of line 3
```

Expected output:

```
1. Hello this is line 1

   Hey this is line 2

2. I go by the name of line 3
```

Actual:

```
1. Hello this is line 1
Hey this is line 2
1. I go by the name of line 3
```

Using `1.` for every line of a numbered list is valid Markdown syntax. The generator is supposed to detect that it's a numbered list and generate the correct number for each line accordingly. I use this trick because it increases productivity and reduces manual errors. It's a pain in the butt to manually write out each step number explicitly.

**Comment by petele** [comment]
Hey Kayce - Is there a behaviour difference between production and staging?

**Comment by garanj** [comment]
Trying this out locally I get your expected behaviour when ensuring I have my text indented to four:

```
1.  Hello this is line 1

    Hey this is line 2

1.  I go by the name of line 3
```

but get your experienced behaviour when using just one space after the number and dot.

Does that work for you?

**Comment by petele** [comment]
Closing as this is a DevSite markdown issue. :(
