### ISSUE TITLE
Missing tutorial code on Service Worker codelab

### ISSUE THREAD

**Issue by AidenWri** [google/WebFundamentals#3831]
Install the site assets section of codelab says to add the following code, but the code appears to be missing.

https://developers.google.com/web/fundamentals/getting-started/codelabs/offline/

![service worker codelab](https://cloud.githubusercontent.com/assets/10399607/20063709/1fa1eeae-a500-11e6-8439-e92ee19828f1.jpg)

**Comment by petele** [comment]
Thanks - I'll investigate what's going on here. In the mean time, you can also find this at <https://codelabs.developers.google.com/codelabs/offline/>

**Comment by petele** [comment]
i think this should be fixed now.
