### ISSUE TITLE
Page with wrong content

### ISSUE THREAD

**Issue by boyusun** [google/WebFundamentals#3876]
https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing

This page shows wrong content.

**Comment by petele** [comment]
What content is wrong? can you be more specific please?

**Comment by boyusun** [comment]
[Please see this pic](http://imgur.com/a/ofQhb)

**Comment by boyusun** [comment]
My bad, I think only the title is wrong.

**Comment by petele** [comment]
No worries. Just submitted PR #3882 which fixes the title. Will publish in the next couple of days.
