### ISSUE TITLE
Guidance about deferred service worker registration

### ISSUE THREAD

**Issue by jeffposnick** [google/WebFundamentals#3883]
I'm planning on putting together an article explaining a pattern for deferring service worker registration until after the initial uncontrolled page has had a change to load, to make it less likely that any precaching requests compete for bandwidth with requests for critical assets needed to display the page.

There will be various bits of supporting text going into more detail, but the gist of it would be to recommend using

```js
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register('/service-worker.js');
  });
}
```

as a sensible default, unless there's a specific need in your web app to register earlier on. (I'll cover those edge cases in the article.)

I've run this by a few folks from Chrome who seem to consider it reasonable, but was curious whether there were any concerns specific to Firefox's service worker implementation that might lead to this snippet being less-than-optimal. CC: @wanderview on that question.

Assuming we go ahead and publish the guidance, this issue can also track going through our backlog of service worker examples in our documentation, and updating them to follow that pattern when it makes sense to do so.

**Comment by wanderview** [comment]
This seems fine and reasonable to me.  This should also be safer if the site is using `clients.claim()` as you are less likely to suddenly start using the SW during the page load.

As a side note, should implementations just defer running registration steps till after load like we do for automatic update checks?

I know there have been some bugs with running `update()` during load in the past, but I believe we have fixed all those.  If you still see issues with that please let us know so we can fix them.  I think @gauntface saw something he thought was that issue, but I don't think we ever got a reproducible test case I could look at.

Thanks for checking with us!

**Comment by jeffposnick** [comment]
There's a valid use case for explicitly trying to register as early as possible: if a SW doesn't precache anything, but does use `clients.claim()` and aggressively uses runtime caching, it might want to activate as quickly as possible so that it has the chance to populate some runtime caches during the first load. That can be viewed as a good thing. So I'd hesitate to say the underlying browser behavior should change to make it impossible to register early.

The guidance is more along the lines of "you might not have realized that the timing of `serviceWorker.register()` matters, but here's why it does, and here's a reasonable best practice to follow for common use cases."
