### ISSUE TITLE
Contradiction in push notifications guidelines: when can the site ask for declined permissions again?

### ISSUE THREAD

**Issue by dandv** [google/WebFundamentals#3912]
At https://developers.google.com/web/progressive-web-apps/checklist#ensure-that-the-ui-that-encourages-users-to-turn-on-push-notifications-isnt-overly-aggressive:

> To test: Ensure that if you dismiss or decline to turn on push notifications that the site does not re-prompt in the same way within the same session.
To Fix: If users say they don't want a certain kind of notification, do not reprompt for at least a few days (for example, one week).

But the [guide to creating user friendly Notifications permissions flows](https://docs.google.com/document/d/1WNPIS_2F0eyDm5SS2E6LZ_75tk6XtBSnR1xNjWJ_DPE/view) linked if you scroll up one notch states:

> In Chrome, when a user denies a site access to a permission, that site will not ever be able to ask for it again.

(also, would be nice to have that guide moved to the devsite)

**Comment by jpmedley** [comment]
@gauntface I believe the later is the correct one, but I'll verify.

**Comment by gauntface** [comment]
So on permission prompt a user can allow, block or close the prompt. If the user allows everything is fine. If the user just closes the prompt then the web app can re-prompylt. If the user blocks then there is not re-prompt.

So the first paragraph should say dismiss, not "deny or dismiss".
