### ISSUE TITLE
Drop-off sentence in PWA codelab

### ISSUE THREAD

**Issue by Meggin** [google/WebFundamentals#3920]
In https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/, this sentence, "We're going to create a Weather app as our first Progressive Web App. The key components will consist of:" stops without any explanation.

Then it's followed by a new paragraph.

It might make sense to actually just delete it, as we are further along in the doc anyway.

**Comment by petele** [comment]
This needs to be updated in the Google Doc version, not the Git version. This is pulled directly from the Google doc version.
