### ISSUE TITLE
Contribution guidelines and sources missing for images

### ISSUE THREAD

**Issue by akshatgoel** [google/WebFundamentals#3927]
This may be a beginner issue but wanted to get clarification.

This is related to issue #3925 which asks for polishing illustration on ["What makes a good notification"](https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/images/tpnr.png)

I don't see any contribution guidelines or source files for images used. Is this something that is open for community contributions or is it meant to be as-is?

**Comment by petele** [comment]
We'd love your contributions - see https://developers.google.com/web/resources/ for more info!

thanks!
