### ISSUE TITLE
Language codes on third-party domains causing false test failure.

### ISSUE THREAD

**Issue by jpmedley** [google/WebFundamentals#3944]
An example is in Paul's [VR article](https://github.com/google/WebFundamentals/pull/3942/files), line 60 of `fundamentals/vr/getting-started-with-webvr/index.md`. 

In this case I was able to remove the `?hl=en` from the URL without consequences. We'll have problems if the code is every critical to the URL we're trying to link to.

**Comment by petele** [comment]
I don't think we should ever be adding a language code to URLs. A user should always get their preferred language, we should never force them into a specific language.
