### ISSUE TITLE
Nested bulleted list items are not indented

### ISSUE THREAD

**Issue by dandv** [google/WebFundamentals#3986]
There seems to be a problem with the Markdown parser: second-level list items are not indented because the generated HTML is a flat list of `<li>`s.

For example, at https://developers.google.com/web/tools/chrome-devtools/network-performance/understanding-resource-timing, I see this:

![image](https://cloud.githubusercontent.com/assets/33569/21383796/5e52d2f6-c71c-11e6-9538-ee7e25a40be9.png)

[The markdown](https://github.com/google/WebFundamentals/blob/master/src/content/en/tools/chrome-devtools/network-performance/understanding-resource-timing.md) is correct.

**Comment by kosamari** [comment]
closing this as this is fixed.
