### ISSUE TITLE
Can't View Computed and Styles at the Same Time

### ISSUE THREAD

**Issue by danallendotcom** [google/WebFundamentals#4011]
There is no practical way to view "styles" and "computed" at the same time. My research indicates that wastes many developers' time, toggling between the two panes. 

![screen shot 2017-01-06 at 10 50 23 pm](https://cloud.githubusercontent.com/assets/6373767/21739520/ae24978a-d462-11e6-93e8-a61e60f6baf6.png)
![screen shot 2017-01-06 at 10 54 40 pm](https://cloud.githubusercontent.com/assets/6373767/21739551/5403d5e4-d463-11e6-9c1d-382d08bc7b8f.png)

**Comment by nayphyoaung** [comment]
@

**Comment by kaycebasques** [comment]
Hi @danallendotcom I see your point that this could be frustrating. I forwarded your feedback to the DevTools issue / feature tracker.

https://crbug.com/689260

**Comment by danallendotcom** [comment]
Thank you taking a look and putting this into the next stage.

One thing I would add: the development tools that come with Chrome for Mac are great.phone

**Comment by KyubiBoy** [comment]
I think this issue has to be reopened. You can't access both styles and computed anymore... It's a bit frustrating after getting used to them :))

Could someone please look into this?

Thanks 😄
