### ISSUE TITLE
Fix sample for How to set Breakpoints

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#4016]
The `uncaught-exception-breakpoint.js` file used in [`/web/tools/chrome-devtools/javascript/add-breakpoints.md`](https://developers.google.com/web/tools/chrome-devtools/javascript/add-breakpoints) is not allowed per DevSite rules.

I've put the script in-line (#4015), but it breaks the sample as you can't edit script blocks in the main HTML. The script will need to be served from another domain, likely our Git samples repo.

**Comment by kaycebasques** [comment]
Fixed in #4136
