### ISSUE TITLE
Unify push notification UX guidelines

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#4034]
From @dandv 

We have two documents on good push notification UX:

What Makes a Good Notification? on Web Fundamentals
and
Best Practices for Push Notifications Permissions UX (strangely, a Google Doc)

Would it make sense to bring the latter under /web and/or merge it into the former?

CC @owencm, @jpmedley

**Comment by ithinkihaveacat** [comment]
Related: the [Material Design notification guidelines](https://material.io/guidelines/patterns/notifications.html).

**Comment by beverloo** [comment]
Missing links:
  - [What Makes a Good Notification](https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/good-notification)
  - [Best Practices for Push Notifications Permissions UX](https://docs.google.com/document/d/1WNPIS_2F0eyDm5SS2E6LZ_75tk6XtBSnR1xNjWJ_DPE/edit)

There's also the [Android UX](https://developer.android.com/training/notify-user/index.html) guidelines.

**Comment by gauntface** [comment]
When I wrote up the original permission UX, I had Owens doc in mind.

Is there a particular bit I'm missing here?
