### ISSUE TITLE
[DevTools CPU Profile Migration] missing features from original version

### ISSUE THREAD

**Issue by brenmar** [google/WebFundamentals#4035]
Missing features in 'new' Performance tab:

No Ability to 'Focus Selected Function' (eye icon), to narrow the call to down to a specific area of interest.

No Ability to exclude selected function (X) icon.

No ability to dedicate the whole dev tools area to the profile, 'new' implementation is like trying to profile through a letterbox, just compare the area dedicated to the profile in the old and 'new' version.

No ability to maintain multiple profiles, profiles tab allows you to record and compare multiple profiles, something essential if you're doing something like, you know, PROFILING!?!?

'new' version automatically clears out profile and starts profiling on a page refresh, making profiling a specific action within a page frustrating, you have to stop the profile, restart the profile then do the action. Might not sound like much, but profiling and performance tuning means repetition, so repeating these non-sensical actions is terrible UX. I understand that some people maybe profiling the page load but there is a specific button for that in the performance panel, this start profiling on page refresh should at least have the option to be disabled in settings.

**Comment by bedney** [comment]
Agree with all above - major step backwards for those of us trying to profile large amounts of JavaScript.

Couldn't figure out how to just start a profile without... reloading the page?? Um, this is the age of SPAs folks. I have (very) long-lived JS that continually stays loaded as I redraw the screen - how do I profile this? I'm not trying to profile page loading...

Tried using the `console.profile()` / `console.profileEnd()` calls to work around some of this... where does the output from that go?

Woosh. If these can't be fixed before this makes it to beta, please turn the old profiler back on.

**Comment by kaycebasques** [comment]
@brenmar @bedney thanks, very useful feedback. I've forwarded to the team.

I'll update the migration post to update this feedback

@bedney recording a running page is described in [How to record a JS profile](https://developers.google.com/web/updates/2016/12/devtools-javascript-cpu-profile-migration#record) from the post. You just click the button that says **Record** and then click the one that says **Stop** when you're done. Does that make sense?

`console.profile[End]()` needs to get migrated... I think that one is a work in progress

**Comment by pavelfeldman** [comment]
The old profiler is back, should be there in Canary tomorrow under DevTools -> Menu -> More Tools!

**Comment by bedney** [comment]
@kaycebasques - yes, that makes sense. I've played around a bit more and there are more things that make sense now.

I think @brenmar's comments were probably more succinct than mine. I would just encourage the team to think about those of us that are very JS focused here. I'm using the profiler to do pure JS profiling. So if changes are to be made, and I'm not against changes per se, I would just encourage folks to think about how the UI is going to handle those of us doing 'heavy JS'.

@pavelfeldman - Thanks for turning the old one back on! We appreciate it.

Thank you for your quick responses folks!

**Comment by kaycebasques** [comment]
I've got another issue to update the "update" post. Seems like the feature-y discussion is resolved. Thanks for getting involved, everybody.
