### ISSUE TITLE
Toggling to/from device mode cleans sessions and redirects to root-path

### ISSUE THREAD

**Issue by kweij** [google/WebFundamentals#4060]
Hi,

When I toggle to or from "Device mode" my session is emptied en when I refresh page, it returns to the homepage/root-path of the domain. This is quite annoying when testing because I can now either test **in** or **out** of "Device mode", toggling between them makes a mess.

I find this behaviour strange and can't see it as a feature, so I guess this is a bug.

Since I don't expect such annoying behaviour from Google products, perhaps there's something wrong with my local setup that could cause this behaviour - if so please let me know if there's a known cause for this.

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out [https://developer.chrome.com/devtools/docs/contributing](https://developer.chrome.com/devtools/docs/contributing) for how to ask questions or file issues on DevTools.
