### ISSUE TITLE
figure out how to fix notes styling on devtools homepage

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#4066]
I want to use the `note` widget to call out recent changes to DevTools panel name changes, but it's displaying funky. Note how the `aside` takes up the whole width of the content, behind the image. 

![screen shot 2017-01-20 at 11 53 29 am](https://cloud.githubusercontent.com/assets/4713486/22163301/154aacfc-df07-11e6-9807-7139a4be39b8.png)

![screen shot 2017-01-20 at 11 51 35 am](https://cloud.githubusercontent.com/assets/4713486/22163251/f0cd8ea8-df06-11e6-9c95-bd2680c0ad02.png)

**Comment by petele** [comment]
yep - devsite issue. you neeed to use a clearfix to fix that issue.
