### ISSUE TITLE
Broken links on MSE for Audio Update

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#4098]
There are a large number of broken links on https://web-central.appspot.com/web/updates/2015/06/Media-Source-Extensions-for-Audio, would you please take a look and remove/update as appropriate?

https://googlesamples.github.io/web-fundamentals/updates/sintel_0.mp3
https://googlesamples.github.io/web-fundamentals/updates/sintel_1.mp3
https://googlesamples.github.io/web-fundamentals/updates/sintel_0.mp3
https://googlesamples.github.io/web-fundamentals/updates/sintel_1.mp3
https://googlesamples.github.io/web-fundamentals/updates/mse-main.js

cc - @dalecurtis

**Comment by samdutton** [comment]
I've emailed separately about finding the most appropriate place for these — I guess we shouldn't have them in the Web Fundamentals repo.

**Comment by petele** [comment]
No, ideally not. @paullewis has a storage bucket that we use for WF that you could probably put them in if you wanted.
