### ISSUE TITLE
Chrome remote debugging (with usb device) docs missing important detail

### ISSUE THREAD

**Issue by isometriq** [google/WebFundamentals#4115]
- [ ] add `{:.external}` to external links
- [ ] "enable developer options" link should point to: https://developer.android.com/studio/debug/dev-options.html
- [ ] necessary to sign in to a chrome account? check if it works in guest mode or incognite mode
- [ ] chrome needs to be open on the Android

The docs about remote debugging, here:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3

..are not specific about the fact that Andoird SDK must be installed AND adb server needs to be running. Please adjust the doc, I've been wasting time to make it work!

My lifesaver:
http://stackoverflow.com/questions/21925992/chrome-devtools-devices-does-not-detect-device-when-plugged-in

**Comment by kosamari** [comment]
cc @kaycebasques

**Comment by kaycebasques** [comment]
Thanks for the bug @isometriq 

I'm assuming you're on Windows?

**Comment by kaycebasques** [comment]
https://blog.wizardsoftheweb.pro/chrome-remote-debugging-on-windows/

**Comment by kaycebasques** [comment]
https://stackoverflow.com/questions/48180771/chrome-dev-tools-not-detecting-nexus-5x-android-8-device

**Comment by kaycebasques** [comment]
https://stackoverflow.com/questions/48193487/getting-chrome-developer-tools-to-work-with-android-webview-over-usb
