### ISSUE TITLE
Fix the images used in the Media Session API updates article

### ISSUE THREAD

**Issue by xxyzzzq** [google/WebFundamentals#4118]
The lockscreen and Android wear images need to be updated
https://github.com/google/WebFundamentals/pull/4057
@beaufortfrancois

**Comment by beaufortfrancois** [comment]
The artwork used in these images is the one defined in the samples (eg. https://dummyimage.com/512x512).
What would you prefer?

**Comment by xxyzzzq** [comment]
Maybe use the notification image in the tldr, i.e. https://en.wikipedia.org/wiki/Rick_Astley#/media/File:Rick_Astley_Tivoli_Gardens.jpg?

**Comment by beaufortfrancois** [comment]
@xxyzzzq As soon as https://github.com/google/WebFundamentals/pull/4120 is reviewed, we should be good ;)
