### ISSUE TITLE
s/scan/select in bluetooth article

### ISSUE THREAD

**Issue by beaufortfrancois** [google/WebFundamentals#4140]
See https://twitter.com/janoszen/status/828538801358266368

**Comment by janoszen** [comment]
Just created a patch, I hope I didn't miss anything:
[google-web-fundamentals-4140.patch.txt](https://github.com/google/WebFundamentals/files/754240/google-web-fundamentals-4140.patch.txt)

Note that I don't have the build setup, I just modified the markdown file so please test it before you apply. Also, the screenshot could do with a better resolution, that's not included in the patch.

**Comment by beaufortfrancois** [comment]
@janoszen Here's https://github.com/google/WebFundamentals/pull/4141 that hopefully addresses your concerns.
