### ISSUE TITLE
Links in translate is missing

### ISSUE THREAD

**Issue by endo199** [google/WebFundamentals#4157]
I read documentation in English, the link is shown. But when I show in Indonesian, the link is gone

**Comment by petele** [comment]
Which page are you seeing this on?

**Comment by endo199** [comment]
[
Progressive Web App Anda yang Pertama](https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/)

The link that I mention before is link to download the source code and other resources
