### ISSUE TITLE
Comments are empty for non-canonical URLs

### ISSUE THREAD

**Issue by beaufortfrancois** [google/WebFundamentals#4169]
Comments show up at https://developers.google.com/web/updates/2017/02/media-session while they don't at https://developers.google.com/web/updates/2017/02/media-session#resources.

I guess we need to use the canonical URL when loading G+ comments.

R:@petele

**Comment by petele** [comment]
The comment widget uses the following script block:

```
<script async defer src="https://apis.google.com/js/platform.js" onload="gapi.comments.render('gplus-comments', {href: window.location, width: document.getElementById('gplus-comment-container').offsetWidth, first_party_property: 'BLOGGER', view_type: 'FILTERED_POSTMOD'});"></script>
```

To fix it, we probably need to build the `href` param from `window.location`,  but without the hash.

**Comment by beaufortfrancois** [comment]
I've sent you a patch to review. Let me know what you think.

**Comment by petele** [comment]
Reviewed, I can't approve, but have tagged in someone who can.

**Comment by beaufortfrancois** [comment]
Internal PR has been accepted and it is now live!
