### ISSUE TITLE
MSE primer nits

### ISSUE THREAD

**Issue by wolenetz** [google/WebFundamentals#4172]
Please feel free to split this out into multiple issues, if you need.

1.  Media Source Extensions spec is not linked. Link it please to https://www.w3.org/TR/media-source/

2.  Clarify "adaptive splicing". Perhaps: "Adaptive splicing, such as ad insertion"

3.  In the two instances of the full example code, there is a check after `updateend` event is received. The portion of the check that checks if `SourceBuffer.updating` is true doesn't make much sense to me in the context of the example, since it should be false. In more complex examples with multiple appendBuffers, it's more important to gate an attempted appendBuffer by first making sure the SourceBuffer isn't still updating. Apart from user agents (I think GPM reported Safari) having issues around managing their `updating` state, it should be false in this primer's two full examples, leading to dead code and never executing endOfStream().

4.  Figure 1 is referenced as "As illustrated above", when it could be to the side when the page is rendered in landscape.

5.  In the "Call endOfStream()" section, it states: "At the end of processing the media file...(call endOfStream)". A more generally applicable statement would be: "Once all of the media has been appended, and no further media is expected to be appended later, ... (call endOfStream)." Rewording the existing portion of "..." will also be necessary to make this fit right. Please also consider adding something like "This call lets the media element know to fire the 'ended' event, rather than wait for more appended media, when playback reaches the end of buffered media." (Yeah, the HTMLMediaElement spec goes into more detail, such as reverse playback direction, looping, etc, but we don't need that detail here IMHO.)

**Comment by wolenetz** [comment]
And 6. "// this refers to the mediaSource instance." should probably now be "e.target refers to ..."

**Comment by wolenetz** [comment]
ANd 7 :) : Please consider including revokeObjectURL somewhere (in the sourceopen handler, most likely) to set a good example for web authors to help prevent resource leaks.

**Comment by wolenetz** [comment]
Finally 8: I see mixed addEventListener and on... usage. From other conversation, my understanding is that addEventListener is preferred for these documents. Specifically the `onupdateend` should probably be switched to `addEventListener` style.

**Comment by jpmedley** [comment]
@wolenetz I think I've covered everything.
