### ISSUE TITLE
Custom Elements primer should clearly show unimplemented features

### ISSUE THREAD

**Issue by samthor** [google/WebFundamentals#4206]
[This page](https://github.com/google/WebFundamentals/blob/master/src/content/en/fundamentals/getting-started/primers/customelements.md) does not make it clear that `is=""` and `extends:` aren't yet supported in Chrome either ([see bug](https://bugs.chromium.org/p/chromium/issues/detail?id=652579)).

**Comment by 75lb** [comment]
ah, so that's why the "Extending native HTML elements" example doesn't work.. 

```js
> class FancyButton extends HTMLButtonElement {} 
> customElements.define('fancy-button', FancyButton, {extends: 'button'});
> b = new FancyButton()
VM2159:1 Uncaught TypeError: Illegal constructor
    at FancyButton (<anonymous>:1:1)
    at <anonymous>:1:5
```
