### ISSUE TITLE
Random superscript "L" sprinkled throughout the text Chrome 56

### ISSUE THREAD

**Issue by scatory** [google/WebFundamentals#4211]
on this page a few random super scripted "L"s has been sprinkled into the text throughout the site when viewed in Explorer Chrome 56. Any ideas?

http://www.qbrelis.com

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
