### ISSUE TITLE
Feedback for: Setting Up the Labs [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4224]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/setting-up-the-labs.md

@petele 

The "Set up Node and install the lab repository" section has multiple formatting issues. The bullets & numbers are messed up, and code is not in code blocks. There might be one issue early on that is propagating down the rest of the section/doc?

Source reference:
https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/setting_up_the_labs.html#set-up-node-and-install-the-lab-repository

**Comment by petele** [comment]
Merging to #4261
