### ISSUE TITLE
Feedback for: Setting Up the Labs [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4229]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/setting-up-the-labs.md

Link issues:

1. "switch to another version" should be linked to https://github.com/creationix/nvm#usage (this was a mistake in the source material, not a conversion error)

2. "disable the HTTP cache" internal link is misformatted
* Underscores in the GitBook file name were converted to dashes
* Underscores were added to internal href value
* The .md extension was added to the GitBook file name

Ex: 

Source link:
https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/tools_for_pwa_developers.html#disablehttpcache

Converted link:
https://pr-4202-dot-web-central.appspot.com/web/ilt/pwa/tools_for_pwa_developers.md#disablehttpcache

Converted resource:
https://pr-4202-dot-web-central.appspot.com/web/ilt/pwa/tools-for-pwa-developers#disable_http_cache

Source doc for reference
https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/setting_up_the_labs.html#set-up-node-and-install-the-lab-repository

**Comment by petele** [comment]
The first issue will need to be fixed in the GDoc source, the second is fixed in 62e7edefc69bbe9380261e8b64165dec7c59f38e
