### ISSUE TITLE
Feedback for: Running a Local Web Server [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4231]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/running-a-local-web-server.md

This doc is outdated. It was from before we started using Node in the labs. It's a nice resource but it doesn't align with the labs anymore. We should probably remove it. If we really want to keep it then it will need to be edited to match the new course design or to exist as a stand alone document. (Also there are grammar issues.)

**Comment by petele** [comment]
Will yank.
