### ISSUE TITLE
Feedback for: Debugging Service Workers in Browsers [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4232]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/debugging-service-workers-in-browsers.md

This doc is outdated. This information was incorporated into the [Tools for PWA Developers](https://pr-4202-dot-web-central.appspot.com/web/ilt/pwa/tools-for-pwa-developers) content. We can remove this.

**Comment by petele** [comment]
Fixed in dc250906c168cc1dbcd1b51b748543193d7997d2
