### ISSUE TITLE
Feedback for: Lab: Scripting the Service Worker [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4250]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/lab-scripting-the-service-worker.md

in "1. Get set up" section, child bullets are losing indentation and formatting like parent bullets.

Example:
![screen shot 2017-02-23 at 3 15 19 pm](https://cloud.githubusercontent.com/assets/16726377/23283517/35ccc930-f9db-11e6-9e59-0e5e2da460b4.png)

Should look like:
<img width="699" alt="screen shot 2017-02-23 at 3 15 31 pm" src="https://cloud.githubusercontent.com/assets/16726377/23283522/3a57efca-f9db-11e6-9b4a-c46e9639120d.png">

[GitBook reference](https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/lab_scripting_the_service_worker.html)
[Source doc](https://docs.google.com/document/d/15gTwKdL7XZNmw1AQlBSRnmA1Xju_mhMcUU0jM5bwhUw/edit#)

**Comment by petele** [comment]
Merging to single issue #4256
