### ISSUE TITLE
Feedback for: Lighthouse PWA Analysis Tool [en]

### ISSUE THREAD

**Issue by nasearle** [google/WebFundamentals#4253]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool.md

URL highlighted as a comment in command line code:

![screen shot 2017-02-24 at 10 31 11 am](https://cloud.githubusercontent.com/assets/14795039/23315821/bcab90f2-fa7c-11e6-9824-cc772c8894de.png)

**Comment by petele** [comment]
Merging to a single bug #4258
