### ISSUE TITLE
Feedback for: Lab: Responsive Design [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4254]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/lab-responsive-design.md

Small syntax highlighting issue - some arbitrary code being highlighted blue.

in **5.2 Add first responsive layout** and **7.2 Use Flexbox progressively** sections:

![screen shot 2017-02-24 at 10 47 28 am](https://cloud.githubusercontent.com/assets/16726377/23317010/9c3b7ea4-fa81-11e6-8d0d-e7431ffa2b1d.png)

in **7.2 Use Flexbox progressively**

![screen shot 2017-02-24 at 10 56 58 am](https://cloud.githubusercontent.com/assets/16726377/23317014/a0fd62e0-fa81-11e6-9610-87a26bf994bf.png)

[GitBook reference](https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/lab_responsive_design.html)
[Source doc reference](https://www.gitbook.com/book/google-developer-training/progressive-web-apps-ilt-codelabs/edit#/edit/master/docs/lab_responsive_design.md?_k=ovh5b0)

**Comment by petele** [comment]
merging to single issue #4258
