### ISSUE TITLE
[ilt-pwa] claat exporter doesn't support nested lists

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#4256]
* `src/content/en/ilt/pwa/lab-scripting-the-service-worker.md`
* `src/content/en/ilt/pwa/lab-promises.md`

**Comment by DavidScales** [comment]
* `src/content/en/ilt/pwa/lab-gulp-setup.md`

**Comment by DavidScales** [comment]
@petele @nasearle we just restructured these in the source docs so that they don't have nested lists. Probably the easiest solution for now.

**Comment by petele** [comment]
this is a md thing that can't be fixed easily
