### ISSUE TITLE
[ilt-pwa] devsite syntax highlighting hiccups

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#4258]
* `src/content/en/ilt/pwa/lighthouse-pwa-analysis-tool.md`
* `src/content/en/ilt/pwa/lab-responsive-design.md`
* `src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md`
* `src/content/en/ilt/pwa/lab-responsive-images.md`

**Comment by DavidScales** [comment]
* `src/content/en/ilt/pwa/lab-fetch-api.md`

**Comment by nasearle** [comment]
- `src/content/en/ilt/pwa/e-commerce-lab-1-create-a-service-worker.md`
