### ISSUE TITLE
Feedback for: Working with the Fetch API [en]

### ISSUE THREAD

**Issue by nasearle** [google/WebFundamentals#4259]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/working-with-the-fetch-api.md

Link to "previous section" not working.

![screen shot 2017-02-24 at 12 07 35 pm](https://cloud.githubusercontent.com/assets/14795039/23319085/02c33fec-fa8a-11e6-8ece-74022ccd7417.png)

Looks like the exporter created an `<a>` tag and wrapped it around the heading instead of creating an empty div tag above the heading:

![screen shot 2017-02-24 at 12 12 38 pm](https://cloud.githubusercontent.com/assets/14795039/23319260/af8082c6-fa8a-11e6-8a15-34eb7195f777.png)

**Comment by petele** [comment]
Fixed - the `<a id="head">` element in the GDoc was formatted as an "Heading 2", which broke the exporter
