### ISSUE TITLE
Feedback for: Lab: Responsive Images [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4260]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/lab-responsive-images.md

in **4.1 Display an image at half the width of the viewport (50vw)** and **5.1 Add a media query to the CSS** sections, there is a small syntax highlighting issue. The `#` symbol is converting the following CSS to a red comment.

![screen shot 2017-02-24 at 12 14 27 pm](https://cloud.githubusercontent.com/assets/16726377/23319500/a9c40082-fa8b-11e6-82ac-b69b861b2499.png)

[GitBook reference](https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/lab_responsive_images.html)
[Source reference](https://docs.google.com/document/d/1HSql73oflxJAujGNzKdzsuN034BOZf1xFUsg1ej_Tz8/edit#)

**Comment by petele** [comment]
Merging into #4258
