### ISSUE TITLE
[ilt-pwa] Block level elements break lists

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#4261]
* `src/content/en/ilt/pwa/setting-up-the-labs.md`
* `src/content/en/ilt/pwa/introduction-to-progressive-web-app-architectures.md`
* `src/content/en/ilt/pwa/tools-for-pwa-developers.md`

**Comment by nasearle** [comment]
src/content/en/ilt/pwa/introduction-to-gulp.md
