### ISSUE TITLE
Feedback for: Lab: Fetch API [en]

### ISSUE THREAD

**Issue by DavidScales** [google/WebFundamentals#4264]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/lab-fetch-api.md

In **Congratulations!** section, "Fetch API Concepts" still links to GitBook rather than /web resource.

[GitBook reference](https://google-developer-training.gitbooks.io/progressive-web-apps-ilt-codelabs/content/docs/lab_fetch_api.html)
[Source reference](https://docs.google.com/document/d/1RwBR3atWRcQIex8lpa2kHAqhtrgxdNVT5-0zfTpx6Ok/edit#)

**Comment by petele** [comment]
The GDoc source was pointing to an old URL, I've updated it in the Google Doc, but in future, please update the GDoc source
