### ISSUE TITLE
new summary text on top of pages displays unhelpful info on devtools homepage

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#4265]
![screen shot 2017-02-24 at 2 57 28 pm](https://cloud.githubusercontent.com/assets/4713486/23324277/a3e09e62-faa1-11e6-9046-3e8733ead20d.png)

See "Option 1" under "Tools"

I'd also like for this to say "Chrome DevTools" rather than "Tools". Maybe we can just re-org the YAML files?

**Comment by petele** [comment]
i think this is fixed, if not, please re-open
