### ISSUE TITLE
HTML Entities appearing in links, under Updates category

### ISSUE THREAD

**Issue by shavs** [google/WebFundamentals#4266]
# Issue:
Currently, HTML entities are being shown in the hamburger menu.
Expected behaviour should be: `"Stream" video using the MediaSource API`
Current behaviour is: `&quot;Stream&quot; video using the MediaSource API` 

## Reproduction of Issue:
[ Link to " "Stream" video using the MediaSource API " page](https://developers.google.com/web/updates/2011/11/Stream-video-using-the-MediaSource-API)

Issue appears in Updates > 2011 > November within the hamburger menu / sidebar menu.

## Other related issues:
` Big boost to DOM performance - WebKit&#x27;s innerHTML is 240% faster `
Found in Updates > 2012 > April
[Link to page affected](https://developers.google.com/web/updates/2012/04/Big-boost-to-DOM-performance-WebKit-s-innerHTML-is-240-faster)

`Don&#x27;t Build Blobs, Construct Them`
Found in Updates > 2012 > June
[Link to page affected](https://developers.google.com/web/updates/2012/06/Don-t-Build-Blobs-Construct-Them)

`Integrating input[type&#x3D;file] with the Filesystem API`
Found in Updates > 2012 > August
[Link to page affected](https://developers.google.com/web/updates/2012/08/Integrating-input-type-file-with-the-Filesystem-API)

`Interactive Globe with CSS shaders &amp; Google Maps`
Found in Updates > 2012 > September
[Link to page affected](https://developers.google.com/web/updates/2012/09/Interactive-Globe-with-CSS-shaders-Google-Maps)

`Profiling Long Paint Times with DevTools&#x27; Continuous Painting Mode`
Found in Updates > 2013 > February
[Link to affected page](https://developers.google.com/web/updates/2013/02/Profiling-Long-Paint-Times-with-DevTools-Continuous-Painting-Mode)

`What&#x27;s the CSS :scope pseudo-class for?`
Found in Updates > 2013 > March
[Link to affected page](https://developers.google.com/web/updates/2013/03/What-s-the-CSS-scope-pseudo-class-for)

`Flexbox layout isn&#x27;t slow`
Found in Updates > 2013 > October
[Link to affected page](https://developers.google.com/web/updates/2013/10/Flexbox-layout-isn-t-slow)

`New Web Animations engine in Blink drives CSS Animations &amp; Transitions`
Found in Updates > 2013 > December
[Link to affected page](https://developers.google.com/web/updates/2013/12/New-Web-Animations-engine-in-Blink-drives-CSS-Animations-Transitions)

`Chrome Dev Summit 2014: Let&#x27;s build some apps with Polymer!`
Found in Updates > 2015 > January
[Link to affected page](https://developers.google.com/web/updates/2015/01/Lets-build-some-apps-with-Polymer)

`Prioritizing Your Resources with link rel&#x3D;&#x27;preload&#x27;`
Found in Updates > 2016 > March
[Link to affected page](https://developers.google.com/web/updates/2016/03/link-rel-preload)

**There may be more pages affected - these are the page links that I have spotted to have issues.**

# Image example of issue
![Image example of HTML Entities Issue](https://cloud.githubusercontent.com/assets/9111519/23339589/ee954a52-fc1d-11e6-8bcc-15073787290a.png)

# Browsers tested
Firefox Mobile version 50.1.0
Firefox Linux x86_64 version 51.0.1

Chromium x86_64 version 56

**Comment by kosamari** [comment]
closing this issue as this is fixed in current version !
