### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by gs-rpal** [google/WebFundamentals#4268]
Encoding is not proper.

![screen shot 2017-02-27 at 4 08 23 pm](https://cloud.githubusercontent.com/assets/23516439/23358225/227b2adc-fd07-11e6-8644-200b7e5f62fd.png)

**Comment by petele** [comment]
What page are you seeing this on?

**Comment by StefanGreffenius** [comment]
Let me [google](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:google.com+%22notifications%26mdash;%22&*) this. Sorry couldn't resist =)

Looks like https://developers.google.com/web/fundamentals/getting-started/primers/service-workers :+1:

**Comment by gs-rpal** [comment]
Yeah. 👍

On Wed, Mar 15, 2017 at 6:53 PM, Stefan Greffenius <notifications@github.com

**Comment by kosamari** [comment]
this seems to be addressed & fixed
