### ISSUE TITLE
Feedback for: Introduction to the Payment Request API [en]

### ISSUE THREAD

**Issue by nasearle** [google/WebFundamentals#4277]
https://github.com/google/WebFundamentals/blob/master/src/content/en/ilt/pwa/introduction-to-the-payment-request-api.md

"Introduction to Push Notifications" link under Concepts in the sidebar links to Introduction to the Payment Request API. And the Introduction to the Payment Request API link is a 404.

**Comment by petele** [comment]
Fixed in 7676d077821f2100273cb2e2159e66f46248878c, should be live in a few minutes.
