### ISSUE TITLE
[DevTools / JS / Get Started / (3) Paused On Correct Line]

### ISSUE THREAD

**Issue by trevor-coleman** [google/WebFundamentals#4303]
Hey there -- I'm paused on line 1598 of a file called "onloadwff.js" -- I imagine it's a browser extension or something.

**Comment by trevor-coleman** [comment]
Ah yeah it was lastpass. Loaded an incognito window and it seems to be working now, but I'm on line 22

` if (getNumber1() === '' || getNumber2() === '') {`

**Comment by trevor-coleman** [comment]
Ah -- when I step through it takes me through evaluating each of those.

**Comment by kaycebasques** [comment]
Hey @trevor-coleman thanks for reporting! I really appreciate it.

Sounds like you figured it out? See this comment if not: https://github.com/google/WebFundamentals/issues/4311#issuecomment-286271346

Thanks to contributions like yours I updated the feedback response (the section that provided you the link to report an issue) describing how to get past this scenario :)
