### ISSUE TITLE
[DevTools / JS / Get Started / (2) Triggered The Breakpoint]

### ISSUE THREAD

**Issue by dshiling** [google/WebFundamentals#4311]
Can't trigger the breakpoint ' function onClick() { '  on step two of js debugger demo. I keep getting the event listener click that I just created so the step through doesn't appear to be working as it should in the next step. I've tried incognito, updating to chrome 57, and disabling  lastpass/abp. See here for incognito screenshot: 
![screen shot 2017-03-12 at 1 34 48 pm](https://cloud.githubusercontent.com/assets/26364453/23834196/b60320cc-0728-11e7-989f-b65b11dfabad.png)

Any help would be appreciated :)

**Comment by kaycebasques** [comment]
Hey @dshiling thanks for reporting. You've got an extension that is intercepting your clicks, I assume that's what you mean by `lastpass/abp`.

So, if I understand correctly, you set the `click` event breakpoint, then click **Add Number 1 and Number 2** on the demo, and then it pauses on the location provided in the screenshot.

From there, have you tried clicking **Resume Script Execution**. DevTools will continue executing until it encounters another `click` event. It should eventually land on the line of code mentioned in the tutorial.

Make sense?

**Comment by kaycebasques** [comment]
Thanks to contributions like yours I updated the feedback response (the section that provided you the link to report this issue) describing how to get past this scenario :)

**Comment by dshiling** [comment]
Thank you for your help! Worked like a charm and glad to know I could provide some decent feedback :)
