### ISSUE TITLE
Podcast XML Feed Error

### ISSUE THREAD

**Issue by mustafa-x** [google/WebFundamentals#4324]
The XML feeds generated seem to pull in some errors when displayed in iTunes. The image appears in the description as HTML. 
![screen shot 2017-03-16 at 12 05 25 pm](https://cloud.githubusercontent.com/assets/1212513/23995453/9562b500-0a41-11e7-899a-ac227db164f6.png)

**Comment by paullewis** [comment]
The problem seems to be this line here: https://github.com/google/WebFundamentals/blob/master/src/templates/shows/podcast.xml#L24

@petele Am I right you did this work? Git blame implies it, but I figure it may be an artifact of merging other things and so on.

**Comment by petele** [comment]
yep - did the work, prob won't have time to fix or investigate until next week when back state side, so feel free to attempt to fix if it's it really bugs ;)

**Comment by paullewis** [comment]
Well the fix looks straight forward, insofar as removing the image from the template... I guess I was wondering if there's a reason it's in there?

**Comment by petele** [comment]
It was in there because we use the imgs for analytics, but on investigation, iTunes doesn't allow any images in the description. I've fixed and cleaned up the feeds a bit.

**Comment by paullewis** [comment]
Thank you sir! 👍

**Comment by mustafa-x** [comment]
Thank you Pete!!
