### ISSUE TITLE
scope key is missing in "The Web App Manifest" primer

### ISSUE THREAD

**Issue by beaufortfrancois** [google/WebFundamentals#4333]
Navigation scope of the web application's application context is missing in https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/

See https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by gauntface** [comment]
Why don't we just link out to the MDN docs?

**Comment by gauntface** [comment]
We link to the complete reference at the end of the docs. Feel free to add in if you think it's important but I feel like the docs is long enough.
