### ISSUE TITLE
Web tutorial on debugging w/ DevTools does not produce expected result.

### ISSUE THREAD

**Issue by alxfyv** [google/WebFundamentals#4343]
In the article Web "Get Started With Debugging JavaScript In Chrome DevTools, at Step 2 "Pause the code with a breakpoint," with DevTools open and in the state directed by the article, clicking on the "Add Number 1 And Number 2" button produces no breakpoint. Nor did the execution stop on another line of code. Rather, it continued to the end reproducing the error (5 + 1 =51).

Moreover, clicking on the "file an issue" link produced no result.

Chrome 57.0.2987.110 (64-bit); MacBook Air running Sierra 10.12.3.

**Comment by kosamari** [comment]
Hi @alxfyv I was not able to reproduce the described bug in deb tools, however, I did noticed  "file an issue" link error. I'll file separate issue for that. Thanks !
