### ISSUE TITLE
Article uses property letter casing instead of attribute casing in code examples

### ISSUE THREAD

**Issue by EvilOatmeal** [google/WebFundamentals#4361]
In the article [Media Updates in Chrome 58](https://developers.google.com/web/updates/2017/03/chrome-58-media-updates) the property letter casing (`controlsList`) is used in places where the attribute letter casing (`controlslist`) should be used.

The correct letter casing can be seen in [the explainer document](https://github.com/WICG/controls-list/blob/gh-pages/explainer.md) linked from the article:
> The `controlsList` property will reflect the `controlslist` attribute

**Comment by EvilOatmeal** [comment]
Ping author @beaufortfrancois

**Comment by beaufortfrancois** [comment]
@EvilOatmeal This is actually intentional.
I didn't want to confuse readers with "controlsList" (in JavaScript) and "controlslist" (in HTML).

**Comment by EvilOatmeal** [comment]
Alright. Closing this then.
