### ISSUE TITLE
[Lighthouse / Estimated Input Latency / Helpful]

### ISSUE THREAD

**Issue by EnoahNetzach** [google/WebFundamentals#4362]
In the doc it is stated to "See the [What the audit tests for](https://developers.google.com/web/tools/lighthouse/audits/estimated-input-latency#what) section of this doc for an explanation" in the "Why" section, but there is no "What" section to be found.

**Comment by EnoahNetzach** [comment]
Just to give context, I'm getting a 0 mark in that test (Estimated Input Latency), but I don't know how, because in that specific page I have no inputs –only pre-rendered anchors and buttons– so user latency on what?

**Comment by kaycebasques** [comment]
Hey @EnoahNetzach the "what" section is the last section, "How the audit is implemented".

That section says that it's not actually testing the responsiveness of user input elements like buttons. It's using a proxy: main thread usage. If the main thread is busy for 50ms or more then you're going to get a low score on the test.

It's a complicated audit, I know. Let me know if this makes sense or if you have more Qs

**Comment by kaycebasques** [comment]
TODO for self: fix the reference to "what the audit tests for"

**Comment by EnoahNetzach** [comment]
Thanks @kaycebasques, my uncertainty arose from the missing `id=''what"`, so I expected there to be more info.

It is not very complicated to understand what the metric means, at this point (at least, for me), but I think there are a couple things there I've not fully understood:
- this metric is taken from the start?
- if so, shouldn't be better called "Estimated Initial Input Latency"?
- if no, how can I reliably and consistently reproduce that estimate? (I'm asking about timings, or when to start to measure)

**Comment by kaycebasques** [comment]
Hey @EnoahNetzach sorry for delay

The timing is from First Meaningful Paint to "end of trace" which is roughly, at max, 5 seconds after Time To Interactive
