### ISSUE TITLE
Feature Request: Delete timeline selection

### ISSUE THREAD

**Issue by greglockwood** [google/WebFundamentals#4364]
It would be helpful to be able to delete irrelevant parts of a timeline recording. 

This would benefit the top panel the most, as it would allow the relevant portion to expand to fill the available width, making it easier to navigate, and enable showing more screenshot snapshots, etc.

The most common use case for this is when I end up with a recording that has a long, uninteresting mostly blank bit in the beginning, followed by all the interesting stuff squished at the end, like so:

![Screenshot](https://i.imgur.com/yI8qeMa.png)

**Comment by kosamari** [comment]
Hi @greglockwood 👋 Thanks for the suggestion. This repo is tracking issues with content on the web fundamentals site. 

Check out https://bugs.chromium.org/p/chromium/issues/list to file a feature request or check out https://developers.google.com/web/tools/chrome-devtools/#get_involvedfor for more communication channel with DevTools folks, thanks!
