### ISSUE TITLE
local-storage refers to, but fails to include a document on Service Worker caches

### ISSUE THREAD

**Issue by dbs** [google/WebFundamentals#4381]
The section on local storage discussing Service Worker caches says "Check out the guide below for more help" but the `include` directive for the guide does not resolve, leading directly to the next section on clearing the SW cache. A bit confusing to read, and not very helpful :)

    ## Service Worker Caches {:#service-worker-caches}
    
    The **Cache Storage** pane on the **Application** panel lets you inspect,
    modify, and debug caches created with the (service worker) Cache API. Check
    out the guide below for more help.

    {# include shared/related_guides.liquid inline=true list=page.related-guides.pwa #}

**Comment by kosamari** [comment]
cc : @kaycebasques

**Comment by kaycebasques** [comment]
[The page in question](https://developers.google.com/web/tools/chrome-devtools/manage-data/local-storage) has been deprecated. Thanks for the report @dbs.
