### ISSUE TITLE
Describe about "error" property in Payment Request document

### ISSUE THREAD

**Issue by agektmr** [google/WebFundamentals#4382]
In response to `updateWith()` function in `shippingaddresschange` event and `shippingoptionchange` event, specifying `error` will display an error in the UI. Clarify that in the document.

**Comment by agektmr** [comment]
Hey @gauntface, if you are working on a doc, can you take this one?

**Comment by gauntface** [comment]
I already have ;)

**Comment by kosamari** [comment]
assuming this is addressed already :) closing the issue.
