### ISSUE TITLE
[Lighthouse / Time To Interactive / Helpful]

### ISSUE THREAD

**Issue by zyzski** [google/WebFundamentals#4390]
Would be nice to see some benchmark numbers and possible real world effects of each.

Ex: 
- 5000ms - too slow, X% of users leave the page
- 4000ms - slow, users expect page to be loaded, trying to press UI elements
- 1000ms - great baseline score
- 500ms - perfect score

**Comment by paulirish** [comment]
good call.  we could do something like that
we could also link to the scoring curve, which kind of indicates these benchmark figures.

cc @patrickhulce @brendankenny @kaycebasques

**Comment by kosamari** [comment]
closing this issue as it is lighthouse matter & issue is filed over at lighthouse repo :D
