### ISSUE TITLE
Add PWAs to the site's top-level navigation

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#4391]
The current top-level navigation includes the following sections:

![image](https://cloud.githubusercontent.com/assets/110953/24812231/117652c6-1b7e-11e7-85cb-3f7e0668e07f.png)

With most top-level categories that fall under /web also getting a callout in the navigation. Take Fundamentals for example:

![image](https://cloud.githubusercontent.com/assets/110953/24812248/2beab782-1b7e-11e7-884a-fba825852f44.png)

As progressive-web-apps are also a top-level item under /web, should we also be including it in the menu?

![image](https://cloud.githubusercontent.com/assets/110953/24812270/406fa244-1b7e-11e7-9f26-48e8732a67ca.png)

**Comment by petele** [comment]
Fixed a few of these issues under the new IA work
