### ISSUE TITLE
Dead links in ‘Mobile Web Video Playback’ article

### ISSUE THREAD

**Issue by simevidas** [google/WebFundamentals#4398]
In the body text of [this article](https://developers.google.com/web/fundamentals/media/mobile-web-video-playback), the links with the name “sample” return 404.

/cc @beaufortfrancois

**Comment by beaufortfrancois** [comment]
Thanks for the warning @simevidas.
@petele will take care of syncing code content at https://github.com/googlesamples/web-fundamentals/tree/gh-pages/fundamentals/media/mobile-web-video-playback.html

**Comment by simevidas** [comment]
Thanks for fixing 👍
