### ISSUE TITLE
DevTools: Custom colors palette

### ISSUE THREAD

**Issue by jarrodek** [google/WebFundamentals#4408]
It's a feature request for DevTools.

Currently when clicking on color icon next to color definition and changing the palette is shows 3 basic palettes: Material, Custom and Page colors:
![image](https://cloud.githubusercontent.com/assets/3320020/24975618/38bfd3c2-1fbe-11e7-8952-339f72c72bde.png)

It would be nice to have a possibility to create more than one custom color palette. It is helpful when working with more than one product (common use case for a graphic/ux designers) and you have different color sets for them.
It would speed up a work instead of opening styleguide for the product to have color codes.

Also - maybe this should be new issue report - it would be nice to assign a variable name for those colors. So instead of searching of the color you could enter a variable name in a color value and this should be replaced with real color value. This is an example:
![image](https://cloud.githubusercontent.com/assets/3320020/24975844/04db026a-1fbf-11e7-9314-220d3f1cc8ea.png)
This could work like a CSS variable (without "var" function). With syntax autocomplete from page's variables and the ones defined in custom colors it would be nice to have but convenient tool.

**Comment by kosamari** [comment]
hey @jarrodek thanks for the request! this repo is used for content of WebFundamentals site. Please file feature request at crbug.com thanks !

**Comment by jarrodek** [comment]
For future reference: https://bugs.chromium.org/p/chromium/issues/detail?id=739891
