### ISSUE TITLE
Switch link to The Offline Cookbook (to /web hosted version) ?

### ISSUE THREAD

**Issue by kosamari** [google/WebFundamentals#4432]
Looking at [this page](https://developers.google.com/web/tools/lighthouse/audits/http-200-when-offline) (linked from Lighthouse results), I noticed link to the offline cookbook is pointed to [the one on Jake's blog](https://jakearchibald.com/2014/offline-cookbook) which is published in 2014.

I assume [this version on web fundamentals](https://developers.google.com/web/fundamentals/instant-and-offline/offline-cookbook/) is mean to be canonical? (or at least updated as recent as Mar 21st 2017)... whichever is the canonical, I think the link should point to the one maintained with updates.

This seems to affect not only the `src/content/en/tools/lighthouse/audits/http-200-when-offline.md` (& its translations) but also some [code labs & articles etc](https://github.com/google/WebFundamentals/search?p=1&q=%22https%3A%2F%2Fjakearchibald.com%2F2014%2Foffline-cookbook%22&type=&utf8=%E2%9C%93)

**Comment by ebidel** [comment]
Good call! We should probably use the /web one since it's more recent and part of our docs.

cc @kaycebasques and @jakearchibald
