### ISSUE TITLE
Add links to Accessibility contents in Lighthouse Audit Reference

### ISSUE THREAD

**Issue by kosamari** [google/WebFundamentals#4433]
Noticed most of Accessibility audit reference does not contain links to learn more about accessibility & why it's important (rather than "how to pass this test").

Proposed content to link (note: @robdodson might know better link to reach audit criteria :) )
- [Elements With ARIA Roles Have Required Attributes](https://developers.google.com/web/tools/lighthouse/audits/required-aria-attributes) add link to [Introduction to ARIA](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/)
- [Element ARIA Attributes Are Allowed For This Role](https://developers.google.com/web/tools/lighthouse/audits/aria-allowed-attributes) add link to [Introduction to ARIA](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/)
- [Element ARIA Attributes Are Valid](https://developers.google.com/web/tools/lighthouse/audits/valid-aria-attributes) add link to [Introduction to ARIA](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/)
- [Element ARIA Attributes Have Valid Values](https://developers.google.com/web/tools/lighthouse/audits/valid-aria-values) add link to [Introduction to ARIA](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/)
- [Background and Foreground Colors Have Sufficient Contrast Ratio](https://developers.google.com/web/tools/lighthouse/audits/contrast-ratio) add link to [Accessible Styles](https://developers.google.com/web/fundamentals/accessibility/accessible-styles)
- [Every Image Element Has An Alt Attribute](https://developers.google.com/web/tools/lighthouse/audits/alt-attribute) add link to [Text Alternatives for Images](https://developers.google.com/web/fundamentals/accessibility/semantics-builtin/text-alternatives-for-images)
- [Every Form Element Has A Label](https://developers.google.com/web/tools/lighthouse/audits/form-labels) add link to [Create Amazing Forms](https://developers.google.com/web/fundamentals/design-and-ui/input/forms/#label_and_name_inputs_properly)

**Comment by robdodson** [comment]
I think that'd be great. Do you have any interest in putting together a PR for it?

**Comment by kosamari** [comment]
will do !
