### ISSUE TITLE
Mapping broken in - Persistence with DevTools Workspaces

### ISSUE THREAD

**Issue by hekkmart** [google/WebFundamentals#4442]
Hello,

I was successfully using DevTools to work on CSS styles for a product UI. Now, the mapping appears to be broken.

- I followed this to start, and it worked fine for weeks: https://developers.google.com/web/tools/setup/setup-workflow

Now, however...
- I have a styles.css file that I can see in the Sources panel
- I have a styles.css file on my local machine
- I can add my local folder/files to show up in the sources panel
- I CANNOT get the two styles.css files to map to each other (or, more accurately, the local/new one to the existing/real one)
- If I update my local css file, it does update in the new source folder, but DOES NOT affect the screen. ie: I can delete all CSS styles in the new/local file, and the screen will not change.

I really need this to work in order for me to continue this project.. Any thoughts??

Thanks!

![code](https://cloud.githubusercontent.com/assets/27779672/25193032/8decb67c-2503-11e7-8279-4bc3ff2aa739.png)

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out [https://developer.chrome.com/devtools/docs/contributing](https://developer.chrome.com/devtools/docs/contributing) for how to ask questions or file issues on DevTools.
