### ISSUE TITLE
mention canvas-encoding in img optimization docs?

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#4448]
I'm writing the reference doc for the "unoptimized images" Lighthouse audit. The audit fails if a JPEG img could be 10KB smaller if it was canvas-encoded. I'm not familiar with that technique but it looks like the technique is to [convert a `canvas` el to a data URI](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).

This technique is not mentioned in the [image optimization](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization#tools_and_parameter_tuning) doc.

By using this technique in the audit, we're implicitly recommending it. Purpose of this issue is just to make sure that we're all on the same page

cc @paulirish @patrickhulce @igrigorik

**Comment by patrickhulce** [comment]
The fact that it's encoded using canvas is somewhat of a temporary workaround while protocol support is lacking. I believe the plan is to add the ability to the protocol to return network body contents under different encodings that would directly use specific encoders. I'd definitely be against mentioning this approach to anyone who needs to do compression of image assets for production :)

**Comment by kaycebasques** [comment]
@patrickhulce explained that canvas-encoding is just a workaround to see how large the image would be if it's quality is set to 80 and its metadata is removed
