### ISSUE TITLE
update jQuery's setTimeout reference in "Optimize JavaScript Execution"

### ISSUE THREAD

**Issue by kosamari** [google/WebFundamentals#4453]
This line
```
In fact, jQuery’s default animate behavior today is to use setTimeout! 
```
in [Optimize JavaScript Execution](https://developers.google.com/web/fundamentals/performance/rendering/optimize-javascript-execution) is no longer true as of [jQeury 3.0](https://jquery.com/upgrade-guide/3.0/#feature-animations-now-use-requestanimationframe)  🙌

cc: @paullewis

**Comment by paullewis** [comment]
Awesome news! TIL! I guess it just needs rephrasing to account for older jQuerys? wdyt?

**Comment by kosamari** [comment]
How about something like this ? 

Original Text : 
```
In fact, jQuery’s default animate behavior today is to use setTimeout! 
You can patch it to use requestAnimationFrame, which is strongly advised.
```

Change To : 
```
In fact, jQuery used to use setTimeout for animate behavior. It was changed to use requestAnimationFrame in version 3.
If you are using older version of jQeury, you can patch it to use requestAnimationFrame, which is strongly advised.
```
