### ISSUE TITLE
"TL;DR" a hidden element is visible.

### ISSUE THREAD

**Issue by ayush1095** [google/WebFundamentals#4458]
Link to affected page:
- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer#text-compression-with-gzip
- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization 
Page contains HTML hidden entities visible on the page.

**Comment by kosamari** [comment]
Closing this issue as it seem to be not a issue anymore. Please re-open if you see the issue still.
