### ISSUE TITLE
[DevTools / Remote debug] missing scope values

### ISSUE THREAD

**Issue by luckylooke** [google/WebFundamentals#4463]
Hi, I am debugging web app on mobile device via usb cable and remote devices. I am able to see code and pause it in debugger of devTools same as on desktop. But I cannot see values of a any variable in code stepping through it. Execution is paused but under "Scope" there is "Not Paused" statement.. event hovering variables does not show their values. :/

**Environment:**

Mobile navigator.userAgent = Mozilla/5.0 (Linux; Android 6.0.1; SM-A310F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36

Desktop navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"

**Setup:**

Page is served from desktop via nodejs server, mobile phone is connected via wireless LAN to desktop. 

Attaching a screenshot.

Thank you!

![chromebug](https://cloud.githubusercontent.com/assets/3660030/25370053/5c1c083a-2988-11e7-990f-548580fdfaaa.png)

**Comment by luckylooke** [comment]
I dont know if it is realted, but devTools shows message: Consider disabling data saver while debugging, even the fact that I have data saver turned off. 🤔

**Comment by kaycebasques** [comment]
Hey @luckylooke 

The screenshot does look buggy.

However, you mentioned that your phone is connected to the desktop server via wireless LAN. I'm pretty sure that remote debugging only works when the mobile is connected to the desktop via USB. Maybe you discovered some workflow that I'm not aware of.

Instructions: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by luckylooke** [comment]
Debugging is via USB, but webapp is served from desktop localhost and I am connected to it via wifi. ;) USB debugging is very slow.. I take an action on mobile and it takes seconds to display new state in devTools.

**Comment by kosamari** [comment]
closing this issue. Hope issue was solved already, but if not, I suggest creating stackoverflow with [google-chrome-devtools] tag :)

**Comment by RusinovAnton** [comment]
Just got this issue while debugging minified JS file, using sourcemaps. It works for desktop debugger, but not for remote one. Device is connected via USB

**Comment by AndreWieghardt** [comment]
Same goes for me. It is a minified JS file using sourcemaps. Everything is fine for desktop but debugging on remote device (Note 3, Android 5.0). The scope is empty. Sometimes there is i.e. local, but without any content.

**Comment by tempestwf** [comment]
This problem just started for me. Day before yesterday no issues, and then yesterday and today I can no longer view my scope variables in exactly the manner described. I get the same message to: "Consider disabling data saver while debugging"

**Comment by dperetti** [comment]
Still happening 🤷‍♂️

**Comment by dontpanic5** [comment]
I'm getting this in Electron v11..

**Comment by marcuswestin** [comment]
Just noticed the same thing.

All scope variables *are* available via "Watch" expressions, but none of the local scope variables automatically show up in the "Scope" section - instead, that section just shows "Not paused" in italics.

**Comment by dontpanic5** [comment]
I found a workaround for this in Electron. I am using Webpack v4 and changing to "eval" source mapping brought back the "Scope" variables.
Just a workaround, not a fix. I wish I could use a different sourcemap "style" because "eval" is a bit hard to read. My hope is that upgrading to Webpack v5 will perhaps help..

**Comment by gdorionara** [comment]
I have the same issue with webpack 5 and Electron 11. Variables can be research and inspected in the Watch panel. But not in the Scope panel. Any ideas, workaround or progress on this?
