### ISSUE TITLE
Editing among contiguous text nodes

### ISSUE THREAD

**Issue by zavaboy** [google/WebFundamentals#4467]
I've noticed strange behavior when editing contiguous text nodes in DevTools. If you edit the content of a text node that is neighboring other sibling text nodes, those other text nodes will disappear once you apply your changes. I believe this to be a bug.

Try yourself here:
https://jsfiddle.net/nLwfryuj/1/

Tested in Google Chrome 58.0.3029.81 on Windows 7.

**Comment by kaycebasques** [comment]
Hi @zavaboy 

Ya, that looks buggy. I filed a bug at https://crbug.com/715311

FYI this is the repo for the DevTools docs. If you ever want to file bugs directly on the DevTools engineering team, use crbug

Thanks for the report
