### ISSUE TITLE
presentaion-api article is shown in the wrong sidebar section

### ISSUE THREAD

**Issue by badersur** [google/WebFundamentals#4476]
https://developers.google.com/web/updates/2015/11/presentation-api should be in November's archive but is shown in December's archive in the left sidebar.

**Comment by badersur** [comment]
After checking auto-generated 2015/_toc.yaml, I see a lot of files that seems to be in a different archive than the expected archive based on the month in the URLs. Maybe, It's an intended behavior or there's an issue with the build system!

**Comment by PaulKinlan** [comment]
It doesnt have the correct meta data - https://github.com/google/WebFundamentals/blame/master/src/content/en/updates/2015/11/presentation-api.md#L6

Not sure it's worth fixing now as it will likely lead to RSS feed changes etc.

**Comment by badersur** [comment]
Could I close this or you want it to be open in case you decide to fix it?
