### ISSUE TITLE
DevTools stacking order visualization

### ISSUE THREAD

**Issue by marcuslindfeldt** [google/WebFundamentals#4477]
It's very hard to see what elements affect the stacking order and how they affect it which often leads to developers setting crazy z-index properties and bugs that are hard to find. It would be great if we could visualize this in a nice way somehow in the DevTools. Thoughts? Ideas?

Regards,
Marcus

**Comment by kosamari** [comment]
Hi! Thanks for the suggestion. This repo is tracking issues with content on the site (including DevTools documentation). 

Check out https://bugs.chromium.org/p/chromium/issues/list to file an feature request, or check out https://developers.google.com/web/tools/chrome-devtools/#get_involvedfor for more communication channel woth DevTools folks!
