### ISSUE TITLE
Introduction to fetch() needs update

### ISSUE THREAD

**Issue by pindaric** [google/WebFundamentals#4493]
[https://developers.google.com/web/updates/2015/03/introduction-to-fetch](https://developers.google.com/web/updates/2015/03/introduction-to-fetch) says:

> With the current fetch() implementation it's not possible to make requests for resources on a different origin from the window global scope.

but this is no longer current and needs updating.

**Comment by gauntface** [comment]
Are we maintaining 2 year old blog posts @PaulKinlan?
