### ISSUE TITLE
Main nav - Underlining current page

### ISSUE THREAD

**Issue by wingoodbody** [google/WebFundamentals#4529]
In the main nav bar for https://developers.google.com/web, I noticed some differences in highlighting the current page.

When the Fundamentals section is selected, that option in nav bar has a white line underneath it.

https://developers.google.com/web/fundamentals

But when any of the other three main areas are selected (Tools, Updates, Case Studies), the section does not have a white underline.

https://developers.google.com/web/tools

Anyway, not the end of life as we know it, but a small UX improvement could be made!

**Comment by petele** [comment]
Thanks. I think we've fixed a couple of these issues in the last couple of weeks.
