### ISSUE TITLE
Profile image looks not good when we change window width

### ISSUE THREAD

**Issue by sotayamashita** [google/WebFundamentals#4549]
see: 
![may-11-2017 15-44-19](https://cloud.githubusercontent.com/assets/1587053/25936051/e2e06b56-3660-11e7-9a1b-bfb0cd3b615a.gif)

I think profile image maintain its width (64px). What do you think?

cc:/ @agektmr

**Comment by kosamari** [comment]
Hey @sotayamashita there is another PR open for squashed bio image, possibly related ??
https://github.com/google/WebFundamentals/pull/4520

**Comment by sotayamashita** [comment]
@kosamari I appreciate your quick reply. :bow: I think it is a different issue because #4520 mentions wrapper of sentences.  I refer to the rule set of the profile.

**Comment by kosamari** [comment]
I believe this has been fixed :)
