### ISSUE TITLE
[DevTools / JS / Get Started / (3) Paused On Correct Line]

### ISSUE THREAD

**Issue by cablegunmaster** [google/WebFundamentals#4564]
- Line 14 function onClick() of get-started.js

- Line 22  Document.addEventListener("click", event => 
I guess this is not line 19 =)?   Oh wait first debug this was adblock.js  whoops .

For better specification just say 
Are you paused on a line with the text "function onClick()" in it of file 'get-started.js'

I Can't find the scope/ watcher of chrome to see what the variables are.

**Comment by kosamari** [comment]
same issue as #4801, closing this issue.
cc @kaycebasques
