### ISSUE TITLE
PaymentRequest doc wrong

### ISSUE THREAD

**Issue by udany** [google/WebFundamentals#4582]
When accessing the "Deep Dive into the Payment Request API", specifically the section "[PaymentRequest Constructor](https://developers.google.com/web/fundamentals/discovery-and-monetization/payment-request/deep-dive-into-payment-request#paymentrequest_constructor)" it display an incorrectly formed paymentDetails object as:
`const paymentDetails = {  
  label: 'Total',  
  amount:{  
    currency: 'USD',  
    value: 0  
  }  
}; `
Whereas it should be:
`const paymentDetails = {  
  total: {
    label: 'Total',  
    amount:{  
      currency: 'USD',  
      value: 0  
    }
  }  
};  `

**Comment by kosamari** [comment]
ping: @gauntface / @agektmr

**Comment by agektmr** [comment]
This should have been addressed by now.
Thanks for the report @udany !
