### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by WingGT1** [google/WebFundamentals#4587]
Followed all directions AFAIK, getting the following error when I try to run npm start:

> WebFundamentals@2.0.0 start C:\Users\<user>\Documents\GitHub\Webfundamentals
> ./start-appengine.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WebFundamentals@2.0.0 start: `./start-appengine.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the WebFundamentals@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2017-05-23T06_45_04_342Z-debug.log

**Comment by kosamari** [comment]
`npm start` is just a alias, so you can directly run `start-appengine.sh` to execute the command
