### ISSUE TITLE
Dead link on Push Notifications Overview page

### ISSUE THREAD

**Issue by juniperbelmont** [google/WebFundamentals#4615]
It appears that Chris Mills' demo no longer exists: https://github.com/chrisdavidmills/push-api-demo

https://github.com/google/WebFundamentals/blame/master/src/content/en/fundamentals/engage-and-retain/push-notifications/index.md#L86

**Comment by wub** [comment]
Fixed by https://github.com/google/WebFundamentals/commit/7a9d2f8b19e0dda20dac9ee228f671a09268d629
