### ISSUE TITLE
[Lighthouse / HTTP 200 When Offline / Helpful]

### ISSUE THREAD

**Issue by tomanistor** [google/WebFundamentals#4618]
The link [Adding a Service Worker and Offline Into Your Web App](https://codelabs.developers.google.com/codelabs/offline) returns as a 403 Forbidden error.

**Comment by wub** [comment]
This may have been a transient issue - works for me!

**Comment by kosamari** [comment]
Hey @tomanistor the site looks to be working OK. Please let us know if you continue to have 403 error.

**Comment by tomanistor** [comment]
Looks to be working now. Thanks!
