### ISSUE TITLE
Typo - Windows has "ctrl"

### ISSUE THREAD

**Issue by merica199** [google/WebFundamentals#4634]
![capture](https://cloud.githubusercontent.com/assets/24942127/26680566/f05503bc-46a7-11e7-9224-c90223f630c5.PNG)

**Comment by 22nds** [comment]
@merica199 Fixed by https://github.com/google/WebFundamentals/pull/4649 
Ticket can be closed.

**Comment by kosamari** [comment]
thanks y'all !
