### ISSUE TITLE
Typo on Push Notifications Subscribing a User Page: "strinigify"

### ISSUE THREAD

**Issue by juniperbelmont** [google/WebFundamentals#4643]
"Strinigify" should probably be "stringify".

https://github.com/google/WebFundamentals/blame/master/src/content/en/fundamentals/engage-and-retain/push-notifications/subscribing-a-user.md#L302

**Comment by 22nds** [comment]
@juniperbelmont  Fixed by https://github.com/google/WebFundamentals/pull/4646
Ticket can be closed.
