### ISSUE TITLE
2.1 Create a Promise -- error

### ISSUE THREAD

**Issue by jmerrikin** [google/WebFundamentals#4644]
In the section 2.1 step for Create a Promise, the paragraph beneath the code section shows "Enter "Spain" into the app's Country Name field. Then, click Get Image Name. You should see a Promise object logged in the console."

However, the code is looking for an exact match of "spain", hence "Spain" does not match and throws the error.

**Comment by 22nds** [comment]
@jmerrikin I couldn't replicate the issue. 

There is a line at the top of [task](https://developers.google.com/web/ilt/pwa/lab-promises) that changes 'Spain' to 'spain'
```
country = country.toLowerCase();
```
Did you copy it to your script?

**Comment by jmerrikin** [comment]
Thank you @22nds, I totally missed that for some reason, my bad. Thank you for responding!!
