### ISSUE TITLE
[devtools] websocket item selecting annoying

### ISSUE THREAD

**Issue by mesutyigit** [google/WebFundamentals#4677]
Selection changes  out of hand self. It's annoying. 
Visual demo: 
![bug1](https://user-images.githubusercontent.com/11429147/27028749-7119e750-4f6e-11e7-8001-e9a03a3a0fec.gif)

Details: 
os: windows 8.1 pro
chrome: version 58.0.3029.110 (64-bit)

**Comment by kaycebasques** [comment]
Hey @mesutyigit so you click on `ws`, and then when you hover away from it, it gets de-selected?

**Comment by mesutyigit** [comment]
its doenst matter about hover it.  After  a few seconds , select always first item of the list at left  side.
This issue dropping with chrome 59 updated.

**Comment by kaycebasques** [comment]
OK cool. From your last response it sounds like the issue was fixed in Chrome 59, so I'll close this issue
