### ISSUE TITLE
[Lighthouse / Blocking Resources] prefetched blocking scripts

### ISSUE THREAD

**Issue by EnoahNetzach** [google/WebFundamentals#4694]
Lighthouse considers scripts loaded after the main `load` event as blocking if they are prefetched.

It is exemplified in [this gist](https://gist.github.com/EnoahNetzach/065ed2d2a9113997c5361e838cbd314a), where in the document's head a 
```html
<link as="script" src="/main.js" rel="preload">
```
tag is present and at the end of the body the preloaded script is added by
```javascript
document.createElement('script')
script.src = '/main.js'
document.head.appendChild(script)
```

Is this to be considered blocking?

**Comment by ebidel** [comment]
That should not be considered blocking. Lighthouse tries to handle lazy loaded `rel="preload"` links, but sometimes finds false positives.

Please post over in https://github.com/GoogleChrome/lighthouse.
