### ISSUE TITLE
Can't see a `what-is-mixed-content` in Korean 

### ISSUE THREAD

**Issue by techhtml** [google/WebFundamentals#4710]
Hello.

I'd see an article '[What is Mixed Content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content)' in Korean.
but it's not showing any browsers. (Another languages are shown well)

but github have a translated source.

https://github.com/google/WebFundamentals/blob/master/src/content/ko/fundamentals/security/prevent-mixed-content/what-is-mixed-content.md

Can you fix it?

**Comment by petele** [comment]
Fixed in #5120
