### ISSUE TITLE
Can't see the images in the Spanish language

### ISSUE THREAD

**Issue by fmenesesp** [google/WebFundamentals#4713]
Hi, I reading your article "Your First Web Push Notification". This article is great, but some images not found in web version.

https://developers.google.com/web/fundamentals/getting-started/codelabs/push-notifications/?hl=es

![report](https://user-images.githubusercontent.com/2514443/27233559-1fe1b85a-52ba-11e7-94e4-167f1a08b7e6.jpg)

**Comment by 22nds** [comment]
Created PR  #4728 which fixes this issue in multiple languages (Spanish is one of them).

**Comment by 22nds** [comment]
@fmenesesp This issue can be closed.
