### ISSUE TITLE
console.clear does not get disabled on Preserve log flag.

### ISSUE THREAD

**Issue by Bamieh** [google/WebFundamentals#4736]
according to the documentation

> if the Preserve log checkbox is enabled, console.clear() is disabled.

this is a very neat feature, however it does not work, `console.clear()` always clears the console regardless of the `preserve log` flag. 

i am running `console.clear()` from javascript, on `Chrome Version 58.0.3029.110 (64-bit)` from my mac

source:
https://developers.google.com/web/tools/chrome-devtools/console/console-reference
"console.clear()" section.

**Comment by kosamari** [comment]
@Bamieh thanks for raising the issue - the bug is filed on the Chromium project. Please chekc on the process over at https://bugs.chromium.org/p/chromium/issues/detail?id=735440

**Comment by Bamieh** [comment]
@kosamari thanks, i did raise the issue there since i wasnt sure where to post it :)
