### ISSUE TITLE
Multi Line selection using 'command' and 'shift' in developer console - Feature request

### ISSUE THREAD

**Issue by sesn** [google/WebFundamentals#4742]
In developer console, using 'command' key, I can edit multiple lines. But Selection of multiple lines using the combination of shift key and command key is not working while editing the files. It is selecting only one line.

### **Issue**

<img width="646" alt="issues" src="https://user-images.githubusercontent.com/1553701/27419116-d989558e-573c-11e7-9ca0-e81658d222a0.png">

### **Feature requested:**

<img width="685" alt="features-request" src="https://user-images.githubusercontent.com/1553701/27419121-e1c16b38-573c-11e7-80bd-40ed44680af8.png">

**Comment by kosamari** [comment]
Thanks for the request ! This repo is only for the content of WebFundamentals site. Please file any feature request over at crbug.com Thanks ! 👍

**Comment by sesn** [comment]
Okay Cool Thanks
