### ISSUE TITLE
device toolbar doesn't trigger style changes

### ISSUE THREAD

**Issue by koop4** [google/WebFundamentals#4761]
Using _media-query_ or _predefined mobile_ button from the device toolbar doesn't trigger the changes on the style which happens instead when changing the window size.

here's a gif example based   on the code below:
![peek 2017-06-27 10-17](https://user-images.githubusercontent.com/4103610/27577729-0debec9a-5b22-11e7-9193-1f3adcd877cb.gif)

```
<!DOCTYPE html><html lang="en">
<head>
      <meta charset="UTF-8" />
      <link rel='stylesheet' type='text/css' media='screen and (max-width: 700px)' href='css/style_smartphone.css' />
      <link rel='stylesheet' type='text/css' media='screen and (min-width: 701px)' href='css/style_tablet.css' />
      <title>test</title>
</head>
<body></body>
</html>
```
style_smartphone

```
html, body{
  height: 100%;
  width: 100%;
}

body {
  background: blue;
}
```

style_tablet
```
html, body{
  height: 100%;
  width: 100%;
}

body {
  background: black;
}
```

**Comment by kosamari** [comment]
Hey @koop4 thanks for raising the issue ! This repo is only for content on WebFundamentals site. 
Please file any bug at crbug.com, thanks ! 🥇

**Comment by koop4** [comment]
posted on crbug.com as required.
link [here](https://bugs.chromium.org/p/chromium/issues/detail?id=740043#) to those who wants to follow
