### ISSUE TITLE
[DevTools / JS / Get Started / (5) Console Evaluation Is Correct]

### ISSUE THREAD

**Issue by Satishsinghx** [google/WebFundamentals#4762]
VM1120:1 Uncaught ReferenceError: addend1 is not defined
    at eval (eval at <anonymous> (:1:1), <anonymous>:1:10)
    at <anonymous>:1:1

This is the error which i get when i execute parseInt(addend1) + parseInt(addend2) on the console window.

**Comment by kosamari** [comment]
duplicate of #4783
