### ISSUE TITLE
[DevTools / JS / Get Started / (5) Console Evaluation Is Correct]

### ISSUE THREAD

**Issue by chrishappy** [google/WebFundamentals#4783]
Typed in

`parseInt(append1) + parseInt(append2)`

Got the error
```
VM142:1 Uncaught ReferenceError: append1 is not defined
    at eval (eval at updateLabel (get-started.js:32), <anonymous>:1:10)
    at updateLabel (get-started.js:32)
    at HTMLButtonElement.onClick (get-started.js:19)
(anonymous) @ VM142:1
updateLabel @ get-started.js:32
onClick @ get-started.js:19
```

Broswer: Google Chrome
Version: 59.0.3071.115 (Official Build) (64-bit)

Screenshot:
![capture](https://user-images.githubusercontent.com/14931423/27667015-94e2db9a-5c2c-11e7-91de-7a800e0a04df.PNG)

**Comment by kaycebasques** [comment]
Hey @Chris-Happy7 sorry for delay, but the cause is that you were supposed to type `addend1` not `append1`

**Comment by kaycebasques** [comment]
Note to self: talk to DevSite team about tracking `expandable` events

**Comment by chrishappy** [comment]
Hey @kaycebasques, sorry for never responding. Thanks for pointing out my error
