### ISSUE TITLE
Set a body background color for developer pages

### ISSUE THREAD

**Issue by mattrheault** [google/WebFundamentals#4797]
[Possibly related issue](https://github.com/google/WebFundamentals/issues/469) (from a while back)

There's no explicit background color set for pages on https://developers.google.com/web/ even though the content color is explicitly set. This makes the content hard to read in browsers that set a dark default body background color.

**Comment by petele** [comment]
Have raised an internal bug with the DevSite team. They'll have to evaluate and decide how to proceed.
