### ISSUE TITLE
[DevTools / JS / Get Started / (3) Paused On Correct Line]

### ISSUE THREAD

**Issue by WillSabido** [google/WebFundamentals#4801]
**Issue:** Pausing on incorrect line due to Adblock extension.

**Solution:** Disable Adblock extension while in developer mode via _**Window > Extensions > 'Developer mode'**_ (see screenshot)

![screen shot 2017-07-05 at 14 11 01](https://user-images.githubusercontent.com/3866753/27866068-e91a50a2-618c-11e7-956a-0da0f9b286a0.png)

**Comment by kosamari** [comment]
@kaycebasques  possibly update the wording in the article ?? :)

**Comment by kaycebasques** [comment]
Bottom of [step 3](https://developers.google.com/web/tools/chrome-devtools/javascript/#event-breakpoint) discusses pausing on the wrong line of code because of extensions.
