### ISSUE TITLE
Save debugging session complete with breakpoints

### ISSUE THREAD

**Issue by HeroicOvenmitt** [google/WebFundamentals#4808]
It would be super snazzy awesome if there were a way to save all current breakpoints in your devtools window somewhere so you can wipe them to work on something else, then reapply them all later if/when you revisit the first issue. Yes, I can disable them all, but I often use the enable/disable all button already and this would complicate things.

This would be very helpful for my team at work since we're fixing a lot of separate little bugs all over the site. 

Thanks!
-ETO

**Comment by kosamari** [comment]
Hey @HeroicOvenmitt thanks for the suggestion!

This repo is for content on web fundamentals site. You can file anfeature request over at https://bugs.chromium.org/p/chromium/issues/list 👍
