### ISSUE TITLE
[DevTools / JS / Get Started / (2) Triggered The Breakpoint] CSP causing reporting widget to error

### ISSUE THREAD

**Issue by kosamari** [google/WebFundamentals#4815]
When I click on `Something's Wrong` button & then click `open an issue` link, widget disappears with CSP error in console. 

![get_started_with_debugging_javascript_in_chrome_devtools_ _ _web_ _ _google_developers](https://user-images.githubusercontent.com/4581495/27936044-d0927cda-627c-11e7-8dc2-c308d8c5a0ca.png)

**Comment by kaycebasques** [comment]
Button was removed because of buggy behavior like this.
