### ISSUE TITLE
Method `getSWRegistration` is not defined on examples snippets

### ISSUE THREAD

**Issue by abraham** [google/WebFundamentals#4820]
The [Subscribing a user guide](https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/subscribing-a-user) mentions the`getSWRegistration` method multiple times. The method itself does not appear to be defined anywhere. Developers will need to know what it is supposed to do.

**Comment by gauntface** [comment]
The code in that guide is here: https://github.com/gauntface/web-push-book/blob/master/src/demos/node-server/frontend/app.js#L33 Although looking through that, I think here is a much nicer way of doing this. Will explore later tonight.
