### ISSUE TITLE
PaymentRequest API: "supportedMethods" not up-to-date

### ISSUE THREAD

**Issue by jonathanGB** [google/WebFundamentals#4826]
[Here](https://github.com/google/WebFundamentals/blob/master/src/content/en/fundamentals/discovery-and-monetization/payment-request/deep-dive-into-payment-request.md#paymentrequest-constructor) 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/8869660/28094739-33438eda-6653-11e7-8f51-593a2f2d3114.png">
and in other code snippets using `supportedMethods`, `supportedMethods` is presented as an **Array**, while the [latest editor's draft](https://w3c.github.io/browser-payment-api/#dom-paymentmethoddata) and the current working draft present it as a **DOMString**:

```idl
dictionary PaymentMethodData {
  required DOMString supportedMethods; <---------- HERE
  object data;
};
```

This should probably be updated to reflect the current status of the API :)

**Comment by kosamari** [comment]
Ping @agektmr what do you think ?

**Comment by agektmr** [comment]
Indeed the spec has been changed. But the implementation hasn't caught up yet. Let us come back to this when a relevant change will be implemented in Chrome and will go beta.

**Comment by petele** [comment]
@agektmr - can you update please?

**Comment by agektmr** [comment]
Working on it.

**Comment by agektmr** [comment]
[The article](https://developers.google.com/web/updates/2017/01/payment-request-updates) is published.
