### ISSUE TITLE
[Lighthouse / Alt Attribute / Helpful] Update alt attribute guide text

### ISSUE THREAD

**Issue by adob** [google/WebFundamentals#4833]
The following advice is not good:

> Every image should have an alt attribute that includes a text description of the contents of that image. 

There are many cases when when images on a page don't provide any additional information beyond the text already there. Adding text descriptions for these images just creates clutter. The article should advise using bare 'alt' attributes in these cases.

**Comment by kosamari** [comment]
Assigned to @robdodson & updated title to reflect issue
