### ISSUE TITLE
[DevTool, Question] Heap snapshots do not capture object retained by timers

### ISSUE THREAD

**Issue by uushuo** [google/WebFundamentals#4839]
I tried the following code, and take heap snapshots, found the memory is used, but can not find what objects takes the memory exactly. I don't known if there's any way to find memory leaks like this.
```javascript
(function() {
    var theThing = null;
    var replaceThing = function () {
      var originalThing = theThing;
      var unused = function () {
        if (originalThing)
          console.log("hi");
      };
      theThing = {
        longStr: new Array(10000000).join('*'),
        someMethod: function () {
          console.log(someMessage);
        }
      };
    };
    setInterval(replaceThing, 100);
})();
```
The objects retained by timer, but not showing in heap snapshot.
![image](https://user-images.githubusercontent.com/3499226/28204635-639c2c80-68b1-11e7-9a35-8092b25fd70f.png)
![image](https://user-images.githubusercontent.com/3499226/28204665-802a341e-68b1-11e7-80fc-533329a66f13.png)

**Comment by kosamari** [comment]
Heya @uushuo ! This repo is used to manage content on Web Fundamentals site, sorry for the confusion! I would suggest to re-post this question to StackOverflow & use tag [google-chrome-devtools](https://stackoverflow.com/questions/tagged/google-chrome-devtools).

cc: @kaycebasques - FYI for future topic to cover in Dev Tools tutorial  :)
