### ISSUE TITLE
Update offline-google-analytics related content to workbox-google-analytics

### ISSUE THREAD

**Issue by kosamari** [google/WebFundamentals#4842]
Note: I thought it would be just changing link path, but I think most of this article is now out-of-date with release of workbox.
https://developers.google.com/web/updates/2016/07/offline-google-analytics

Probably add some warning on top "This is obsolete, use workbox [Link to workbox article]",  WDYT?

**Comment by jeffposnick** [comment]
This was fixed by https://github.com/google/WebFundamentals/pull/5985
