### ISSUE TITLE
[Lighthouse / Manifest Short Name Truncation / Helpful]

### ISSUE THREAD

**Issue by Ruffio** [google/WebFundamentals#4859]
The page states 'If the short_name is longer than 12 characters, it'll be truncated on the homescreen.'

From that statement having a short_name of 12 chars is valid and no truncation should be performed, as is is only if it is **longer** than 12 that the truncation will kick in. 

However further down it says '  So, if you don't include a short_name in your manifest, but your name is less than 12 characters, then the audit passes.'

IMHO the audit should pass if the short_name is equal to 12 chars. The wording and implementation of the audit aren't consistent.

**Comment by kosamari** [comment]
Hey @Ruffio thanks for the input!
This repo is for content of the site, looks like your suggesting involves updating audit logic itself, would you mind filing issue over at [lighthouse repo](https://github.com/GoogleChrome/lighthouse/issues)? sorry any confusion !

**Comment by Ruffio** [comment]
@kosamari this issue should not be marked as closed as the wording is still incorrect/inconsistent. According to https://developer.chrome.com/apps/manifest/name#short_name the short_name can have a length of 12 chars. and be valid.
![image](https://user-images.githubusercontent.com/1877612/28498910-751c83c0-6fa9-11e7-8266-dbaf6b74c5a8.png)

Also here is says that the short_name can have a length of 12 chars. (maximum recoomended length): https://developers.google.com/web/tools/lighthouse/audits/manifest-contains-short_name
![image](https://user-images.githubusercontent.com/1877612/28498916-92915d86-6fa9-11e7-94b5-b622c7b9696e.png)

So we can conclude that the short_name can have a max length of 12 chars. and be valid, right?

So back to my original issue, the wording of the 'How the audit is implemented' is wrong on this page: 
https://developers.google.com/web/tools/lighthouse/audits/manifest-short_name-is-not-truncated
![image](https://user-images.githubusercontent.com/1877612/28498933-327eaeb6-6faa-11e7-9e0c-681150a73fdc.png)

It says 
> Lighthouse fetches the manifest and verifies that the short_name property is less than 12 characters. 

But it should say
> Lighthouse fetches the manifest and verifies that the short_name property is less than 13 characters. 

or
> Lighthouse fetches the manifest and verifies that the short_name property is less than or equal to 12 characters.

**Comment by Ruffio** [comment]
Also if you take a look in the code for Lighthouse, you can see that 12 chars. i maximum:
https://github.com/GoogleChrome/lighthouse/blob/63b4ac14d0a871ade0630db2885edd7848843243/lighthouse-core/gather/computed/manifest-values.js

![image](https://user-images.githubusercontent.com/1877612/28499001-c2d0b5b2-6fab-11e7-89d3-c8b40d4e9f54.png)

**Comment by Ruffio** [comment]
And here you see the actual code that performs the validation:
https://github.com/GoogleChrome/lighthouse/blob/63b4ac14d0a871ade0630db2885edd7848843243/lighthouse-core/gather/computed/manifest-values.js#L67

![image](https://user-images.githubusercontent.com/1877612/28499008-f3c896b2-6fab-11e7-9960-beb653aa9d51.png)

The code validates that the length can be less than or equal to 12. That is what <= means

**Comment by Ruffio** [comment]
@kosamari could you please reopen this issue as it has not been resolved. Thanks.
