### ISSUE TITLE
[lighthouse] Consistently interactive documentation

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#4868]
From @deepanjanroy

https://developers.google.com/web/tools/lighthouse/audits/consistently-interactive

Hi,

The second point on "Why this audit is important" on this page is not accurate. Currently it reads:
"The page strictly meets the R guideline of the RAIL performance model: everything on the page responds to user input within 100ms. See Response: respond in under 100ms."

However, while this is certainly the motivation, the definition does not actually look at if the page is directly meeting the R guideline, e.g. it does not matter how long your scroll handler takes to run. Instead, the definition checks if the page is meeting the I guideline, which says the app must yield control back to main thread every <50ms. Changing the whole sentence to the following will be better:

"The page strictly meets the I guideline of the RAIL performance model: the must yield control back to the main thread every <50ms. See Response: Idle Guidelines <link to idle guidelines> ."

You can add that this ultimately helps reaching the R guideline if you want, because if the app if not hitting the I guideline, the R guideline will likely suffer, but that is an indirect effect.

**Comment by kaycebasques** [comment]
@deepanjanroy this is where I got the definition:

> FirstInteractive is the first moment when a website is completely and delightfully interactive - not only everything shown on the page is interactive, but the page strongly meets the R guidelines of RAIL: it always responds to user input within 100ms.

https://docs.google.com/document/d/1GGiI9-7KeY3TPqS3YT271upUVimo-XiL5mwWorDUD4c/edit#

So is that wrong, too?

Based on that definition, it sounds like the true motivation is to improve Response time. Your comment makes it sounds like, under the hood, the audit is testing Idle time, but Response time is the real goal here. In which case, that's an implementation detail, and I wouldn't change the Lighthouse documentation. 

cc @paulirish @patrickhulce @brendankenny

**Comment by patrickhulce** [comment]
IMO, the 50ms main thread yielding vs. R guideline is an implementation detail that will only be relevant in cases where TTCI doesn't do a great job capturing the moment the app meets the R guideline :)

I'm in favor of keeping the bulk of what's currently in "Why this audit is important" as it's the user experience side of why you need to care about this thing at all, but perhaps softening it to reflect that it's what the metric is *trying* to capture in spirit and citing the "how it's implemented" for details on how that's done/when it might not work out.

**Comment by deepanjanroy** [comment]
Hm - that excerpt is more in the motivation-ish section of that doc, and states people generally think FirstInteractive should be. The real definition that's implemented in Lighthouse comes later in the doc, and I think saying that definition requires pages to "strictly meets the R guideline" can be misleading - we really don't check (and I'm not sure we will ever check) how long each event handler on the page takes to execute. We directly check for the Idle guideline instead, and linking to that instead of the R guideline will give developers better guidance about what they should be doing to get a better score (e.g. generally trying to keep main thread tasks below 50ms)

cc @tdresser

**Comment by deepanjanroy** [comment]
The Idle guideline explains its relationship to the Response guideline [pretty well](https://developers.google.com/web/fundamentals/performance/rail#idle): 

> To allow for <100ms response, the app must yield control back to main thread every <50ms, such that it can execute its pixel pipeline, react to user input, and so on.

I prefer pointing developers to the guideline that more closely correlates to the current metric to avoid confusion about the metric behavior. I would mention good response time as a motivation or result of abiding by the Idle guidelines.

**Comment by kaycebasques** [comment]
OK, that makes sense, thanks for the insights @deepanjanroy 

It'd help if you or @tdresser updated that doc that I've referenced to align with this discussion (i.e. changing that motivation section that references Response), since the Lighthouse reference doc links out to it

**Comment by deepanjanroy** [comment]
Good point. Updated doc.
