### ISSUE TITLE
Webpages are not rendered responsively

### ISSUE THREAD

**Issue by Nix07** [google/WebFundamentals#4879]
On the mobile phones/smaller screens the webpage -  "https://developers.google.com/web/fundamentals/performance/critical-rendering-path/optimizing-critical-rendering-path" is not rendered responsively. The label at the bottom is overflowing the screen.
![google1](https://user-images.githubusercontent.com/22103406/28671535-b17a5ee2-72fa-11e7-83d6-185e97fc8912.jpg)

**Comment by petele** [comment]
Good catch - fixed in #5121, will roll out in the next day or so.
