### ISSUE TITLE
[DevTools Network Issues Guide Suggestion]

### ISSUE THREAD

**Issue by vini1900** [google/WebFundamentals#4884]
How does one monitor network response time and health of chrome browser ? Is this tool a good resource?

Or is this only for App Dev

**Comment by kosamari** [comment]
Hey @vini1900 this repo is only used for content on WebFundamentals, I'd suggest posting question to StackOverflow with [google-chrome-devtools](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag. 
Sorry for the confusion !
