### ISSUE TITLE
[Lighthouse / noopener / Helpful]

### ISSUE THREAD

**Issue by mikaelnet** [google/WebFundamentals#4885]
The documentation of the lighthouse noopener -> how it's implemented, states that it "Filter out any same-host links", and then it describes an edge case regarding this.

As far as I can see, this is not done. The lighthouse report claims I'm missing rel="noopener" attributes on links that are on the same host. 

In my opinion, the documentation is the expected behaviour and the implementation shows false positives.

**Comment by kosamari** [comment]
Hey @mikaelnet thanks for raisin the issue, would you mind putting issue on [Lighthouse repo](https://github.com/GoogleChrome/lighthouse) ?
This repo is only used for managing content on WebFundamentals. Thanks & sorry for any confusion !
