### ISSUE TITLE
Update WebUSB article

### ISSUE THREAD

**Issue by beaufortfrancois** [google/WebFundamentals#4886]
Here's the list of things to update in our [WebUSB article](https://developers.google.com/web/updates/2016/03/access-usb-devices-on-the-web):

- [ ] Mention `chrome://usb-internals/` internal page
- [ ] Update `navigator.usb.requestDevice` screenshot
- [ ] Remove mention of `--disable-webusb-security` switch
- [ ] Update Origin Trials section 
- [ ] Add serial number filter key
- [ ] In What's next, mention Permissions API

@scheib @reillyeon Please review this list and suggest more.

**Comment by scheib** [comment]
- [ ] Remove allowed origins concepts.
- [ ] https://github.com/webusb/arduino still up to date? I suspect many will click over to that.

**Comment by reillyeon** [comment]
I just merged a pull request to https://github.com/webusb/arduino which removes the allowed origin concept there. I was leaving it unmerged because of a Chrome bug that prevented devices without allowed origins from displaying the landing page notification even if the descriptor was present.

**Comment by reillyeon** [comment]
- [ ] Remove the link to my "WebUSB Security Model" article as it covers the allowed origins concept which has been removed
- [ ] Remove reference to the "Public Device Registry"
- [ ] In addition to the HTTPS requirement mention the [integration](https://wicg.github.io/webusb/#feature-policy) with Feature Policy.

**Comment by btkostner** [comment]
It would be helpful if a link to [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=404161) was also added. It can be quite a pain point if you don't know about it.

**Comment by beaufortfrancois** [comment]
I've just uploaded a PR to address all issues mentionned above at https://github.com/google/WebFundamentals/pull/5056

Let me know what you think.
