### ISSUE TITLE
[DevTools Network Issues Guide Suggestion]

### ISSUE THREAD

**Issue by y4hoo** [google/WebFundamentals#4905]
Hi,
I just want to suggest a tiny improvment
First of all this tool is great for using detecting issues.
But many bussinees users, have to use proxy-servers to accessing the web-sites.
Sometimes we may remove proxy setting and forget it like that.
I am not sure about that is it possible to implement in to the Devtools.
Simply check proxy setting tab, if any value inside in area , then warn user about proxy settings.

Best Regards,

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out [https://developer.chrome.com/devtools/docs/contributing](https://developer.chrome.com/devtools/docs/contributing) for how to ask questions or file issues on DevTools.
