### ISSUE TITLE
Primer on loading prioritisation (link rel=preload, Resource Hints)

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#4919]
Ship primer on loading prioritisation (link rel=preload, Resource Hints)

**Comment by addyosmani** [comment]
Also cc'ing in Jeff who previously wrote the Updates post on preload: https://developers.google.com/web/updates/2016/03/link-rel-preload

I've written up preload, prefetch and priorities in Chrome: https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf (more of a brain-dump on the state of the world)

and Yoav did the canonical write-up on preload back a few years ago: https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/

**Comment by sgomes** [comment]
PR out: #5236

**Comment by sgomes** [comment]
This article is now live at https://developers.google.com/web/fundamentals/performance/resource-prioritization
