### ISSUE TITLE
Tracking User-centric Performance Metrics

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#4921]
Ship a primer on new loading speed metrics (Time to consistently interactive, FMP etc)

Phil worked on https://developers.google.com/web/updates/2017/06/user-centric-performance-metrics back in May. It would be great to expand on this and turn it into our canonical reference page on modern loading metrics.

**Comment by addyosmani** [comment]
Tagging in case to help coordinate here as he's already been writing some of the Lighthouse specific docs around our modern metrics:

https://developers.google.com/web/tools/lighthouse/audits/consistently-interactive
https://developers.google.com/web/tools/lighthouse/audits/first-interactive
https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

**Comment by addyosmani** [comment]
@philipwalton Do you think you'll have time before January 15th to move https://developers.google.com/web/updates/2017/06/user-centric-performance-metrics from /updates to /fundamentals with the following changes?

- Link up to your article on why developers need to care about interactivity
- Update the language in the first Note: to be timeless (e.g drop a few weeks ago)
- Sanity check the state of APIs like PerformanceObserver that are mentioned

Context: I'd like to try wrapping up guidance for the new loading section soon so that we can note our team wrapped up a "loading" bundle of content during the DevRel Summit later in the month.

This article could benefit from a little further reworking (we've discussed this before I think), but I'm happy to defer this exercise to a later time so we at least have something.

**Comment by philipwalton** [comment]
Is the 15th a hard deadline for some other larger push?

I can try my best to get to this, but I'm also wrapping up some other work and trying to put together a demo before M64. We can talk offline if you want to discuss how this fits with those priorities.
