### ISSUE TITLE
Primer on HTTP/2 Server Push + gotchas

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#4922]
Ship a primer on HTTP/2 Server Push + gotchas. There are still lots of icky bugs remaining here https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/ that Jake documented well. 

Guidance with strong caveats might still be useful. I was thinking something similar to what we did with the PRPL pattern where the doc was labelled experimental and kept that way for incubation:

![image](https://user-images.githubusercontent.com/110953/29049189-671100da-7b89-11e7-8d63-7789ce3103e5.png)

Side: one large gotcha is that the platform still doesn't have support for Cache Digests, so if we do talk about Server Push we may need to mention using cookies to keep track of what is in the user's cache to avoid over-pushing. h20 does this.

**Comment by addyosmani** [comment]
After chatting about H2 Push with the team, our position is that unless you're an advanced team skilled enough to work around the various cross-browser bugs and quirks (lack of Cache Digests), we're not going to broadly recommend H2P to anyone just yet.

The only real H/2 Push guidance on /web today is https://developers.google.com/web/fundamentals/performance/http2/#server_push.

Some things I would love us to do if there's time:

* Link up to Jake's H/2 push gotchas post: https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/
* Add a `note` disclaimer with our current recommendation around Push. This could be the place we link up to Jake's post or could do that lower down in the doc with the rest of the read more material.

@surma @sgomes is this something either of you would be up for?

**Comment by sgomes** [comment]
Yup, I can look at this! When would we need it by, @addyosmani?

**Comment by surma** [comment]
Happy to collab if you want, @sgomes :) Just OOO currently.

**Comment by sgomes** [comment]
Sounds good, let's work on this when you're back, @surma! Enjoy your vacation and get off of GitHub! :P

**Comment by addyosmani** [comment]
Before end of the quarter would be great.

**Comment by addyosmani** [comment]
Before end of the quarter would be amazing :)

On Dec 6, 2017 8:56 AM, "Surma" <notifications@github.com> wrote:

Happy to collab if you want, @sgomes <https://github.com/sgomes> :) Just
OOO currently.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/WebFundamentals/issues/4922#issuecomment-349703759>,
or mute the thread
