### ISSUE TITLE
Primer on efficient Web Font Loading

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#4923]
@notwaldorf wrote up an excellent piece on this a while back https://meowni.ca/posts/web-fonts/ and was down for writing up an up to date article on this topic for /web.

Ilya has previously written up a Web Font optimization guide at https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization so we'll need to make a call on whether this is expanding that guide (preference) or introducing something significantly new. 

If we were updating the existing guide, it would be great to capture recent progress on guidance around ideas like using `font-display: optional`

**Comment by notwaldorf** [comment]
I think we should just expand on Ilya's. I just re-read it, and it's *so good*

**Comment by denar90** [comment]
It will be super cool 👍 
I've been using @notwaldorf's article for [perf audit](https://medium.com/@denar90/vue-js-docs-performance-audit-e89b11dfc43) vuejs docs site. 
I'm sure guys, you will write solid stuff! 
Waiting for it 😍

**Comment by jeffposnick** [comment]
This was fixed in #5302
