### ISSUE TITLE
Primer on Service Worker performance best practices

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#4926]
I'll defer to Jeff for the content of this guide. Some ideas we kicked around with the loading team the last time we thought about creating such an article:

- Pro tip #1: Mitigate startup cost with Navigation Preload
- Pro tip #2: avoid responding with a reissued request from SW
- Pro tip #3: use streaming respondWith for improved performance
- Pro tip #4: no fetch event handler optimization
- Pro tip #5: prefer a conservative “scope”

@jakearchibald covered [nav preload](https://developers.google.com/web/updates/2017/02/navigation-preload) in an updates post earlier in the year.

**Comment by addyosmani** [comment]
Thanks for getting this started, @jeffposnick!

**Comment by jeffposnick** [comment]
I've put together a draft that's been reviewed, and I think I'm ready to file a PR.

Should I host the content alongside the existing articles, like https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/registration? Or was the idea to host this in a (yet to be created) new section?

CC: @petele

**Comment by petele** [comment]
Hey Jeffy - in the new IA, it'll go under /web/fundamentals/primers/service-workers/. Take a peek at the [webfu-new-ia branch](https://github.com/google/WebFundamentals/tree/webfu-new-ia/src/content/en/fundamentals/primers/service-workers) and you can see it semi-staged [here](https://pr-5003-dot-web-central.appspot.com/web/fundamentals/primers/service-workers/)

**Comment by petele** [comment]
The goal is to get the new site launched mid-next week.

**Comment by jeffposnick** [comment]
Sounds good. I'll file a PR with the `webfu-new-ia` branch as the base.
