### ISSUE TITLE
Setting menu icon/link to to be WCAG compliant contrast

### ISSUE THREAD

**Issue by kosamari** [google/WebFundamentals#4942]
[via Twitter feed back](https://twitter.com/betaorbust/status/897163919734718466)

**Comment by robdodson** [comment]
Hm. Seems like there are some bigger issues related to this. Like no decent focus states on the top navigation.

Is this stuff that we're empowered to change or is this handled by Luke and the devsite team?

**Comment by petele** [comment]
Please file a bug with the DevSite team on Buganizer. I'm sure they'd be happy for you to fix once you check with them.

**Comment by robdodson** [comment]
I'll save this ticket and open a bug after all the Polymer Summit frenzy settles down.
