### ISSUE TITLE
[devtools] Breakpoints disappeared after refreshing tab

### ISSUE THREAD

**Issue by lcc19941214** [google/WebFundamentals#4952]
I'm using Sources of develop tools to debug my codes.
I set breakpoints at specific lines, however, breakpoints labels would disappear when I refresh the tab.
Breakpoints would work but I couldn't manually toggle those breakpoints labels.
Only if I close current tab and enter my dev site again, those lovely blue labels would  appear again, or breakpoints would still be there and I couldn't exit my 'debug mode', 

How could I make breakpoints labels always be there?

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out [https://developer.chrome.com/devtools/docs/contributing](https://developer.chrome.com/devtools/docs/contributing) for how to ask questions or file issues on DevTools.
