### ISSUE TITLE
Migrate Workbox documentation to /web

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#4982]
As part of our efforts to centralize docs for Chrome's OSS projects, we'd like to move the official Workbox docs from https://workboxjs.org to https://developers.google.com/web/tools/workbox/. This would place the docs along-side Lighthouse and DevTools.

**Markdown source**
Content will be migrated from https://github.com/GoogleChrome/workbox-microsite.

We believe a lot of the existing articles can be migrated without too much friction:

https://workboxjs.org/get-started/webpack.html
https://workboxjs.org/get-started/gulp.html
https://workboxjs.org/get-started/npm-script.html
https://workboxjs.org/examples/workbox-sw/
https://workboxjs.org/examples/workbox-broadcast-cache-update/index.html etc.

**Domain**
Once docs have been migrated, we will redirect https://workboxjs.org to /web/tools/workbox/.

**When**
If we're able to get TW help, we might be able to move the site content over sooner. If not, workbox-core are happy to move the site over after BlinkOn later in September. We'll want to complete this before the V3 launch of Workbox aimed at October.

**To discuss**
Our generated JSDocs are the main piece that will require some additional thought. 

Projects like DevTools maintain these types of docs (e.g for the remote debugging protocol) on GitHub pages: https://chromedevtools.github.io/devtools-protocol/. We could do similar for our JSDocs and keep all other main content on /web.

cc @jeffposnick @gauntface @philipwalton from workbox-core
cc @kaycebasques as TW fyi
cc @PaulKinlan @petele on move

**Comment by gauntface** [comment]
Started migration here: https://github.com/google/WebFundamentals/tree/workbox

Reference docs will need some rebuilding to be DevSite friendly.

**Comment by gauntface** [comment]
Update from me: DevSite JSDoc template is in and I've added the code to auto-update reference docs in WebFun. Now just need to figure out the last complaints from DevSite (Which sadly WebFun doesn't catch).

**Comment by jeffposnick** [comment]
The content from https://workboxjs.org/examples/ have been moved to Glitch, at https://workbox-samples.glitch.me/examples/

The URLs should (assuming I configured things correctly...) map 1:1 from `https://workboxjs.org/example/*` to `https://workbox-samples.glitch.me/examples/*`, so it would just be a question of configuring the old Firebase Hosting domain to do a 301 Redirect to the Glitch domain for anything under `/examples/`.

**Comment by gauntface** [comment]
This is currently pending a review: https://github.com/google/WebFundamentals/pull/5099#issuecomment-334482462

**Comment by gauntface** [comment]
Moved over now.
