### ISSUE TITLE
UI>Frontend: Repetitive words "a user" are displayed

### ISSUE THREAD

**Issue by 312312** [google/WebFundamentals#4985]
Step 1:
Launch the URL: https://developers.google.com/web/tools/lighthouse/audits/address-bar#feedback
Step 2:
Navigate to "How to pass the audit" section
Step 3:
Read the sentence which is described as "The theme-color meta tag ensures that the address bar is branded when a user a user visits your site as a normal webpage."

**Actual Result:** Application display **"a user"** words more than one time
**Expected Result:** Application should not display repetitive words like "a user" that gives bad user experience
![repetitive words](https://user-images.githubusercontent.com/31514113/29931247-4aac968a-8e8e-11e7-9525-49038e73fe05.jpg)

**Comment by brittanystoroz** [comment]
Sorry this has been resolved with PR #4990 and can be closed, I must've missed the issue number in the commit message. 😬
