### ISSUE TITLE
[Lighthouse / Manifest Short Name Truncation / Helpful]

### ISSUE THREAD

**Issue by jabcreations** [google/WebFundamentals#5016]
I've never heard of this and the page contains absolutely no meaningful context. Is this a JSON string, CSS property, etc? If so where would it typically be implemented? A meta element? A header?

After a few searches it appears this page has the most recognizably relevant information:
https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by kaycebasques** [comment]
Hey @jabcreations what specifically have you never heard of? The web app manifest or the `short_name` property?

The "How to pass the audit" section of this doc links off to more info about how to implement the web app manifest.

**Comment by jabcreations** [comment]
There are object (unknown) contexts being referred to that are not defined. When I come across them again I will list them all here.

**Comment by jabcreations** [comment]
From the Firefox/Waterfox web console:

> ReferenceError: reference to undefined property 7[Learn More] s.php:355:1
> ReferenceError: reference to undefined property "fireOnResizeEnd"[Learn More]  paymentform:1:21027
> ReferenceError: reference to undefined property "excludeCanvas"[Learn More]  f.js:1:862
> ReferenceError: reference to undefined property "maxTouchPoints"[Learn More]  f.js:1:25332
> ReferenceError: reference to undefined property "_keyUpTimer"[Learn More]  iframe:31:11943
> ReferenceError: reference to undefined property "_keyUpTimer"[Learn More]

If there is anything I can do to help resolve these problems please let me know. I pride myself in having a completely clean web console as that infers that I've got everything covered; my clients are worth it. :-)

**Comment by kaycebasques** [comment]
I don't think these errors are related to Lighthouse.
