### ISSUE TITLE
/updates needs a next page button

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#5021]
https://developers.google.com/web/updates/ needs to have a big arrow button for "see more". It's very easy to miss the "archive" link at the bottom of the page. It's visually the same as the other article links on that page:

<img width="1056" alt="screen shot 2017-09-10 at 9 19 08 am" src="https://user-images.githubusercontent.com/238208/30250772-1da74180-9609-11e7-9cf2-ea77cbf87fef.png">

I bet a lot of people miss it and don't find our other content. We also release a bunch of articles at once, so it's easy for new stuff to get pushed into "archives" right away.

**Comment by paperplanes53** [comment]
Hi. I'm not sure if you are supposed to use the Chrome Developer tools but I added the next page button. Please remove it if you don't like it. I'm not sure if it matches the color scheme. I am in my last semester as a Computer Science and Applied Mathematics student and thought I would contribute to open source projects.

**Comment by petele** [comment]
I pushed an update that adds "By Year" and "By Tag" to the lower tabs on the page, making it much easier to see that there's a lot more content. Feel free to re-open if you don't think that's enough.
