### ISSUE TITLE
Code example for "Creating elements from a <template>" does not always work

### ISSUE THREAD

**Issue by mlcdf** [google/WebFundamentals#5032]
Hi there,

The following code snippet (found [here](https://developers.google.com/web/fundamentals/architecture/building-components/shadowdom)) does not work when extracted in its own .html file:

```
<template id="x-foo-from-template">
  <style>
    p { color: orange; }
  </style>
  <p>I'm in Shadow DOM. My markup was stamped from a &lt;template&gt;.</p>
</template>

<script>
  customElements.define('x-foo-from-template', class extends HTMLElement {
    constructor() {
      super(); // always call super() first in the ctor.
      let shadowRoot = this.attachShadow({mode: 'open'});
      const t = document.querySelector('#x-foo-from-template');
      const instance = t.content.cloneNode(true);
      shadowRoot.appendChild(instance);
    }
    ...
  });
</script>
```
I have the following error in the console Chrome `TypeError: Cannot read property 'content' of null`
because `document.querySelector('#x-foo-from-template');` returns `null`. 

When I put directly the code snippet in my main HTML file (inside off putting it in it's own HTML file and importing it), I works fine. Am I missing something here?

I tried with `document.querySelector('template');` too but it doesn't work.

**Comment by imsingh** [comment]
@mlcdf Use the following
```
<template id="x-foo-from-template">
  <style>
    p { color: orange; }
  </style>
  <p>I'm in Shadow DOM. My markup was stamped from a &lt;template&gt;.</p>
</template>

<script>
  const t = document.currentScript.ownerDocument.querySelector('#x-foo-from-template');
  customElements.define('x-foo-from-template', class extends HTMLElement {
    constructor() {
      super(); // always call super() first in the ctor.
      let shadowRoot = this.attachShadow({mode: 'open'});
      const instance = t.content.cloneNode(true);
      shadowRoot.appendChild(instance);
    }
    ...
  });
</script>
```

I already made a pull request for that. I hope it helps.

**Comment by mlcdf** [comment]
TIL `document.currentScript.ownerDocument` is a thing. 

Thank you so much @imsingh, it works great. Have a nice evening!

**Comment by imsingh** [comment]
Thanks @mlcdf . But do check the comments on my pull request by @robdodson . Those are helpful.
