### ISSUE TITLE
[DevTools / JS / Get Started / Tutorial Is Helpful]

### ISSUE THREAD

**Issue by ariansen** [google/WebFundamentals#5047]
I like chrome a lot and have until now been very satisfied with debugging, however recently I've had problems debugging javascript and jquery with setting breakpoints. 

I start by pushing [F12] to open deveoper tools. In the console panel I have made a console.log() command and have earlier been able to push a link on the right hand side that takes me into the Source panel where I can debug with break points, but now developer tools have changed. Instead of coming to Source panel I've been taken to the Application panel and there I'm not able to debug. I have also tried to go to the source panel to find the jquery file in the left hand window, but under the map "styles" where I have s js map, it shows nothing. It's not possible to open the file in Source panel. Veeery frustrating. Kind regards, Jon Haakon Ariansen

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
