### ISSUE TITLE
[UI] Polytechnic Events

### ISSUE THREAD

**Issue by kevinweekes** [google/WebFundamentals#5062]
Are Polytechnic events still applicable? 
I came across the link after visiting the PWA training

Recreating the steps:
1. Visit [Web Fundamentals](https://developers.google.com/web/fundamentals/)
2. Click the hyperlink in the top banner that begins, "Are you a developer in an agency in the UK, Indonesia or India? Find out more about our free 2 day"
3. When the new page loads, click the link for [Polytechnics](https://developers.google.com/web/events/polytechnic/)

**Comment by petele** [comment]
No, I don't think there are any currently planned, sorry.
