### ISSUE TITLE
Adding Push Notifications to a Web App

### ISSUE THREAD

**Issue by yorgeeBG** [google/WebFundamentals#5070]
The URL to the https://web-push-codelab.appspot.com/  shows 404. That’s an error.

Here is the tutorial URL https://developers.google.com/web/fundamentals/codelabs/push-notifications/

**Comment by petele** [comment]
@gauntface - i know you're working on getting it fixed, but FYI

**Comment by yorgeeBG** [comment]
I found alternative URL that works for now https://web-push-codelab.glitch.me/

**Comment by gauntface** [comment]
I've updated the codelab with this change as well, so WebFundamentals just needs to rebuild I think.

**Comment by gauntface** [comment]
https://codelabs.developers.google.com/codelabs/push-notifications/index.html?index=..%2F..%2Findex#2
