### ISSUE TITLE
10 missing HREF on googlesamples.github.io

### ISSUE THREAD

**Issue by lucab85** [google/WebFundamentals#5081]
The page [https://developers.google.com/web/fundamentals/design-and-ux/responsive/images](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images) references 10 missing URI:

- https://googlesamples.github.io/web-fundamentals/fundamentals/media/media.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/sizes.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/breakpoints.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/compressive.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/conditional-mq.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/image-set.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/media-query-dppx.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/icon-svg.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media/icon-font.html
- https://googlesamples.github.io/web-fundamentals/fundamentals/media//image-sprite.html

**Comment by amckinlay** [comment]
Came here for the same reason. This is disappointing.

**Comment by petele** [comment]
fixed in #5123
