### ISSUE TITLE
[Lighthouse / Blocking Resources / Helpful]

### ISSUE THREAD

**Issue by MatteoNY** [google/WebFundamentals#5106]
Adding async so I pass audit is great but what is the side-effect.   My guess adding async to script tags is if supported by the browser it will help and in other cases do nothing.  In a test I added async to all the major <script> tags on the outer server-side page not inside of Angular and my performance went down from a high of 30% (removed the scripts) to 21%.  My app is an Angular v4 app and at this time I need to use Material Design for DatePicker and Ng-bootstrap for autoComplete as the Material Design version does not work in Mobile (iOS) so I can't use it. This means I need to load both .css and libs (I can select imports with Material Design nice!) but with ng-bootstrap not finished I can't select what I need. This app should be more of a 90% performance vs 30%. Need better documentation on how to make perform better. Render blocking CSS?  is it coming from Material Design's CSS or Bootstrap 4?  I don't have much CSS of my own css in this test just a few lines to tweak as .scss. Need more details on how to improve CSS or maybe this is the best until MD and BS4 are final. I have another Angular v4 app that gets 60% and I'm trying to improve that. On that app I'm using lazy-loading so I'm not sure why it's not showing up faster. Any way Angular v5 is coming out :-). Thanks for a cool tool. I hope the above helps.

**Comment by kaycebasques** [comment]
Sounds like these issues only apply to your particular technology stack and may not be appropriate for the Lighthouse docs.
