### ISSUE TITLE
New Developer > setting > preference request

### ISSUE THREAD

**Issue by TimoPot** [google/WebFundamentals#5108]
in Developer Tools;

In the Sources panel the files are shown as tabs. When using large filenames the start of the filename and the extension is shown 

Example: the filename is: iamalargefilename.js

Now the tab shows: iamalar.....js
I need to see the end part of the filename like: i.....filename.js

I would like to have a preferences that I can choose what part of the filename is shown in the tab.

**Comment by kaycebasques** [comment]
@TimoPot please file a feature request at https://crbug.com
