### ISSUE TITLE
Urgent: Hate Symbol of alt-right used in dev tools examples

### ISSUE THREAD

**Issue by jakearchibald** [google/WebFundamentals#5142]
https://developers.google.com/web/updates/2017/10/devtools-release-notes

Pepe appears in multiple examples here. This needs removed, now.

https://en.m.wikipedia.org/wiki/Pepe_the_Frog

**Comment by jakearchibald** [comment]
It's in both the first and second video

**Comment by jakearchibald** [comment]
https://github.com/google/WebFundamentals/pull/5143

**Comment by jakearchibald** [comment]
Fixed.

**Comment by clobber** [comment]
LMAO this is hilarious - it's a cartoon frog.
