### ISSUE TITLE
[DevTools Network Issues Guide Suggestion]

### ISSUE THREAD

**Issue by njajay** [google/WebFundamentals#5154]
In chrome developer tools when we capture the network traffic and save the har file. We are seeing first request is not starting at 0th ms. This issue is seen with latest chrome as we had not seen this behavior before.

Can you please let us know why there will be a difference or lag at start of first request? Should the finish time not include the lag as current finish time reported doesnt include the lag.

**Comment by pratul397** [comment]
We have observed that the HAR files, saved from the chrome developer tools profile, show incorrect start time of the first html request. We expect this time to be same or very close to the page load start time (also shown in the HAR) but they are not. This ultimately causes alignment issues for the first request in the HAR file and also shows incorrect total time.

**Comment by sumon30427** [comment]
All the best wishes the almighty allah, pls., send the systems of service of your lebel best.

**Comment by kaycebasques** [comment]
@njajay and @pratul397 if you're still seeing this issue please file a bug at https://crbug.com
