### ISSUE TITLE
this link is point to blank page  

### ISSUE THREAD

**Issue by inyee786** [google/WebFundamentals#5227]
https://developers.google.com/web/tools/chrome-devtools/ui#settings
in the  "To enable DevTools experiments" section the first link is point to blank page
the link is "chrome://flags/#enable-devtools-experiments."

**Comment by BalajiJBcs** [comment]
It is not actually link and if you used chrome and it should work fine.

**Comment by jpmedley** [comment]
This isn't a web link and it's not intended to be be. It's a link to one of Chrome's configuration pages.
