### ISSUE TITLE
[DevTools / JS / Get Started / (3) Paused On Correct Line]

### ISSUE THREAD

**Issue by Yeganefatih** [google/WebFundamentals#5246]
Hello I m new in the github I was wondering around thanks to you I found this website for learning basics of javascripting and how to use.

The problem is I can't see the javascript .js file on the inspect sources panel 
![data](https://user-images.githubusercontent.com/33336577/32358058-2337d512-c04b-11e7-9e21-37bff2d17049.png)

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out [https://developer.chrome.com/devtools/docs/contributing](https://developer.chrome.com/devtools/docs/contributing) for how to ask questions or file issues on DevTools.
