### ISSUE TITLE
Typo in Lab: Scripting the Service worker

### ISSUE THREAD

**Issue by glennsimon** [google/WebFundamentals#5259]
On page https://developers.google.com/web/ilt/pwa/lab-scripting-the-service-worker
There is a typo in section "1. Get set up":
>    open the service-worker/app folder.

should read

>    open the service-worker-lab/app folder.

**Comment by DavidScales** [comment]
I've updated the typo in our source docs and the content should get updated in a week or so when we run our next build. Thanks for the catch!
