### ISSUE TITLE
Setting network offline in devtools does not affect localhost server

### ISSUE THREAD

**Issue by glennsimon** [google/WebFundamentals#5274]
In section 3 of the "Caching Files with ServiceWorker" lab in the PWA training (https://developers.google.com/web/ilt/pwa/lab-caching-files-with-service-worker#3_serve_files_from_the_cache), the student is instructed to "take the app offline".  The hyperlink on that instruction tells how to use devtools to set the browser to offline mode, but the server being used is on localhost.  Since localhost does not need the network, setting the browser to offline doesn't prevent the files from being fetched from the server.

Instead, I simply stopped the server and the behavior was as expected - cached items were displayed, non-cached items came back with a 404 error.

Fix:  The instructions should tell the student to stop the server when they want to test the cache and restart it when they want to resume normal operation.  These instructions appear several times in this tutorial.

BTW, I'm glad to know about the instruction for disabling the network using devtools, but it just doesn't work in this particular case.

**Comment by DavidScales** [comment]
Hi again Glenn - thanks for filing another bug! 

Although it certainly doesn't seem like it, Chrome's offline mode actually does work for localhost! ... usually ;) There is currently a [bug that causes unexpected behavior in offline mode](https://bugs.chromium.org/p/chromium/issues/detail?id=772133#c1), but it has been corrected in Chrome 63. 

Unfortunately those instructions are scattered throughout dozens of tutorials, so we probably won't be able to update them before Chrome 63 comes out anyways. But in the meantime, shutting down the server works just as well.
