### ISSUE TITLE
Page not working

### ISSUE THREAD

**Issue by Ankiewicz** [google/WebFundamentals#5278]
Haha,  Sorry I think its ironic. 

On the google.com search page I got a popup asking for me to test my website speed at https://testmysite.thinkwithgoogle.com/.

When I go there to test it, the page doesn't work. When I click the send/submit button it just sits, no matter the url entered. the form validation works because if you enter it with a empty field it validates.

**Comment by rohithmacherla** [comment]
The form validation fails after you attempt one valid search.
