### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#5286]
- Update Node
- Make test build so it's a single command to test if travis is going to build
- Move python files into a directory rather than the root of the project.

**Comment by gauntface** [comment]
- kill wf_blink_components test or make it more specific to what pages it tests on.

**Comment by ebidel** [comment]
Let's not kill that one. It's part of the WP program and helps us associate
content related to each component.

**Comment by gauntface** [comment]
@ebidel I know it has a use, but the linting rule has never been useful for me and instead fills up the log from warnings that could be useful. By "kill wf_blink_components" I was really referring to the lint test.

**Comment by PaulKinlan** [comment]
Why wouldn't we associate the service worker component with this content?
