### ISSUE TITLE
Lighthouse / Critical Request Chains / seems broken wrong data

### ISSUE THREAD

**Issue by adardesign** [google/WebFundamentals#5293]
I am looking at [This page](https://www.adorama.com/ifjxt2.html) and [here is the lighthouse report](http://www.webpagetest.org/lighthouse.php?test=171116_VT_25a81b7a878073f7ec1b79ab4eb290a9&run=2)
 
I clearly see that `/plugins/like.php?href=` is deferred and even delayed
Why does it still show up as a critical resource?

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Lighthouse issue. If you're still seeing it, would you please file a bug with [Lighthouse](https://github.com/GoogleChrome/lighthouse)
