### ISSUE TITLE
When using debugger and you refreshes the page, the reading area code in Sources tab of Developer Tools gets smaller and, smaller and, smaller

### ISSUE THREAD

**Issue by vyk2rr** [google/WebFundamentals#5299]
When using `debugger;` (when on javascript code) and you refreshes the page, the reading area code in Sources tab of Developer Tools gets smaller and, smaller and, smaller until you have to close tab and open a new one, Here is an animated image showing what is happening: 

http://recordit.co/ahkBR2soy2
[<img src="http://g.recordit.co/ahkBR2soy2.gif">](http://recordit.co/ahkBR2soy2) 

Here some data:

Google Chrome | 62.0.3202.94 (Official Build) (64-bit)
-- | --
Revision | 4fd852a98d66564c88736c017b0a0b0478e885ad-refs/branch-heads/3202@{#789}
OS | Mac OS X
JavaScript | V8 6.2.414.42
Flash | 27.0.0.187 /Users/vyk/Library/Application Support/Google/Chrome/PepperFlash/27.0.0.187/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by jpmedley** [comment]
We need your version of Chrome too. Go to chrome://version/

**Comment by vyk2rr** [comment]
@jpmedley 

Google Chrome | 62.0.3202.94 (Official Build) (64-bit)
-- | --
Revision | 4fd852a98d66564c88736c017b0a0b0478e885ad-refs/branch-heads/3202@{#789}
OS | Mac OS X
JavaScript | V8 6.2.414.42
Flash | 27.0.0.187 /Users/vyk/Library/Application Support/Google/Chrome/PepperFlash/27.0.0.187/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path | /Users/vyk/Library/Application Support/Google/Chrome/Default
Variations | c134752e-ca7d8d80c68ab9a3-3f4a17df3095aa95-3f4a17df7c1bc906-f55a797447e5d3db-3d47f4f41210a805-ecd831cd43bf3e5-bd7cd813ba3f87da-45bda65679616653-3f4a17dffe2a3897-64e7d9aed7ba060-91c810ef9e201a2b-6e3ce1c5b3ed0a1-3f4a17df68812885-4d2fac87684d1cdf-160692dcb684f56f-4d2fac87f347910c-3d47f4f49773d3bd-f23d1dea99144bc3-3cc2175e9e5c75f1-7ebf8ff8e79c5ffa-28ad44af79cb77b-3d47f4f4be3b5415-bed958527219e67-b20471784ea303a6-ecbb250ed92562a9-ca7d8d801c2f7bbf-ca7d8d80b2f0086-93053e47ef25c1eb-ca7d8d80494d8760-91c810eff47ae82a-86f22ee53ac60855-486e2a9cf296190c-477de7984442aae2-6bdfffe7ed1d377-e1cc0f1475f0f0a0-d7f6b13ce2b18481-6754d7b7e7e71889-4ad6057594e68624-803f8fc4828a5926-9d7acf42da4aaa01-ca7d8d80

**Comment by vyk2rr** [comment]
I updated chrome to this version, and it stills happen

Google Chrome	63.0.3239.108 (Official Build) (64-bit)
Revision	d2626860fae283daee484943e6820af18fc73fd9-refs/branch-heads/3239@{#676}
OS	Mac OS X
JavaScript	V8 6.3.292.48
Flash	28.0.0.126 /Users/vyk/Library/Application Support/Google/Chrome/PepperFlash/28.0.0.126/PepperFlashPlayer.plugin
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36
Command Line	/Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path	/Users/vyk/Library/Application Support/Google/Chrome/Default
Variations	c134752e-b8b72c88
c514edff-ca7d8d80
3095aa95-3f4a17df
6c43306f-ca7d8d80
7c1bc906-f55a7974
47e5d3db-3d47f4f4
1210a805-ecd831c
b1edbc38-cf4f6ead
d43bf3e5-bd7cd813
ba3f87da-45bda656
776de70c-eadfd437
79616653-3f4a17df
9e201a2b-6e3ce1c
68812885-4d2fac87
684d1cdf-160692dc
f347910c-3d47f4f4
4b61504a-d25ea691
9773d3bd-f23d1dea
8e3b2dc5-93702590
9e5c75f1-1039a221
f79cb77b-3d47f4f4
4ea303a6-ecbb250e
d92562a9-ca7d8d80
90bcbadc-d25ea691
25fc488a-4d2fac87
1c2f7bbf-3f4a17df
1bced4a3-59ba3fef
b2f0086-93053e47
ef25c1eb-3f4a17df
494d8760-6843eff2
f47ae82a-86f22ee5
3ac60855-486e2a9c
f296190c-477de798
4442aae2-6bdfffe7
ed1d377-e1cc0f14
75f0f0a0-d7f6b13c
e2b18481-6754d7b7
e7e71889-4ad60575
94e68624-803f8fc4
f141d4bc-28ad44a
e9ce63c1-3d47f4f4
da4aaa01-ca7d8d80

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
