### ISSUE TITLE
Issue in selecting Css files in chrome console while adding new style

### ISSUE THREAD

**Issue by pvngit** [google/WebFundamentals#5318]
Hi Team,
First of all, Let me appreciate you guys for providing a great tool for development.

But I have recently found some issues in chrome console. I have listed down two issue that is very annoying.

1. In the style section, when clicked on the 'plus' icon, the css selector will be added to a css file. Previously it was adding styles to inspector style sheet. But now it is getting added to the first possible file in the list. Its not actually asking for an option in which file it should be saved. This is really annoying. If possible keep inspector style sheet itself. 

2. When clicked on the color selector in style section, the color picker appears but nothing else will work unless the console is closed.

Hope you would fix these issues very soon.

Thank you so much.
Praveen S

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
