### ISSUE TITLE
Upgrade to Node 8

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#5337]
@petele @PaulKinlan is there any reason not to upgrade to Node 8? Otherwise can I put in a PR that just bumps us up to Node 8 for Travis and unblock people from using node 8 features (i.e. async and await).

**Comment by PaulKinlan** [comment]
I don't know of a reason, can we run node 8 internally (might be best to
discuss internally)?

**Comment by gauntface** [comment]
Move to internal discussion (Not sure why).
