### ISSUE TITLE
Missing languages on Web Fundamentals

### ISSUE THREAD

**Issue by limhenry** [google/WebFundamentals#5353]
There are some missing languages on the the [production site](https://developers.google.com/web/fundamentals/):
 - العربية‬
 - עִבְרִית
 - Hindi
 - Italiano
 - Nederlands
 - Polski
 - Türkçe
 - 中文（繁體）

There's an option for these languages on the [staging site](https://web-central.appspot.com) but not on the [production site](https://developers.google.com/web/fundamentals/).

**Comment by agektmr** [comment]
@limhenry do you see italian in this page?
https://developers.google.com/web/fundamentals/performance/http2/

I think the list may be adoptive to what's available.

**Comment by limhenry** [comment]
Yes, i can see the italian translation for this article ([Introduzione a HTTP/2](https://developers.google.com/web/fundamentals/performance/http2/)

**Comment by limhenry** [comment]
Yep. Is that article/page have the translation, then that language will shows on the footer.

Example
 - Showing option for zh-tw: https://developers.google.com/web/fundamentals/design-and-ux/animations/animating-between-views
 - Not showing option for zh-tw: https://developers.google.com/web/fundamentals/

**Comment by agektmr** [comment]
People with proper locale set on their browser will see the translated content anyway. I believe the best way to fix this is not to worry about it.
