### ISSUE TITLE
Contributor credit is not properly displayed in staging environment

### ISSUE THREAD

**Issue by agektmr** [google/WebFundamentals#5354]
If you look at contributor's credit portion of the HTML it's broken in staging environment.
For example, while [this Italian page](https://developers.google.com/web/fundamentals/performance/http2/?hl=it) shows following:
<img width="437" alt="screen shot 2017-11-29 at 18 36 05" src="https://user-images.githubusercontent.com/218144/33368205-60acfc9e-d534-11e7-8248-48a6b631468b.png">

staging equivalent of the same page shows this:
<img width="758" alt="screen shot 2017-11-29 at 18 35 54" src="https://user-images.githubusercontent.com/218144/33368210-652440ca-d534-11e7-9edb-8ab46c4e90c9.png">

I think `contributor` directory is located in odd place under `en/_shared/`. Maybe we are expecting this to be translated as well?

cc: @petele

**Comment by petele** [comment]
I think this is fixed now.
