### ISSUE TITLE
Define set of required rules and enforce with eslint

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#5361]
At the moment the PR for doc building is being held up by rules not enforced by anything.

What rules do we want, then lets get it enforced via eslint and add to travis.

So far I'm aware of a requirement for jsdocs on all gulp-tasks. Is there anything else?

**Comment by petele** [comment]
jsdocs on gulp-tasks is better code hygiene. I didn't do it in the past, but I was the only one ever editing that stuff, so if there's new stuff, I want to start being better. At a bare minimum, I'd like to at least have the file level docs and eventually drive to full jsdocs.

What rules does lighthouse and workbox use? Are they the same? If so, let's use those. If they're different, let's be reasonable and go from there!

**Comment by gauntface** [comment]
The eslint file in #5336 will do this.
