### ISSUE TITLE
No ToC in WNDT64

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#5369]
Pete do you know why this page isn't displaying the left ToC?

https://developers.google.com/web/updates/2017/11/devtools-release-notes

<img width="1413" alt="screen shot 2017-11-29 at 1 16 10 pm" src="https://user-images.githubusercontent.com/4713486/33399520-c4a3b486-d507-11e7-8dbd-10835e13996b.png">

**Comment by petele** [comment]
Usually if the left nav isn't displaying, there's a problem with the TOC and the article not being in the TOC.  It seems to be working now.

**Comment by kaycebasques** [comment]
@petele do I need to add update articles to a _toc.yaml file? I thought the ToC for articles got generated in the build system.
