### ISSUE TITLE
Django includes in markdown code block shouldn't be allows

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#5374]
The code parse is used first conversion

{% include "<path>"%}

to

{% include &quot;<path>&quot;}

Resulting in a failing build. This works on WebFundamentals.

**Comment by petele** [comment]
Is this still an issue?

**Comment by gauntface** [comment]
No idea - I think you did some regular expression changes - but no idea if it caught this error. I know my PR for it didn't land.
