### ISSUE TITLE
Dev Tools Elements Expand All not working

### ISSUE THREAD

**Issue by gsgriffin** [google/WebFundamentals#5380]
have the latest version of Chrome as of today.  Dev Tools > Elements > Expand All does not work using Ctrl-Alt and clicking the arrow....only opens one level.  Firefox works fine.  Even right-click and selecting option only opens one level.  Very annoying!!!

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
