### ISSUE TITLE
Guide on best practice for linking to maps

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#542]
All OS's now have maps

Apple: https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html#//apple_ref/doc/uid/TP40007899-CH5-SW1
Google: TBD
MS: TBD
FFOS: TBD

**Comment by petele** [comment]
I don't believe that this is in scope for WebFundamentals and should instead refer developers to the specific maps API docs that they want to use. Closing for now, we can re-evaluate in the future if the scope changes.
