### ISSUE TITLE
Best practice guidance for integration with Reading Mode

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#543]
Apple: TBD [Note: this is the extension docs](https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/WorkingWiththeReader/WorkingWiththeReader.html#//apple_ref/doc/uid/TP40009977-CH22-SW3)
Google: N/A
Microsoft: http://msdn.microsoft.com/en-us/library/ie/dn688985(v=vs.85).aspx

**Comment by petele** [comment]
I don't believe that this is in scope for WebFundamentals. Closing for now, we can re-evaluate in the future if the scope changes.
