### ISSUE TITLE
Make wf_blink_components metadata required

### ISSUE THREAD

**Issue by ebidel** [google/WebFundamentals#5436]
@petele and I chatted about this. We should make this metadata required on new and existing documentation and make sure `npm test` and the build scripts flag it.

Q: How do we prevent this from being too noisy? e.g. pages that are not related to web platform features. Should we ask that authors use `{# wf_blink_components: nil #}` to explicitly say there's not a related component?

https://blinkcomponents-b48b5.firebaseapp.com/ is a new page that lists the blink components and helps authors generate the required metadata tag. We can link to that page in the pull request status.

**Comment by kaycebasques** [comment]
This one always confused me. Outputting instructions on how to format this would help. Does it have to match the format in List of Blink Components? How do you specify multiple components? CSV? I'm also curious on how you're using it.

**Comment by ebidel** [comment]
@kaycebasques does the new https://blinkcomponents-b48b5.firebaseapp.com/ page with instructions helps?

**Comment by kaycebasques** [comment]
Yes, that's great.

Although, personally, if I wrote a performance article under
/web/fundamentals, I'd be at a loss as to which component to use, and I
wouldn't necessarily want to comb through that long list.

**Comment by ebidel** [comment]
That's what the filtering is for :)

**Comment by petele** [comment]
For any article that is new or has been edited, you'll be required to update the `wf_blink_components` tag. If the tag doesn't apply, you can simply add `N/A`.

To reduce the noise, the test won't run when merging into master.

**Comment by jpmedley** [comment]
Is 'N/A' case sensitive?

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by petele** [comment]
> Is 'N/A' case sensitive?

Nope.
