### ISSUE TITLE
Add schema.org "update time" information

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#544]

**Comment by gauntface** [comment]
I've added the following and assuming this is the right set of tags


{% if page.published_on %}
<meta itemprop="datePublished" content="{{ page.published_on }}" />
{% endif %}
{% if page.updated_on and page.published_on != page.updated_on %}
<meta itemprop="dateModified" content="{{ page.updated_on }}" />
{% endif %}
