### ISSUE TITLE
Idea google-chrome-devtools: Record automated script tracer with optional detail

### ISSUE THREAD

**Issue by paulthomas75** [google/WebFundamentals#5462]
# Idea:

I'd like to hit a button to start recording a new trace of scripted class methods that have been executed until I hit stop.

The output could be dumped to a screen or log that should easily be exported to a database for analysis and further correlation.

### By default: 

- Class Name

### Optional:  
-   Include Method Names
-    Only record if code is in included specific folders or files 
-    Respect existing debug exclude folder
-    Include a variable watch when in scope

Would by brilliant to show a graph of the interaction just like the git revision graph.

### Background:

A lot of companies I've worked with are moving old code c# to typescript with code generators and tey hook them to Angular front ends.  But trying to find out what is being used is very difficult to remove redundant code or develop useful tests.  Also this is a great idea for general debugging without having to go line by line to see where the rabbit hole goes.

### Support:

-   Javascript
-   TypeScript and sourcemaps

**Comment by petele** [comment]
Hi! Sorry, our Git repo is meant for issues with content on the site. Check out [https://developer.chrome.com/devtools/docs/contributing](https://developer.chrome.com/devtools/docs/contributing) for how to ask questions or file issues on DevTools.

**Comment by kaycebasques** [comment]
Hi @paulthomas75, thanks for the idea.

As Pete mentioned, this is the docs repo. You can open a feature request on https://crbug.com

Just pasting a link to the description that you've created above should be good enough: https://github.com/google/WebFundamentals/issues/5462#issue-280531757
