### ISSUE TITLE
buttons not functioning on Feedback section of Remote Debugging

### ISSUE THREAD

**Issue by BlindPacemaker** [google/WebFundamentals#5479]
Page Affected: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
OS: High Sierra
Chrome: Version 62.0.3202.94

Issue: 

![feedback buttons not functioning](https://thumbs.gfycat.com/DifferentCompassionateFlee-size_restricted.gif)

It is only possible to select one button at a time even though there are two separate questions, and selecting one does not seem to do anything.

**Comment by BlindPacemaker** [comment]
I've also discovered that these buttons are not functioning on firefox or Safari. 

In safari the behaviour is similar, however I get a console error when clicking on the buttons (there is not console error in chrome when clicking on the buttons). The error I receive is:

```
TypeError: window.ga.getAll is not a function. (In 'window.ga.getAll()', 'window.ga.getAll' is undefined)
```

In FF, the buttons do not function but there are no console errors.

**Comment by kaycebasques** [comment]
I removed the feedback section from that doc (I'm revisiting the whole thing, anyways), thanks for the report
