### ISSUE TITLE
Localhost:3000 hijacked by google service worker

### ISSUE THREAD

**Issue by KAdairHawkins** [google/WebFundamentals#5484]
My google service worker is caused hours of frustration by taking over my localhost 3000, which is also the default React.js host. To make matters worse, there is no easy way to turn off the service worker. If you do, then the inspect tools defaults to a modal that follows you around like a lost puppy. Please, fix this.

**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by petele** [comment]
You can remove service workers by going to chrome://serviceworker-internals
