### ISSUE TITLE
auto-updated on

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#5541]
If I write the function to manage this, can I just automatically update the wf_updated_on in husky?

This would be based on the git diff logic we already have in gulp tests.

**Comment by petele** [comment]
Sounds awesome!

**Comment by gauntface** [comment]
Logic is here: https://github.com/google/WebFundamentals/pull/5681/commits/3310d84d6e755645ea18e826e861197fd71649a9#diff-c5f9b992fa42296ad4a79bcc0c58861d
