### ISSUE TITLE
[Lighthouse / Blocking Resources / Helpful]

### ISSUE THREAD

**Issue by sathyaprakash94** [google/WebFundamentals#5569]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

The article is good but not excellent. main intention of this article to educate people to optimise the web page performance. This article definitely worth to read, if it gives a perfect example like what is in mozilla developer page.

**Comment by kaycebasques** [comment]
What mozilla developer page are you referring to?

**Comment by kaycebasques** [comment]
Thank you for the input, but I can't make the docs better unless you give me more specific feedback.
