### ISSUE TITLE
PWA navbar entry disappears

### ISSUE THREAD

**Issue by janat08** [google/WebFundamentals#5571]
**Page Affected:**
https://developers.google.com/web/fundamentals/security/credential-management/
**What needs to be done?**
Make PWA visisble : https://developers.google.com/web/progressive-web-apps/

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by petele** [comment]
Thanks for the feedback! This is by design, you can link to it from the bottom of the page.
