### ISSUE TITLE
explain why the size column has 2 numbers

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#5578]
https://stackoverflow.com/questions/47970166

- [ ] add sections for size, initiator, time... link to large request rows
- [ ] mention in the total size section per gklandes suggestion
- [ ] update large request rows section

**Comment by gklandes** [comment]
Thanks for this. Saw your comment on SO. If it helps, this is where I expected to find the info:
https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#total-size
Good place for at least the reference to the compression info, but ideally the short explanation.

**Comment by kaycebasques** [comment]
Thanks for telling me where you expected to find it, @gklandes. That is very helpful information.
