### ISSUE TITLE
[Lighthouse / Blocking Resources / Helpful]

### ISSUE THREAD

**Issue by tedsecretsource** [google/WebFundamentals#5581]
**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

It would be helpful to have more information on how to identify **critical css** and what, exactly, is meant by inlining, with complete examples (including how to load a stylesheet via JavaScript) and maybe links to tools such as [critical](https://github.com/addyosmani/critical/).

**Comment by kaycebasques** [comment]
Thank you for the actionable feedback!
