### ISSUE TITLE
Chrome developer tools display errors when using ES2015 modules

### ISSUE THREAD

**Issue by urbanhop** [google/WebFundamentals#5605]
Chrome supports modules, but Chrome developer tools stil display js import statements as syntax errors.

Reproduce: open https://paulirish.github.io/es-modules-todomvc/ 

![image](https://user-images.githubusercontent.com/9371283/34600783-8e46944e-f1f9-11e7-90bf-dddc2fdc62d8.png)

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
