### ISSUE TITLE
Update 'wf_blink_component' list

### ISSUE THREAD

**Issue by lucab85** [google/WebFundamentals#5625]
**Page Affected:** https://blinkcomponents-b48b5.firebaseapp.com/

**What needs to be done?**

Update the Blink Components page.

**How to reproduce?**

1. Insert the following header
`{# wf_blink_components: Blink>MediaStream,Blink>SecurityFeature>XFrameOptions #}`

1. Do local `npm test`

1. Result:
```
Unknown 'wf_blink_component' (Blink>MediaStream), see https://goo.gl/VXmg9e
Unknown 'wf_blink_component' (Blink>SecurityFeature>XFrameOptions), see https://goo.gl/VXmg9e
```

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by petele** [comment]
Fixed!
