### ISSUE TITLE
[Loading] Web Performance Tooling

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#5664]
We currently vend a number of different performance tools and efforts:

- Lighthouse
- WebPageTest 
- Chrome DevTools
- PageSpeed Insights (and derivatives like Test My Site)
- Chrome User Experience Report (which PageSpeed Insights now captures too)

and then there are other performance efforts Google provides (like Google Analytics "Site Speed" feature) which we haven't really talked about on /web before. 

I'd love to make it clearer to developers where these different tools fit in their workflow. 

Talked about this with @Meggin but would love to get some help over the next few quarters from @kaycebasques @igrigorik and @dgash on crafting this narrative.

We can then direct folks over to the individual tool/product pages for these efforts:

https://developers.google.com/web/tools/lighthouse/
https://developers.google.com/web/tools/chrome-devtools/
https://developers.google.com/web/tools/chrome-user-experience-report/ etc.

**Comment by vinamratasingal** [comment]
Hey Addy- Some of us (including Ilya, and other xfn folks) are working on an infographic to address this very concern. Will share the draft via email to you and other folks.

**Comment by kaycebasques** [comment]
https://developers.google.com/web/fundamentals/performance/speed-tools/
