### ISSUE TITLE
Missing closing parenthesis

### ISSUE THREAD

**Issue by iliyaML** [google/WebFundamentals#5684]
**Page Affected:** https://developers.google.com/web/fundamentals/media/capturing-images/

**What needs to be done?**

The second to last code snippet which is under the Grab a snapshot and above the Tips section is missing a closing parenthesis.

![error](https://user-images.githubusercontent.com/19851002/35188919-68b94f92-fe05-11e7-9178-426ba4279a1c.PNG "Logo Title Text 1")

The closing parenthesis should be right after the last closing curly brace.

**Comment by rottina** [comment]
This appears to be fixed as of Aug 5, 2018.
https://developers.google.com/web/fundamentals/media/capturing-images/
