### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DamonHD** [google/WebFundamentals#5685]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

Fix typo in link anchor text " First Meaningful Paint: A Layout-Based Aproach."

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by shanejustice** [comment]
@DamonHD I am new to Github, I would like to contribute to this issue
