### ISSUE TITLE
New in Chrome 64 - Chromium 404 link

### ISSUE THREAD

**Issue by jadjoubran** [google/WebFundamentals#5709]
**Page Affected:** https://developers.google.com/web/updates/2018/01/nic64#import-meta

**What needs to be done?**

**Chromium source repository change list** link is a 404 (https://chromium.googlesource.com/chromium/src/+log/63.0.3239.84..64.0.3282.TODO)

I can send a PR if anyone has the correct URL

**Comment by rottina** [comment]
Seems to be working as of Aug 5, 2018. Link was updated and is pointing to: https://chromium.googlesource.com/chromium/src/+log/63.0.3239.84..64.0.3282.140

**Comment by jadjoubran** [comment]
Yep indeed 👍 
It seems someone already fixed it
