### ISSUE TITLE
wndt65 x-refs

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#5735]
mention that  you don't need to turn on experimental flags

https://www.youtube.com/watch?v=8dCUzOiMRy4&list=PLNYkxOF6rcICWx0C9LVWWVqvHlYJyqw7g&t=350s&index=19

**Comment by kaycebasques** [comment]
oh hey, one nit: you may want to reword "color deficiencies" to "color vision deficiencies"
also, not sure if you want to go into this, but color contrast is really for all users, not just folks with low vision. Like if text is grey on white, it's hard for everyone to read.

**Comment by jpmedley** [comment]
Please, do go into that. "Design" is no excuse for hard to read text.

**Comment by kaycebasques** [comment]
Merged this into #5670
