### ISSUE TITLE
Is "🎉 This has been pushed live to https://developers.google.com/web/" needed?

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#5739]
Each time the bot posts this comment I get an update and it's not particularly useful for me personally. 

Feel free to close this, but I wanted to mention it in case anyone has the same opinion.

**Comment by petele** [comment]
I've had a few folks ask for it so that they know when their article/PR has been pushed live.

**Comment by kaycebasques** [comment]
I've also found it useful for quickly referring back to when a doc was first published to prod.
