### ISSUE TITLE
404s in BLE article

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#5745]
In https://web-central.appspot.com/web/updates/2015/07/interact-with-ble-devices-on-the-web, the following URLs are returning non-200 results. Would you please take a look?

* https://developer.bluetooth.org/TechnologyOverview/Pages/GATT.aspx
* https://developer.bluetooth.org/gatt/services/Pages/ServicesHome.aspx
* https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicViewer.aspx?u=org.bluetooth.characteristic.heart_rate_measurement.xml

**Comment by beaufortfrancois** [comment]
So much useful!
Thank you @petele.
