### ISSUE TITLE
404s in lighthouse audits

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#5750]
In the lighthouse audits listed below, the following URLs are returning non-200 results. Would you please take a look?

Lighthouse Audit Pages:
* /web/tools/lighthouse/audits/aria-allowed-attributes
* /web/tools/lighthouse/audits/valid-aria-attributes
* /web/tools/lighthouse/audits/valid-aria-values
* /web/tools/lighthouse/audits/required-aria-attributes
* /web/tools/lighthouse/audits/offscreen-images

URLs that are 404'ing:

* https://www.w3.org/TR/wai-aria/roles#role_definitions
* https://www.w3.org/TR/wai-aria/roles#role_definitions
* https://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def
* https://www.w3.org/TR/wai-aria/roles#role_definitions
* https://github.com/WICG/IntersectionObserver/tree/gh-pages/polyfill

**Comment by kaycebasques** [comment]
I ended up redirecting those a11y docs to the aXe docs because this is what the Lighthouse report UI does.
