### ISSUE TITLE
Feedback for: /index.html - Web Starter Kit is too hard to find

### ISSUE THREAD

**Issue by marcacohen** [google/WebFundamentals#577]
WSK seems like a pretty important part of the Web Fundamentals initiative, yet it's surprisingly hard to find via existing navigation. The only references to WSK on the WF landing page are two inline hyperlinks (which don't readily jump out at visitors and also aren't seen unless the user scrolls the main page) and one ref near the very bottom of the page. I think WSK merits a navigation link at the top of the page, perhaps to the right of the "Tools" item (similar to how it appears below the corresponding navigation links at the bottom of the main page).

I'm happy to submit a PR if this resolution is approved.

**Comment by Garbee** [comment]
Does the recent update with `/web/tools` solve this discover-ability problem?

**Comment by petele** [comment]
yes - i believe so!
