### ISSUE TITLE
[Lighthouse / Blocking Resources / Helpful]

### ISSUE THREAD

**Issue by gvlekke** [google/WebFundamentals#5812]
**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/blocking-resources

**What needs to be done?**
I understand what is wrong but I don't know how to fix it.
How can I defer my stylesheets?

I have only a screen stylesheet and I it will be helpfull if the page explains how you can separate your css in critical and non critical css and then especially how you can defer the non-critical css.

**Comment by kaycebasques** [comment]
Thanks for the feedback. Is there a reason you closed this?

**Comment by gvlekke** [comment]
yeah was duplicate of #5581
