### ISSUE TITLE
[Lighthouse / Offscreen Images / Helpful]

### ISSUE THREAD

**Issue by bhargavpjoshi** [google/WebFundamentals#5871]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?** this is most important for any developer to provide solution including code of example would make better place to development and work we know that there is issue but still...

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by kaycebasques** [comment]
The request is to add code to the doc explaining how to handle offscreen images.

**Comment by kaycebasques** [comment]
The doc links to IntersectionObserver. I agree that it'd be better if we included code in the doc, but I'm afraid that I won't keep it up to date. Therefore, it's better to just link to the URLs that will stay up-to-date.
