### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by aecheverrir** [google/WebFundamentals#5959]
**Page Affected:** https://developers.google.com/web/fundamentals/accessibility/

**What needs to be done?**
Implement an option to choose the language for the article. If using chrome, it will automatically set the language to one based on some information chrome saves. Using incognito and/or a censorship (like ultrasurf) will not set the language to its default (english). Changing to another browser (like firefox) will work.

**Comment by petele** [comment]
There is a language picker at the bottom of the page, or you can add `?hl=XX` to the URL
