### ISSUE TITLE
[Console / Get Started / Helpful]

### ISSUE THREAD

**Issue by geoxx3** [google/WebFundamentals#6022]
My Console DevTools is not so intelligent and it does not detect vwhen I want a multi-line scenarios for Javascript. I have to use Shift_return  shortcut. What can I do it be default?

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by kaycebasques** [comment]
Hi @geoxx3,

There is no setting for changing that behavior. You can create a request for the setting at https://crbug.com
