### ISSUE TITLE
Lighthouse 3.0 and I/O launches docs needed. 

### ISSUE THREAD

**Issue by vinamratasingal** [google/WebFundamentals#6065]
## deliverables

- [ ] Updates Post
- [ ] Migration Guide
  - [ ] complete the "JSON output changes" table
- [ ] v3 Scoring Guide
  - [ ] Update report screenshot

## original notes from V

**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

**Page Affected:** https://developers.google.com/web/tools/lighthouse/

**What needs to be done?**

- Lighthouse 3.0 blog post covering things like: new scoring model, change of default LH setting to be 4G rather than 3G, introduction of new perf metrics like FCP. 
- Docs on Lantern, and explaining the move to Lantern. 
- Doc guiding devs who are consuming LH via the CLI of all the breaking changes. 
- Doc on LH API, exposing the new LHRLite object (see GitHub request here: https://github.com/GoogleChrome/lighthouse/pull/4983

This all needs to land before I/O. 

See internal comms doc for reference of all the new launches: https://docs.google.com/document/d/1TYu75BExp2D9fA3wX7AbTzk1UWoKSZk3Or5ONG45KLE/edit

**Comment by kaycebasques** [comment]
@vinamratasingal seems like item 2 ("docs on lantern") can be wrapped up into item 1?

**Comment by kaycebasques** [comment]
try out the API? not quite there yet.

output changes aren't there yet

list of output changes are in the github

changes to how you call LH have landed. flags for throttling. config flags. no more --perf, use --preset=blah

can specify all settings in config now that you used to be able to only pass via CLI

what users will experience the break? extensions and devtools people won't notice. report users won't see, other than visual update, and throttling change. CI users are going to see changes.

**Comment by vinamratasingal** [comment]
Yup, the deliverables SGTM to me. API getting started guide can be punted for when we do a public release of the API.

**Comment by vinamratasingal** [comment]
Also- we might need to make some updates to the scoring guide as well: https://developers.google.com/web/tools/lighthouse/scoring
