### ISSUE TITLE
Spelling Mistake :)

### ISSUE THREAD

**Issue by ankitchainani** [google/WebFundamentals#6152]
![chromeinspecterror](https://user-images.githubusercontent.com/8729276/40084762-d0da69c8-585d-11e8-8166-65b095c5e939.PNG)

Simple spelling mistsake I found in inspect element settings.
Check out the image attached with this thread.

Thanks,

**Comment by kaycebasques** [comment]
Hi, that's actually not a spelling mistake. The debugger is DevTools. The debuggee is the thing that you're debugging... the viewport in other words.
