### ISSUE TITLE
[Install Prompt / Needs More Info]

### ISSUE THREAD

**Issue by reykyle** [google/WebFundamentals#6195]
i want to show  ( Add to Home Screen prompt ) on my pwa website but i don´t know how to use and put the ( beforeinstallprompt ) event  . thanks for help !

**Comment by virginielgb** [comment]
Hello,
Same here, I've followed https://developers.google.com/web/fundamentals/app-install-banners/ and put exactly the same code, but it's not fired even though lighthouse gives me a 100/100 for pwa...
Any idea why that would be?
Thanks

**Comment by kaycebasques** [comment]
Thank you @reykyle! I've just put in an update to the doc that links you off to code describing how to use `beforeinstallprompt`.
