### ISSUE TITLE
Subscription doesn't work

### ISSUE THREAD

**Issue by postpersonality** [google/WebFundamentals#6229]
**Page Affected:** 
https://developers.google.com/web/updates/ (scroll down and press Subscribe button)

**What needs to be done?**
Please fix subscribtion functionality.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by petele** [comment]
We don't have a subscription, only a link to our RSS feed.

**Comment by postpersonality** [comment]
![screenshot 2019-02-24 at 10 03 39](https://user-images.githubusercontent.com/2012215/53296217-ce6c7e80-381b-11e9-8022-09ec2b57bdc8.png)
