### ISSUE TITLE
[feedback] /web/tools/chrome-devtools/console/get-started

### ISSUE THREAD

**Issue by OranguTech** [google/WebFundamentals#6240]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/console/get-started

**What needs to be done?**

On the "Get started with the console" tutorial, clicking on the "Throw Error" button does not, in fact, throw an error. (The 404 and the example info/debug/warn buttons above work as expected.)

Teste w/ Chrome on Windows, Version 67.0.3396.79 (Official Build) (64-bit), and Firefox Dev 58.0b11 (64-bit).

**Comment by kaycebasques** [comment]
I can reproduce. Thank you, @OranguTech

**Comment by suarezzz** [comment]
@kaycebasques 
Also on this page, there's no button "Log Numbers" as shown in the picture in Step 1, Part C
