### ISSUE TITLE
[feedback] /web/tools/chrome-devtools/css/

### ISSUE THREAD

**Issue by tchkreddy** [google/WebFundamentals#6242]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/css/

**What needs to be done?**
I found the best postion for Dev Tools for going through the interactive tutorial in this page is to open them on the right with 50% width. The responsive documentation is beautifully fitting this way. For first timers, mentioning this tip would help.

**Comment by kaycebasques** [comment]
Thanks for the idea. Do you mean like this?

![image](https://user-images.githubusercontent.com/4713486/41679688-e95e9f5e-7483-11e8-9217-c296a7d76225.png)
