### ISSUE TITLE
Invalid 'ignoreUrlParametersMatching' example in workbox-precaching.md

### ISSUE THREAD

**Issue by dejan9393** [google/WebFundamentals#6277]
**Page Affected:** https://developers.google.com/web/tools/workbox/modules/workbox-precaching#ignore_url_parameters

**What needs to be done?**

The 'ignoreUrlParametersMatching' parameter requires an array, the example on the above mentioned page shows a singular Regex pattern.

**Comment by jeffposnick** [comment]
This was fixed by https://github.com/google/WebFundamentals/pull/6278
