### ISSUE TITLE
[feedback] /web/tools/chrome-devtools/console/get-started

### ISSUE THREAD

**Issue by bamovhakan** [google/WebFundamentals#6290]
**Page Affected:** 

https://developers.google.com/web/tools/chrome-devtools/console/get-started#feedback

**What needs to be done?**

There is Issue in the **Part C: Filter messages** section. It is not showing the button **Log Numbers,** but instead shows a code snippet.

![fireshot capture 3 - get started with the console i tools_ - https___developers google com_web_t](https://user-images.githubusercontent.com/40494049/41778205-a0f74a4a-7636-11e8-80be-4c923547e13f.png)

**Comment by kaycebasques** [comment]
Current status here: https://github.com/google/WebFundamentals/issues/6297#issuecomment-448707924
