### ISSUE TITLE
[feedback] /web/tools/chrome-devtools/console/get-started

### ISSUE THREAD

**Issue by MariaUlianko** [google/WebFundamentals#6297]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/console/get-started

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

Page URL:
https://developers.google.com/web/tools/chrome-devtools/console/get-started

- [x] **Throw Error**button  (in section "Part B: View messages from the browser") does not work: nothing happens in Console, when you click on it

- [x]  **Log Numbers** button is missing in the section "Part C: Filter messages" (see screenshot)
![log numbers_button_is_missing_](https://user-images.githubusercontent.com/37151954/41910047-7c59aa0e-7940-11e8-8ddb-477946e9a8c9.png)

**Comment by kaycebasques** [comment]
This is fixed (kinda). The button is displaying correctly, but the functionality is broken. I have another issue tracking that.
