### ISSUE TITLE
[Lighthouse / First Meaningful Paint / Helpful]

### ISSUE THREAD

**Issue by andyturner** [google/WebFundamentals#6325]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

"aproach" is spelt wrong

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by rottina** [comment]
This page leads to a `404` status as of 8/8/18
