### ISSUE TITLE
[Lighthouse / No JS / Helpful]

### ISSUE THREAD

**Issue by esaveya** [google/WebFundamentals#6327]
In Chrome Dev tools the Lighthouse Audit for Progressive Web App is reporting that the site does not provide fallback content when Javascript is not available. We have verified that the site does indeed provide content when JS is disabled. Is this a bug perhaps?

Using Chrome Version 67.0.3396.99 (Official Build) (64-bit)

Thanks!

**Comment by kaycebasques** [comment]
If you're still experiencing this issue please report it to the Lighthouse repo.

https://github.com/GoogleChrome/lighthouse/issues/new
