### ISSUE TITLE
Feedback for: /resources/styleguide/index.html

### ISSUE THREAD

**Issue by keniobats** [google/WebFundamentals#634]
First of all, awesome work! :)

On mobile there's an option "Toggle Code Snippets", which shows how to implement the html markup of each component.

![screen shot 2014-07-29 at 23 55 38](https://cloud.githubusercontent.com/assets/855242/3744629/0d5ef2dc-1795-11e4-814a-218ac23cb16e.png)

On desktop there's no option to show snippets. I've spent some time digging through the code until I realized about this.
![screen shot 2014-07-29 at 23 58 04](https://cloud.githubusercontent.com/assets/855242/3744648/5cdc6bfa-1795-11e4-8a63-4971e3cf213d.png)

Hope it makes sense to you.

Cheers.

**Comment by gauntface** [comment]
Moving forward we've discussed making a different styleguide, if that becomes the case then I'd like to do this with that, but for now closing this since it's for the old styleguide.
