### ISSUE TITLE
Trying to understand why Lighthouse audit says my audited page is blocked from indexing

### ISSUE THREAD

**Issue by jckr** [google/WebFundamentals#6489]
Greetings, I ran lighthouse audits on my page and I'm trying to figure out why in the SEO section, it says it is blocked from indexing:

<img width="693" alt="screenshot 2018-08-13 16 44 54" src="https://user-images.githubusercontent.com/9727630/44064174-9e8dfbd6-9f18-11e8-98a5-d3fd065bd376.png">

In the "learn more" link https://developers.google.com/web/tools/lighthouse/audits/indexing, from which I opened this issue, I am offered 2 explanations - a meta tag in the header of my page or an X-Robots-Tag in my HTTTP response. 

My page has neither. Yet it's very likely that it is blocked from indexing, because despite being on a sitemap it is not indexed, so I am trying to understand what can be the cause. 
It's a page from a web app which sits on github, the content is generated from javascript.
Thanks!
In the google webmasters tool, here's the full HTTP response - Googlebot is able to fetch it and render it as it appears to a person visiting that page.

```
HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: text/html; charset=utf-8
Strict-Transport-Security: max-age=31557600
Last-Modified: Wed, 08 Aug 2018 20:23:20 GMT
Access-Control-Allow-Origin: *
Expires: Wed, 08 Aug 2018 20:33:43 GMT
Cache-Control: max-age=600
X-Fastly-Request-ID: bdb2ef4376f189c5a2602b5ef0753169ed999b93
X-GitHub-Request-Id: E1AE:1CDA:191DF56:2117EF9:5B6B514F
Content-Length: 764
Accept-Ranges: bytes
Date: Wed, 08 Aug 2018 20:23:43 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-dca17749-DCA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1533759824.581215,VS0,VE6
Vary: Accept-Encoding
 
 
 
 
 
 
 
 
 
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
 
    
 
    
      
      <meta name="description" content="A documentation website for Ocular, made with Ocular">
      
    
 
    <title>ocular-website</title>
 
    
 
    
    <meta content="width=device-width, initial-scale=1" name="viewport">
    
 
    
    
    <link rel="icon" type="img/ico" href="favicon.ico">
    
 
    
    
    <link href="styles-03f89c54eed4aadb280e.css" rel="stylesheet">


  </head>
  <body>
    

    
    <div id="root"></div>
    
    

    

    

    

    
    
    <script src="bundle-03f89c54eed4aadb280e.js" type="text/javascript"></script>
    
    

    

    
  </body>
</html>
Download Time: 0.043 seconds
```

**Comment by kaycebasques** [comment]
Hey @jckr, I thought this was a docs issue, but might be better suited as a bug report on the main Lighthouse repo: googlechrome/lighthouse
