### ISSUE TITLE
"Tony" project cannot be found

### ISSUE THREAD

**Issue by sergeykizlo** [google/WebFundamentals#6490]
There is a wrong link to "Tony" project in this tutorial: https://developers.google.com/web/tools/chrome-devtools/speed/get-started

Broken link to "Tony" project: https://glitch.com/edit/#!/tony

**Comment by sergeykizlo** [comment]
@kaycebasques can you please check that?

**Comment by kaycebasques** [comment]
I clicked this lock icon thinking that it would prevent anyone from accidentally making changes to the code, but it seems like it may have made the code private instead. Should be fixed now. Sorry for the confusion.
