### ISSUE TITLE
Invalid option "navigationFallback"

### ISSUE THREAD

**Issue by steebchen** [google/WebFundamentals#6496]
**Page Affected:** https://developers.google.com/web/tools/workbox/guides/generate-complete-sw#navigation_fallback

**Line Affected**: https://github.com/google/WebFundamentals/blob/f64420d4fdb3a7dd8796577c7683e81e69d2305e/src/content/en/tools/workbox/guides/generate-complete-sw.md#L230

**What needs to be done?**

This option does not exist and will throw an error that this options is not supported. Instead, the correct option to use is [navigateFallback](https://developers.google.com/web/tools/workbox/modules/workbox-build#generateSW-navigateFallback) as documented on the workbox modules docs.

**Comment by jeffposnick** [comment]
Thanks for catching this!
