### ISSUE TITLE
Fix "throw error" and "log numbers" buttons in /web/tools/chrome-devtools/console/get-started

### ISSUE THREAD

**Issue by ZacharyWartell** [google/WebFundamentals#6574]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/console/get-started

**What needs to be done?**

In Part C after the paragraph "Click Log Numbers. The Console prints out whether [..]",  the 
"Log Numbers" button is not displayed.  The verbatim pretty print of the code for creating that button appears.   But without the actual button, the reader can't perform the example in Part C.

Thanks!

**Comment by kaycebasques** [comment]
Somebody else put in a fix for this recently. The button is displaying correctly now, but it's not logging numbers to the Console anymore 🤦‍♂️

**Comment by kaycebasques** [comment]
The commit above might fix it... our staging server behaves a little differently than our production server, so I can't be sure.

**Comment by wasif909** [comment]
The issue of the button still seems to be there. It's not rendered.
