### ISSUE TITLE
Shurtcut for "Continue to here"

### ISSUE THREAD

**Issue by stijnsanders** [google/WebFundamentals#6596]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/shortcuts

**What needs to be done?**

_"Sources panel keyboard shortcuts" doesn't list the shortcut for the "Continue to here" option that is available from the right-mouse-click-menu on a line of source code._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by kaycebasques** [comment]
Thank you for the report @stijnsanders... adding now
