### ISSUE TITLE
Feature idea: Download rate for Chrome Dev Tools Network Monitor

### ISSUE THREAD

**Issue by jetic83** [google/WebFundamentals#6599]
In the network monitor in Chrome's Developer tools, if would be nice to have an optional column for the download rate (B/s or Mb/s).

This is not simply the file size column divided by time column, since the time column also includes waiting times. It would rater be the "file size" divided by "content download time".

**Rationale:** The download rate would be good to find bottlenecks in the network infrastructure (e.g. when parts of the web page come from different servers).

**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/network-performance/

**What needs to be done?**

In the `Network` pane in Chrome Dev Tools, add an optional column for `Download rate (B/s)`, which equals to `Size` divided by `content download time`.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by kaycebasques** [comment]
Please send this feature request to [Chromium Bugs](https://bugs.chromium.org/p/chromium/issues/list).
