### ISSUE TITLE
Typo on chrome devtools css page

### ISSUE THREAD

**Issue by Dehsen** [google/WebFundamentals#6618]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** 
https://developers.google.com/web/tools/chrome-devtools/css/

**What needs to be done?**
Typo needs amending

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._
under the "Change the dimensions of an element" section, you will find the following text:
"In the Box Model diagram in the Styles tab, hover over padding. The element's margin is highlighted in the viewport." Shouldn't it be the element's _padding_  is higltighted in the viewport

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by sunilkumarvalmiki** [comment]
@Dehsen checked your issue, yes it's a mistake,

it should be like this " The element's padding is highlighted in the viewport." 

but it shown like this "The element's margin is highlighted in the viewport."
