### ISSUE TITLE
Console.info special formatting was removed

### ISSUE THREAD

**Issue by swrobel** [google/WebFundamentals#6624]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/console/console-reference#consoleinfoobject_object

**What needs to be done?**
Align with current behavior (console.debug also seems to have been removed, for example)
ref: https://bugs.chromium.org/p/chromium/issues/detail?id=712103

**Comment by kaycebasques** [comment]
Thank you for the report, @swrobel.
