### ISSUE TITLE
Feedback from HackerNews: What I look for in monetization/analytics

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#665]
https://news.ycombinator.com/item?id=8175032

I look for two basic things:
1. Where did people come from and how did I convert them?
2. What is my conversion/impression/sales, etc. for the month/quarter and how does that compare to previous month/quarter or a specific date?
So, what I mean is if I have an event coming up and I am marketing to that event - I have email lists, twitter accounts, FaceBoook, a popular blog, co-op email partners, and I buy ads on multiple platforms...I want to know how many people came from each source, what the conversion rate was, how far they got in the process, and I want to see how this year's event is comparing to last years'. Or last months'. Or last weeks'. Or an event I had three quarters ago.
I need the data to be as accurate as I can get, because if people are coming into the site, and all of the ones coming from, say, Twitter, are not buying and don't even read anything, then I need to know that.
As an example, for a sports event I run in the summer, two years ago I dropped PayPal as an option entirely. I had so many complaints from consumers about PayPal in general I just decided to implement Stripe. A lot of people told me that since PayPal is so ubiquitous, I would be cutting out an ease-of-payment option and I would lose sales.
But my data showed two things: a lot of people DID use PayPal but I lost a ton of conversions when people hit the PayPal page AND my #1 complaint topic was PayPal related. About 60% of the people who signed up used PayPal.
Both of the last two years after implementing Stripe my conversion rate increased dramatically and I have ZERO complaints about the payment process. Literally, zero.
So that's what I'm always looking for. How do I optimize and track turning people who are searching into customers without wasting their time or my time? How do I remove frustration for users? Where do they navigate to? If they hit a specific page and then suddenly jump around looking for a 'contact us' page, I need to figure out what those people are looking for and fix it for them.
With Google analytics or adwords, I get some data but a lot of it other than a few pieces is superficial or the data doesn't match my server logs.
Sorry for the digression

**Comment by petele** [comment]
We've essentially remove that section.
