### ISSUE TITLE
Cursor not changing with the Dev Tools Opened

### ISSUE THREAD

**Issue by stanislav-lohtin** [google/WebFundamentals#6655]
When the Dev Tools are closed the behaviour is correct.
If the Dev Tools are opened, then the mouse cursor is not changing even though the css class was added with the new cursor. As you can see in the following example, when the box is clicked and mouse button is held down, then even though the class was added, no change occurs and the cursor stays the same until the mouse button is released.

```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test1</title>
    <style>
        div {
            width: 20%;
            height: 100px;
            margin: 20px;
            background-color: #2F96D1;
            cursor: grab;
            float: left;
        }

        .grabbing {
            cursor: grabbing;
        }
    </style>
</head>
<body>
    <h1> Test of mouse cursor</h1>
    <div id="box1"></div>
</body>
<script>
    var elem = document.getElementById("box1");
    elem.addEventListener("mousedown", function () {
        console.log("mousedown");
        elem.classList.add("grabbing");
    });
</script>
</html>
```

**Comment by kaycebasques** [comment]
Please send this bug to [Chromium Bugs](https://bugs.chromium.org/p/chromium/issues/list).
