### ISSUE TITLE
This site is unsafe The site http://162.144.57.67:2087/ 

### ISSUE THREAD

**Issue by jay511** [google/WebFundamentals#6667]
Hi Google person,

Reach me at(407) 416-4446 or 877-322-7139 or jay@a iatiincontinuinged.com

Please help us remove the unsafe website designation Google has given us.  We are a professional online training company with Federal Aviation Administration approval as well as client around the globe.  

We had trouble with our emails being blacklisted from the start and managed to get all but one company to take us off their blacklist.  Now after rebuilding our server over the Labor Day holiday we find though our Bluehost provider that Google has once again placed us on thus UNSAFE WEBSiTE list.  

This issue all started three years ago when we first got the IP ADDRESS from Bluehost .  I believe the IP address provided by BLuehost in the first place is the issue.  The previous owner was doing those things.  We have never allowed this type activity and have employed Sitelock to make certain that it never occurs.  

Maybe Bluehost should give us a new IP ADDRESS.  This time, verify that it’s a good one.  

Jay Shanley

On Sep 25, 2018, at 4:35 PM, "cases@support.bluehost.com" <cases@support.bluehost.com> wrote:

Hello, 

Thank you for your patience as we review your case. At this time the page you see when navigating to 162.144.57.67  is a screen that google places to warn users that this server at one point has had malware, or Phishing tied to it. We provide the server with root access, and a dedicated IP, with that being said, outside of making sure the server is on and has access to the internet , the maintenance including software installation, updates, and reputation of, relies heavily on your development team. You can find more information in our Terms Of Service https://www.bluehost.com/terms/user-agreement specifically paragraph 20 Section C and paragraph 16 section B. The following link is a report generated by google, which you can dispute with them directly.

https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2F162.144.57.67:2087%2F&hl=en-US

Thank you 

Tier 2 Support

Hi,  

**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by jay511** [comment]
Please help!!!   We are losing business and employ Sitelock to thwart these attacks. 

Jay

**Comment by petele** [comment]
Please see the information at https://developers.google.com/web/fundamentals/security/hacked/ 

This bug tracker is for reporting issues with our documentation, and is not monitored by the team who handles safe site stuff.

**Comment by jay511** [comment]
What.....   and you couldn’t forward it to them ????



Jay Shanley
