### ISSUE TITLE
Add mention of crossorigin="use-credentials" to manifest's <link> tag

### ISSUE THREAD

**Issue by nigelmcnie** [google/WebFundamentals#6672]
**Page Affected:** https://developers.google.com/web/fundamentals/web-app-manifest/

**What needs to be done?**

Short version: I'd find it very helpful if the "tell the browser about your manifest" section mentioned that if your manifest requires credentials (basic auth, cookie or whatever), that it MUST have a `crossorigin="use-credentials"` attribute, *even if it's on the same origin*.

Long version: I've just come from filing a bug against Lighthouse, then Chrome, about why chrome wouldn't download a manifest behind HTTP basic authentication. The behaviour was initially very confusing to me as `<link>` tags to resources on the same origin haven't historically had this behaviour (e.g. `<link rel="stylesheet">`). I got a good reason for this from the chrome team:

> My understanding for the crossOrigin attribute requirement is that it's necessary due to using FETCH to get the manifest - everything using FETCH needs to respect CORS.
> 
> By default, elements retrieved via <link> elements implicitly send credentials because they were spec'd before FETCH was available. Manifest was added later, and retrofitting it into the <link> element came with the compromise requirement of needing the crossOrigin attribute for credentials/cross-origin requests.

This answer resolves my mystery. I wondered if you would consider adding mention of this to your page about the manifest, as it's one of the pages I used to learn about how to implement a manifest properly, and I'm sure many others have used it too.

More information:

https://bugs.chromium.org/p/chromium/issues/detail?id=863218#c13 (beginning of the relevant discussion from the chrome bug report)
https://github.com/GoogleChrome/lighthouse/issues/5658 the original lighthouse bug

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by dominickng** [comment]
Ping @petele

**Comment by HolgerJeromin** [comment]
FYI: I added the information in [MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest#Deploying_a_manifest_with_the_link_tag).
