### ISSUE TITLE
DevTools For Beginners HTML and the DOM - tutorial broken and/or incomplete

### ISSUE THREAD

**Issue by sdemar** [google/WebFundamentals#6692]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools
![devtoolsforbeginners_bug](https://user-images.githubusercontent.com/13689219/46452355-3e387a80-c750-11e8-871a-f75895f87d80.PNG)
) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/beginners/html

**What needs to be done?**

The tutorial page ends with the topic "Copy your changes" with two problems.
1) the sample content provided is not code, it is rendered HTML content for the page.
2) there are no following tutorial steps or 'next page' to continue the tutorial.  

I'm guessing either the intern document writer who created this tutorial either...
- her Google internship ended before completing the site contents
- she made some error in the site upload of her contents
- or no one proofed the site to notice the missing content prior to moving to production

There are clearly many more steps to complete the tutorial, and its simply not showing up on the site.  If I'm looking at the wrong site, can you please let me know where I can find the rest of this tutorial?  Thanks,

**Comment by kaycebasques** [comment]
Sorry, I thought that was fixed. I'll work on it.

**Comment by kaycebasques** [comment]
It's fixed on our staging site but not production :rofl: 

I knew I had looked at this...

![image](https://user-images.githubusercontent.com/4713486/50123134-65153180-0214-11e9-9f71-e12e4a9adfba.png)
