### ISSUE TITLE
Deprecate /web/tools/chrome-devtools/device-mode/device-input-and-sensors

### ISSUE THREAD

**Issue by Chaseabbott** [google/WebFundamentals#6714]
**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

The Emulate Geolocation Coordinates check box is not longer available within the Sensors tab when enabled. 
![screen shot 2018-10-10 at 08 48 11](https://user-images.githubusercontent.com/11094983/46748808-41a89600-cc69-11e8-885e-8eb9c793db75.png)

Chrome Version 69.0.3497.100 (Official Build) (64-bit)

I've scoured the internet for any additional data on if I've done something wrong and I run into old results that no longer apply to my chrome version.

I checked chromium.org for any changes to this feature and could find nothing directly related. 

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by Chaseabbott** [comment]
If I'm being an idiot and just missing something very obvious, I'm cool with that. I've just done the diligence that I can do and haven't found the solution.

**Comment by kaycebasques** [comment]
The doc looks outdated. Sorry for the confusion.

https://developers.google.com/web/tools/chrome-devtools/device-mode/device-input-and-sensors#override_geolocation_data

**Comment by kaycebasques** [comment]
I've got an up-to-date doc on all of our mobile device simulation features here: https://developers.google.com/web/tools/chrome-devtools/device-mode/#geolocation
