### ISSUE TITLE
Don't say that target=_blank is a security vulnerability

### ISSUE THREAD

**Issue by sirdarckcat** [google/WebFundamentals#6720]
**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/noopener

**What needs to be done?**

It says `On top of this, target="_blank" is also a security vulnerability.` this is not true.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by mathiasbynens** [comment]
Instead of removing it, can you recommend a better way of warning about [the problem that `rel=noopener` solves](https://mathiasbynens.github.io/rel-noopener/)? I believe that was the intention of this paragraph (although I am not its author).

**Comment by ericlaw1979** [comment]
It'd probably be more accurate to say `On top of this, target="_blank" is exposes attack surface.`

The sentence in the prior paragraph is also incorrect in the new world of site isolation ("When your page links to another page using target="_blank", the new page runs on the same process as your page.")

**Comment by EdOverflow** [comment]
I would suggest rewording the statement in question to something along these lines:

> On top of that, `target=_blank` can introduce reverse tabnabbing issues whereby the target page can access your `window` object via the `window.opener` property, potentially allowing them to redirect the previous page to a malicious URL as described in https://mathiasbynens.github.io/rel-noopener/ and https://danielstjules.github.io/blankshield/.

**Comment by kaycebasques** [comment]
Thanks for the detailed suggestions on how to change the doc. I'm on it.

**Comment by kaycebasques** [comment]
Someone pointed out that https://danielstjules.github.io/blankshield/ and we may not want to link there. I haven't looked into yet, just noting for my future reference.
