### ISSUE TITLE
Do not advertise TMP as "spec" 

### ISSUE THREAD

**Issue by digitarald** [google/WebFundamentals#6740]
**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint

**What needs to be done?**

TMP is called a _Spec_ (with a link to a 2y old doc), which is can cause confusion.

[TTI](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive) links to its _Definition_, which is a better wording. It might also be interesting to recommend/link _First Contentful Paint_ for tracking it in the wild (similar to FID in TTI).

**Comment by kaycebasques** [comment]
Looks like the "spec" wording has been fixed but have not yet linked to docs on how to track it in the wild.
