### ISSUE TITLE
My web is secure https:// but there is one image that isn't. How do I change this?

### ISSUE THREAD

**Issue by zaesarius** [google/WebFundamentals#6787]
Hi!

Your documentation is fine but there are some specific issues that doens't bring to clear way to solved by you.

I have a https:// website. But there is one url from one image that is http://... not secure. How can I change this? Why should this affect my PWA?

Thank you

**Comment by kaycebasques** [comment]
This is called [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content). The solution is to host the image on an HTTPS server.
