### ISSUE TITLE
User Agent setting not in drop down in latest chrome

### ISSUE THREAD

**Issue by anagio** [google/WebFundamentals#6803]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports#user_agent_type

**What needs to be done?**

The screenshot in the "Optional controls (e.g. touch, media queries, DPR)" section showing User agent type as a menu item might be out dated. The latest version of Chrome which i'm on Version 70.0.3538.77 (Official Build) (64-bit) only has user agent options in network conditions drawers. Or if I add a custom device type i'm able to choose the user agent / touch no touch options.

The options I see in the drop down
![image](https://user-images.githubusercontent.com/1071553/47919375-96fd4f00-de85-11e8-8055-95a196425663.png)

**Comment by kaycebasques** [comment]
That does seem to be outdated. Thanks for the report.
