### ISSUE TITLE
[Remote Debugging] - add troubleshooting note about PTP mode

### ISSUE THREAD

**Issue by jcward** [google/WebFundamentals#6821]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**What needs to be done?**

Please add a new suggestion (set USB mode to PTP) to the "troubleshooting your remote connection" section. I suggest changing this bullet:

* If you don't see the Allow USB Debugging prompt on your Android device, try disconnecting and then re-connecting the USB cable while DevTools is in focus on your development machine and your Android homescreen is showing. In other words, sometimes the prompt doesn't show up when your Android or development machine screens are locked. Consider updating the display settings for your Android device and development machine so that they never go to sleep.

To this:

* If you don't see the Allow USB Debugging prompt on your Android device:
  1) Try disconnecting and then re-connecting the USB cable while DevTools is in focus on your development machine and your Android homescreen is showing. In other words, sometimes the prompt doesn't show up when your Android or development machine screens are locked.
  2) Try setting your Android's USB mode to PTP.
  3) Consider updating the display settings for your Android device and development machine so that they never go to sleep.

FYI, my experience:

My phone never showed up in Remote Devices. I revoked my USB permissions as noted on the page, but I oddly never got the "Allow USB debugging" prompt. After finding this [SE answer](https://android.stackexchange.com/a/137006/58322), I discovered that changing my phone's USB mode from "charging" to "PTP" solved the issue, gave me the USB debugging permission dialog, and ultimately made my device appear in the menu.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by kaycebasques** [comment]
Thanks for the specific feedback. I'll look into it.

**Comment by kaycebasques** [comment]
Just put in a fix. Thank you for the excellent instructions.
