### ISSUE TITLE
Documentation fonts are blocked in Chrome (x-client-data)

### ISSUE THREAD

**Issue by phistuck** [google/WebFundamentals#6881]
**Page Affected:** https://developers.google.com/web/updates/2017/10/using-twa

**What needs to be done?**
The fonts are blocked, so the page looks like this -
![image](https://user-images.githubusercontent.com/184400/48981963-e16c9700-f0e4-11e8-86dc-8d58a0d4df9d.png)

I guess Chrome 72 sends an `x-client-data` HTTP header to Google related entities, which results in many CORS related errors (fixable by allowing that header, I guess) -

Access to font at 'https://fonts.gstatic.com/s/googlesans/v9/4UaGrENHsxJlGDuGo1OIlL3Owp4.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
4UaGrENHsxJlGDuGo1OIlL3Owp4.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOmCnqEu92Fr1Mu4mxK.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc4.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOlCnqEu92Fr1MmEU9fBBc4.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/materialicons/v41/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc4.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOlCnqEu92Fr1MmWUlfBBc4.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOkCnqEu92Fr1Mu51xIIzI.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOkCnqEu92Fr1Mu51xIIzI.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/robotomono/v5/L0xkDF4xlVMF-BfR8bXMIjC4iGqxf78.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
L0xkDF4xlVMF-BfR8bXMIjC4iGqxf78.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/robotomono/v5/L0x5DF4xlVMF-BfR8bXMIjhLq38.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
L0x5DF4xlVMF-BfR8bXMIjhLq38.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/robotomono/v5/L0xkDF4xlVMF-BfR8bXMIjDwjmqxf78.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
L0xkDF4xlVMF-BfR8bXMIjDwjmqxf78.woff2:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fABc4EsA.woff2' from origin 'https://developers.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOlCnqEu92Fr1MmEU9fABc4EsA.woff2:1 Failed to load resource: net::ERR_FAILED
TCgT8dzSiU8?autohide=1&showinfo=0&enablejsapi=1:1 Access to XMLHttpRequest at 'https://googleads.g.doubleclick.net/pagead/id' from origin 'https://www.youtube.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
googleads.g.doubleclick.net/pagead/id:1 Failed to load resource: net::ERR_FAILED
using-twa:1 Access to XMLHttpRequest at 'https://ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=331' from origin 'https://developers.google.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
ogs.google.com/u/0/_/og/botguard/get?rt=j&sourceid=331:1 Failed to load resource: net::ERR_FAILED
content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
(anonymous) @ content.min.js:2
TCgT8dzSiU8?autohide=1&showinfo=0&enablejsapi=1:1 Access to XMLHttpRequest at 'https://googleads.g.doubleclick.net/pagead/id' from origin 'https://www.youtube.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
googleads.g.doubleclick.net/pagead/id:1 Failed to load resource: net::ERR_FAILED
apis.google.com/u/0/_/widget/render/comments?usegapi=1&href=https%3A%2F%2Fdevelopers.google.com%2Fweb%2Fupdates%2F2017%2F10%2Fusing-twa&width=805&first_party_property=BLOGGER&view_type=FILTERED_POSTMOD&hl=en&origin=https%3A%2F%2Fdevelopers.google.com&search=&hash=&gsrc=3p&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.CUp85wbT4DI.O%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-XBQda2DFvo9hxbj_dGnCV84SJMA%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Cscroll%2Copenwindow&id=I0_1543165255252&_gfid=I0_1543165255252&parent=https%3A%2F%2Fdevelopers.google.com&pfname=&rpctoken=28904081:1 Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details
content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
(anonymous) @ content.min.js:2
content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
(anonymous) @ content.min.js:2
TCgT8dzSiU8?autohide=1&showinfo=0&enablejsapi=1:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2' from origin 'https://www.youtube.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOmCnqEu92Fr1Mu4mxK.woff2:1 Failed to load resource: net::ERR_FAILED
apis.google.com/u/0/_/widget/render/comments?usegapi=1&href=https%3A%2F%2Fdevelopers.google.com%2Fweb%2Fupdates%2F2017%2F10%2Fusing-twa&width=805&first_party_property=BLOGGER&view_type=FILTERED_POSTMOD&hl=en&origin=https%3A%2F%2Fdevelopers.google.com&search=&hash=&gsrc=3p&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.CUp85wbT4DI.O%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-XBQda2DFvo9hxbj_dGnCV84SJMA%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Cscroll%2Copenwindow&id=I0_1543165255252&_gfid=I0_1543165255252&parent=https%3A%2F%2Fdevelopers.google.com&pfname=&rpctoken=28904081:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2' from origin 'https://apis.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOmCnqEu92Fr1Mu4mxK.woff2:1 Failed to load resource: net::ERR_FAILED
apis.google.com/u/0/_/widget/render/comments?usegapi=1&href=https%3A%2F%2Fdevelopers.google.com%2Fweb%2Fupdates%2F2017%2F10%2Fusing-twa&width=805&first_party_property=BLOGGER&view_type=FILTERED_POSTMOD&hl=en&origin=https%3A%2F%2Fdevelopers.google.com&search=&hash=&gsrc=3p&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.CUp85wbT4DI.O%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-XBQda2DFvo9hxbj_dGnCV84SJMA%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Cscroll%2Copenwindow&id=I0_1543165255252&_gfid=I0_1543165255252&parent=https%3A%2F%2Fdevelopers.google.com&pfname=&rpctoken=28904081:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc4.woff2' from origin 'https://apis.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOlCnqEu92Fr1MmWUlfBBc4.woff2:1 Failed to load resource: net::ERR_FAILED
apis.google.com/u/0/_/widget/render/comments?usegapi=1&href=https%3A%2F%2Fdevelopers.google.com%2Fweb%2Fupdates%2F2017%2F10%2Fusing-twa&width=805&first_party_property=BLOGGER&view_type=FILTERED_POSTMOD&hl=en&origin=https%3A%2F%2Fdevelopers.google.com&search=&hash=&gsrc=3p&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.CUp85wbT4DI.O%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-XBQda2DFvo9hxbj_dGnCV84SJMA%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh%2Cscroll%2Copenwindow&id=I0_1543165255252&_gfid=I0_1543165255252&parent=https%3A%2F%2Fdevelopers.google.com&pfname=&rpctoken=28904081:1 Access to font at 'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfChc4EsA.woff2' from origin 'https://apis.google.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
KFOlCnqEu92Fr1MmWUlfChc4EsA.woff2:1 Failed to load resource: net::ERR_FAILED
TCgT8dzSiU8?autohide=1&showinfo=0&enablejsapi=1:1 Access to XMLHttpRequest at 'https://googleads.g.doubleclick.net/pagead/id' from origin 'https://www.youtube.com' has been blocked by CORS policy: Request header field x-client-data is not allowed by Access-Control-Allow-Headers in preflight response.
googleads.g.doubleclick.net/pagead/id:1 Failed to load resource: net::ERR_FAILED

**Comment by Huppys** [comment]
I'm facing the exact same errors. Are you sitting behind any kind of proxy?

**Comment by phistuck** [comment]
@Huppys - no, but this seems fixed for me at the moment (Chrome canary 73.0.3630.0).
I guess Chrome improved its algorithm for sending those `x-client-data` headers to not send them in CORS-sensitive requests.

**Comment by khambadkone** [comment]
I'm seeing this same problem all of a sudden with Version 76.0.3809.100 (Official Build) (64-bit).

The pages render fine when in Incognite mode.

**Comment by phistuck** [comment]
@khambadkone - can you paste the errors from the console of the Developer Tools?

**Comment by khambadkone** [comment]
For example, on accessing https://firebase.google.com/support/troubleshooter/report/bugs/

we see the following : 
Access to fetch at 'https://fonts.gstatic.com/s/materialicons/v48/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
5The FetchEvent for "<URL>" resulted in a network error response: the promise was rejected.
sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
Access to fetch at 'https://fonts.gstatic.com/s/googlesans/v14/4UabrENHsxJlGDuGo1OIlLU94YtzCwZsPF4o.woff2' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2:1 Failed to load resource: net::ERR_FAILED
4UabrENHsxJlGDuGo1OIlLU94YtzCwZsPF4o.woff2:1 Failed to load resource: net::ERR_FAILED
Access to fetch at 'https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2:1 Failed to load resource: net::ERR_FAILED
Access to fetch at 'https://fonts.gstatic.com/s/googlesans/v14/4UaGrENHsxJlGDuGo1OIlL3Owp5eKQtG.woff2' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
4UaGrENHsxJlGDuGo1OIlL3Owp5eKQtG.woff2:1 Failed to load resource: net::ERR_FAILED
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/devsite_heading_module.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/webcomponents-lite.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/firebase/css/app.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_feedback.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/firebase/images/lockup.png' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/app_loader.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/devsite_snackbar_module.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_heading.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_spinner.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_snackbar.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_support_form.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_content_footer.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_tooltip.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/css/devsite_dialog.css' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/firebase/js/devsite_app.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/devsite_dialog_module.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/devsite_tooltip_module.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/devsite_support_form_module.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/devsite_feedback_module.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/js/devsite_spinner_module.js' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://www.gstatic.com/devrel-devsite/vaf8baf42c0837f5f008e8c7cd622dab17fda7175a36251cef2ba8d3369798ea7/images/lockup-color.png' (redirected from 'https://firebase.google.com/_static/images/lockup-color.png') from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
Access to fetch at 'https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2' from origin 'https://firebase.google.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.
sw.js:1 Uncaught (in promise) TypeError: Failed to fetch
fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2:1 GET https://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlfBBc4AMP6lQ.woff2 net::ERR_FAILED

**Comment by phistuck** [comment]
I cannot reproduce (I tried F5, Control+F5, disabling cache in the Developer Tools...), but anyway, the Firebase documentation is off topic for the Web Fundamentals repository...

**Comment by phistuck** [comment]
@erickertz - do you get the exact error that @khambadkone mentioned (pragma, not x-client-data)?

Does it reproduce in incognito mode as well?
(If not, an extension that you use might be adding this header)

**Comment by khambadkone** [comment]
Akamai's chrome plugin for testing their CDN was causing my issue. On
disabling it, the site loaded fine
