### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rValin** [google/WebFundamentals#6914]
**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/user-timing

**What needs to be done?**

- Section Recommendations
The link to the User Timing Api is broken and return a 404..

**Comment by kaycebasques** [comment]
That link works fine on my laptop and personal phone. Maybe something is up with your network?

<img width="1552" alt="screen shot 2018-11-30 at 10 55 12 am" src="https://user-images.githubusercontent.com/4713486/49308914-804f1580-f48e-11e8-9831-a1b037579642.png">
