### ISSUE TITLE
add icon for "show console sidebar" in /web/tools/chrome-devtools/console/get-started

### ISSUE THREAD

**Issue by kaycebasques** [google/WebFundamentals#6938]
<img width="788" alt="screen shot 2018-12-04 at 10 17 06 am" src="https://user-images.githubusercontent.com/4713486/49463654-d7fec100-f7ad-11e8-9c8a-7e67e51dc0ab.png">

**Comment by italukder** [comment]
Ttank u for all thank icon

**Comment by italukder** [comment]
Thank u for all families and welcome to icon family
