### ISSUE TITLE
Information that sounds good but is useless.

### ISSUE THREAD

**Issue by TC2u** [google/WebFundamentals#6951]
One of the main reasons I don't use your site, is it's not clear enough for people that have little to no experience in website SEO. I've been trying to figure out how to setup the cache, and what you put out is useless to me, since I don't know how to implement it. It's the same with most sites, so it's not just you. 90% out there is jibberish, and serves little to no purpose. How do I know, because I constantly see people searching for the same things I am, and their frustrations with finding it.

I also downloaded you SEO pack, and same thing. Tells you what you need to do, but not how to do it. That's worthless. I couldn't even figure out what the excel sheet was for...

**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by ebidel** [comment]
http://developers.google.com/web/ is guides, tools, and developer documentation on building web apps. I encourage you to check out https://developers.google.com/search/ if you're interested in learning more about SEO. It covers that topic indepth with guides and practical advise.
