### ISSUE TITLE
Duplicate descriptions in meta tags

### ISSUE THREAD

**Issue by PaulKinlan** [google/WebFundamentals#699]
This ultimately affects our SEO and discovery (not sure how much but web master tools reports it)

|Pages with duplicate meta descriptions|Pages|
|-------------------------------------------------|--------|
Learn about the simplest ways to add video to your site and ensure users get the best possible exper	https://developers.google.com/web/fundamentals/media/video/ | https://developers.google.com/web/fundamentals/media/video/add-a-video
Responsive web design patterns are quickly evolving, but there are a handful of established patterns	https://developers.google.com/web/fundamentals/layouts/rwd-patterns/ | https://developers.google.com/web/fundamentals/layouts/rwd-patterns/column-drop | https://developers.google.com/web/fundamentals/layouts/rwd-patterns/layout-shifter | https://developers.google.com/web/fundamentals/layouts/rwd-patterns/mostly-fluid | https://developers.google.com/web/fundamentals/layouts/rwd-patterns/off-canvas | https://developers.google.com/web/fundamentals/layouts/rwd-patterns/tiny-tweaks
Serving advertisements provides a way for web developers to make their content and site free while s	https://developers.google.com/web/fundamentals/monetization/ads/ | https://developers.google.com/web/fundamentals/monetization/ads/index
Learn how to integrate navigation patterns into your site and get users to complete the actions you 	https://developers.google.com/web/fundamentals/layouts/navigation-patterns/ | https://developers.google.com/web/fundamentals/layouts/navigation-patterns/index
TBD.	https://developers.google.com/web/fundamentals/tools/build/deploy | https://developers.google.com/web/fundamentals/tools/test/simulator
Desc	https://developers.google.com/web/fundamentals/layouts/principles/cta-front-and-center.html | https://developers.google.com/web/fundamentals/layouts/principles/cta-front-and-center
Most browsers and devices have access to the user's geo-location. Learn how to work with the user's 	https://developers.google.com/web/fundamentals/device-access/user-location/ | https://developers.google.com/web/fundamentals/device-access/user-location/index
A picture is worth 1000 words, and images play an integral part of every page. But they also often a	https://developers.google.com/web/fundamentals/media/images/ | https://developers.google.com/web/fundamentals/media/images/index
Touchscreens are available on more and more devices,  from phones up to desktop screens. Your app sh	https://developers.google.com/web/fundamentals/input/touch/ | https://developers.google.com/web/fundamentals/input/touch/index
Much of the web isn't optimized for those multi-device experiences. Learn the fundamentals to get yo	https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/ | https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/?utm_source%3Dwmc-blog%26utm_medium%3Dreferral%26utm_campaign%3DFR-post | https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints | https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/set-the-viewport | https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/size-content-to-the-viewport | https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/use-media-queries | https://developers.google.com/web/fundamentals/multi-device-layouts/rwd-fundamentals/?utm_source%3Dwmc-blog%26utm_medium%3Dreferral%26utm_campaign%3DFR-post
Forms are hard to fill out on mobile. The best forms are the ones with the fewest inputs.	https://developers.google.com/web/fundamentals/input/form/ | https://developers.google.com/web/fundamentals/input/form/index | https://developers.google.com/web/fundamentals/input/form/label-and-name-inputs
Build your multi-device site from the ground up. Learn what a build process is, how to build a site 	https://developers.google.com/web/fundamentals/tools/build/ | https://developers.google.com/web/fundamentals/tools/build/index
On devices with phone capabilities, make it easy for users to directly connect with you by simply ta	https://developers.google.com/web/fundamentals/device-access/click-to-call/ | https://developers.google.com/web/fundamentals/device-access/click-to-call/click-to-call | https://developers.google.com/web/fundamentals/device-access/click-to-call/index
Set up your environment to include a good editor, debugging tools, and build tools for the multi-dev	https://developers.google.com/web/fundamentals/tools/setup/ | https://developers.google.com/web/fundamentals/tools/setup/index
By default CSS is treated as a render blocking resource, which means that the browser will hold rend	https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css | https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css?hl=iw-IL
The amount of data downloaded by each app continues to increase. To deliver great performance we nee	https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/ | https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/index
This is an example of a showcase page	https://developers.google.com/web/fundamentals/spotlights/example-showcase/ | https://developers.google.com/web/fundamentals/spotlights/listing/

**Comment by gauntface** [comment]
We should reopen this if it's an issue after material branch launch
