### ISSUE TITLE
Rendering on the web

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#7197]
This is a placeholder issue for a new article on rendering on the web (server-rendering, CSR etc) that @developit and I are working on. 

We're aiming to get this published on https://developers.google.com/web/fundamentals/ under either performance (similar to PRPL) or as a primer (similar to https://developers.google.com/web/fundamentals/primers/modules). I'm also very open to it living elsewhere in the IA. We'll likely rework this content for web.dev at some point further down the year.

**Comment by PaulKinlan** [comment]
Can we not just aim for web.dev first?

**Comment by ahtee** [comment]
I see that https://developers.google.com/web/fundamentals/performance/rendering/ exists, does this issue still need to be open?
