### ISSUE TITLE
I want see the English documentation but I can't find the button to change language!

### ISSUE THREAD

**Issue by baixiaoji** [google/WebFundamentals#7327]
**What needs to be done?**

Thank you for page showing Chinese for me, but the page don't have a button to change language the writer wrote by. I want to see documentation between Chinese and English，just like when I read in MDN(it so nice to provide a language button),  it can help me understand the document deeply in my mother-language, improve read English document speed and build my confidence and patience.  I search the stackoverflow and can't find the similar problem. And some article didn't translate, so it still english, so if it having, could you tell me where is, if it's not having, could you provide in future, Thx.
[souce-page-link](https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints?refresh=1)

**Comment by jpmedley** [comment]
There is a button at the bottom of the page on the left side.

![image](https://user-images.githubusercontent.com/8204171/53587036-3a155b00-3b3e-11e9-8c95-e598d80e4cdb.png)

**Comment by baixiaoji** [comment]
> There is a button at the bottom of the page on the left side.
Thx, and I never scroll to  such bottom😭
