### ISSUE TITLE
Remove generated resources from repository

### ISSUE THREAD

**Issue by agektmr** [google/WebFundamentals#739]
Following auto-generated resources conflicts with updates.
They are really annoying when merging updates.
- src/site/_sass/_components/_icons.scss
- src/site/css/styles.css
- src/site/css/styles.min.css
- src/site/icons/icons.eot
- src/site/icons/icons.svg
- src/site/icons/icons.ttf
- src/site/icons/icons.woff

Is it ok to remove them from repository?

**Comment by gauntface** [comment]
Not relevant to material-branch
