### ISSUE TITLE
Minor typo in example code for .MatchAll

### ISSUE THREAD

**Issue by randsu** [google/WebFundamentals#7412]
**Page Affected:** https://developers.google.com/web/TODO
https://developers.google.com/web/updates/2019/02/string-matchall

**What needs to be done?**
The output from the foreach is wrong, 
because the third capture group in the regular expression captures 1, not 2 for the first match test1.

This was a bit confusing when I read the article.

The first iteration output in article:
`['test1', 'e', 'st1', '2', index: 0, input: 'test1test2', groups: undefined]`

but it should be
`['test1', 'e', 'st1', '1', index: 0, input: 'test1test2', groups: undefined]`

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._
Update output to reflect correct value.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by jpmedley** [comment]
The fix in #7412 has been deployed. https://developers.google.com/web/updates/2019/02/string-matchall
