### ISSUE TITLE
Clarification for prefers-reduced-motion

### ISSUE THREAD

**Issue by StephanBijzitter** [google/WebFundamentals#7428]
**Page Affected:** https://developers.google.com/web/updates/2019/03/prefers-reduced-motion

**What needs to be done?**
A bit more information could be added.

The article says that

>Note: prefers-reduced-motion is available as of Chrome 74.

But I just looked though all options in Chrome 75 and could not find any place where I can set my preference. 

I am now under the assumption that this is supposed to be a system-wide settings (if I select "Reduce motion" in my Mac's preferences, it will also be applied to content displayed by Chrome), but if that is the case then it'd be nice to have that clarified in the article.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by jpmedley** [comment]
Sorry if this wasn't clear. You are correct you are not looking for a Chrome setting. You are looking for an operating system setting. Then web site authors may or may not take it into account.

**Comment by StephanBijzitter** [comment]
Yeah I just toggled the setting on my Mac and it seems Chrome 75 doesn't even need to be re-started for the change to take effect. That's pretty cool, but it's not very clear :-)

**Comment by jpmedley** [comment]
The update pushed in #7436 has deployed.
