### ISSUE TITLE
Broken URL path due to redundancies

### ISSUE THREAD

**Issue by rgordon95** [google/WebFundamentals#7470]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

**Page Affected:** 
https://developers.google.com/web/fundamentals/payments/

**What needs to be done?**

Fix "Payment method basics" link in following:

"Payment Method Identifiers: The Payment Method Identifiers defines how strings (basic-card, https://google.com/pay, etc.) can be used to identify a payment method. Along with standardized payment method identifiers, it allows anyone to define their own payment method with URL-based payment method identifiers. Learn more at [Payment method basics](url)."

Incorrectly has URL with redundant path sections https://developers.google.com/web/fundamentals/payments/basics/payments/basics/payment-method-basics instead of
https://developers.google.com/web/fundamentals/payments/basics/payment-method-basics

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by ahtee** [comment]
I guess just to clarify, the page https://developers.google.com/web/fundamentals/payments/basics/how-payment-ecosystem-works has a broken link to  `Payment method basics`.
Fix it to https://developers.google.com/web/fundamentals/payments/basics/payment-method-basics
