### ISSUE TITLE
monitor function almost useless..

### ISSUE THREAD

**Issue by Zibri** [google/WebFundamentals#7480]
The console monitor function is almost useless as it is.

If a function is called with objects as arguments, the monitor function returns:

function value called with arguments: [object Object]

Which is totally useless.
It should show the objects like in the normal console view/console.log

**Comment by kaycebasques** [comment]
Thanks for the report. I filed a bug here: https://crbug.com/955799

In the future you can file issues directly to that tracker. This repo is just for DevTools documentation.
