### ISSUE TITLE
Proposed Timing Calculation Does Not Match Chrome's Network Summary

### ISSUE THREAD

**Issue by pxwee5** [google/WebFundamentals#7485]
Proposed timing calculation
```
interactive = t.domInteractive - t.domLoading,
dcl = t.domContentLoadedEventStart - t.domLoading,
complete = t.domComplete - t.domLoading;
```
Does not match Chrome Devtools Calculation.

The one below has the nearest calculation.
```
dcl = t.domContentLoadedEventEnd - t.fetchStart,
complete = t.loadEventEnd - t.fetchStart,
```

**Page Affected:**
https://developers.google.com/web/fundamentals/performance/critical-rendering-path/measure-crp#feedback

**What needs to be done?**
Update code ?

**Comment by kaycebasques** [comment]
@addyosmani or @philipwalton what's your take on this?

**Comment by philipwalton** [comment]
I don't think there's anything wrong here, but I can see how it might be confusing:

```js
interactive = t.domInteractive - t.domLoading,
dcl = t.domContentLoadedEventStart - t.domLoading,
complete = t.domComplete - t.domLoading;
```

The above calculations measure the time it takes for the DOM to get to each of these moments **relative to when the DOM started loading**, whereas DevTools will generally tell you the time it takes to get to each of these moments from the beginning of the navigation.

Both variations could be useful to a developer, and I don't think Ilya's article implies his `interactive` calculation is from the beginning of the navigation.
