### ISSUE TITLE
[Lighthouse] Unpopular, badly maintained library should not be recommended

### ISSUE THREAD

**Issue by wtho** [google/WebFundamentals#7527]
**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/oversized-images

**What needs to be done?**
The recommendation for the Library `responsive-images-generator` should be removed.

The library `responsive-images-generator` was never released with v1 (currently v0.2.2) and no commits/publishes have happened since over two years. npmjs scores the popularity to only 5% and maintenance to 1%.

Maybe alternative tools can be recommended instead.

**Comment by kaycebasques** [comment]
Good call, thanks. Any recommended alternatives?

**Comment by wtho** [comment]
I am definitely no expert in this area, just stumbled upon it for a jekyll-based project, but after doing a little research (e. g. checking [this SO thread](https://stackoverflow.com/questions/24026320/node-js-image-resizing-without-imagemagick) there seem to be a few good options:
* https://github.com/lovell/sharp, which is also used internally by the referenced `gulp-responsive`. It seems well maintained and used by lots of other projects. When looking at the dependents of sharp [on npmjs](https://www.npmjs.com/browse/depended/sharp) there are definitely some interesting middlewares for different frameworks, but I did not look into them.
* For my project, for jekyll, there is the plugin `jekyll-responsive-image` available, it uses `rmagick` internally
* Other solutions are often based on `imagemagick`

I think it does not make sense to recommend framework specific tools. It seems difficult to recommend two or three options without knowing what the lighthouse user is actually looking for. I would like lighthouse to only create awareness of general library availability without promoting too many (or any at all).
