### ISSUE TITLE
JavaScript modules note on file extensions is incorrect

### ISSUE THREAD

**Issue by GeoffreyBooth** [google/WebFundamentals#7623]
**Page Affected:** https://developers.google.com/web/fundamentals/primers/modules

**What needs to be done?**

This part:

> Still, we recommend using the `.mjs` extension for modules, for two reasons:
>
> 1. …
> 2. It’s consistent with Node.js, where the experimental modules implementation only supports files with the `.mjs` extension.

Is incorrect. Node.js since 12.0.0 no longer requires the `.mjs` extension for ES modules:

- https://nodejs.org/api/esm.html#esm_enabling
- https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff (section “`import` and `export` in `.js` files”)

As the second link explains, this change was made in large part due to pushback from the community; and also due to certain scenarios where `.mjs` isn’t usable for compatibility reasons. I’m part of the Node group that made this change.

It’s also debatable whether the `.mjs` extension is something to be recommended for frontend Web development. For developers who control where their files will be served from, either via control over their server or their CDN, sure, it’s a safe recommendation; but there are lots of JavaScript developers who lack such control. They could be publishing a public library, whether something standalone like jQuery or something that’s part of a larger package like a WordPress theme, and the author may not know if the eventual end user will be hosting the files on a server configured to serve `.mjs` files properly. The author themselves may be using shared hosting or a CDN that doesn’t serve `.mjs` with the proper MIME type. It’s arguable that the ability to tell apart Script from Module files on one’s local machine (the only cited advantage of `.mjs` that’s still true) is outweighed by `.js`’s benefit of knowing that one’s Module JavaScript will always be served properly, wherever it’s hosted.

At the very least, an introductory primer is a poor place for taking a stand on a controversial topic. I would stick to straightforward, uncontroversial facts about `.mjs`, so the user can make their own decision based on their needs and priorities, rather than Google recommending a course of action that may not be viable for all developers.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by mathiasbynens** [comment]
This content has moved to https://v8.dev/features/modules and is no longer part of Web Fundamentals.

**Comment by mathiasbynens** [comment]
Continue here: https://github.com/v8/v8.dev/pull/228
