### ISSUE TITLE
New Autoplay Policy is a BUG that broke my financial trading application notification system

### ISSUE THREAD

**Issue by Tectract** [google/WebFundamentals#7685]
**Page Affected:** https://developers.google.com/web/TODO
(private membership needed to access)

**What needs to be done?**
My financial application plays a "ding.mp3" file whenever a trade has executed on a users account, notifiying them to go look at the page. The expected use case is for this sound to trigger user interaction, so it is NOT POSSIBLE to have this sound be "enabled" or "allowed" by a prior user interaction. 

I'm requesting a reversion of the new Chrome Autoplay Policy until a more gracefull solution can be made. Some pages actually NEED background sounds guys, you broke a TON of people's applications and caused financial HARM to many companies with this BUG.

**Comment by dylmye** [comment]
Think you've got the wrong place. This is for reporting issues about the documentation, not about the features themselves. You may wish to file a feature request here: http://crbug.com

**Comment by andrewburns99** [comment]
Fu

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
