### ISSUE TITLE
User Idle Detection

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#7715]
Fugu article for [User Idle Detection](https://bugs.chromium.org/p/chromium/issues/detail?id=878979)

**Comment by tomayac** [comment]
Reviews happening in https://docs.google.com/document/d/1mQfS2Bv_tJVubqy75GdhsRScqlrjZTeYEZz1kH9qdzc/edit# (sorry, Google-internal).

**Comment by tomayac** [comment]
Closing here, since work is now happening in https://github.com/GoogleChrome/web.dev/issues/1948.
