### ISSUE TITLE
Wix edit not loading in google chrome.

### ISSUE THREAD

**Issue by TrVlogs** [google/WebFundamentals#7766]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

**Page Affected:** https://www.wix.com

**What needs to be done? Fix the bug not letting me edit on the wix site.

https://youtu.be/jsC2hDo3VWU

![1](https://user-images.githubusercontent.com/51675840/59216530-cd244f00-8b89-11e9-8cbe-d6e258bab76f.png)

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)
