### ISSUE TITLE
ERROR: Failed to resolve: com.github.GoogleChrome.custom-tabs-client:customtabs:d08e93fce3

### ISSUE THREAD

**Issue by jdchanda** [google/WebFundamentals#7878]
I get this error when I build the project

**Comment by budiselic** [comment]
same problem here

**Comment by jdchanda** [comment]
I hope someone addresses it.. It may be either because of our mistake or something is missing in their end!!

**Comment by hblanken** [comment]
Please address and resolve  - we are getting same bug.
debug
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/github/GoogleChrome/custom-tabs-client/customtabs/-SNAPSHOT/maven-metadata.xml]
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/github/GoogleChrome/custom-tabs-client/customtabs/-SNAPSHOT/customtabs--SNAPSHOT.pom]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/com/github/GoogleChrome/custom-tabs-client/customtabs/-SNAPSHOT/customtabs--SNAPSHOT.jar]
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/github/GoogleChrome/custom-tabs-client/customtabs/-SNAPSHOT/maven-metadata.xml]
Resource missing. [HTTP GET: https://repo.jfrog.org/artifactory/libs-release-bintray/com/github/GoogleChrome/custom-tabs-client/customtabs/-SNAPSHOT/customtabs--SNAPSHOT.pom?referrer]
Resource missing. [HTTP HEAD: https://repo.jfrog.org/artifactory/libs-release-bintray/com/github/GoogleChrome/custom-tabs-client/customtabs/-SNAPSHOT/customtabs--SNAPSHOT.jar?referrer]

**Comment by mordka** [comment]
@petele could you please check why the library is not getting resolved? None of the versions are found, was it removed from jitpack?

**Comment by nerrydanna** [comment]
in the build.gradle of project add this:

`allprojects {
    repositories {
        google()
        jcenter()
        **maven { url "https://jitpack.io" }**
    }
}`

**Comment by ohenepee** [comment]
Seriously... someone should look into this its over 30 days now... come on!! None of the tags resolve, even the latest one `91b4a1270b`

@petele @PaulKinlan @gauntface @jpmedley @flaviocopes

**Comment by ohenepee** [comment]
Okay... sorry for referencing any of the contributors... nothing is more frustrating than a failed build, especially when all u needed to do was add a url.

I solved the problem...
```
*buildscript* {
   repositories {
       google()
       jcenter()
       maven { url "https://jitpack.io" } <<<<<<<< DON'T PUT IT HERE, REMOVE IT IF YOU HAVE
   }
}
```
must rather be this...
```
*allprojects* {
   repositories {
       google()
       jcenter()
       maven { url "https://jitpack.io" }
   }
}
```

**Comment by brightest-dazes** [comment]
I changed because I wanted too. Not because of you

**Comment by andreban** [comment]
Hi everyone, sorry for the delay on responding, I didn't see this previously.

Can you confirm if you are still seeing the issue? If so, it would be great if you could share both the application and module build.gradle files.

**Comment by andreban** [comment]
I think we can close this, as the issue seems to have been a misconfigured build.gradle. Please, re-open if the issue continues to happen.

@petele I don't have access to close the issue. Can you help?

**Comment by haloboy777** [comment]
> Okay... sorry for referencing any of the contributors... nothing is more frustrating than a failed build, especially when all u needed to do was add a url.
> 
> I solved the problem...
> 
> ```
> buildscript { // <<<<<<<< DON'T PUT IT HERE
>    repositories {
>        google()
>        jcenter()
>        maven { url "https://jitpack.io" } // <<<<<<<<<<< REMOVE IT IF YOU HAVE
>    }
> }
> ```
> 
> must rather be this...
> 
> ```
> allprojects { // <<<<<<<<<<<<<<<<< THIS IS WHERE CHOCOLATE IS
>    repositories {
>        google()
>        jcenter()
>        maven { url "https://jitpack.io" } // <<<<<<<<<<< THIS IS WHERE IT NEEDS TO BE
>    }
> }
> ```
> 
> At least that's the mistake I made, I don't know about you guys.

And After this Go to Build > Clean Project.

**Comment by andreban** [comment]
We have released a new library, [android-browser-helper](https://github.com/GoogleChrome/android-browser-helper) ([blogpost](https://developers.google.com/web/updates/2020/twa-android-browser-helper)). The new one is delivered via the [Google Maven](https://maven.google.com/). When using the new library, the step mentioned in this issue is not needed anymore.

The [original blogpost](https://developers.google.com/web/updates/2019/02/using-twa) has been updated to use the new library too.

**Comment by NazarKohh** [comment]
Help please)

build:gradle(:app)

plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.affil.dietcalculator"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        def map
        map = manifestPlaceholders =[
                hostName       : "dietcalculator.tech",
                defaultUrl     : "https://dietcalculator.tech",
                launcherName   : "DietCalculator",
                assetStatements: '[{ "relation": ["delegate_permission/common.handle_all_urls"],' +
                        '"target": {"namespace": "web", "site": "https://dietcalculator.tech"}}]'
        ]
        map
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
    implementation 'com.google.android.material:material:1.1.0'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.2.0'
    implementation 'com.github.GoogleChrome:custom-tabs-client:a0f7418972'
    implementation platform('com.google.firebase:firebase-bom:26.5.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'



and the error:
Duplicate class android.support.customtabs.ICustomTabsCallback found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.ICustomTabsCallback$Stub found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.ICustomTabsCallback$Stub$Proxy found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.ICustomTabsService found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.ICustomTabsService$Stub found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.ICustomTabsService$Stub$Proxy found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.IPostMessageService found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.IPostMessageService$Stub found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.IPostMessageService$Stub$Proxy found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.trusted.ITrustedWebActivityService found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.trusted.ITrustedWebActivityService$Stub found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class android.support.customtabs.trusted.ITrustedWebActivityService$Stub$Proxy found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsCallback found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient$1 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$1 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$2 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$3 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$4 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsClient$2$5 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsIntent found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsIntent$Builder found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsService found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsService$1 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsService$Relation found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsService$Result found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsServiceConnection found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsServiceConnection$1 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsSession found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsSession$PendingSession found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsSessionToken found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsSessionToken$1 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.CustomTabsSessionToken$MockCallback found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.PostMessageService found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.PostMessageService$1 found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.PostMessageServiceConnection found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)
Duplicate class androidx.browser.customtabs.TrustedWebUtils found in modules browser-1.3.0-runtime (androidx.browser:browser:1.3.0) and jetified-customtabs-a0f7418972-runtime (com.github.GoogleChrome.custom-tabs-client:customtabs:a0f7418972)

**Comment by andreban** [comment]
You are importing  both `android-browser-helper` and `custom-tabs-client`. The second doesn't work on AndroidX and will conflict with the first.

**Removing** the following line should fix it:
```
implementation 'com.github.GoogleChrome:custom-tabs-client:a0f7418972'
```

**Comment by andreban** [comment]
Closing this issue as obsolete - the recommended library is `android-browser-helper`, which shouldn't have this issue and the docs have been updated to reflect that.
