### ISSUE TITLE
Found broken link

### ISSUE THREAD

**Issue by PraveenPal4232** [google/WebFundamentals#8081]
**Page Affected:** https://developers.google.com/web/fundamentals/performance/why-performance-matters/

**Replace a broken link**
A link to https://www.nccgroup.trust/uk/ website is broken
please check line no 1168 
**Broken link:** https://www.nccgroup.trust/uk/about-us/resources/cook-real-user-monitoring-case-study/?style=Website+Performance&amp;resources=Case+Studies

**Comment by danbarretto** [comment]
Hello, I'm a Computer Science student at University of São Paulo (USP) in São Carlos, SP Brazil, and I would like to help as my first contribution in a open source project.

**Comment by PraveenPal4232** [comment]
Thanks @danbarretto

**Comment by PraveenPal4232** [comment]
Hi @danbarretto!
Would you like to check my PR #8106  for this issue

**Comment by PraveenPal4232** [comment]
Issue solved at PR #8106 by @PraveenPal4232
