### ISSUE TITLE
This page is missing the audio part of the title!

### ISSUE THREAD

**Issue by Jerry-Merchand** [google/WebFundamentals#8109]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

_Please provide description of what's needs to be done here. Please be sure to include the link to the original page
and any supporting links/data._

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by connerturner** [comment]
Hi, Can you please let us know the page you're referring to? Thanks!

**Comment by Jerry-Merchand** [comment]
sorry i did not see this until it was just closed.
https://developers.google.com/web/fundamentals/media/video

the title is under Media & VR | Video and Audio Playback | Using <video>
and <audio> but, I do not see any audio example here. I can make audio tag
work and new Audio() work in plan HTML5 but when trying to work with Vuejs
it's a not go.

Jerry
