### ISSUE TITLE
Dead link in your document

### ISSUE THREAD

**Issue by J0ne** [google/WebFundamentals#8163]
I'm searching help for this:
[Violation] Avoid using document.write()

The site: https://developers.google.com/web/updates/2016/08/removing-document-write

The link "maintaining a set of known services that provide asynchronous loader support" is dead:  https://developers.google.com/speed/docs/insights/UseAsync (404)

Thx!

**Comment by connerturner** [comment]
Thanks for filing the issue, it seems to be a Duplicate of #7832

**Comment by J0ne** [comment]
Yeah, it seems so.
