### ISSUE TITLE
https://developers.google.com/web-components not accessible

### ISSUE THREAD

**Issue by akashbijwe** [google/WebFundamentals#8204]

**Comment by akashbijwe** [comment]
This link redirects to 404.
When I tried to click on learn more inside web components section on  https://developers.google.com/web-components on this page.

**Comment by connerturner** [comment]
Hi, the link should be https://developers.google.com/web/fundamentals/web-components, On which page did you click the link?

**Comment by akashbijwe** [comment]
Hey,
In this section https://developers.google.com/web/fundamentals#whats-hot If you click on learn more inside Web Components, you will be redirected to https://developers.google.com/web-components which eventually throws 404.

**Comment by akashbijwe** [comment]
🎉  Fixed & has been pushed live to https://developers.google.com/web/
