### ISSUE TITLE
Links Do Not Have Descriptive Text does not mention URLs as link text

### ISSUE THREAD

**Issue by CharlesBelov** [google/WebFundamentals#8207]
**Page Affected:** https://developers.google.com/web/tools/lighthouse/audits/descriptive-link-text

**What needs to be done?**
If link text such as www.example.com is not appropriate link text, add it to the section Recommendations.

If Lighthouse is updated to flag URLs as link text, add to the section More Information.

Examples of code that would be recommended against the same as "click here" is currently recommended against:
```
<a href=https://example.com>https://example.com/</a>
<a href=https://example.com>example.com</a>
```

**Comment by CharlesBelov** [comment]
Related to Lighthouse issue [Flag URLs as link text with Links Do Not Have Descriptive Text #9807](https://github.com/GoogleChrome/lighthouse/issues/9807)

**Comment by CharlesBelov** [comment]
For clarification, 

`<a href=https://example.com>https://example.com/</a>`

or

<a href=https://example.com>example.com/</a>

are both examples of what I would consider (and am suggesting the documentation state as being) poor link text.

**Comment by CharlesBelov** [comment]
Updated original post to include examples.

**Comment by paulirish** [comment]
picking up the convo in https://github.com/GoogleChrome/lighthouse/issues/9807
