### ISSUE TITLE
i18n based manifest

### ISSUE THREAD

**Issue by calidion** [google/WebFundamentals#8404]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/TODO

**What needs to be done?**

currently manifest only support a string for key `name` and `short_name`.

I would like to suggest, they use i18n based object to represent  i18n strings.

for example:

from 
```
{
name: "An Angular Based Application"
short_name: "angular"
}
```

to 

```
{
name:  {
"en" : "An Angular Based Application",
"zh" : "一个基于角度的程序",
"ja" : "角度ベースのアプリケーション",
}，
short_name: {
"en" : "Angular",
"zh" : "角度",
"ja" : "角度",
}
}
```

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by myakura** [comment]
Uou might want to file a bug against the W3C Web App Manifest specification, as this feature is not Chrome specific, and this repository is not meant for Chrome development.
https://github.com/w3c/manifest/
