### ISSUE TITLE
Pretty-Print screenshot needs a highlight

### ISSUE THREAD

**Issue by zacharysyoung** [google/WebFundamentals#8588]
**Welcome!** Please use this template for reporting documentation issues on https://developers.google.com/web/.

_For questions about **Chrome DevTools**, checkout the
[`google-chrome-devtools`](https://stackoverflow.com/questions/tagged/google-chrome-devtools) tag on StackOverflow.
For questions about **Chrome**, check the [`google-chrome`](https://stackoverflow.com/questions/tagged/google-chrome)
tag. If you think you've found a Chrome bug, check out our 
[feedback page](https://developers.google.com/web/feedback/#how-to-file-a-good-bug) for more details on how to file it._

**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/javascript/pretty-print
**What needs to be done?**

The Pretty-Print button **`{}`** is kinda small in UI, I think the screenshot should have a highlight around the **`{}`** button to draw the readers attention directly to where they need to click to get this very awesome benefit.

- [ ] Appropriate `type-something` label has been added.
- [ ] Appropriate `section-something` label has been added.

**Comment by connerturner** [comment]
Hi, That page is deprecated. The JS Debugging reference does have a highlight on where the button is:

https://developers.google.com/web/tools/chrome-devtools/javascript/reference#format

**Comment by zacharysyoung** [comment]
Awesome, thanks!
