### ISSUE TITLE
Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/index.html

### ISSUE THREAD

**Issue by PakanaHoldings** [google/WebFundamentals#878]
I'm not a UX/UI designer but I did not find it obvious that the "01" and "02" Guide links were actually links until I hovered over them.

**Comment by arthurvr** [comment]
Looked quite clear to me, honestly. What would you suggest that needs clarification?

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
