### ISSUE TITLE
Documentation needs to be updated for androidx

### ISSUE THREAD

**Issue by jonfhancock** [google/WebFundamentals#8797]
**Page Affected:** https://developers.google.com/web/android/custom-tabs/implementation-guide

**What needs to be done?**

The documentation on this page begins with an outdated dependency, and an outdated gradle api. 

```
dependencies {
    ...
    compile 'com.android.support:customtabs:23.3.0'
}
```
 should be:
```
dependencies {
    ...
    implementation 'androidx.browser:browser:1.2.0'
}
```

Beyond that, this entire page, and all links to api references need to be updated to reflect the most recent api changes in the new androidx Browser artifact.

**Comment by andreban** [comment]
Timely bug - I created #8796 earlier today that should improve this. It fixes both the import and the android references. The docs were just a copy / reorganization of the outdated docs on https://developer.chrome.com/multidevice/android/customtabs and were only supposed to by listed after this update. I guess it was still linked somewhere and was indexed by search. Along with this PR, we're going to redirect the old docs to these docs.

**Comment by jonfhancock** [comment]
With  #8796 merged, I think this issue can be closed.
