### ISSUE TITLE
Roboto Condensed font not included properly for site, needs to be updated

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#887]
From email: We should take a look at the web font integration for the Webfont optimization site.  It would appear as if Google Fonts API (CSS) for Roboto Condensed had been copy&pasted into styles.min.css.  Given the use of the old serving domain, old version of the font and lack of unicode-range support, it appears to be quite stale.

@gauntface: This comes back to the old discussion of how to get this working without the additional call to g web fonts.
@PaulKinlan: Yeah, in our case we can work this out at build time using the api.

**Comment by gauntface** [comment]
Whats the plan here?

At the moment we are hardcoding fonts and quite frankly - it looks horrible.

https://github.com/google/WebFundamentals/blob/master/src/_sass/styles.scss#L17

Sooner or later this is bound to break.

**Comment by petele** [comment]
Agreed - but it may be easiest to deal with this with Material.

**Comment by gauntface** [comment]
Sorry Pete, I don't get what that means - "deal with this with Material" the problem of our approach will remain open.

I think we should just use Google Web Fonts link.

**Comment by petele** [comment]
Sorry - brain not engaged today. I'm happy if you want to change this and add the link to the head.

**Comment by gauntface** [comment]
@PaulKinlan Still hates this idea and wants something built into the build system which uses an API to fetch the latest woff font files and use that for fonts. Any takers for the work? @wibblymat ?

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
