### ISSUE TITLE
Feedback for: /fundamentals/index.html

### ISSUE THREAD

**Issue by weboverhauls** [google/WebFundamentals#889]
There are redundant tooltips (title attributes) on links throughout the entire course. The title text is the same or virtually the same as linked text so adds no value and is distracting for mouse users. Here's one of many examples:

```
<a class="main-nav__link main-nav__link--parent" href="/web/fundamentals/getting-started/" title="Go to Get Started">Get Started <i class="main-nav__icon icon icon-chevron-right"></i></a>
```

**Comment by PaulKinlan** [comment]
Hmm, this is the opposite of the feedback that we got for accessibility.

**Comment by weboverhauls** [comment]
Who gave that feedback?

**Comment by PaulKinlan** [comment]
I can't recall at the moment.  But I am not really planning on changing
right now.
