### ISSUE TITLE
Missing information about issues nag banner

### ISSUE THREAD

**Issue by oliversalzburg** [google/WebFundamentals#8930]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/issues

**What needs to be done?**

Explain how to disable the notification banner.

![image](https://user-images.githubusercontent.com/1658949/89185271-43f48680-d59a-11ea-9d51-c4a9f1abe587.png)

**Comment by petele** [comment]
Hi! Thanks for the feedback, this sounds like a Chrome issue. If you're still seeing it, would you please file a bug with Chrome at [https://new.crbug.com](https://new.crbug.com)

**Comment by oliversalzburg** [comment]
It seemed like a new feature and I found a lot of information on it on that page, that's why I assumed that part should be explained there as well. The entire new feature seemed to be behaving as designed. Not having any option to dismiss the bar seemed intentional. I just can't find where to disable it.

That link results in a certificate issue error in my browser btw. But I know how to file bugs for Chromium anyway :) Thanks

**Comment by oliversalzburg** [comment]
Reported at https://bugs.chromium.org/p/chromium/issues/detail?id=1112684
