### ISSUE TITLE
FPS Meter Documentation

### ISSUE THREAD

**Issue by JeremyTCD** [google/WebFundamentals#9006]
**Page Affected:** https://developers.google.com/web/tools/chrome-devtools/evaluate-performance#bonus_open_the_fps_meter

**What needs to be done?**

FPS meter was changed in a recent Chrome release. New FPS meter is not intuitive to some. Might want to update your docs.  

Several Stackoverflow questions (unanswered) about the new FPS meter:

- [Chrome fps meter no longer shows frame rate](https://stackoverflow.com/questions/63782867/chrome-fps-meter-no-longer-shows-frame-rate)
- [Different chrome FPS meters](https://stackoverflow.com/questions/63697334/different-chrome-fps-meters)

Also, no mentions of the change in [What's New In DevTools (Chrome 86)](https://developers.google.com/web/updates/2020/08/devtools).

**Comment by addyosmani** [comment]
@hashseed

**Comment by chybie** [comment]
cc @chybie.
