### ISSUE TITLE
editing a page creates constructed stylesheet and cannot access user agent stylesheet anymore

### ISSUE THREAD

**Issue by Berzerk3000** [google/WebFundamentals#9083]
after making some changes devTools switch to constructed stylesheet... searched the internet to find out why this happens and/ or how to access the files.

i like testing things locally and the user agent stylesheet usually keeps track on whats done however i cannot access it anymore.
appreciate someone taking the time to explain what is happening here and how i can work arround/ prevent it.

![chromeDev](https://user-images.githubusercontent.com/65219501/97114221-84722500-16ef-11eb-9630-859638fbb576.PNG)

**Comment by gloup29** [comment]
@Berzerk3000 As the issue has been closed, how did you fix this ? I am still experiencing it, and appears not to be the only one.

**Comment by Berzerk3000** [comment]
I did not fix it. Seemed like no one cares and it's not happening too often/ affecting me that much so I just shrugged it off.
