### ISSUE TITLE
Correct the text written

### ISSUE THREAD

**Issue by RiteshKSingh1709** [google/WebFundamentals#9246]
Wrongly written text ,attaching screenshot , It should not be `don't` 
<img width="866" alt="Screenshot 2021-02-05 at 6 46 30 PM" src="https://user-images.githubusercontent.com/10517315/107038566-b90f7580-67e2-11eb-92e7-1dce10b50d2e.png">

**Comment by ARH-MNAJS** [comment]
Filtering out any cookies which don't contain the text
