### ISSUE TITLE
Feedback for: /fundamentals/media/video/quick-reference.html

### ISSUE THREAD

**Issue by jacquerie** [google/WebFundamentals#931]
Text wraps in table cells even when a command is pictured, with unpleasant output:

![quick_reference_ _web_fundamentals](https://cloud.githubusercontent.com/assets/381280/4761522/0075e934-5af9-11e4-903d-33442a618631.jpg)

The rule
```CSS
white-space: nowrap;
```
would fix this behaviour, but where do we apply it?
```CSS
table tr code { ... }
```
would work, but looks ugly and a violation of [BEM principles](http://bem.info/method/definitions/).

**Comment by petele** [comment]
I'm going to close this for now as we're working on a complete site refresh using material design lite which should fix this issue.
