### ISSUE TITLE
Broken link in article

### ISSUE THREAD

**Issue by Mhmdrza** [google/WebFundamentals#9421]
There is a broken link in the article ->> 
https://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

**Page Affected:** 
https://developers.google.com/web/updates/2018/09/inside-browser-part3#raster_and_composite_off_of_the_main_thread

**What needs to be done?** 
change or remove the link;

**Comment by Jassi10000** [comment]
Can you please put a screenshot , in what part of the page , the broken link is located 
It would be much easier to resolve then

**Comment by Mhmdrza** [comment]
Here it is  
<img width="767" alt="Screen Shot 1400-07-11 at 21 52 45" src="https://user-images.githubusercontent.com/23448421/135766591-62f54a90-d015-44da-b37a-2e605d98d69f.png">

**Comment by Jassi10000** [comment]
> Here it is <img alt="Screen Shot 1400-07-11 at 21 52 45" width="767" src="https://user-images.githubusercontent.com/23448421/135766591-62f54a90-d015-44da-b37a-2e605d98d69f.png">

you mean to say 
that by clicking on  " compositing only animations " it shows invalid / broken link  ?

**Comment by Mhmdrza** [comment]
it's not broken now, but is was when I created this issue :(
