### ISSUE TITLE
Incorrect/Unavailable thumbnail Images to redirect links

### ISSUE THREAD

**Issue by Scholasticpal** [google/WebFundamentals#9561]
**Pages Affected:**

- https://developers.google.com/web/updates/2019
- https://developers.google.com/web/updates/2018
- https://developers.google.com/web/updates/2017
- https://developers.google.com/web/updates/2016
- https://developers.google.com/web/updates/2015
- https://developers.google.com/web/updates/2014
- https://developers.google.com/web/updates/2013
- https://developers.google.com/web/updates/2012
- https://developers.google.com/web/updates/2011

**What needs to be done?**

The aforementioned pages contain multiple redirect links to other articles. However, for some articles, the thumbnail image shows a basic shape/icon, that is not related to the contents. 

![image3](https://user-images.githubusercontent.com/80644106/159923681-f83a3ec4-804c-47e0-8202-ddaed411eae1.PNG)
![image4](https://user-images.githubusercontent.com/80644106/159924334-72f119c5-5867-430c-91fb-2a5b17d2eaa1.png)

**Comment by utkarsh-shrivastav77** [comment]
hi I want to work on this issue

**Comment by rachelandrew** [comment]
we are not maintaining the content on this site as we are in the process of migrating it to other sites. So this issue will soon go away, as we're close to complete on the content move. Sorry for the mess, but it isn't worth raising issues on content on this site. If you follow a redirect and find an issue then raise it on the site you end up on (either web.dev or developer.chrome.com) - thanks!
