### ISSUE TITLE
Redirect for /web/fundamentals/app-install-banners/native/ is broken.

### ISSUE THREAD

**Issue by malchata** [google/WebFundamentals#9590]
**Page Affected:**
Any pages that link to https://developers.google.com/web/fundamentals/app-install-banners/native, which redirects to https://web.dev/app-install-banners-native that throws a 404 Not Found.

**What needs to be done?**
We need to figure out where this should redirect to, as it is referenced in 22 instances throughout the web.dev codebase (and likely referenced in other repos and this repo as well).

- [ ] Appropriate `type-something` label has been added (@petele).
- [ ] Appropriate `section-something` label has been added (@petele).

cc: @rachelandrew

**Comment by rachelandrew** [comment]
@malchata I found it, it ended up on dcc, though the spreadsheet says web.dev.

https://github.com/GoogleChrome/developer.chrome.com/pull/2547

https://developer.chrome.com/blog/app-install-banners-native/
