### ISSUE TITLE
Issues with IT translations

### ISSUE THREAD

**Issue by jacquerie** [google/WebFundamentals#977]
WIP

### General issues ###

* Translation quality is overall quite low, as if strings were fed into Google Translate.
* Sometimes the ` character is used instead of the ' character (used in Italian to separate words when a letter is omitted, as in "dell**'**amore"). This also leads to spurious inline code blocks (like at the end of https://web-central.appspot.com/web/fundamentals/performance/critical-rendering-path/constructing-the-object-model?hl=it)

### Specific issues ###

* 'Dispositivi multipli' sounds awkward. Perhaps 'siti multidispositivo' or 'siti per più dispositivi'? (https://web-central.appspot.com/web/fundamentals/getting-started/your-first-multi-screen-site/?hl=it)
* I've never seen the phrase 'siti reattivi'. 'siti responsive' is better. (https://web-central.appspot.com/web/fundamentals/getting-started/your-first-multi-screen-site/?hl=it)
* DOM has been translated as 'modello a oggetti'. It should be left untranslated. (https://web-central.appspot.com/web/fundamentals/performance/critical-rendering-path/constructing-the-object-model?hl=it)
* 'Polilinea picturefill' is a mishmash of '`picture` polyfill', which should be left untranslated. (https://web-central.appspot.com/web/fundamentals/media/images/images-in-markup.html?hl=it)

**Comment by arthurvr** [comment]
> Translation quality is overall quite low, as if strings were fed into Google Translate.

I'm, of course, only able to read few languages but none of them are super high quality TBH. None of the non-English things I read felt fluent.
