### ISSUE TITLE
Localization query parameter is not inherited to headers/footer navigation menues

### ISSUE THREAD

**Issue by agektmr** [google/WebFundamentals#985]
In this Japanese page
https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints?hl=ja

Any links on headers or footers have query parameters of `hl=ja`. This breaks localization chain.

**Comment by petele** [comment]
Fixed by f2304eb85b933279648b4404f82902b87936f4cc
