### ISSUE TITLE
Move local build to GAE

### ISSUE THREAD

**Issue by ianbarber** [google/WebFundamentals#998]
We currently have 3 local build states, which include one targeting GAE for web-central.appspot.com, one targeting developers.google.com and one straight Jekyll build. We should simplify to a single output structure which is handled by GAE on local and staging, and is easily mappable for d.g.c. This will require a new local dev requirement, but in the process we should be able to simplify some of the other build requirements. 

/cc @wibblymat

**Comment by wibblymat** [comment]
Closed by #1076
