### ISSUE TITLE
Review and refactor WF Ruby plugins

### ISSUE THREAD

**Issue by ianbarber** [google/WebFundamentals#999]
We have several Ruby plugins used for Jekyll. These should be reviewed: 

1) To remove any unused plugins
2) To combine similar plugins 
3) To simplify any overly confusing structures
4) To harmonise to a styleguide (see #746 for discussion of which to follow) 

/cc @wibblymat

**Comment by petele** [comment]
Closing since it's already happening in the MDL refresh
